components/jupyterhub/docker/Dockerfile
- Bump Python version so we don't need to run pip upgrade
- Don't store wheels cache in dockerfile
=> Cleanup JupyterHub Dockerfile

README.md
Per discussion [here](https://github.com/google/kubeflow/issues/33), we are adding the proposal link to README to make it more discoverable.
- first commit remove useless trailing whitespaces
- second commit add the proposal link
@jlewi  @DjangoPeng  PTAL
=> Add proposal link

README.md
When I typed CLI instruction from README:
> ks apply default kubeflow-core
The  errors occured like:
```
$ ks apply default kubeflow-core
ERROR 'apply' requires an environment name; use `env list` to see available environments
Usage:
ks apply <env-name> [-c <component-name>] [--dry-run] [flags]
Examples:
#
ks apply dev .....
```
This PR fixes misleading instructions on README.
=> fix(doc): correct cli instruction

README.md
Hi,
First of all, great project, looking forward to it developing further!
I've noticed that the model-server pods are crashing in Minikube with:
```
Illegal instruction (core dumped)
```
(that's the full output). That error message got me to https://github.com/mozilla/DeepSpeech/issues/912 which suggested the CPU's virtualisation might be the problem. And indeed, changing my Minikube's driver from `kvm2` to `virtualbox` fixed it. 
It would be nice for this to work with KVM which in my experience has performed better than virtualbox when under load. In the meantime, here's a PR adding a note about it not working with KVM. It's possible the issue is just on my machine (Intel i7-6700 CPU) so feel free to reject the PR if it's actually working.
=> Add a note about TF serving Deployment not working with Minikube's kvm driver

README.md, components/k8s-model-server/README.md, user_guide.md
* Remove note about building ksonnet from source; there is now a released artifact for version 0.8.0
* Remove instructions about setting up K8s clusters; just link to the K8s docs.
* Move notes about minikube and GKE to a troubleshooting section.
* Add info about why ksonnet.
=> Some improvements to docs.

components/k8s-model-server/README.md
1. Simplified the image build and push process for model server (parametrized make invocation rather than having to manually update the Makefile).
2. Added instructions for how to enable GCR from command line.
3. Linked to more useful part of gcloud docs
=> Makefile override

kubeflow/tf-job/prototypes/tf-job.jsonnet
* Args for TfJob should be set to the args parameter and not the namespace parameter.
* Fix https://github.com/google/kubeflow/issues/107
=> fix #107; args improperly set to the namespace

README.md
In response to [Issue 91](https://github.com/google/kubeflow/issues/91),
raised by @sebgoa.
Although I was the one who had originally complained about the ksonnet
installation, I think the problem has been solved by not asking the user
to manually install it from source anymore and it's okay to point at the
top-level of the ksonnet documentation rather than the release page.
=> Updated Quick Start section on README

user_guide.md
There were a few missing things that prevented the guide from being completed successfully.
Haven't tested the Advanced section.
=> Fixing errors and missing variables in user guide.

tf-controller-examples/tf-cnn/launcher.py, tf-controller-examples/tf-cnn/tf_job_cpu.yaml, tf-controller-examples/tf-cnn/tf_job_cpu_distributed.yaml, tf-controller-examples/tf-cnn/tf_job_gpu.yaml, tf-controller-examples/tf-cnn/tf_job_gpu_distributed.yaml
* Related to #192 
* Now that terminationPolicy can be used to specify a non-master chief, we no longer need to add a master to run the tf-cnn we can just use worker 0 as the chief which allows the example to run out of the box.
=> update tf-cnn example use terminationPolicy to address not using master replica

user_guide.md
Also added more info on the inception endpoint. Still need to provide an example with an inception client.
=> Document flow improvements, expanded on Jupyter usage

kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tf-job.libsonnet, kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet, testing/test-infra/debug_pod.yaml, testing/test_deploy.py
* Fix the TFCNN prototype; the termination policy wasn't being properly set
* Create service accounts and role bindings for the TfJob operator and UI
* Fix #129 
* Fix #125
* Fix #95; presubmits/postsubmits need to use the code at the commit we checked out
* We do this by replacing the directory in vendor with a symbolic link to where we checked out the source.
* It looks like using "--as" with ksonnet leads to strange errors about the server not being able to create the config map
* If we don't use "--as" need to fetch credentials a second time or else we get RBAC issues creating the cluster
=> Fix TfJob operator roles and TfCNN prototype

user_guide.md
This changes occurrences of `datascientists` to `data scientists`.
=> Fix datascientists typo

.gitignore, testing/README.md, testing/test-infra/app.yaml, testing/test-infra/components/nfs-jupyter.jsonnet, testing/test-infra/vendor/kubeflow/core/README.md, testing/test-infra/vendor/kubeflow/core/jupyterhub.libsonnet, testing/test-infra/vendor/kubeflow/core/nfs.libsonnet, testing/test-infra/vendor/kubeflow/core/parts.yaml, testing/test-infra/vendor/kubeflow/core/prototypes/all.jsonnet, testing/test-infra/vendor/kubeflow/core/tf-job.libsonnet
1. Fix some text format in README
2. checkin the vendor for test-infra app.
3. set service_type for jupyterHubLoadBalancer in nfs-jupyter.jsonnet
=> Fix the instruction for setting up cluster to run test

components/tensorflow-notebook-image/Dockerfile.cpu, components/tensorflow-notebook-image/Dockerfile.gpu, components/tensorflow-notebook-image/Makefile, components/tensorflow-notebook-image/jupyter_notebook_config.py, components/tensorflow-notebook-image/start-notebook.sh, components/tensorflow-notebook-image/start-singleuser.sh, components/tensorflow-notebook-image/start.sh
As described in the issue #126
=> Add tensorflow-notebook-image dockerfiles

kubeflow/argo/README.md, kubeflow/argo/argo.libsonnet, kubeflow/argo/parts.yaml, kubeflow/argo/prototypes/argo.jsonnet, kubeflow/registry.yaml
* An argo ksonnet package
* Makes it easy to deploy argo
* Related to #21
=> Argo ksonnet package

components/k8s-model-server/README.md, kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
- Made it so that the image created in the instructions is utilizied
- Removed downloaded model due to incompatibility with recent TF server versions
- Made tf-serving image configurable
- Minor flow/grammar tweaks
=> Model Server Component documentation triage.

kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tf-job.libsonnet, kubeflow/tf-job/tf-job.libsonnet
Sidenote: I've managed to pin most things to make sure the documentation is more robust. However I don't know how best to pin the kubeflow repo itself.
Ideally in the docs something like `ks registry add kubeflow github.com/kubeflow/kubeflow/tree/9a3e71f3/kubeflow` is done, however without a target tag I'd have to do a follow up PR to pin everything to the desired commit.
=> Changing tensorflow.org to kubeflow.org. Fixing CRD deployment.

kubeflow/core/jupyterhub.libsonnet
* The two services were incorrectly using the same name.
* The LB should not set the ClusterIP to None as this causes a problem
when the service type is loadbalancer.
* Fix #203
=> Fix bug with using LoadBalancer for JupyterHub.

README.md, testing/test_deploy.py, testing/workflows/components/workflows.libsonnet, user_guide.md
See https://github.com/kubeflow/tf-operator/issues/350
We have migrated tensorflow/k8s to kubeflow/tf-operator, then we should update the repo name.
Signed-off-by: Ce Gao <gaoce@caicloud.io>
=> *: Replace tensorflow/k8s with kubeflow/tf-operator

components/tensorflow-notebook-image/Dockerfile.cpu, components/tensorflow-notebook-image/Dockerfile.gpu
- to fix #138 
- added Ksonnet 0.8.0 install to both CPU and GPU dockerfile
- verified in docker CLI that jovyan is able to execute ks
```shell
jovyan@658114ba5b01:~$ ks
You can use the `ks` commands to write, share, and deploy your Kubernetes
application configuration to remote clusters.
```
=> install Ksonnet 0.8.0 in both CPU and GPU dockerfile.

kubeflow/seldon/core.libsonnet, kubeflow/seldon/crd.libsonnet, kubeflow/seldon/json/apife-deployment.json, kubeflow/seldon/json/apife-service.json, kubeflow/seldon/json/operator-deployment.json, kubeflow/seldon/json/pod-template-spec-validation.json, kubeflow/seldon/json/rbac-cluster-binding.json, kubeflow/seldon/json/rbac-service-account.json, kubeflow/seldon/json/redis-deployment.json, kubeflow/seldon/json/redis-service.json, kubeflow/seldon/parts.yaml, kubeflow/seldon/prototypes/core.jsonnet
Fixes #159 
* Called seldon rather than seldon-core not to overlap with existing core prototype
* Raw JSON is keep in separate folder and then ksonnet Mixins used for construction.
Known issues
* RBAC setting is clusterwide admin at present. Not done work to define a more limited defn.
* Not sure if there is a style guide for jsonnet files but I'm using emacs and didn't find a nice mode to format them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/268)
=> Add seldon ksonnet integration

user_guide.md
`disks` parameter should be set for the `kubeflow-core` component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/259)
=> Fix typo in user_guide.md

kubeflow/core/iap.libsonnet
Visiting / returns a 404 right now. This change will redirect
/ to jupyterhub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/257)
=> Redirect / to /hub for the envoy pods

components/k8s-model-server/README.md, kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
with the http-proxy image, now user can finally test the inception model without client requirements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/228)
=> Add ksonnet template for http proxy

testing/run.sh
depending on https://github.com/kubeflow/testing/pull/39
After this change, we will update the testing image for kubeflow/kubeflow to:
- use prow_config.yaml if exists
- else, use legacy workflow
This will be backward compatible, and we can check in the prow_config.yaml later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/275)
=> update image to use prow_config if exists

prow_config.yaml
prow_config.yaml contains the workflows that we want to run by prow.
By using prow_config.yaml, we can use the same testing image for different kubeflow repos.
Related to #276 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/271)
=> add prow_config.yaml

kubeflow/tf-serving/tf-serving.libsonnet
* Remove spaces from argument prefixes
* Make the binary name a command instead of argument
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/280)
=> Fix tf-serving command and args

kubeflow/core/jupyterhub_spawner.py
While we were adding pvc for every jupyter instance, we didn't mount it
anywhere.
Let's mount it to work dir, as I assume this is dir where users will
likely put their notebooks. This will ensure that work will be retained
even if pod dies.
Fix #19
Fix #22 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/270)
=> Add mount of pvc

kubeflow/tf-serving/tf-serving.libsonnet
Kubernetes requires port names for services with
more than one port
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/283)
=> Add names to tfserving service ports

user_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/304)
=> Add seldon to user guide docs as example serving component

kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
#295 
tf-serving : added optional parameter "service_type" default to clusterIP.
this parameter is then passed to modelService().
This can be tested as follows:
```BASH
ks param set ${MODEL_COMPONENT} service_type LoadBalancer
ks apply ${KF_ENV} -c ${MODEL_COMPONENT}
```
should see your serving component is now of type LoadBalancer instead of ClusterIP
```
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                         AGE
inception1   LoadBalancer   10.59.249.163   *.*.*.*   9000:31346/TCP,8000:32337/TCP   14m
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/302)
=> add option service_type to set TFServing service type

components/tensorflow-notebook-image/Dockerfile.cpu, components/tensorflow-notebook-image/start.sh
Besides adding chown /home/$USER also move non-install layers lower in
Dockerfile to make better use of docker cache during edits
Later we will probably switch to root user (issue #300), so it will make this whole section redundant.
Aslo touches #101 
Fixes #285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/311)
=> Fix #285 and make few tweaks to notebook Dockerfile

components/tensorflow-notebook-image/start.sh
During fixing pvc issue made it so CONDA_DIR is chowned always (instead
of just when UID differs from expected) and it takes long time. This
change splits behavior and only chowns /home/ on every run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/320)
=> Optimize start.sh

components/tensorflow-notebook-image/Dockerfile.cpu, components/tensorflow-notebook-image/Dockerfile.gpu
* An attempt to fix jupyterlab not working by upgrading jupyterlab.
Fix #262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/328)
=> Fix jupyterlab by upgrading Jupyterlab

components/tensorflow-notebook-image/Dockerfile.cpu, components/tensorflow-notebook-image/Dockerfile.gpu
The main purpose of this change is to fix two limitations of Python 2 kernels:
1. The set of libraries installed by default for Python 3 kernels were
not being installed for the Python 2 kernels.
2. The tensorflow-transform libary (which only works in Python 2 for now)
was not being included in the Python 2 kernels even though it could be.
To address these limitations, this change does the following:
1. Move the creation of the Python 2 conda environment after the last
installation of a Python package in the default (root) environment.
2. Create the Python 2 conda environment with every Python package from
the Python 3 environment that can be installed in it.
3. Install tensorflow-transform inside of the Python 2 environment.
Two additional changes had to be included in order to unblock …
=> Improve the Python 2 kernels for both CPU and GPU instances.

README.md
Closes #329 
- improve attribution to Project Jupyter, a non-profit, open source project 
- edit and add links for JupyterHub, Jupyter Notebooks and Project Jupyter
- edit confusing statement about additional resources and the notebook (the notebook uses the resources that is provided to it)
- add reference to scikit-learn
cc/ @minrk @yuvipanda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/330)
=> Refine the text and links related to JupyterHub and Jupyter

components/k8s-model-server/http-proxy/server.py
Right now, the default tf-model exported example is using classify api, this pr add classify support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/341)
=> Add classify support for http-proxy

kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
This allows the model serving image to download from any S3 compatible API.
The pattern may also find its way into other components such as tf-job in order to facilitate reading/writing to s3 during training.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/323)
=> Adding S3 support to model serving.

kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
There are situations in which many models will be deployed with different names, however currently the model name uses the deployment name, which means changing the client to match each individual deployment.
This makes it so that you can set the model name independently, and reuse an unmodified client to query each deployed model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/359)
=> Allow seperate naming of model name vs deployment name for TF Serving.

user_guide.md
I added commands of how to delete a training job to the user guide for users who are not familiar with the Ksonnet.
I also added commands of how to monitor a tf-cnn jobs since I did not realize at first that tf-cnn job is also a tfjobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/378)
=> add commands of how to delete a training job

kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/iap-envoy.jsonnet
It is defined in https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/config.proto in the JWT message
Tested by deploying to dev.kubeflow.org and verifying that JWT validation works when IAP is turned off
Related https://github.com/kubeflow/kubeflow/issues/394
Related https://github.com/kubeflow/kubeflow/issues/60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/401)
=> Use the correct jwt validation config

components/k8s-model-server/images/Dockerfile.cpu, components/k8s-model-server/images/Dockerfile.gpu, kubeflow/tf-serving/tf-serving.libsonnet
Even though model server itself can be the entry point itself but then run with PID 1 would make the server not responding to SIGINT or SIGTERM
which is problematic during k8s rolling up new version
Using [Tini](https://github.com/krallin/tini) has several benefits:
- It protects you from software that accidentally creates zombie processes,
which can (over time!) starve your entire system for PIDs (and make it
unusable).
- It ensures that the *default signal handlers* work for the software you run
in your Docker image. For example, with Tini, `SIGTERM` properly terminates
your process even if you didn't explicitly install a signal handler for it.
- It does so completely transparently! Docker images that work without Tini
will work with Tini without any changes.
--- …
=> use tini to start model server

kubeflow/core/iap.libsonnet
Use bypass_jwt field to bypass jwt validation for /healthz and
/noiap/whoami routes
Tested by disabling IAP - verified that /healthz and /noiap/whoami work
and other routes return an error - Required JWT token is missing
Fixes https://github.com/kubeflow/kubeflow/issues/404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/407)
=> Replace two envoy containers with a single one

kubeflow/core/prototypes/iap-envoy.jsonnet
Related to #401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/409)
=> Use kubeflow-images-staging to store envoy image instead of kubeflow-dev

kubeflow/core/ambassador.libsonnet, kubeflow/tf-serving/tf-serving.libsonnet
This change restricts the ambassador deployment to a single k8s
namespace. The idea is that we should be able to deploy multiple
instances of kubeflow to a single k8s cluster by restricting each
kubeflow instance to a single namespace.
Tested on my cluster and verified that ambassador and ambassador
admin both work fine after this change.
Related to https://github.com/kubeflow/kubeflow/issues/374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/408)
=> Replace ClusterRole/ClusterRoleBinding for ambassador with Role/RoleBinding

kubeflow/tf-serving/tf-serving.libsonnet
* Use the params s3Enable not cloud to decide whether to enable S3 modifications. Use of S3 can be orthogonal to cloud.
* Fix a typo in the variable name.
* PR #387 was automatically committed as a quirk of our auto-merge code
even though there were outstanding comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/399)
=> Fix 2 issues with s3 config from #387.

components/k8s-model-server/README.md, kubeflow/tf-serving/tf-serving.libsonnet
Related #385
Verified that serving with a model in my GCS bucket does not work unless passing the param:
cloud = gcp
gcpCredentialSecretName = secret_name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/416)
=> GCP credential support for TF serving

components/k8s-model-server/images/releaser/components/params.libsonnet, components/k8s-model-server/images/releaser/components/workflows.libsonnet, testing/workflows/components/params.libsonnet, testing/workflows/components/workflows.libsonnet
Related: https://github.com/kubeflow/testing/issues/18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/411)
=> Use kubeflow-ci as the test cluster

testing/workflows/components/workflows.libsonnet, testing/workflows/debug_pod.yaml
We now push worker images to kubeflow-ci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/440)
=> Use kubeflow-ci/test-worker as worker image

testing/test_jsonnet.py, testing/workflows/components/workflows.libsonnet
* Create test_jsonnet.py - it goes through all the jsonnet tests and executes it
* Add test_jsonnet.py to kubeflow-e2e workflow
Related to #432
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/443)
=> Run jsonnet tests as part of kubeflow-e2e workflow

docs/gke/iap.md, kubeflow/core/cert-manager.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/cert-manager.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet
Fixes #255 and alternative solution to #437 
Import of ksonnet components to install cert-mananger and certificate for the Ingress used by IAP component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/441)
=> Use cert-manager for obtaining valid certificates

kubeflow/tf-job/prototypes/tf-job.jsonnet, kubeflow/tf-job/tf-job.libsonnet
most tensorflow training examples use worker 0 as the chief worker instead of master. 
using ksonnet tf-job prototype to create training jobs dosen't allow that
and will make the tfjob fails if we set num_masters to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/444)
=> set termination policy to worker 0 by default when no master exists

components/tensorflow-notebook-image/Dockerfile
It's really hacky way to add api to jupyter image. We should remove it
and make it properly once package becomes available for python 3.
Fixes #355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/358)
=>  Add tensorflow-serving-api to jupyter image 

testing/test_jsonnet.py, testing/workflows/components/workflows.libsonnet
* Update the argo workflow to pass /src/kubeflow/kubeflow directory as
jsonnet_path_dirs
* Will fix the issue in PR https://github.com/kubeflow/kubeflow/pull/450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/456)
=> Add jsonnet_path_dirs flag to test_jsonnet script

components/tensorflow-notebook-image/Dockerfile
/assign @jlewi
This is for the issue #428 "remove tensorboard link from jupyter" and #297 "add prototypes for TensorBoard". In general we're utilizing the ksonnet way to launch tensorboard rather than using a button in jupyterhub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/446)
=> remove the pip install tensorboard

README.md, components/k8s-model-server/README.md, docs/gke/iap.md, user_guide.md
Now that https://github.com/kubeflow/kubeflow/pull/426 is merged, we do
not need to set namespace at the component level. namespace will be
automatically inherited by the component from env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/463)
=> Update docs so that namespace is only set at ks env level

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, releasing.md
* Build 1.4.1, 1.5.1, 1.6.0 versions for gpu and cpu
* Update ksonnet version
* Update bazel version
* Built all images locally to test it.
The images will have the following URI format
```
gcr.io/kubeflow-images-staging/tensorflow-1.4.1-notebook-gpu:20180320-afw9aow
gcr.io/kubeflow-images-staging/tensorflow-1.4.1-notebook-cpu:20180320-afw9aow
```
Fixes #375
Fixes #467 (Multiple Jupyter images for different TF Versions).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/471)
=> Update tensorflow-notebook-image workflow to pin tf and cuda version

kubeflow/core/tests/ambassador_test.jsonnet
It was broken by #396
/cc @wbuchwalter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/476)
=> Fix ambassador_test.jsonnet

kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
* #444 add an argument for the termination policy but the TFCnn prototype
isn't setting it.
* The TFCnn prototype overrides the termination policy so we can just pass null
for the TP.
* Fix #458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/461)
=> Fix the TFCnn prototype which was broken by #444.

components/k8s-model-server/images/releaser/components/workflows.libsonnet, components/k8s-model-server/images/test-worker/result-gpu.txt, testing/test_deploy.py, testing/test_tf_serving.py
Fix #291 
- refactor workflow to avoid code duplication
- Append cpu/gpu to the workflow name and junit name so that they can be distinguished
- Added result file for GPU. It's slightly different (0.0001) than CPU result (not sure why)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/442)
=> E2e test for TF serving with GPU

testing/test_jsonnet.py, testing/workflows/components/workflows.libsonnet
* This will catch any syntax errors in *sonnet files.
* Skip all ksonnet prototypes since they need additional deps
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/480)
=> Update jsonnet tests so that it tests all files under kubeflow

components/k8s-model-server/images/releaser/components/workflows.libsonnet, testing/test_deploy.py, testing/test_tf_serving.py
Fix #484
- increase waiting time for deployment
- avoid log name collision for each deployment
- add more retry for prediction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/485)
=> Enhance tf serving gpu test

components/tensorflow-notebook-image/Dockerfile
This is the official python client library for GCS
It will be used to read/write to GCS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/492)
=> Add google-cloud-storage package to jupyterhub notebook

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
* Argo workflow names cannot have `.` character, so use `-` as a separator.
* jsonnet 0.9.5 does not have the `std.strReplace` function, so we need to
pass workflow_name as a separate parameter. With `std.strReplace`, we 
could have used `workflow_name = std.strReplace(tf_version, '.', '-')`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/488)
=> Update buildTemplateImage to take workflow_name

kubeflow/core/iap.libsonnet
Downloading images takes some time - envoy simply
shows upstream request timeout which is a bad user
experience
Run jsonnet autoformat
Verified that I no longer see upstream timeout on dev.kubeflow.org when spawning an image
Fixes https://github.com/kubeflow/kubeflow/issues/261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/486)
=> Use a 10 minute timeout for jupyterhub backend in envoy config

releasing.md, releasing/releaser/components/workflows.libsonnet, releasing/releaser/environments/releasing/params.libsonnet
- Update releasing.md: serving_image is not used, versionTag needs to be set.
- env/params.libsonnet: needs +{ instead of {
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/509)
=> Fix TF serving release process

README.md, components/tensorflow-notebook-image/Dockerfile, user_guide.md
ks 0.9.1 had a bug in which ks env set default --namespace=kubeflow doesn't change the namespace 
This is fixed in ks 0.9.2 so we need to update to 0.9.2.
Fixes https://github.com/kubeflow/kubeflow/issues/477
Related to #506 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/515)
=> Use ks version 0.9.2

kubeflow/core/ambassador.libsonnet, kubeflow/core/tests/ambassador_test.jsonnet
Deployed kubeflow on a new cluster and tested new ambassador by
deploying an inception model and routing traffic through ambassador
Related to https://github.com/kubeflow/kubeflow/issues/506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/513)
=> Update ambassador and statsd to 0.30.1 as part of 0.1 release

releasing.md
This commit:
1.  Adds instructions for authenticating to GCP,
2.  adds instructions for setting the right kubectl context, and
3.  ensures that workflow names are less than 63 characters.
Related to
#215 Minimal release process
#506 Cut a 0.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/493)
=> Update release instructions to ease onboarding

components/tensorflow-notebook-image/Dockerfile
Fixes #489 
@jlewi Your instructions appear to be correct for py3. Not sure why it was failing in your env. I tested with [interact](http://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html) but maybe you have something else in mind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/518)
=> Install jupyter widgets in tensorflow-notebook-image

releasing.md
This commit clarifies that a `kubeflow.org` account is not necessary to authenticate to GCP as part of cutting a Kubeflow release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/520)
=> Clarify authentication requirements in release process

components/k8s-model-server/images/releaser/components/workflows.libsonnet
The test is flaky: #484
However, it's hard to reproduce the error, so I am going to re-enable it and see.
/cc @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/497)
=> Enable tf serving gpu test

kubeflow/core/prototypes/all.jsonnet, testing/workflows/components/workflows.libsonnet
* The updated TFJob includes the fix to delete pods when job finishes
rather than leave them running.
* We need to pin the commit of the tf-operator in the extra repos so
that we checkout the tests at the commit that matches the image.
Related to #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/533)
=> Update the TFJob image in preparation for a new RC.

kubeflow/core/jupyterhub_spawner.py
tf1.4 gpu image has issues building with the latest tfma, so that's
not updated in this PR. Related  : https://github.com/kubeflow/kubeflow/issues/571
Also add tf1.7 images
/cc @jlewi
/cc @ojarjur
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/570)
=> Update tf jupter notebook images to include tfma (from #544)

kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/all.jsonnet, user_guide.md
Per discussion, we think default should be as easy to setup as possible,
and dependency on StorageClass makes it less straightforward to start
working with kubeflow. Change this default to remove need for persistent
storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/577)
=> Disable PVC by default

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
This fixes an issue that was recently uncovered for the prebuilt
images where the version of tensorflow used in the python 2.7
environment was not the one explicitly specified when building
the image.
When we set up the python 2.7 environment, the source of the
tensorflow package was getting dropped, so instead of installing
the specified version, we installed the latest version from
PyPI (which is currently 1.7).
This was uncovered when enabling the tensorflow_model_analysis
package for GPU images revealed that the installed version of
tensorflow relied on a different version of libcublas than the
one bundled in the base image.
However, this also revealed a potential issue where we were
installing tensorflow_model_analysis even if the specified
version of tensorflow did not support it. …
=> Fix the tensorflow version in prebuilt images for python 2.7.

kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/all.jsonnet, user_guide.md
Per discussion, we think default should be as easy to setup as possible,
and dependency on StorageClass makes it less straightforward to start
working with kubeflow. Change this default to remove need for persistent
storage.
* Related to #506 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/582)
=> Disable PVC by default (#577)

kubeflow/tf-serving/tf-serving.libsonnet
* CP #556 into the 0.1 release branch.
Related to #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/584)
=> Correct typo for param defaultHttpProxyImage (#556)

components/tensorflow-notebook-image/Dockerfile
This is required for pydot to work. It was accidentally removed in
https://github.com/kubeflow/kubeflow/pull/471
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/583)
=> Install graphviz in tensorflow notebook image

docs/gke/iap.md, kubeflow/argo/prototypes/argo.jsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/cert-manager.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/cert-manager.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/tests/ambassador_test.jsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet, kubeflow/core/tests/nfs_test.jsonnet, kubeflow/core/tests/spartakus_test.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/core/tf-job.libsonnet, kubeflow/seldon/crd.libsonnet, kubeflow/seldon/prototypes/core.jsonnet, kubeflow/seldon/prototypes/serve-simple.jsonnet, kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet, kubeflow/tf-job/prototypes/tf-job.jsonnet, kubeflow/tf-job/tf-job.libsonnet
Converts the IAP initContainer to a sidecar that configures IAP and monitors for changes to the backend service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/552)
=> sidecar for envoy pod to keep IAP up to date

components/tensorflow-notebook-image/Dockerfile
This is required for pydot to work. It was accidentally removed in
https://github.com/kubeflow/kubeflow/pull/471
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/585)
=> CP: Install graphviz in tensorflow notebook image (#583)

docs_dev/images.md
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/614)
=> images: Add the link

testing/test_deploy.py, testing/vm_util.py
* deploy step should wait for VM to be created and report any errors
if the VM can't be created; e.g. because of insufficient quota.
* teardown step should ensure the VM's disk is deleted so that we don't
leak disks.
* Fix a bug in wait for VM; there is no op_id since we are trying to
ssh into the VM and not executing a GCE operation.
Related to #618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/620)
=> Fix setup/teardown of VM for minikube.

testing/test_deploy.py, testing/workflows/components/workflows.libsonnet
* TestGrid relies on the regex junit_[^_]*.xml. So we don't want
any underscores other than the one after junit. This preventing
appropriate rows from being created in test_grid.
* Fix #631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/638)
=> Use dashes not underscores in junit file names.

user_guide.md
This makes it more clear how to expose the Jupyter notebook if you are
on a standalone, non-cloud node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/625)
=> Improve user guide wrt exposing notebook in non-cloud setup

kubeflow/core/tf-job.libsonnet
Drivers installation was updated recently for AKS, this PR update our ks template to reflect that change.
I'm keeping the distinction between aks and acsengine even though they are identical today, because acs-engine is going to receive the update for device-plugin pretty soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/650)
=> [Azure] Update nvidia driver volumes for AKS

docs/gke/iap.md, kubeflow/core/cert-manager.libsonnet, kubeflow/core/cloud-endpoints.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/cert-manager.jsonnet, kubeflow/core/prototypes/cloud-endpoints.jsonnet
Fixes #586 
- Import of cloud-endpoints CRD and controller. Depends on kube-metacontroller which is bundled with the component.
- Updated iap-ingress component to create the `CloudEndpoint` resource if the FQDN matches the form of `NAME.endpoints.PROJECT.cloud.goog`
- Updated the IAP doc with steps for using Cloud Endpoints.
/cc @kunmingg
/cc @ankushagarwal 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/605)
=> import of cloud-endpoints component and support in iap-ingress component

bootstrap/Dockerfile, bootstrap/Makefile
by building bootstrap package within docker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/670)
=> make Dockerfile & Makefile cross platform 

kubeflow/openmpi/assets.libsonnet
Hi, I'm really pleased kubeflow is going to support openmpi.  I'm also happy to contribute this openmpi package.  It is because I'm also developing very similar tool of [everpeace/kube-openmpi](https://github.com/everpeace/kube-openmpi/) by myself.  
current openmpi package doesn't work well on kubernetes cluster having custom dns (other than `cluster.local`) because `hostfile` includes fixed `cluster.local` string.
This PR just removed `svc.cluster.local` from `genHostfile` function.  StatefulSets depends on Headless Service to create sub-domain, and sub-domain is always under `svc.<cluster-dns>`.   So, removing `svc` is safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kube …
=> openmpi package doesn't work on kubernetes cluster having custom dns.

user_guide.md
Closes #612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/652)
=> add link to Intel's tutorial

bootstrap/README.md, bootstrap/cmd/bootstrap/app/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/680)
=> create rolebinding within namespace to guarantee permission

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, components/tensorflow-notebook-image/requirements.txt, components/tensorflow-notebook-image/start.sh
Remove a lot of bloat - install only the minimal set of packages
required to get started with ML. Any packages required can be installed
by the user in the notebook itself using pip install/conda install
Image size has gone down from 12GB to 3GB for cpu image
Having a lot of packages makes it very challenging to maintain them
because of version conflicts
Run everything as jovyan user - this enables user to run conda install
/ pip install without requiring sudo
Add comments on every step
Fixes https://github.com/kubeflow/kubeflow/issues/668
Fixes https://github.com/kubeflow/kubeflow/issues/37
Fixes https://github.com/kubeflow/kubeflow/issues/472
/assign @pdmack 
/cc @lluunn 
FYI @jlewi
--- …
=> Refactor tensorflow-notebook-image/Dockerfile

kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
introducing `schedulerName` parameter in openmpi prototype.
In Kubernetes default scheduler, scheduling multiple openmpi prototypes will sometimes lead deadlocks as discussed https://github.com/kubeflow/tf-operator/issues/165 .  Please imagine the case 2 openmpi prototypes with 100 workers were scheduled simultaneously. 
In that case,  users would want to do _gang-scheduling_ (scheduling a group of pods all-together).  Currently, [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/doc/usage/batchd_tutorial.md#3-create-poddisruptionbudget-for-application)  can achieve such scheduling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/683)
=> openmpi: make 'schedulerName'  configurable to use custom schedulers.

kubeflow/openmpi/assets/init.sh
@jiezhang Most docker images don't have apt cache (it was regularly cleaned up  in `Dockerfile`).  So we must `apt-get update` first.  I think `init.sh` should support it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/690)
=> openmpi: fix failing installing redis-tools in init.sh

bootstrap/Dockerfile, bootstrap/Makefile, bootstrap/README.md, bootstrap/cmd/bootstrap/app/server.go
1. fix https://github.com/kubeflow/kubeflow/issues/657#issuecomment-382922523
2. fix cross namespace permission
3. typo fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/699)
=> permission bug fix and image tag update

components/k8s-model-server/images/releaser/components/params.libsonnet, components/k8s-model-server/images/releaser/environments/releasing/params.libsonnet, components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, components/tensorflow-notebook-image/releaser/environments/releasing/params.libsonnet, components/tensorflow-notebook-image/requirements.txt, components/tensorflow-notebook-image/start.sh, kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet, releasing/releaser/environments/releasing/params.libsonnet, testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
/assign @ankushagarwal 
/cc @jlewi 
/cc @willb 
From Slack discussion of potentially cutting a 0.1.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/703)
=> CP to V0.1 branch: TF notebook slimming, joyvan pip installs, and new gcr.io locations

kubeflow/openmpi/assets.libsonnet, kubeflow/openmpi/service.libsonnet, kubeflow/openmpi/workloads.libsonnet
openmpi package currently creates __fixed named__ pods which are `openmpi-master`, `openmpi-worker-n`, and `openmpi-assets`.  This prevents users from creating multiple openmpi components in one namespace.  
I think prefixing component name to namespaced resource names would be preferred.
```
$ COMPONENT=c1
$ ks generate openmpi ${COMPONENT} --image ${IMAGE} --secret ${SECRET} --workers ${WORKERS} --gpus ${GPUS} --exec "${EXEC}"
$ COMPONENT=c2
$ ks generate openmpi ${COMPONENT} --image ${IMAGE} --secret ${SECRET} --workers ${WORKERS} --gpus ${GPUS} --exec "${EXEC}"
$ ks apply default
...
$ k get po,svc,cm --show-all 
NAME             READY     STATUS    RESTARTS   AGE
po/c1-master     1/1       Running   0          12s
po/c1-worker-0   1/1       Running   0          11s
po/c1-worker-1 …
```
=> openmpi: namespaced resource names should be prefixed with component name

components/openmpi-controller/.gitignore, components/openmpi-controller/Dockerfile, components/openmpi-controller/Makefile, components/openmpi-controller/controller/controller.py, components/openmpi-controller/controller/main.py, components/openmpi-controller/requirements.txt, kubeflow/openmpi/README.md, kubeflow/openmpi/all.libsonnet, kubeflow/openmpi/assets.libsonnet, kubeflow/openmpi/assets/init.sh, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
* openmpi-controller monitors the master pod's status and creates a semaphore file "term.sig" to signal openmpi-job to terminate
* openmpi-job is now decoupled from kubernetes
* openmpi-controller and openmpi-job shares a volume for inter-container communication
* openmpi-controller can be extended in the future to support data snapshot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/704)
=> [openmpi] Introduce a sidecar container for inter-pod synchronization

docs/gke/iap.md, kubeflow/core/cloud-endpoints.libsonnet
fix https://github.com/kubeflow/kubeflow/issues/709
Original problem: 
1. Service ```cloud-endpoints-controller``` will always created with default namespace, which is not accessible by other resources when user specify their namespace.
2. When generate cert-manager, user should provide namespace as well, to make sure ```issuer``` is accessible by other resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/714)
=> controller bug fix

components/tensorflow-notebook-image/requirements.txt
We removed a lot of packages in #689. Adding back a few of them
Fixes https://github.com/kubeflow/kubeflow/issues/719
/cc @jlewi 
/cc @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/724)
=> Add a few packages to the jupyter notebook image

bootstrap/Dockerfile
so we can use disk-based registry in docker and unblock https://github.com/kubeflow/kubeflow/pull/720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/725)
=> update ksonnet version to v0.10.0-alpha.3

docs/gke/iap.md
There was a spurious comma in the IAP docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/729)
=> Remove spurious comma

kubeflow/tf-serving/tf-serving.libsonnet
Was getting the following error when applying Serving template using S3 enabled:
```
ERROR handle object: can't update deployments serving.mnist-v1: Deployment.apps "mnist-v1" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`]
```
Looks like for GCP and S3 parts, metadata is not getting inserted. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/741)
=> Fix Serving metadata

kubeflow/argo/argo.libsonnet, kubeflow/argo/prototypes/argo.jsonnet
This will allow to use a specific docker image tag for the `exec` and `controller` image.
For example, I hit an issue trying: https://github.com/kubeflow/examples/tree/master/mnist I fixed it using the `v2.1.0-beta2` tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/728)
=> Argo Ksonnet package - Add Docker image Tag

components/k8s-model-server/Serve a local model using Tensorflow Serving.md, kubeflow/tf-serving/tf-serving.libsonnet, user_guide.md
As for now, tf-serving can only support model located on cloud. I changed `tf-serving.libsonnet` file, add 2 more params: `modelStorageType` and `nfsPVC`. For now, `modelStorageType` can only detect if it's `nfs`. If so, container will mount a persistentVolumeClaim(PVC) specified by `nfcPVC`. We can support more choices in the future.
A guideline for running nfs-based model is put on `components/k8s-model-server` folder.
As a new param is added, I changed `user_guide.md`, `Serve a model using Tensorflow Serving` section, and add `ks param set ${MODEL_COMPONENT} modelLocate ${MODEL_STORAGE_TYPE}`. Also give a quick guideline of `Create a component for your model located on nfs` following `Create a component for your model located on cloud`.
--- …
=> tf-serving support model on NFS

kubeflow/openmpi/README.md, kubeflow/openmpi/assets.libsonnet, kubeflow/openmpi/assets/init.sh, kubeflow/openmpi/assets/mca-params.conf, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/util.libsonnet, kubeflow/openmpi/workloads.libsonnet
cpu: CPU limits per worker.
memory: Memory limits per worker.
initTimeout: Timeout in seconds to abort the initialization.
nodeSelector: Comma-delimited list of "key=value" pairs to select the worker nodes. e.g. "cloud.google.com/gke-accelerator=nvidia-tesla-k80"
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/754)
=> [openmpi] Add more parameters for GPU training

components/openmpi-controller/Makefile, components/openmpi-controller/controller/controller.py, components/openmpi-controller/controller/main.py, components/openmpi-controller/controller/util.py, kubeflow/openmpi/assets/init.sh, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
For auto-scaling GPU node pool, the nvidia driver will be installed by [nvidia-driver-installer](https://cloud.google.com/kubernetes-engine/docs/concepts/gpus#installing_drivers).
The MPI job should be kicked off after the driver is present in the container.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/761)
=> [openmpi] Wait for nvidia driver to be installed before running MPI job

kubeflow/openmpi/all.libsonnet, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/service.libsonnet, kubeflow/openmpi/serviceaccount.libsonnet, kubeflow/openmpi/workloads.libsonnet
openmpi package _always_ creates a `ServiceAccount` and its `ClusterRoleBinding`.
However, end users who run this in batch mode sometimes are NOT allowed to create them by cluster administrator because the permission, granting `create` `ServcieAccount` and `ClusterRoleBinding`, is too strong.  Particularly, granting `create` for `ClusterRoleBinding` resources to some users nearly equal to give cluster admin rights to them. 
_NOTE: Actually openmpi prototype can work correctly if its service account can at least `get` for `pods` resources.  However I would like to handle this issue with another PR._
- introduce `serviceAccountName` paramter to openmpi prototype.  Users can specify service account name which would be provisioned by cluster administrators.  its default value is `"null"` …
=> [openmpi] make RBAC be optional

scripts/update_prototype.py
Closes #322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/769)
=> Python script to set parameters for ksonnet prototypes

kubeflow/openmpi/assets/init.sh
We mainly use Open MPI `2.1.3` because OpenMPI `3.0.1` contains some bug on GPU Direct feature.
But unfortunately `mpiexec` in OpenMPI `v2.1.3` doesn't exit properly when it couldn't resolve
hostnames of worker pods.   Consequently `wait_mpi_ready()` loop in `init.sh` will hang forever.
The only way I found to stop hanged `mpiexec` was to set `MPIEXEC_TIMEOUT` environ.  So, I put this environ only in the loop of `wait_mpi_ready()`.   I know it is a dirty hack though.
ref: https://www.open-mpi.org/doc/v2.1/man1/mpiexec.1.php#sect4
I would be happy if someone know other workarounds for it 🙇 
This was published as `everpeace/kubeflow-openmpi-21x-test:latest`.  So you don't need to build yourself.  Please check what the image contains and  proceed next step.
```
FROM ubuntu:16.04
ARG …
```
=> [openmpi]: Fix `wait_mpi_ready()` hangs when using OpenMPI 2.1.3

kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
Machine learning tasks sometimes require special hardware.  Currently we operate several custom resources on our on-premise Kubernetes cluster to run distributed machine learning tasks (with openmpi package) which requires special hardware other than GPUs.  
- introduce `customResources` parameter.   This specifies custom resources to assign `openmpi-job` containers in worker pods.
- The value should be comma separated list of `custom-resource-name=amount`.  
This feature doesn't break any backward compatibility.  So I would be very happy if it could be merged to the official repo.  But I'm not sure that such general custom resources feature should be supported in this package.  I am happy if I could have feedbacks.
Development of device plugin in kubernetes repository seems to be  very …
=> [openmpi] Add custom resources support

kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
When using openmpi package, end users often build their own docker images which would contain some their custom code and these images are possibly published to private repositories.
But, openmpi package doesn't support `imagePullSecrets` section so users can not pull from private repositories.  
In Kubernetes, I think there are two ways to pull private images.
- [Add ImagePullSecrets to a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account)
- [Create a Pod that uses your Secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret)
The first one(add secrets to service accounts) would need a strong permission, that is `edit` for …
=> [openmpi] support `imagePullSecrets`

testing/test_deploy.py, testing/workflows/components/workflows.libsonnet
Fixes https://github.com/kubeflow/kubeflow/issues/740
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/777)
=> Argo workflow e2e test

kubeflow/examples/parts.yaml, kubeflow/examples/prototypes/tf-job-simple.jsonnet, kubeflow/examples/prototypes/tf-serving-simple.jsonnet, kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet
examples package is intended to contain self-contained prototypes for
deploying tf-job, tf-serving, etc.
The idea is that users should be able to fully customize and extend
these prototypes by modifying the jsonnet
Fixes https://github.com/kubeflow/kubeflow/issues/564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/768)
=> Create an examples package in kubeflow

components/README.md, components/build_image.py, components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/versions/1.4.1/version-config.json, components/tensorflow-notebook-image/versions/1.4.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.5.1/version-config.json, components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.6.0/version-config.json, components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.7.0/version-config.json, components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json
- share the same python script to build TF notebook and TF serving (and can extend to other components)
- add gnupg to Dockerfile, otherwise got `E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation`
Still verifying all versions work.
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/791)
=> Python script to build TF notebook images

kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet, kubeflow/tf-job/prototypes/tf-job.jsonnet, kubeflow/tf-job/tf-job.libsonnet, kubeflow/tf-job/util.libsonnet
as @inc0 proposed in https://github.com/kubeflow/kubeflow/pull/771#pullrequestreview-118363134
This PR adds the support of `imagePullSecrets` (parameter name is actually in snake case) to two prototypes(`io.ksonnet.pkg.tf-job`, `io.ksonnet.pkg.tf-cnn`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/785)
=> [tf-job] support image pull secrets

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/configs/cluster.jinja.schema, docs/gke/configs/env-kubeflow.sh, docs/gke/gke_setup.md, docs/gke/testing/deploy.sh, prow_config.yaml, testing/workflows/app.yaml, testing/workflows/components/gke_deploy.jsonnet, testing/workflows/components/gke_deploy.libsonnet, testing/workflows/components/params.libsonnet, testing/workflows/environments/kubeflow-testing/main.jsonnet, testing/workflows/environments/kubeflow-testing/params.libsonnet
* The config just creates the GKE cluster we still have a lot of work to do
to get a complete solution for deploying Kubeflow.
* The goal is to provide a complete declarative solution that makes it easy to
get started with Kubeflow. The idea is the configs should provide sensible
defaults (e.g. n1-standard-8) so people can just copy it to create a good
initial setup.
* For more advanced setup users can customize the config. For example, they
might configure VPC networks as part of their deployment.
* The current thinking is that deployment manager should create the K8s cluster
and other resources (service accounts, namespaces, etc...) to run the
bootstrapper.
* Deployment manager could then kick off the bootstrapper which would create
a ksonnet app to deploy Kubeflow and then deploy …
=> Initial set of deployment manager configs for creating a GKE cluster to run Kubeflow

kubeflow/seldon/prototypes/serve-simple.jsonnet, kubeflow/seldon/serve-simple.libsonnet
This PR is related to #733 . 
As for now, `seldon/seldon-serve-simple` prototype only read model files in docker image. 
Actually, seldon-serve can read env variables to find model file in any place. 
In this PR, add one more params: `pvcName`. If `pvcName` is not "null" or "", a PVC will be created by default storage class, and is mounted in `/mnt`. 
User can put their model file in PV, and specify the model location  in predictions file (eg. [IssueSummarization.py](https://github.com/kubeflow/examples/blob/master/github_issue_summarization/notebooks/IssueSummarization.py#L20))  or in env variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/799)
=> seldon load model files from PVC

bootstrap/build_image.sh, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, testing/workflows/components/workflows.libsonnet
Change e2e test on gke: now we use bootstrapper to setup test env & resources.
Each e2e test will build bootstrapper image from PR src so e2e test now takes more time (~5min) to run.
Good news is we cover bootstrapper logic in e2e test, and it should be more stable than env-setup scripts.
Cover https://github.com/kubeflow/kubeflow/issues/742.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/803)
=> add bootstrapper to e2e test

kubeflow/core/iap.libsonnet
Fixes #809 
```
// TODO(ankushagarwal): We should eventually
// redirect to the central UI once its ready
// See https://github.com/kubeflow/kubeflow/pull/146
// Redirect to jupyterhub when visiting /
{
timeout_ms: 600000,
path: "/",
prefix_rewrite: "/hub",
use_websocket: true,
weighted_clusters: {
clusters: [
{
name: "cluster_jupyterhub",
weight: 100.0,
},
],
},
},
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/827)
=> IAP should route to central ui instead of jupyterhub

components/openmpi-controller/Dockerfile, components/openmpi-controller/Makefile, kubeflow/openmpi/assets/init.sh, kubeflow/openmpi/assets/ssh_config, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/util.libsonnet, kubeflow/openmpi/workloads.libsonnet
Fixes #793 
- introduce `runAsUser`, `runAsGroup`, `supplementalGroups` parameters.
- If these parameters set, this package will put `securityContext` to the master/worker pods.
- changed `init.sh` to support non-root users can spawn sshd servers.
- changed openmpi-controller path from `/root` to `/openmpi-controller` so that non-root users can execute the controller
- this bump version of openmpi-controller docker image.
__new openmpi-controller's docker image needs to be published before merging this__.
@jiezhang I need your assistance.  Could you build and publish `jiezhang/openmpi-controller:0.0.3` before this pr is approved 🙇  ??
--- …
=> [openmpi] support non-root users run jobs (introducing `runAsUser`, `runAsGroup`, `supplementalGroups`)

user_guide.md
Hi,
I learned about kubeflow recently and gave it a run, but it occurred to me that:
1. If there aren't enough nodes in the cluster, then creating server in browser (tf-hub-0) will wait forever.
2. When kubeflow docker image is being installed, if node doesn't have enough storage, `kubectl port-forward tf-hub-0` process will have issue.
```
E0405 13:41:46.006868   61040 portforward.go:331] an error occurred forwarding 8000 -> 8000: error forwarding port 8000 to pod 237c9ddb56660461a4328110bdbb2624eea8ef4dc5055031bd00d0c6d393a831, uid : container not running (237c9ddb56660461a4328110bdbb2624eea8ef4dc5055031bd00d0c6d393a831)
```
This updates the user guide to get around the issues. At the same time I want to raise them if maybe they can be solved without updating the user guide (pre-check …
=> Update README to reflect install experience

components/build_image.py
This is for usomg build_image.py in the release workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/840)
=> Use relative directory path so that build_image.py can be called from another dir

bootstrap/cmd/bootstrap/app/server.go, components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/pvc-check.sh, components/tensorflow-notebook-image/start-singleuser.sh, kubeflow/core/kubeform_spawner.py, kubeflow/core/tests/jupyterhub_test.jsonnet, user_guide.md
Put all of /home/jovyan on a PVC when using PVC with Jupyter notebooks.
* One consequence of mounting a PVC at /home/jovyan is that any files placed in /home/jovyan will be
hidden by the PVC once its mounted
* We take two approaches to solving this
* We move most things we care about (e.g python pip/conda packages in /home/jovyan ) to other locations e.g. /opt that won't be overwritten
* Files that need to be in /home/jovyan like jupyter_notebook_config.py are copied on container
start into /home/jovyan so that they will be copied onto the PVC
Fixes #561 
/cc @jlewi 
/cc @inc0 
~~Pretty much what @jlewi described. Dockerfile installs conda, pip, etc. in situ at `/home/jovyan` then we tar it up to `/tmp` and remove the content at `/home/jovyan`. Then `start-singleuser.sh` invokes a new …
=> Modify NB Dockerfile and start scripts to support mount of /home/jovyan 

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/configs/env-kubeflow.sh, docs/gke/gke_setup.md
* This config creates the K8s resources needed to run the bootstrapper
* Enable the ResourceManager API; this is used to get IAM policies
* Add IAM roles to the cloudservices account. This is needed so that
the deployment manager has sufficient RBAC permissions to do what it needs
to.
* Delete initialNodeCount and just make the default node pool a 1 CPU node pool.
* The bootstrapper isn't running successfully; it looks like its trying
to create a pytorch component but its using an older version of the registry
which doesn't include the pytorch operator.
Related to: #802 Use deployment manager to run bootstrapper
Related to #802 On GCP trigger bootstrapper with deployment manager
Related to #757 Install Kubeflow via deployment manager
Related to  #833 Internal errors
--- …
=> Start deploying the bootstrapper via deployment manager.

components/k8s-model-server/images/Makefile
This PR fixed two small issues when pushing the tf-serving image to dockerhub:
* For pushing to dockerhub the official registry, the base URL should be `registry.hub.docker.com` or `docker.io`
* `push_gpu_dockerhub` should be `docker push`, I believe it was a typo when copying from `gcloud docker -- push`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/857)
=> Fix push_dockerhub in k8s-model-server/images/Makefile

bootstrap/Dockerfile, bootstrap/bootstrapper.yaml, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/config/default.yaml, bootstrap/config/gcp_prototype.yaml, testing/e2e_env.yaml, testing/workflows/components/workflows.libsonnet
This provide us flexibility to control kubeflow resources when facing different code version / env. 
solve https://github.com/kubeflow/kubeflow/issues/829
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/853)
=> Use yaml config to manage k8s resources deployed by bootstrapper

scripts/autoformat_jsonnet.sh
Update the script so that we don't assume that the remote repository is named origin.
Instead search for all remote repositories and select the correct one
based on remote URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/867)
=> Update the script so that we don't assume that the remote repository is

kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/tf-job-operator.jsonnet, kubeflow/core/tf-job-operator.libsonnet
* K8s doesn't support installing multiple versions of a CRD in the same cluster.
* So we add an option to choose which version to support.
* We don't add an E2E test in this PR because its not straightforward.
Currently the E2E test deploys Kubeflow in a different namespace but not
a different cluster. This won't allow us to simulatenously test both
versions.
* So to test multiple versions we will need to spin up a separate GKE cluster.
Related to: kubeflow/tf-operator#599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/851)
=> ksonnet changes to support deploying the v1alpha2 TFJob operator.

docs/gke/configs/cluster.jinja, testing/deploy_kubeflow.py, testing/deploy_kubeflow_gcp.py, testing/deploy_utils.py, testing/teardown_kubeflow_gcp.py, testing/workflows/components/gke_deploy.libsonnet, testing/workflows/components/params.libsonnet
* The scripts replaces our bash commands
* For teardown we want to add retries to better handle INTERNAL_ERRORS
with deployment manager that are causing the test to be flaky.
Related to #836 verify Kubeflow deployed correctly with deployment manager.
* Fix resource_not_found errors in delete (#833)
* The not found error was due to the type providers for K8s resources
being deleted before the corresponding K8s resources. So the subsequent
delete of the K8s resource would fail because the type provider did not
exist.
* We fix this by using a $ref to refer to the type provider in the type field
of K8s resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/866)
=> Create a python script to deploy Kubeflow on GCP via deployment manager.

components/tensorflow-notebook-image/Dockerfile
Fixes #850 
Re-enables git ssh push/pull within NB container.
/assign @ankushagarwal 
/cc @cwbeitel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/882)
=> Restore openssh-client to NB images

docs/gke/configs/cluster.jinja
Having longer names leads to errors with objects which have limits on
their names. Deployment name is concise enough to name objects.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/893)
=> Use deployment name as the NAME_PREFIX and CLUSTER_NAME

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja
Add option for
* Private Clusters
* Separate Service Account
* masterIpv4CidrBlock
* Pod Security Policy
* Secure Node Metadata
* Authorized Networks for k8s Master
* Reduce oauth scopes for worker nodes and replace it with gke-default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/879)
=> Add GKE Security Features to Deployment Manager config

components/tensorflow-notebook-image/pvc-check.sh, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet
Fixes kubeflow/testing#144 and more generally merges PVC from the spawner config and any provisioner. Tested in dev.kubeflow.org.
/cc @jlewi 
/cc @ankushagarwal 
/cc @inc0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/892)
=> Merge PVC from spawner and provisioners

bootstrap/Dockerfile, bootstrap/Makefile, bootstrap/build.py, bootstrap/build_image.sh, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/config/default.yaml, bootstrap/config/gcp_prototype.yaml, testing/e2e_env.yaml, testing/workflows/components/workflows.libsonnet
For https://github.com/kubeflow/kubeflow/issues/880
Bootstrapper now can apply and update ksonnet apps from multi repos.
Users now can one-command-deploy any custom ksonnet apps set through bootstrapper. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/900)
=> Make bootstrapper support multi ks registry, including private ones

components/jupyterhub/docker/Dockerfile, components/jupyterhub/docker/Makefile, kubeflow/core/prototypes/all.jsonnet
* JupyterHub 0.9 is now available and 0.8 for Kubespawner.
* These updates include improvements that should help with UX when spawning
notebooks by providing more information about progress.
* As part of this change we switch to using the JupyterHub image as our
base image and only installing the additional modules that we care about.
* It looks like the original image was manually intalling nodejs presumably
to support the javascript proxy inside JupyterHub. If nodejs is needed
by jupyterhub then I expect it to be included in the official image
so we shouldn't need to manually install it.
* I verified this manually by spinning up a new JupyterHub instance using this image
* The spawner provides a much greater UI
* The UI shows K8s events e.g. "notebook spawned"
* It also has a status bar …
=> Upgrade jupyterhub and kube_spawner

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/configs/env-kubeflow.sh, docs/gke/create_k8s_secrets.sh, docs/gke/gke_setup.md, kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/cloud-endpoints.jsonnet
* Create a service account to be used to authorize TFJobs and other work
within the cluster.
* Create a helper script to download service account keys and turn
them into K8s keys
* Fix some bugs in the docs.
* Fix #878 create a GCP service account for the user.
* IAP script needs a GCP service account with network admin privileges.
* Add network admin privileges to the admin service account.
* Name the secrets in K8s so that be default the names are the same across
the deployments. This way there's one less parameter to set for
every deployment.
* VM service account should have a unique name per deployment so deployments
are isolated.
* Need to grant the VM service account logs and monitoring access to support
monitoring.
* I don't think there's any reason to allow user to specify name of …
=> Improvements and bug fixes in DM config.

kubeflow/core/tf-job-operator.libsonnet
related to: kubeflow/tf-operator#437
Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/874)
=> tfjob(v1alpha2): Add validation

kubeflow/katib/modeldb.libsonnet, kubeflow/katib/parts.yaml, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/suggestion.libsonnet, kubeflow/katib/vizier.libsonnet, kubeflow/registry.yaml
Katib ksonnet components, following what are deploying in
https://github.com/kubeflow/katib/blob/master/scripts/deploy.sh
Fix https://github.com/kubeflow/katib/issues/32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/873)
=> Katib ksonnet package

components/tensorflow-notebook-image/Dockerfile
Fixes #906 
PTAL
/cc @jlewi 
/cc @ankushagarwal 
Are we good with just dropping the `--user` py2 install and letting it get installed to `/opt/conda/envs`? Are there some other tests I should try?
Also, should we install the Beam pkg @jlewi was referring to in #906 while we're here?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/907)
=> Install py2 to global conda env

testing/workflows/components/workflows.libsonnet
Since we copy test artifacts to GCS, it should be safe to delete the test directory. Otherwise it keeps growing and runs out of disk.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/926)
=> Delete test directory after test completes

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/gke_setup.md
* Tested this works if users isn't specified or if users is specified.
* For the VM service account we should be using KF_VM_SA_NAME
* We want to use unique service accounts for each deployment. This creates
fewer problems/interference between deployments.
Fix #883
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/928)
=> DM config should allow setting users/groups to grant IAP access to.

bootstrap/cmd/bootstrap/app/server.go, bootstrap/cmd/bootstrap/main.go
fix https://github.com/kubeflow/kubeflow/issues/901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/921)
=> keep bootstrapper pod alive when error occurs

testing/dm_configs/cluster.jinja
Tests sometimes run in parallel and patching iam policy in parallel
is not allowed. It leads to failure in deployment manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/936)
=> Remove service account creation in testing deployment manager

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/env-kubeflow.sh, docs/gke/gke_setup.md
related to https://github.com/kubeflow/kubeflow/issues/927.
This bug should be covered by e2e test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/931)
=> fix vm service account config, doc update

docs/gke/configs/cluster.jinja, docs/gke/create_k8s_secrets.sh, kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/iap.libsonnet, kubeflow/core/setup_iap.sh
* We want a single process to update the backend service and IAP.
Right now we do this in the envoy side car which is replicated.
* The script gets a lock to prevent multiple services from trying to update
IAP simultaneously.
* But until the process acquires the lock it can't update the local copy
of the envoy config to do proper JWT validation.
* So we move updating the backend into a separate deployment that has a single
replica 1 (although we still use a lock).
* envoy sidecars now do not modify the backend but just get relevant info
and update the envoy config.
* To support getting the ksonnet app of the bootstrapper add source repository
IAM role to the admin service account and mount the service account
into the bootstrapper.
This will allow use to push the ksonnet app from the …
=> Prevent deadlocks trying to setup IAP.

testing/deploy_kubeflow_gcp.py, testing/dm_configs/cluster-kubeflow.yaml, testing/workflows/components/workflows.libsonnet
* Update deploy_kubeflow_gcp to add tfjob_version flag
* In GKE Testing workflow, bring up two k8s clusters - one to test v1alpha1 and other to test v1alpha2
* Deploy kubeflow on both clusters using bootstrapper - set tfjob_version different for both clusters
* Using different kubeConfig for both clusters
* Teardown both clusters at the end
Fixes https://github.com/kubeflow/kubeflow/issues/852
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/918)
=> Run v1alpha1 and v1alpha2 TfJob tests in GKE workflow

bootstrap/.gitignore, bootstrap/Makefile, docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/create_k8s_secrets.sh, docs/gke/gke_setup.md, docs_dev/releasing.md, kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/setup_iap.sh
* docks/gke/configs/cluster-kubeflow.yaml was out of date and needed to
be updated to work with the latest bootstrapper to image.
* Update the bootstrapper image so we pull in the latest registry configs.
* Make the instructions cleaner about what steps need to be performed to
configure gcp.
* create_k8s_secrets.sh needs to create the kubeflow namespace because the
namespace won't exist yet because the bootstrapper hasn't run because
its blocked waiting for the GCP key.
* Don't include git tags in the image tag for the bootstrapper image.
* cluster-kubeflow.yaml is using the wrong name for the GCP service account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/956)
=> A bunch of fixes to the DM configs for GCP to work with latest bootstrapper

testing/workflows/components/workflows.libsonnet
* The v1alpha2 test probably shouldn't be using MNIST anyway; we should be
running a smoke test as in v1alpha1.
Related to #974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/975)
=> Disable the v1alpha2 test because it is failing because mnist data can't be downloaded.

docs/gke/configs/cluster.jinja
* Source admin permission was granted to cloud services account but
that service account is only used by deployment manager and shouldn't
need source admin.
* We want the Kubeflow service accounts to have access to source admin
so that we can push the ksonnet app to source control and so that users
can access their code in pods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/965)
=> Source admin role should be granted to KF service accounts.

bootstrap/cmd/bootstrap/app/server.go, bootstrap/config/gcp_prototype.yaml
1. fix https://github.com/kubeflow/kubeflow/issues/954:
```ks apply``` allow us to define CRDs and use them during same apply action,
while ```ks show | kubectl apply``` doesn't guarantee so.
2. edit gcp_prototype.yaml following new format to make sure it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/976)
=> use ks apply in bootstrapper to avoid creation ordering issue

testing/vm_util.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/987)
=> Retry on ssl.SSLError in vm_util - this resolves test flakiness

docs/gke/configs/cluster.jinja
Fix https://github.com/kubeflow/kubeflow/issues/910.
Fix https://github.com/kubeflow/kubeflow/issues/953.
Deploy manager iam role works similar to k8s multi-pod locks: one version can only have one consumer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1001)
=> fix iam role delete for deployment manager

testing/tf_job_simple_test.py, testing/workflows/components/workflows.libsonnet
tf_job_simple_test.py tests the tf-job-simple prototype by creating a tfjob from that prototype and checking that the appropriate pods and service accounts get created
Fixes https://github.com/kubeflow/kubeflow/issues/462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1010)
=> Add test for tf-job-simple prototype

ack_guide.md, bootstrap/bootstrapper.yaml, docs/gke/configs/cluster-kubeflow.yaml, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/tf-job-operator.jsonnet, testing/deploy_kubeflow.py
Fix https://github.com/kubeflow/kubeflow/issues/977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1012)
=> Set default version of TFJob operator to be v1alpha2

kubeflow/examples/prototypes/tf-job-simple.jsonnet, kubeflow/examples/prototypes/tf-serving-simple.jsonnet, kubeflow/examples/prototypes/tf-serving-with-istio.jsonnet
This fixes the hard coded "name" variable in the example prototypes so that it can take the value from exposed parameters and be compatible with the user guide.
The other hard coded variables remain as-is to keep it simple. However they could also be modified in the same way, if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1013)
=> Fix hard coded "name" variable in example prototypes

components/centraldashboard/frontend/index/index.html
Fix #810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1016)
=> Add a link to JupyterHub in the CentralUI

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet
The permissions handed out in the jupyter-role were allowing "*" in the
apiGroups, in stead of "". This means that it gives permissions to all
different kinds of apiGroups, in stead of the default one, which is
actually sufficient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/978)
=> Fix permissions for jupyter-role

kubeflow/core/kubeform_spawner.py
* There's no reason to upgrade to a more recent Jupyter image because it
looks like the last change to the images was #907 on 06/05.
Fix #1014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1015)
=> Include the TF 1.8 image in kubeform_spawner.

user_guide.md
This fixes the user guide so that it works with the refactored tf-cnn
exampe in the examples package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/995)
=> Fix user guide for the refactored tf-cnn example

bootstrap/bootstrapper.yaml, docs/gke/configs/cluster-kubeflow.yaml
fix https://github.com/kubeflow/kubeflow/issues/1018.
Will cherry pick to ```v0.2-branch```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1021)
=> update bootstrapper image to use tfJobsVersion v1alpha2 as default

kubeflow/core/centraldashboard.libsonnet, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tests/centraldashboard_test.jsonnet
* Expose central UI image as a parameter.
* We want to pin the central UI image to a particular version so that updates
to latest don't break users.
Related to #805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1019)
=> Pin the central UI image.

components/k8s-model-server/images/versions/1.7gpu/version-config.json, kubeflow/tf-serving/tf-serving.libsonnet
9.1 is not supported by driver now.
Fix #1009 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1030)
=> Update TF serving 1.7 gpu image to use cuda 9.0

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
1. Kept default workers to 1 which is needed for distributed training. 
2. Removed num_ps parameter which is unused incase of pytorch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1040)
=> Changing defaults in Pytorch-job

releasing/apply_image_tags.py, releasing/image_tags.yaml
* See #1060
* Use a YAML file to keep track of a map from images referenced by sha
to tags to apply
* Add a script to apply the tags as listed in the YAML file.
* This will make it easy to promote images as part of our release process.
* I think a next step is to create a script to automate updating image_tags.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1061)
=> Some scripts to support retagging our images as part of our releases.

docs_dev/releasing.md, kubeflow/core/kubeform_spawner.py, releasing/add_image_shas.py, releasing/add_image_tag.py, releasing/apply_image_tags.py, releasing/image_tags.yaml, releasing/update_image_tags.sh, releasing/update_ksonnet.sh
* Provide some python scripts to match images and then apply a tag to
them like "v0.2.0". This makes it possible to easily apply a new release
tag to set of images like the Jupyter images.
* Creeate a shell script to use sed and other twos to update images
in our ksonnet prototypes.
* Add instructions for doing this.
* I used the scripts to add the v0.2.0 tag to our Jupyter images.
Related to #1060
/assign @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1066)
=> Tooling to make it easier to tag images and update the ksonnet prototypes

testing/test_deploy.py
Fixes https://github.com/kubeflow/tf-operator/issues/696
The error appears when building tf-operator but the fix applies to testing/test_deploy.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1084)
=> fix for file_cache is unavailable when using oauth2client >= 4.0.0

kubeflow/katib/modeldb.libsonnet, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/suggestion.libsonnet, kubeflow/katib/vizier.libsonnet
This change will make easier to pin Katib to any version we have images
for. Once we tag images with 0.2.0 for Katib, we should pin this to
0.2.0 in Kubeflow branch as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1085)
=> Add katib tag to images

releasing/update_images.sh
* Looks like instructions were already added in #1066
Related to #1060 
/assign @kunmingg 
/assign @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1063)
=> Create a script to update some of the docker images in the prototypes

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/kubeform_spawner.py
We want to launch pods and jobs from the jupyter notebook, hence
attaching a service account to it with appropriate permissions
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1110)
=> Add a jupyter-notebook-role and use it for notebooks in jupyterhub

hack/retag_katib_images.sh, kubeflow/katib/modeldb.libsonnet, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/suggestion.libsonnet, kubeflow/katib/vizier.libsonnet
* The latest images are too old; we should be using the images with tag "master"
* For the 0.2 release we want to pin the images to specific images which
we tag 0.2.0
* Delete the protoype parameter katibImagTag; image parameters should provide
the full image reference including the tag. This makes it much easier
to override certain images and is consistent with other components.
* Create a simple, oneoff script to retag the existing Katib images into
the Kubeflow image repository
* We most likely won't ever use this again but its good to leave a paper
trail.
Related to:
kubeflow/katib#133 Katib images in 0.2.0-rc.1 are too old
* Will need to cherry pick this.
Fix kubeflow/katib#132 Get rid of katibImageTag
Fix kubeflow/katib#131 Katib prototype needs to pin docker images
---
This change …
=> Pin and fix katib images.

hack/retag_katib_images.sh, kubeflow/katib/prototypes/all.jsonnet
* The latest images are too old; we should be using the images with tag "master"
* For the 0.2 release we want to pin the images to specific images which
we tag 0.2.0
* Delete the protoype parameter katibImagTag; image parameters should provide
the full image reference including the tag. This makes it much easier
to override certain images and is consistent with other components.
* Create a simple, oneoff script to retag the existing Katib images into
the Kubeflow image repository
* We most likely won't ever use this again but its good to leave a paper
trail.
Related to:
kubeflow/katib#133 Katib images in 0.2.0-rc.1 are too old
* Will need to cherry pick this.
Fix kubeflow/katib#132 Get rid of katibImageTag
Fix kubeflow/katib#131 Katib prototype needs to pin docker images
---
This change …
=> Pin and fix katib images. (#1113)

components/tensorflow-notebook-image/Dockerfile
* We need to install & enable the extensions system wide; otherwise the relevant
config changes are stored in /home/jovyan and the changes are lost
when we mount a PV in /home/jovyan.
* It doesn't look like we need to change the command
jupyter labextension install @jupyter-widgets/jupyterlab-manager
* It doesn't take a --system flag and it looks like its already installed
system wide.
jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
* Related to #1130
/assign @pdmack 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1131)
=> Fix TFMA jupyter extensions.

kubeflow/core/metric-collector.libsonnet, kubeflow/core/prototypes/metric-collector.jsonnet, metric-collector/Dockerfile, metric-collector/Makefile, metric-collector/service-readiness/kubeflow-readiness.py
fix https://github.com/kubeflow/kubeflow/issues/955
Provide stackdriver/prometheus compatible data exporter, monitoring kubeflow status after deployment: 
the signal ```kubeflow_availability==1``` means https url behind IAP can be logged in with credentials.
How to integrate:
1. directly access port 8000 on pod.
2. read through stackdriver (if beta feature turned on for cluster).
3. read through prometheus engine (if deployed in cluster).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1123)
=> add service monitor prototype for monitoring deployment status

scripts/gke/deploy.sh, scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml, scripts/gke/deployment_manager_configs/cluster.jinja, scripts/gke/deployment_manager_configs/cluster.jinja.schema, scripts/gke/teardown.sh, scripts/minikube/deploy.sh, scripts/util.sh
* Move away from using bootstrapper by doing everything locally
* Try to use gcloud to infer as much as possible (PROJECT, ZONE, EMAIL, etc.)
* Delete k8s resources from DM configs
* Require prerequisite of gcloud, kubectl and ks
TODO(ankushagarwal): Add integration test for this. 
TODO(ankushagarwal): Delete https://github.com/kubeflow/kubeflow/tree/master/docs/gke/configs
Fixes https://github.com/kubeflow/kubeflow/issues/1068
After this PR the getting started experience for kubeflow on GKE:
```
git clone https://github.com/kubeflow/kubeflow/
cd kubeflow
git checkout v0.2.0-rc.1
./scripts/gke/deploy.sh
```
We can get rid of `CLIENT_ID and CLIENT_SECRET` step soon
After this the getting started experience for kubeflow on GKE:
```
git clone https://github.com/kubeflow/kubeflow/
cd kubeflow …
```
=> Create a deployment script for gke and minikube

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
* See if this makes the build more reliable and faster
* We should really be setting disk space because it looks like (see #1135)
that is one resource that is under pressure. Need to figure out
if that is easy to control with K8s.
Related to:
#1135 Docker image building workflows are failing
#1132 Building Jupyter images took over 4 hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1136)
=> Set requests and limits for RAM and CPU in TF notebook image releaser.

testing/tf_job_simple_test.py, testing/vm_util.py
* Skip install the default registries because we don't need them and talking
to Git just creates a source of flakiness.
* Add retries to setting up the ksonnet app.
Fix #1128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1133)
=> Make the test robust to test flakes due to problems initializing the ksonnet app

components/centraldashboard/frontend/Makefile
Properly compute the git tag for the central ui image.
* The existing tag was not a valid GIT commit.
* Add a docker image label containing the git version of the code for
the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1149)
=> Fix the makefile so that we tag the image with the comit.

scripts/upgrade_ks_app.py
* Related to: kubeflow/website#57
* Based on the script in ksonnet/ksonnet#237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1100)
=> Create a script to update a ksonnet app to the latest Kubeflow package

testing/workflows/components/workflows.libsonnet
* Project should already be setup (e.g. APIs enabled). The project
setup tests just lead to test flakiness.
Fix #1158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1162)
=> Skip project setup during deployment.

testing/teardown_kubeflow_gcp.sh, testing/workflows/components/workflows.libsonnet
Deleting the namespace deletes ingress objects which deletes the GCP
resources associated with it like backends, instance groups,
healthchecks, etc.
This PR should help with resource leaks in the kubeflow-ci project and quota issues
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1167)
=> Delete kubeflow namespace before deleting the cluster

scripts/gke/deployment_manager_configs/cluster.jinja
This allows us to submit docker builds to google cloud container builder
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1163)
=> Give KF_USER_NAME service account roles/cloudbuild.builds.editor role

docs_dev/releasing.md, kubeflow/core/kubeform_spawner.py, releasing/README.md, releasing/apply_image_tags.py, releasing/image_tags.yaml, releasing/run_apply_image_tags.sh, releasing/update_image_tags.sh, releasing/update_images.sh, releasing/update_ksonnet.sh
* These images includes fixes to TFMA in the Jupyter images.
* Related to #1129 - Upgrade images for 0.2.1
* Related to #1130 - Fix TFMA
* Upgrade the images in the ksonnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1170)
=> Cherypick: Tag the latest Jupyter images with v0.2.1 (#1144)

scripts/gke/deploy.sh, scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml, scripts/gke/deployment_manager_configs/cluster.jinja, scripts/gke/deployment_manager_configs/cluster.jinja.schema, scripts/gke/teardown.sh
Cherry pick #1164
* Sync the contents of scripts/gke to what's on upstream/master because
we want to use the new deploy.sh script with v0.2. This doesn't depdend
on the bootstrapper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1172)
=> Make GKE VM service account storage.objectViewer to have read access of gcr #1164

scripts/deploy.sh, scripts/gke/deploy.sh
* Download tarballs of the repo; this avoids GITHUB API token limits
and is much faster because it avoids GitHistory
* Install most of the packages into the app so that the user won't
have to do that step to start using other packages.
* Move scripts/minikube/deploy.sh to scripts/deploy.sh - This script is generic and will work for any existing K8s cluster not just minikube.
Fix #1154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1174)
=> Make the deploy scripts more efficient and other fixes.

docs/gke/README.md, docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja, docs/gke/configs/deploy.sh, scripts/deploy.sh, scripts/gke/deploy.sh, scripts/gke/deployment_manager_configs/cluster.jinja, scripts/upgrade_ks_app.py, scripts/util.sh
* Make the deploy scripts more efficient and other fixes.
* Download tarballs of the repo; this avoids GITHUB API token limits
and is much faster because it avoids GitHistory
* Install most of the packages into the app so that the user won't
have to do that step to start using other packages.
Fix #1154
* Enable anonymous usage collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1180)
=> Make the deploy scripts more efficient and other fixes. (#1174)

kubeflow/core/prototypes/all.jsonnet
* PV is working reliably now and its a better default experience to have
notebooks backed up. Users who don't have a default storage class can disable
it.
Fix #1187
/assign @pdmack 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1188)
=> Use PV for /home/jovyan by default

scripts/gke/deployment_manager_configs/cluster.jinja
roles/viewer is required for viewing the logs of a GCB build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1185)
=> Grant roles/viewer to kubeflow user service account

scripts/deploy.sh, scripts/deploy_test.sh, scripts/gke/deploy.sh, scripts/gke/deploy_test.sh
* Fix deploy.sh moving the unpacked repo.
* It looks like GitHub is stripping out the v in the name of the top level
directory.
Make the scripts less brittle by not assuming the top level directory
will be named a certain way.
Related to 1193.
* Fix indent.
* * Add simple test scripts to verify that the configs are created
* Add an option to gke/deploy.sh to skip deployment to facilitate testing
* Add an option to gke/deploy.sh to not recreate the DM configs if they
already exist; the sed commands assume we are starting from scratch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1196)
=> Cherrypick #1194 to master - Fix deploy.sh moving the unpacked repo

scripts/cleanup_kubeflow_ci.sh
This script cleans up ingress related compute engine resources like backend-services,
forwarding rules, health-checks, etc. from kubeflow-ci project which
do not belong to the kubeflow-testing cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1199)
=> Add a script to cleanup leaked kubeflow-ci ingress resources

components/contrib/kaggle-notebook-image/Dockerfile, components/contrib/kaggle-notebook-image/README.md
Related to  #1057 - pytorch notebook image
Related to #258 - Kaggle image
PTAL
/cc @jlewi 
/cc @ankushagarwal 
/cc @johnugeorge 
Launched for me but obviously not exhaustively tested. Created a contrib dir to give it that YMMV vibe.
Notes (IMHO):
- py3 only
- we should just manually build/push to gcr.io once per release, no other support
- definitely should not be in any argo or release workflows
- waaaay too big an image, there may be some slimming that could be done with my mods but almost certainly it would remain north of 20 Gb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1109)
=> Add Kaggle notebook Dockerfile

kubeflow/core/tf-job-operator.libsonnet
Fix [Unable to check logs in TFJob ui for v1apha2](https://github.com/kubeflow/tf-operator/issues/723)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1210)
=> fix tf-job-dashboard fails to show logs

docs_dev/tf_serving.md
/cc @jlewi 
/cc @ynqa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1165)
=> Add doc for TF Serving

bootstrap/Dockerfile, bootstrap/Dockerfile.Builder, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/cmd/bootstrap/app/server_test.go, bootstrap/cmd/bootstrap/main.go, bootstrap/glide.lock, bootstrap/glide.yaml, bootstrap/hack/send_ks_request.py, bootstrap/start.sh, scripts/run_gofmt.sh
We have two use cases.
We want to create a click to deploy web app. This will be a client side
javascript app. This app needs a way to run ksonnet. We will do that
by deploying the bootstrapper on the K8s cluster and then sending RPCs.
Using RPCs will allow the web app to send a bearer token containing user
credentials to do authorization so that we don't need to give the RPC
elevated permissions.
We also want a microservice to do ksonnet substitution that can be used
with hyperparameter tuning to fill in the hyperparamters into a template.
Fix #962 handle file and http registries in a consistent manner.
* The AppConfig can now specify registries consisting of a (name, URI)
pair. URI can be anything ks registry add supports (e.g. file or git link).
* Registries that have been prefetched …
=> Turn bootstrapper into an RPC server for ksonnet.

components/gcp-click-to-deploy/public/index.html, components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/DeployForm.tsx, components/gcp-click-to-deploy/src/Gapi.ts, components/gcp-click-to-deploy/src/Header.tsx, components/gcp-click-to-deploy/src/Utils.ts
This PR uses the Service Management API to enable any required services that are disabled before proceeding with the deployment. It does this by listing services, and enabling the disabled ones in a loop until the listed services include all of the required ones.
Additionally, the PR also adds Google Sans font.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1235)
=> [gcp-deployer] Enable required GCP services before deploying

scripts/gke/deploy.sh
Fix #1233 
/cc @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1243)
=> Fix deploy.sh when re-trying on existing deployment name

prow_config.yaml
Scoping the kubeflow workflows such that:
- GKE is run on pre and postsubmit jobs
- Minikube is only run on postsubmit jobs
- TF-serving-image is only run when tf-serving directory is modified
Fix kubeflow/testing#150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1244)
=> Scope kubeflow prow jobs by job type and modified dirs

components/gcp-click-to-deploy/src/App.tsx
* We want to link kubeflow.org not github.com/kubeflow
/assign @yebrahim
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1236)
=> Fix link on front page.

testing/workflows/components/workflows.libsonnet
* kubeflow/tf-operator#749 renamed the prototype
* ksonnet just fails silently if the component doesn't exist so the test just ends up failing with 404 trying to wait for the job.
* Fix 1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1267)
=> Fix tfjob test; the simple tfjob test prototype was renamed.

kubeflow/tf-serving/tf-serving.libsonnet
- remove unnecessary logic of http proxy image
- http proxy requests lower resource
Fix #360 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1270)
=> Small fix to tf serving component

docs_dev/kubeflow_deployment.md
* This is not a proposal but a description of the current state.
/assign @ankushagarwal 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1159)
=> Create a doc to describe the deployment process.

scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml, scripts/gke/deployment_manager_configs/cluster.jinja
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1273)
=> Enable GKE node-pool autoscaling options

scripts/gke/deploy.sh
* Check if resources like secrets already exist and if they do don't
recreate them.
* Prevent users from checking in their GCP secrets
1. Store them in a directory with a .gitignore file
2. Remove the secrets as soon as we are done storing them in the cluster.
* Allow GCFS_INSTANCE to be set to null; e.g.
export GCFS_INSTANCE=
If GCFS_INSTANCE is null don't set it to some default value; instead
we interpret this as the user doesn't want GCFS to be installed.
* Related to #1282 can't create GCFS for legacy network.
* Related to #1284 support rerunning deploy.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1290)
=> Make it easier to rerun deploy.sh

kubeflow/katib/README.md
This goes hand in hand with https://github.com/kubeflow/website/issues/72, which is now fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1292)
=> Pointing katib doc to kubeflow/website

kubeflow/tf-serving/tf-serving.libsonnet
Most of people will use env name as key in secret, might as well make it
default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1304)
=> Add reasonable default to tf-serving s3 creds

bootstrap/cmd/bootstrap/app/SaKey.go, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/glide.lock, bootstrap/glide.yaml
Add 2 handlers to web app go backend:
service account key handler: 
given service account and tmp token, create service account key and insert into GKE cluster.
check health handler
check if backend respond to post request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1329)
=> [gcp-deployer] add service account key handler and a check health handler

prow_config.yaml, testing/deploy_kubeflow.py, testing/wait_for_deployment.py, testing/wait_for_kubeflow.py, testing/workflows/components/kfctl_test.jsonnet, testing/workflows/components/params.libsonnet, testing/workflows/components/unit_tests.jsonnet, testing/workflows/components/workflows.libsonnet, testing/workflows/environments/kubeflow-testing/params.libsonnet
* Update wait_for_deployment.py to use KUBECONFIG so its not limited to GKE.
* I don't think we actually need wait_for_deployment; all it does is wait
for the CRD to be created and that's not very useful. It would
be better to wait for the actual controller deployments to start.
* Create a script wait_for_kubeflow based on deploy_kubeflow.py that
waits for Kubeflow to be deployed and performs basic checks like
ensuring everything started correctly.
* Fix a typo in wait_for_kubeflow
* Add steps to copy artifacts to prow bucket.
* Create a workflow for unittests."
* Don't run workflows.jsonnet on presubmit; we use kfctl_test now.
* Add an option to kfctl_test to not delete the cluster; useful
for leaving it up to debug tests.
Related to: #1325 Make our E2E tests more reusable and …
=> Add more tests to the subgraph we created to run the tests.

kubeflow/core/jupyterhub.libsonnet
Jupyter connections are failing because Ambassador rules don't not enable websockets.
Fix #1344
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1345)
=> fixes issue #1344

scripts/kfctl.sh
Platform deletion was improperly being triggered on what= k8s and not what=platform; this was a bug.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1360)
=> fix 'kfctl.sh delete platform'  doesn't delete platform correctly.

bootstrap/Dockerfile, bootstrap/bootstrapper.yaml, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/config/default.yaml, bootstrap/config/gcp_prototype.yaml, bootstrap/glide.lock, bootstrap/glide.yaml, bootstrap/image_registries.yaml
Now both ksonnet app and go library have version 0.11.0.
Bug fixes:
1. create namespace for create-app request if not already exists.
2. read RegUri from know-registries config if not exist in create-app request.
3. API change following version upgrade.
fix https://github.com/kubeflow/kubeflow/issues/1340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1356)
=> ks version update to 0.11.0, and bug fixes.

kubeflow/core/prototypes/tf-job-operator.jsonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1341)
=> Update TFJob operator to the latest image.

kubeflow/core/jupyterhub.libsonnet
Deploying `Jobs` is a common use case and was missing earlier. This PR makes the tiny change.
/cc @ankushagarwal @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1374)
=> Add Jobs permission to jupyterhub-noteook role to  for common use cases

kubeflow/core/jupyterhub.libsonnet
Role groups for a few resources were not correct.
- `deployments` belongs to `apps` group (and also `extensions` for compatibility with older versions)
- `jobs` belongs to `batch` group
- Allow all resource verbs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1380)
=> Fix groups for various resources

testing/install_minikube.sh
Fixes https://github.com/kubeflow/kubeflow/issues/1383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1384)
=> Fixes the install_minikube.sh script for non-Ubuntu OSes

kubeflow/core/tf-job-operator.libsonnet
This fixes the 500 errors in tf-job-dashboard
Related to kubeflow/tf-operator#754
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1397)
=> Add namespaces to the tf-job-dashboard role

kubeflow/core/cert-manager.libsonnet, kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/iap.libsonnet, kubeflow/core/ingress_bootstrap.sh, kubeflow/core/metric-collector.libsonnet, kubeflow/core/prototypes/cert-manager.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/setup_backend.sh, kubeflow/core/tests/iap_test.jsonnet, scripts/gke/deployment_manager_configs/cluster.jinja
- Added k8s job for patching ingress with the TLS spec after the certificate is acquired.
- Refactored IAP enabler to use BackendConfig to enable IAP. Script still has to set timeout and health check. BackendConfig is only available on GKE __1.10.5__.
- Updated cert-manager to v0.4.0 which no longer depends on container for ingress-shim. 
Fix #1146 Use BackendConfig to enable IAP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1327)
=> Fix iap-ingress certificate creation and use BackendConfig for IAP

kubeflow/core/prototypes/tf-job-operator.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/core/tf-job-operator.libsonnet
PR in tf-operator : https://github.com/kubeflow/tf-operator/pull/789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1403)
=> Update tf-job-operator prototype to support namespace-scoped deployment

components/ingress-setup-image/Dockerfile, components/ingress-setup-image/README.md, kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/iap.libsonnet, kubeflow/core/ingress_bootstrap.sh, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/setup_backend.sh
Docs changes are here : https://github.com/kubeflow/website/pull/173
* Creates a new component: Ingress Setup
* Updates all various ingress related bash scripts to use Ingress Setup docker image
* Don't create certificate CRD when using private cluster
* Add `privateGKECluster` and `ingressSetupImage` flags to iap prototype
/cc @jlewi @danisla
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1396)
=> Updates to iap component to support private clusters

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/kubeform_spawner.py, kubeflow/core/prototypes/jupyterhub.jsonnet
This is configurable via the ksonnet parameter - useJupyterLabAsDefault
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1423)
=> Use JupyterLab as default instead of Jupyter Tree interface

testing/tf_job_simple_test.py, testing/workflows/components/workflows.libsonnet
Fix the E2E test for the TFJob simple prototype test.
* Fix #1426
There are two problems with the test
1. Test isn't properly reporting results to gubernator; so test failures
aren't being noticed.
2. Test needs to be updated to work with v1alpha2.
* The TestSuite name needs to be set because this is used as the name
of the junit XML file.
* simple-prototype-test should set test_dir and artifacts_dir.
* Fix the test; use tf_job_client to wait for the job to be in the Running
condition. This should be more reliable than checking for actual pods.
* The test has probably been broken for a while but this went unnoticed
because results weren't being properly surfaced in test grid because
the XML file is improperly named. I suspect things broke as part of
the switch to v1alpha2 which changed …
=> Add logging statements to help figure out why test results aren't reported

kubeflow/weaveflux/README.md, kubeflow/weaveflux/prototypes/weaveflux.jsonnet
My last PR somehow lost data in rebase. Attempt to fix this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1434)
=> Weaveflux version 0.1.2. 

prow_config.yaml, testing/deploy_kubeflow.py, testing/workflows/components/workflows.libsonnet
* In #1406 we deleted deploy_kubeflow.py but this file is still used
by the minikube test.
* Partially reverts commit a4e4a8e9caf7bfa40958d9b8c9094fd7f9c7534e.
* Related to #1331
* Trigger minikube on presubmits if files used by minikube E2E test are changed.
run_e2e_workflow.py uses fnmatch so we can specify individual files
or other expressions
* Fix #1350 trigger minikube test on presubmit when test modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1411)
=> Fix minikube test and trigger on presubmit when modified.

scripts/setup-minikube.sh
setup-minkube.sh needs to set this env for kfctl before its invoked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1443)
=> Ensure MOUNT_LOCAL env var is forwarded to kfctl

bootstrap/cmd/bootstrap/app/initHandler.go, bootstrap/cmd/bootstrap/app/k8sAuth.go, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/saKey.go, components/gcp-click-to-deploy/kf_app.yaml, components/gcp-click-to-deploy/package.json, components/gcp-click-to-deploy/src/DeployForm.tsx, components/gcp-click-to-deploy/src/configs/cluster-kubeflow.yaml, components/gcp-click-to-deploy/src/configs/cluster.jinja, components/gcp-click-to-deploy/src/configs/cluster.jinja.schema
Update API calls to backend service.
Now all manual steps are covered by backend:
Update: 
1. one-click-to-deploy works now on any projects.
2. use DM config based on the one used by kfctl.
3. backend security enhancement: make sure auth token only shorted lived in memory. 
4. ingress compatibility: simplify ingress rule & handle health check.
Follow up:
1. (recommended) auto redirect when detect that IAP is up.
2. (optional) polish UI elements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1372)
=> [kfctl web app] frontend & backend update to agree with api changes

bootstrap/cmd/bootstrap/app/initHandler.go, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/saKey.go, components/gcp-click-to-deploy/src/DeployForm.tsx
1. make web app stateless: frontend only did one RPC call to backend and then wait.
refresh or close page during wait won't affect ongoing deployment anymore.
2. fix backend potential deployment name conflict:
Basically in memory map ```apps``` migrate from ```name -> app``` to ```project + name -> apps``` 
Now deployment name only need to be unique within each project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1458)
=> make web app stateless & backend security update

scripts/gke/deployment_manager_configs/cluster.jinja
Regarding #1432 I've added the read only scope to the Google deployment manager templates (cluster.jinja). 
This will allow the GKE to pull private images from gcr.io/<project>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1466)
=> Add GCS read only scope to GKE VM scopes

scripts/gke/deploy.sh
* We need to cd to the directory containing the deployment manager configs
before issuing gcloud deployment-manager update
* It works when the deployment doesn't exist because in that case we execute
a code block that cd's to the directory.
* Looks like previous fix #1243 never got cherrypicked onto 0.2 branch.
* Fix #1233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1475)
=> Fix bug with updating an existing deployment.

bootstrap/Dockerfile.Builder
With this, make build-builder will not reinstall the dep if we only change code
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1502)
=> separate dep and src for bootstrapper

scripts/kfctl.sh
- Fix if statements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1425)
=> Fix kfctl.sh gcpInitProject is always skipped

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet, kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
1. Added v1alpha2 as the default operator version
2. Added support for v1alpha2 in pytorch job
Default operator image is set to the released image  #1479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1511)
=> Adding v1alpha2 as the default PyTorch operator version

kubeflow/core/kubeform_spawner.py, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/core/tf-job-operator.libsonnet, kubeflow/mxnet-job/mxnet-operator.libsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet
Azure supports device plugin in both AKS/acs-engine so we don't need the custom logic to use `alpha.kubernetes.io/nvidia-gpu` anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1512)
=> Remove unused Azure specific config

bootstrap/Dockerfile, bootstrap/glide.lock, bootstrap/glide.yaml, components/gcp-click-to-deploy/manifest/kf_app.yaml
Fix #1507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1508)
=> update ks version to 0.12 for webapp backend

components/gcp-click-to-deploy/src/configs/cluster.jinja
some regions deprecated 1.10.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1516)
=> edit gke version to 1.10.6

kubeflow/registry.yaml
I found `chainer-job` package is missing in `registry.yaml`.  So, `ks pkg list` doesn't show `chainer-job` package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1529)
=> add chainer-job package to registry.yaml

bootstrap/cmd/bootstrap/app/ksServer.go
For case when user delete their deploy and redeploy with same name:
GKE master ip will be different while old ip still in cloud source repos.
With this PR we update GKE master ip on every request to avoid potential bugs.
@lluunn 
@abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1536)
=> edit server address for app config on each request

bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/server.go, components/gcp-click-to-deploy/manifest/kf_app.yaml, components/gcp-click-to-deploy/src/DeployForm.tsx
1. Support specifying registy version in create request;
2. Provide field for kubeflow version on UI.
So now we don't rely on bake-in repos any more.
User can choose to deploy with any kubeflow commit they want.
fix https://github.com/kubeflow/kubeflow/issues/1417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1528)
=> Support specifying registy version in create request

kubeflow/core/jupyterhub.libsonnet
/assign @kkasravi 
Kam, looks like the tf-hub-lb got left out in #1437 maybe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1539)
=> Restore missing tf-hub-lb service

testing/workflows/components/workflows.libsonnet
* jsonnet unittests are now run by a separate E2E workflow.
* The jsonnet tests when run as part of minikube were failing because they
were not updated as part of #1437
* Fix #1543 failing postsubmits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1545)
=> The minikube test should not be running the jsonnet unittests.

components/gcp-click-to-deploy/src/DeployForm.tsx
cloud source repo is used for kubeflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1553)
=> enable sourcerepo.googleapis.com api if needed

components/gcp-click-to-deploy/src/Gapi.ts
Default page size for enabled service list is 25.
Returned result will be truncated and incomplete if there are too many enabled services in a project.
Which confuses the caller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1558)
=> increase pageSize for service list to avoid truncate

bootstrap/cmd/bootstrap/app/gcpUtils.go
fix #1559 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1561)
=> Bug fix for #1559

kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet, kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet, kubeflow/weaveflux/README.md, kubeflow/weaveflux/all.libsonnet, kubeflow/weaveflux/prototypes/weaveflux.jsonnet
fixes #1050 
First round of changes include updating `image_gpu, num_schedulers, num_servers, num_workers, num_gpus and giturl` in files:
```
kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
kubeflow/weaveflux/README.md
kubeflow/weaveflux/all.libsonnet
kubeflow/weaveflux/prototypes/weaveflux.jsonnet
```
More is on the way but I need the get green light on this first before making the rest of changes that I mentioned in here: https://github.com/kubeflow/kubeflow/issues/1050#issuecomment-422537610
Otherwise this should be sufficient for the release and I can file a separate issue and a subsequent PR to work on that after we are done with the release.
I'm open to either one, please let me know.
--- …
=> Fix for issue 1050 - camelCase for some recently fixed params. 

scripts/gke/deployment_manager_configs/cluster.jinja
* This should fix presubmits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1571)
=> Bump GKE version because 1.10.7-gke.1 is no longer valid master version.

kubeflow/core/cert-manager.libsonnet
The value of http01 is not important. The point is it can't be trimmed by ks.
https://github.com/jetstack/cert-manager/blob/release-0.5/pkg/apis/certmanager/v1alpha1/types_issuer.go#L137
fix #1567 
/cc @kunmingg 
cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1568)
=> Fix cert-manager

kubeflow/core/ambassador.libsonnet, kubeflow/core/prototypes/ambassador.jsonnet, scripts/gke/use_gcr_for_all_images.sh
This prevents that appear the following error logs in large quantities
```
socat[1581671] E getaddrinfo("statsd-sink", "NULL", {1,0,2,17}, {}): Name does not resolve
```
This error always occurs.
It is hardcoded [here](https://github.com/datawire/ambassador/blob/0.37.0/statsd/Dockerfile#L5) in ambassador and it is mismatched so it seems to fail to resolve name.
It may resolve #945 (or it maybe already resolved)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1537)
=> Prevent ambassador getaddrinfo error logs

kubeflow/core/cert-manager.libsonnet, kubeflow/core/util.libsonnet
std.prune will delete key with empty value, which could be dangerous as we have some required keys with empty value.
related: 
https://github.com/kubeflow/kubeflow/issues/1567
https://github.com/kubeflow/kubeflow/pull/1544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1580)
=> remove prune from kubeflow core which delete required fields

bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/ksServer.go, components/gcp-click-to-deploy/manifest/kf_app.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1582)
=> fix iam patch logic and update image in config

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, releasing/image_tags.yaml
- Tag the latest pytorch-operator image as v0.3.0
- Update the image on master
- Will cherry pick to 0.3.0 branch afterwards
- Related to #1541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1619)
=> Tag and update pytorch operator

docs_dev/releasing.md, kubeflow/core/prototypes/tf-job-operator.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, releasing/image_tags.yaml
* This makes the change on master
* Will need to cherry pick it onto the 0.3 branch afterwards.
* Related to #1599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1608)
=> Update the TFJob image to the latest image and tag 0.3

bootstrap/Dockerfile, bootstrap/Dockerfile.Builder, bootstrap/Makefile
To simplify test and local dev.
Old method:
go pkg was compiled in builder image:
1. every line of change requires build two images: builder and final image. 
2. resulting in need of edit builder image version in Makefile every time before run ```make build``` 
3. resulting in frequent version change of builder image.
New method:
builder image is cache of glide & vendor dir, ```glide.lock``` file 100% determines the content of builder image. So use hash code of ```glide.lock``` as builder image version. And resolve 1,2,3 of old method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1621)
=> make builder image version consistent with glide.lock hash

prow_config.yaml
This change adds post-submit jobs that push CentralDashboard and Jupyter notebook images to gcr.io/kubeflow-images-public.
Related to #1601 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1624)
=> Add postsubmits to push centralui and Jupyter notebook images to kubeflow-images-public

kubeflow/core/prototypes/jupyterhub.jsonnet
JupyterLab extensions work differently that JupyterNotebook
Once we have tested and validated JupyterLab, we can switch to it as
default.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1628)
=> Use JupyterNotebook as default instead of JupyterLab

kubeflow/kubebench/prototypes/kubebench-job.jsonnet, releasing/image_tags.yaml
- Tag the latest Docker image for kubebench-controller as v0.3.0.
- Update the ksonnet component on master
Related to #1602 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1627)
=> Tag and update 0.3.0 release for Kubebench controller

scripts/kfctl.sh, scripts/util.sh, testing/test_deploy.py, testing/workflows/components/workflows.libsonnet
Related to #1483
This is run as part of the kfctl e2e test after setting up the kubeflow on the gke cluster.
It uses kubectl to verify the various deployments made by katib ksonnet component.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1638)
=> Add a simple e2e-test for katib

scripts/kfctl.sh, scripts/util.sh, testing/test_deploy.py, testing/workflows/components/workflows.libsonnet
Master PR #1638
Related to #1483
This is run as part of the kfctl e2e test after setting up the kubeflow on the gke cluster.
It uses kubectl to verify the various deployments made by katib ksonnet component.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1646)
=> [Cherry-pick] Add a simple e2e-test for katib

kubeflow/core/prototypes/centraldashboard.jsonnet, releasing/image_tags.yaml
(cherry picked from commit a0f01fbd409b1445429585069a9d34c0cd137600)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1660)
=> Cherrypick (#1657) tag image and change libsonnet for centraldashboard image 

scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml, scripts/gke/deployment_manager_configs/cluster.jinja, scripts/gke/util.sh, scripts/kfctl.sh
Update initial clsuter version in cluster.jinja based on what gcloud get-server-config returns (#1650)
* Update initial clsuter version in cluster.jinja based on what gcloud get-server-config returns
* Fix cluster-version string for cluster.jinja
* update the grep for more strict version checking and enhance the code style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1654)
=> Cherrypick #1650; automatically set master version to supported version.

releasing/image_tags.yaml
The previous 0.3 image was not working properly due to an issue in build, this updates the reference to the new image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1661)
=> Change kubebench 0.3 image

scripts/kfctl.sh
* Parts of the script assume there is no trailing slash. So if we don't
normalize things we have problems.
* Will need to cherry-pick this into v0.3
Related to #1663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1664)
=> Remove trailing slash from KUBEFLOW_REPO

components/centraldashboard/dashboard.go, components/centraldashboard/frontend/layout/index.html, releasing/image_tags.yaml
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1685)
=> Cherry-pick #1676 fix centralUI

scripts/kfctl.sh
* Remove trailing slash from KUBEFLOW_REPO
* Parts of the script assume there is no trailing slash. So if we don't
normalize things we have problems.
Related to #1663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1677)
=> cherrypick - Remove trailing slash from KUBEFLOW_REPO (#1664)

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, kubeflow/core/kubeform_spawner.py
- Build TF 1.9.0 and 1.10.1 notebook images on postsubmit
- Adds those images to kubeform spawner
- Fixes the HTML error where only default image is displayed in the dropdown
Fixes #1671 #1672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1686)
=> Build TF notebook images for TF 1.9.0 and 1.10.1

components/gcp-click-to-deploy/package-lock.json, components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/DeployForm.tsx, kubeflow/katib/prototypes/all.jsonnet
* Improve the instructions
* Turn instructions into a numbered list
* Move the Kubeflow version field to the bottom of the form since in most
cases users won't need to set it.
Here's a screen shot of the updated UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1703)
=> Add TOS and Privacy links and some other UI improvements.

releasing/hubsync/.gitignore, releasing/hubsync/README.md, releasing/hubsync/hubsync.py, releasing/hubsync/keys.yaml.sample, releasing/hubsync/requirements.txt
This will sync gcr to dockerhub per #1320 . It functions in this way
1) runs gcloud to pull down all image repos within gcr.io/kubeflow-images-public
2) runs a follow-up gcloud command to pull down image tags (latest)
3) Build cloudbuild.yaml file to authenticate with DockerHub, pull the image from gcr.io/kubeflow-images-public, tag the image, and push it to DockerHub
This is base code and is pre-coded largely just to pull from GCR to DockerHub. Users could modify the code in order to push to their own GCR or DockerHub. keys.yaml is the file where you store your credentials. 
I am hoping for a version 2.0 with a CLI. This would break it down into steps so that a user can build and sync what they want. However, for now, this will move all images from gcr.io/kubeflow-images-public to …
=> HubSync v1.0

kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet, kubeflow/tf-serving/tf-serving-template.libsonnet, testing/test_tf_serving.py
1. remove http proxy as we have http from TF serving. We should be able use istio for request logging [1], so http proxy is not needed anymore.
2. Add istio annotation. Will update documentation for this later (in website repo). Related: #1309 
[1]: https://istio.io/docs/tasks/telemetry/fluentd/#configure-istio
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1714)
=> TF serving template cleanup

scripts/download.sh
* This should prevent people from running the v0.3 version of download.sh
and then downloading the code on master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1734)
=> Change the default branch in download.sh to v0.3-branch as opposed to master

scripts/gke/util.sh, scripts/kfctl.sh
* We need to call createNamespace during the apply phase for k8s
otherwise the namespace might not exist.
Need to patch into 0.3
Related to #1675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1747)
=> Ensure namespace exists

deployment/gke/deployment_manager_configs/cluster.jinja
Added condition to enable this beta feature if using API version v1beta1.
Information about the feature can be found [here](https://cloud.google.com/monitoring/kubernetes-engine/installing).
Fixes #1768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1772)
=> Enable new beta Stackdriver Kubernetes Monitoring feature if using v1beta1 (#1768)

scripts/autoformat_jsonnet.sh
Allow folks to have the kubeflow github repo over https + improve error message -- we don't actually need testing.git for the remote
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1626)
=> Allow folks to have the kubeflow github repo over https + improve error message

scripts/gke/deploy.sh
line 170: uuidgen is used for generating a unique identifyer for optional usage metrics collection.
But uuidgen isn't available in Cloud Shell, and deploy.sh exists with an error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1674)
=> gke/deploy.sh: test uuidgen exists before using it

kubeflow/core/ambassador.libsonnet, kubeflow/core/prototypes/ambassador.jsonnet, scripts/gke/use_gcr_for_all_images.sh
Fixes https://github.com/kubeflow/kubeflow/issues/1651
The next step should be upgrading the ambasssador deployment to 0.40.0, where statsd is disabled by default.
I'm not sure if theres a set of e2e tests I should be running to verify behavior, but I went through and ran the kfctl.sh deploy scripts manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1760)
=> remove statsd from ambassador deployment

OWNERS, bootstrap/OWNERS, components/centraldashboard/OWNERS, components/gcp-click-to-deploy/OWNERS, components/jupyterhub/OWNERS, components/k8s-model-server/OWNERS, components/tensorflow-notebook-image/OWNERS, kubeflow/OWNERS, kubeflow/core/OWNERS
* Move some top level approvers into subdirectory OWNERs files that better
match their areas of expertise
* Remove some reviewers that haven't been that active.
* This will make blunderbuss more efficient.
* Data can be seen here
https://devstats.kubeflow.org/d/46/user-reviews-repository-groups?orgId=1&var-period=d7&var-repo_name=All&var-repo=all&var-reviewers=ScorpioCPH&var-reviewers=willb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1773)
=> Cleanup the OWNERs files.

bootstrap/cmd/bootstrap/app/gcpUtils.go, deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml, deployment/gke/deployment_manager_configs/cluster.jinja, scripts/gke/util.sh, scripts/kfctl.sh
This pins the bootstrapper to use the highest patch and build version of a minor release of Kubernetes.
From the deployment manager config:
```
"latest": picks the highest valid Kubernetes version
"1.X": picks the highest valid patch+gke.N patch in the 1.X version
"1.X.Y": picks the highest valid gke.N patch in the 1.X.Y version
"1.X.Y-gke.N": picks an explicit Kubernetes version
"","-": picks the default Kubernetes version
```
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters
Lets merge https://github.com/kubeflow/kubeflow/pull/1762 first, so this change will be much smaller.
Related to #1653 
--- …
=> pin to minor GKE version in dm config

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/suggestion.libsonnet, releasing/update_katib_ksonnet.sh
* Add katib's hyperband/bayesianoptimization suggestion images
* Reformat jsonnet
* Add default params for base-images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1777)
=> Cherry pick #1727

kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
fixes #838 
now kubeflow support ks `0.11.0`, so no blocking issues to merge this feature.
This supports `volume` and `volumeMounts` parameter on `openmpi` package.
This enables users to mount arbitrary volumes to master and worker pods like below:
```shell
ks param set ${COMPONENT} volumes '[{ "name": "vol", "hostPath": { "path": "/mnt/vol" }}]'
ks param set ${COMPONENT} volumeMounts '[{ "name": "vol", "mountPath": "/mnt/vol"}]'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1750)
=> [openmpi] support `volumes` and `volumeMounts`

deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml, prow_config.yaml
* We recently moved the DM configs out of ./scripts into ./deployment
but we didn'tmodify prow_config.yaml to properly trigger the presubmits
if they were modified.
* Remove the field stackdriver-agents from cluster-kubeflow.yaml since it
isn't used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1776)
=> Presubmits should be triggered if the DM configs are modified.

bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/glide.lock, bootstrap/glide.yaml
Added few basic counters to track deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1787)
=> Add a few basic metrics for deployment service

prow_config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1813)
=> stop e2e test for deploy app till fix letsencrypt rate limit

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/install.sh, components/tensorflow-notebook-image/releaser/components/params.libsonnet, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, components/tensorflow-notebook-image/releaser/environments/kubeflow-ci/params.libsonnet, components/tensorflow-notebook-image/start-singleuser.sh, components/tensorflow-notebook-image/versions/1.10.1/version-config.json, components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.4.1/version-config.json, components/tensorflow-notebook-image/versions/1.4.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.5.1/version-config.json, components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.6.0/version-config.json, components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.7.0/version-config.json, components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.8.0/version-config.json, components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.9.0/version-config.json, components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json, prow_config.yaml
Fix the build of the Jupyter images with TFMA and TFDV in the GPU Jupyter images.
* Looks like activating the widgets requires the GPU libraries because we end up importing tensorflow which fails without the GPU libraries.
* Modify the build of the jupyter images so the config (e.g. package versions) is loaded from the .json file rather than being specified in the Argo workflow file.
* Move a really long Dockerfile command into its own shell script (install.sh) to make it more readable.
* Related to #1818 installing and enabling the TFMA Jupyter extension at build time won't work because we end up trying to import TensorFlow which fails because the GPU cuda libraries are missing
* Related to #1718 TFMA and TFDV not properly installed in the appropriate versions of TF notebook images.
--- …
=> Fix TFMA and TFDV in Jupyter Images

scripts/kfctl.sh
Fixes #1837 
Deploy all other default components except argo & katib when platform is minikube.
Due to the large image sizes of default KF components, this makes it possible to deploy the platform to a minikube instance with 8GB RAM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1838)
=> Remove argo & katib from default minikube

components/https-redirect/Dockerfile, components/https-redirect/Makefile, components/https-redirect/main.py, components/https-redirect/main_test.py, components/https-redirect/requirements.txt
* We can use this with Envoy/Ambassador to redirect HTTP to HTTPs
* Example would be redirecting devstats.kubeflow.org to HTTPS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1832)
=> Create a simple flask server to redirect http to https

kubeflow/core/prototypes/ambassador.jsonnet, kubeflow/core/prototypes/jupyterhub.jsonnet, kubeflow/core/tests/ambassador_test.jsonnet
part of fix for #1542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1835)
=> part of fix for 'add jsonnet tests for all libsonnet files'

kubeflow/metacontroller/metacontroller.libsonnet, kubeflow/metacontroller/tests/metacontroller_test.jsonnet, scripts/kfctl.sh, scripts/util.sh
fixes #1833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1834)
=> fixes 'metacontroller's compositecontrollers and decoratorcontrollers need to be at Cluster scope'

kubeflow/core/util.libsonnet, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/util.libsonnet, kubeflow/openmpi/workloads.libsonnet, kubeflow/weaveflux/util.libsonnet
Some workloads are impacted by overhead of overlay network and I believe can benefit from running on the host network.
Allows passing in `useHostNetwork true` to configure worker pods to run on the host network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1805)
=> Add support for using host network for OpenMPI worker pods

kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/prometheus.yml
1. and retry logic in configure_envoy_for_iap.sh for activate-service-account
related: https://github.com/kubeflow/kubeflow/issues/1807
2. edit prometheus config: 
* remove namespace condition
* fix typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1847)
=> fix iap set up and prometheus config

bootstrap/README.md, bootstrap/developer_guide.md, docs_dev/ksonnet_packages.md, docs_dev/kubeflow_deployment.md, docs_dev/releasing.md, docs_dev/tf_serving.md, kubeflow/seldon/json/README.md, testing/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1788)
=> Fix typos in markdown

bootstrap/cmd/bootstrap/app/ksServer.go
1. make alert metrics count type
2. add service heartbeat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1849)
=> make alert metrics count type & add service heartbeat

testing/deploy_kubeflow.py, testing/deploy_utils.py, testing/workflows/components/workflows.libsonnet
https://github.com/kubeflow/tf-operator/pull/849 changed the way we launch TFJob E2E tests. This PR changes the workflow definition to the new format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1851)
=> Fix broken presubmit tests

prow_config.yaml
PR https://github.com/kubeflow/kubeflow/pull/1829 broke minikube e2e tests, but it got merged because the tests were not triggered. This PR adds scoping such that e2e minikube tests are run when core component files change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1864)
=> Run minikube e2e test if core components change

deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml, deployment/gke/deployment_manager_configs/cluster.jinja
* Cluster deployment will fail in regions with no GPUs.
* GPUs are expensive and not included in default GCP quota.
* To support deploying in regions with no GPUs we don't create a GPU
node pool by setting max GPU nodes to 0.
* Also expose a jinja parameter to set the GPU type.
Fix #1767 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1810)
=> Don't add a GPU pool by default

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/versions/1.10.1/version-config.json, components/tensorflow-notebook-image/versions/1.4.1/version-config.json, components/tensorflow-notebook-image/versions/1.5.1/version-config.json, components/tensorflow-notebook-image/versions/1.6.0/version-config.json, components/tensorflow-notebook-image/versions/1.7.0/version-config.json, components/tensorflow-notebook-image/versions/1.8.0/version-config.json, components/tensorflow-notebook-image/versions/1.9.0/version-config.json
You can reference images by digest in the FROM or `docker pull` commands.
https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier
The tag is ignored, but you can keep it there to give more context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1784)
=> components: tf-notebook-image: pin to base image

kubeflow/core/configure_envoy_for_iap.sh
format ```{1..10}``` doesn't work inside iap image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1874)
=> fix iap script

scripts/download.sh
According to the getting started guide, the KUBEFLOW_REPO is already made before running this script.
* The script no longer uses the env ${KUBEFLOW_REPO} so there's no reason to check whether
that directory exists.
* The script now downloads the source to the current directory.
* The check if directory ${KUBEFLOW_REPO} exists is a legacy of a previous version of the script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1873)
=> Fixing the conflict with the getting started guide

kubeflow/argo/argo.libsonnet
Fixes https://github.com/kubeflow/kubeflow/issues/1694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1865)
=> Add base href for correct link in Argo UI

components/k8s-model-server/images/versions/1.7gpu/version-config.json, components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.5.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.6.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.7.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json
Fixes #1783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1785)
=> [cuda] use runtime image instead of development image

scripts/kfctl.sh
* skipInitProject is a boolean so we need to use the syntax
if ${SKIP_INIT_PROJECT}
and not
if [ ]
* kfctl.sh was using a mix of spaces and tabs for indentation. Convert to spaces. spaces were being
used more than tabs and this is consistent with python style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1902)
=> Fix skip init project; use spaces consistently for indentation

kubeflow/pytorch-job/pytorch-operator.libsonnet
Adding CRD and deployment for Pytorch v1beta1 operator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1930)
=> Adding support for Pytorch v1beta1 operator

components/gcp-click-to-deploy/src/DeployForm.tsx
fixes #1420 
Fetching a GET on the dashboard URI which belongs in a different domain from the deployer in general gets prevented by the browser due to CORS prevention. This fix gets around that issue by leveraging the fact that a static image fetch hosted at the other dashboard site would not be prevented by the browser. Once that image is able to load within the deployer, it can redirect the user to the dashboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1945)
=> Redirect deployer webapp page to Kubeflow dashboard after its ready

components/tensorflow-notebook-image/jupyter_notebook_config.py
Little add-on to the jupyter notebook configuration, so that Jupyter Notebook deployed on GKE can be acessed via Cloud Shell (Avoid "Blocking Cross Origin API request" error) -  kubeflow/pipelines#179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1956)
=> Allow CloudShell origin pattern in Jupyter config

scripts/kfctl.sh
Fixes #1936  
Modify `kfctl.createEnv` to check for a case-mismatch between the `EMAIL` value provided by `$(gcloud config get-value account)` and the value in the iam-policy, and to use the iam-policy value in the case of a mismatch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1937)
=> Use iam-policy value for EMAIL if case-sensitive.

ROADMAP.md
* This is largely based on the work done by Chris Cho and the PM working
group.
* Roadmap is intended to be high level with issues providing fine grained
information about features and timelines.
* The Roadmap is a markdown doc in the kubeflow/kubeflow repo so that
it can be a living document that is continually updated.
* We picked kubeflow/kubeflow as opposed to kubeflow/community because
kubeflow/kubeflow has higher visibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1963)
=> Initial version of a Kubeflow Roadmap.

kubeflow/core/iap.libsonnet, kubeflow/core/setup_backend.sh, kubeflow/core/update_backend.sh
"setup_backend.sh is doing two things
1. updating the backend service
2. updating the envoy config in each instance with the info needed for
JWT validation
"
This PR separates those two concerns into two separate scripts.
Fixes #1145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1841)
=> Separate logic for setup_backend.sh

bootstrap/cmd/bootstrap/app/ksServer.go, components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/DeployForm.tsx, deployment/gke/cloud_shell_templates/conn.md, deployment/gke/cloud_shell_templates/conn.sh
1. make IAP optional for click-deploy app
2. update instructions for both cases (IAP / no IAP)
3. add button for both cases to smooth experience
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1927)
=> make IAP optional for click-deploy app

scripts/kfctl.sh, scripts/util.sh
Fixes #1739.
Stems from discussion in #1898.
Add check to `kfctl.sh` for platform GCP to ensure python module `pyyaml` is present before function `updateDM` calls `iam_patch.py` and imports `yaml`.
Script ends `exit 1` if module not present.
Also removed a duplicate `source ${ENV_FILE}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1975)
=> Check for python module pyyaml when using kfctl.sh on platform GCP.

testing/test_deploy_app.py
1. make prober always sleep before execute
2. catch ```kubectl create``` exception when it happens
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1908)
=> make prober always sleep before execute

kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/mysql.libsonnet, kubeflow/pipeline/parts.yaml, kubeflow/pipeline/pipeline-apiserver.libsonnet, kubeflow/pipeline/pipeline-persistenceagent.libsonnet, kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet, kubeflow/pipeline/pipeline-ui.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet, kubeflow/pipeline/spartakus.libsonnet, kubeflow/registry.yaml
Mostly copied from existing registry
https://github.com/kubeflow/pipelines/tree/master/ml-pipeline/ml-pipeline
- Removed argo from the pipeline package. Rely on kubeflow argo instead
- Keep Spartakus entry for tracking pipeline specific usage
I'll have a separate PR to integrate the one-click and kfctl deployment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1973)
=> initial change - add pipeline entry to kubeflow registry

kubeflow/katib/studyjobcontroller.libsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet, kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet, kubeflow/tf-training/tests/tf-job_test.jsonnet, kubeflow/tf-training/tf-job-operator.libsonnet
* PyTorch, TFJob, StudyJob CRD's should have scope namespace because the
resources always belong to a namespace.
* For TFJob the deploymentScope parameter doesn't affect the CRD definition
it only affects the controller itself and determines whether the controller
monitors a particular namespace or all namespaces.
* Add a unittest for the PyTorch CRD and Deployment ksonnet specs.
Fix #1985, #1524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1987)
=> Fix CRD scopes.

components/gcp-click-to-deploy/manifest/kf_app.yaml
The jupyterhub component was erroneously deleted from the gcp-click-to-deploy kf_app in #1998  (although I'm not sure if this is even used, since click-to-deploy maintains its own separate component yaml)
https://github.com/kubeflow/kubeflow/pull/1998/files#diff-cd856e8ab03263ee7dca07ad17f6405aL14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2003)
=> Fix bad merge conflict on v0.3-branch

kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet, testing/test_jsonnet.py
* jsonnet tests should be able to output a json object containing a field
"pass"
* The python test wrapper can then check this value to see if the test passed.
* This allows the object to output information about expected and actual
values which make it easier to debug.
Fix #1988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1989)
=> Make it easier to debug jsonnet tests

deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
Pipeline needs the dataproc editor permission to run the xgboost dataproc samples
For details, see
https://github.com/kubeflow/pipelines/tree/master/components/dataproc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2035)
=> Add roles/dataproc.editor for kubeflow user account

components/tensorflow-notebook-image/Dockerfile
Added the credential helper to make sure that the mounted service account credentials are used for pushing without any credentials
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2038)
=> Add fairing library to jupyter images

deployment/gke/deployment_manager_configs/cluster.jinja
The change is based on the new GKE API spec
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#privateclusterconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2085)
=> Update private IP configuration with new GKE API

kubeflow/pipeline/pipeline-apiserver.libsonnet
Adding a job meets the requirement of 
- Load samples once when pipeline is deployed
- Not run job again during kf upgrade
- If loading samples failed, not blocking api server from start
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2071)
=> Add job to load pipeline samples

scripts/util.sh
Fix  #1615
+ Avoid downloading from default registries, add --skip-default-registries to the ks init command here
https://github.com/kubeflow/kubeflow/blob/master/scripts/util.sh#L49
+ Define an extra environment variable ${KS_INIT_EXTRA_ARGS} to contain additional arguments to pass to the ks init command so that folks can specify additional arguments if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2100)
=> ks init: --skip-default-registries + append ${KS_INIT_EXTRA_ARGS}

kubeflow/tensorboard/aws.libsonnet, kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet, kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet, kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
1. Update tf serving aws prototype to use same pattern as gcp in order to reuse template. (Right now it's broken since k8s service was move out from tf-serving-template.libsonnet)
2. Remove useless parameters
Website are updated correspondingly. 
https://github.com/kubeflow/website/pull/362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2097)
=> Update aws parameters in serving and dashboard

kubeflow/core/tests/util_test.jsonnet, kubeflow/core/util.libsonnet, kubeflow/openmpi/util.libsonnet, kubeflow/weaveflux/util.libsonnet, testing/workflows/components/workflows.libsonnet
Had one PR to address issue on 0.3 branch 
https://github.com/kubeflow/kubeflow/pull/2073
Submit another one for master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2104)
=> Replace with std.asciiUpper with supported by required version of jsonnet

kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
By default, if we just enable s3 for model storage, we get string type from default template. 
```
ks param set ${MODEL_COMPONENT} s3Enable True
ks show default -c mnist-v3
...
- name: S3_REGION
value: us-west-1
- name: S3_USE_HTTPS
value: "true"
- name: S3_VERIFY_SSL
value: "true"
...
```
If we set true/false or 1/0 to these two parameters,  it will become boolean in libsonnet and kubernetes resource file. 
```
ks param set ${MODEL_COMPONENT} s3UseHttps true
ks param set ${MODEL_COMPONENT} s3VerifySsl true
...
- name: S3_REGION
value: us-west-1
- name: S3_USE_HTTPS
value: true
- name: S3_VERIFY_SSL
value: true
...
```
In that case, since kubernetes environment require `String` value. deployment creation will fail as following log shows. 
I think if we enforce use string type in …
=> Enforce use string type param for S3_USE_HTTPS and S3_VERIFY_SSL

scripts/gke/util.sh
* Originally we were using deployment manager to set IAM permissions.
* DM uses the cloud services account so we needed to grant the account IAM
permissions.
* We no longer use DM to set IAM permissions; in part because we don't want
to give cloudservice so much permisison.
Fix #1140 flakiness caused by setting the IAM policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2101)
=> Don't grant cloudservices account IAM admin priveleges.

kubeflow/core/prototypes/centraldashboard.jsonnet, kubeflow/jupyter/ui/default/config.yaml, kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, kubeflow/tf-training/prototypes/tf-job-operator.jsonnet, releasing/image_tags.yaml, releasing/update_components.sh, releasing/update_image_tags.sh
Updating the following kubeflow components to v0.4.0:
- tf-operator
- pytorch-operator
- centraldashboard
- Jupyter notebook images
Katib was recently updated (see https://github.com/kubeflow/kubeflow/pull/2064) so it is not included here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2112)
=> Update kubeflow components to v0.4.0

kubeflow/jupyter/jupyter_config.py, kubeflow/jupyter/ui/default/config.yaml, kubeflow/jupyter/ui/default/script.js, kubeflow/jupyter/ui/default/spawner.py, kubeflow/jupyter/ui/default/template.html, kubeflow/jupyter/ui/rok/config.yaml, kubeflow/jupyter/ui/rok/script.js, kubeflow/jupyter/ui/rok/spawner.py
This PR provides various enhancements and fixes to the existng Jupyter Spawner. More specifically:
- Adds support for custom container Images in the JH Spawner UI, as suggested by @jlewi  - Fixes #2060 (see provided GIF below for a preview) 
- Updates the list of available container Images with the latest TF versions from [gcr.io](https://gcr.io/kubeflow-images-public/)
- Adds basic server-side validation for Spawner options values that are marked as readOnly in `config.yaml`. In a future PR, we plan to further improve the Spawner options validation and provide descriptive messages to the users in each case to provide a better UX (e.g. when a `readOnly` Spawner option gets mutated)
- Implements various fixes for the Spawner of existing JH Spawner UIs (`default` and `rok`)
@jlewi let us …
=> JH Spawner Enhancements - Fixes #2060

scripts/kfctl.sh
* kfctl init ${DEPLOYMENT_NAME} will create a directory named ${DEPLOYMENT_NAME}.
* We want to check if that directory already exists and if it does return an
error; we don't want to overwrite the contents.
* There was a bug in the code though and we were checking if the directory
exists after creating the directory ${DEPLOYMENT_NAME} and cd'ing into it
so it wasn't having any effect.
* Check if init is passed a path rather than a name and if it is return error.
* Fix #2009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2115)
=> Fix the check if directory named ${DEPLOYMENT_NAME} exists

deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml, deployment/gke/deployment_manager_configs/cluster.jinja, deployment/gke/deployment_manager_configs/cluster.jinja.schema, deployment/gke/deployment_manager_configs/iam_bindings_template.yaml, scripts/gke/util.sh
Pipeline would use cloud sql for GCP scenarios. This change would give user the option to create a cloud sql instance, database and a root user as part of deployment.
The sql instance will have private IP enabled 
https://github.com/kubeflow/kubeflow/pull/2123/files#diff-a9c1d9db18e6d68f99216458ba3ab83fR203
so it can be accessed by GKE cluster by private IP. 
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#private-ip
This feature is currently disabled by a flag. 
https://github.com/kubeflow/kubeflow/pull/2123/files#diff-a9c1d9db18e6d68f99216458ba3ab83fR178
Will turn it on when pipeline fully integrate with cloud sql
--- …
=> Create cloud sql database for ml pipeline 

kubeflow/gcp/cloud-endpoints.libsonnet, kubeflow/gcp/tests/cloud-endpoints_test.jsonnet, testing/workflows/components/unit_tests.jsonnet
fixes #2120
cloud-endpoints (from https://github.com/danisla/cloud-endpoints-controller) was uprevv'd to 0.2.1 and is compatible with metacontroller 0.3, however the manifests in kubeflow/gcp/cloud-endpoints.libsonnet weren't uprevv'd to work with the image(gcr.io/cloud-solutions-group/cloud-endpoints-controller:0.2.1) and there were redundant manifests that are already deployed in kubeflow/metacontroller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2122)
=> fixes "Cloud Endpoints Controller not working on mmaster"

scripts/kfctl.sh
* We want to enable the stackdriver monitoring agents by default. This allows
pod logs to be fetched by pod label which is very valuable.
* To enable this we need to use the v1beta1 API for GKE
https://cloud.google.com/kubernetes-engine/docs/reference/api-organization#beta
* Remove the field CLUSTER_VERSION from kfctl.sh
This was added in #1888 but it doesn't look like it was actually being
use to set the CLUSTER_VERSION; it looks like cluster-version is set
in the deployment manager config cluster-kubeflow.yaml
* I think the changes will be rolled out to click to deploy as soon as we cut a new release with the updated DM configs and push that to click to deploy.
Fix to #1757
--- …
=> Enable stackdriver agents for GKE  by default.

components/gcp-click-to-deploy/package-lock.json, components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/Css.ts, components/gcp-click-to-deploy/src/DeployForm.tsx
- Importing material-ui core components using non-default imports causes the entire library to be bundled with the app.
- Fixed styling for the client id and secret fields.
- The remaining is white-space fixes using vscode auto-format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2139)
=> Package size fix, client id and secret textfield styling fix

components/gcp-click-to-deploy/package-lock.json, components/gcp-click-to-deploy/package.json, components/gcp-click-to-deploy/src/Css.ts, components/gcp-click-to-deploy/src/DeployForm.tsx
This PR:
- Updates dependencies to latest. This resolves a few issues with the material UI library used for the UI, such that most of the theme overrides aren't needed anymore.
- Uses material style checkbox and dropdown controls.
- Removes glamorous since it's deprecated, and switches to using inline styling, which is enough for an app this size.
- Makes some other small improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2158)
=> Style fixes

scripts/util.sh
(previously hard coded to ks when falling back to type check) - closes https://github.com/kubeflow/kubeflow/issues/2162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2163)
=> Fix check install to use param for type as well as which check 

testing/README.md
"argo" should be "Argo" in the readme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2168)
=> "argo" should be "Argo"

kubeflow/jupyter/ui/default/config.yaml, kubeflow/jupyter/ui/rok/config.yaml
* Upgrade the images in the Arrikto ROK UI as well; it looks as though
they hadn't been updated to the 0.4 images.
Related to #2098 0.4 Release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2181)
=> Add the TF 1.11 & TF 1.12 Jupyter images to the spawner drop down box.

scripts/kfctl.sh
* Checking the IAM policy for the email address is a hack to get
the proper case for the user's email.
* We need to allow for the possibilit that the user isn't explicitly
in the IAM policy because they might have access through a group.
Related to #2186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2188)
=> kfctl.sh shouldn't fail if a user isn't explicitly in the IAM policy - 0.4 patch.

scripts/kfctl.sh
* Checking the IAM policy for the email address is a hack to get
the proper case for the user's email.
* We need to allow for the possibilit that the user isn't explicitly
in the IAM policy because they might have access through a group.
Related to #2186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2187)
=> kfctl.sh shouldn't fail if a user isn't explicitly in the IAM policy.

kubeflow/pipeline/pipeline-apiserver.libsonnet
Loading the sample job has sporadically failures due to race condition with api server start up. They both can create the db foreign key. 
The gorm library handles foreign key existence but it won't be safe in race condition
https://github.com/jinzhu/gorm/blob/master/scope.go#L1221
This is a temporary fix to allow samples load correctly. In long term, the sample loading shouldn't be a job because job doesn't work well with ksonnet. It won't work during upgrade scenario. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2199)
=> Add retry to loading the sample job

kubeflow/gcp/OWNERS
* Some GitHub ids were misspelled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2202)
=> Fix OWNERs file for gcp package.

kubeflow/seldon/prototypes/core.jsonnet
* Adds an optional parameter to include ClusterRoles, false by default.
Fixes #1452
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2039)
=> Remove Seldon Cluster Roles by default

kubeflow/tf-serving/tf-serving.libsonnet
Added replicas parameters in tf-serving.libsonnet so that multiple tf-serving pods can be deployed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2113)
=> Update tf-serving.libsonnet for replicas

scripts/kfctl.sh
This patch attemps to address issue 2189 by checking that
DEPLOYMENT_NAME is less than 25 characters, and that it does
not contain a '.'.
Fixes: #2189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2191)
=>    Check the name of the deployment is < 25 characters on GCP

kubeflow/jupyter/notebooks.libsonnet, kubeflow/jupyter/sync-notebook.jsonnet, kubeflow/jupyter/tests/notebooks_test.jsonnet, kubeflow/jupyter/util.libsonnet
Fix #2185
**Problem**: Metacontroller deletes notebook deployment if there is a version mismatch between the Deployment created and the Deployment specified.
**Fix**: sync-notebook needs to look for a Deployment kind that is version independent.
**Details**: https://github.com/kubeflow/kubeflow/issues/2185#issuecomment-450441261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2194)
=> sync-notebook needs to look for a Deployment kind that is version independent

bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/ksServer.go
1. reduce false alerts.
2. reformat prometheus metrics and unify tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2215)
=> add status tag to deployments_failure; exclude failure caused by quota or permission issue

kubeflow/kubebench/prototypes/kubebench-job.jsonnet, kubeflow/kubebench/prototypes/kubebench-operator.jsonnet, releasing/image_tags.yaml, releasing/update_components.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2216)
=> Update kubebench tags for 0.4.0 release

components/gcp-click-to-deploy/src/DeployForm.tsx
Avoid dependency on source repo:
currently for multi deploy in same project, user will be asked whether or not ```git pull``` in cloud shell, cause confusions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2218)
=> simplify cloud shell; add instruction message

testing/test_tf_serving.py
_Undefined names_ have the potential to raise NameError at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2228)
=> Undefined name: from six.moves import xrange for line 50

kubeflow/README.md, kubeflow/application/prototypes/README.md, kubeflow/argo/README.md, kubeflow/chainer-job/README.md, kubeflow/common/README.md, kubeflow/credentials-pod-preset/README.md, kubeflow/gcp/README.md, kubeflow/jupyter/prototypes/README.md, kubeflow/katib/README.md, kubeflow/mpi-job/README.md, kubeflow/mxnet-job/README.md, kubeflow/new-package-stub/README.md, kubeflow/nvidia-inference-server/README.md, kubeflow/openmpi/README.md, kubeflow/pachyderm/README.md, kubeflow/profiles/prototypes/README.md, kubeflow/pytorch-job/README.md, kubeflow/tf-serving/README.md, kubeflow/weaveflux/README.md
The readme in the prototypes directory was quite inconsistent, though very similar. This PR lines them all up. Many don't have Readme's, so it adds a readme to the prototype stub too, in the hopes devs fill these in.
- Consistently use doctoc where-ever there are READMEs in the
prototype directory:
1. Header
2. [optional] Summary
3. TOC
4. Body
- Fix several dead links
- Add README to prototype stub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2221)
=> Consistent formatting of prototype docs

scripts/gke/util.sh, scripts/kfctl.sh
Pytorch operator installation by kfctl is added to all platforms
Related: #2212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2225)
=> Adding pytorch operator to non gcp platforms

kubeflow/tf-serving/tf-serving.libsonnet
Enable HorizontalPodAutoscaler in TF-Serving component.
Current implementation will let pods scale based on CPU usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2231)
=> Add HorizontalPodAutoscaler to TF-Serving component

components/gcp-click-to-deploy/src/DeployForm.tsx
As reusing deploy name will reuse app config of previous deploy, we should set ```jupyterHubAuthenticator``` explicitly even the value is default value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2235)
=> set jupyterHubAuthenticator explicitly even for default values

releasing/requirements.txt, releasing/sync_images.py
When Kubeflow releases, we need to sync up the official images to the own registry.  For example,
```
python sync_images.py --registry registry.aliyuncs.com
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2230)
=> Sync up Kubeflow official docker images to user's registry

testing/test_jsonnet.py
_Undefined names_ have the potential to raise NameError at runtime.
[flake8](http://flake8.pycqa.org) testing of https://github.com/kubeflow/kubeflow on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./docs/gke/iap_request.py:140:25: F821 undefined name 'signer_email'
signer_email))
^
./components/tensorflow-notebook-image/jupyter_notebook_config.py:23:5: F821 undefined name 'get_config'
c = get_config()
^
./kubeflow/jupyter/jupyter_config.py:27:1: F821 undefined name 'c'
c.JupyterHub.ip = '0.0.0.0'
^
./kubeflow/jupyter/jupyter_config.py:28:1: F821 undefined name 'c'
c.JupyterHub.hub_ip = '0.0.0.0'
^
./kubeflow/jupyter/jupyter_config.py:31:1: F821 undefined name 'c'
c.JupyterHub.cleanup_servers = False
^ …
```
=> Undefined name: 'false' --> 'False'

scripts/kfctl.sh, scripts/util.sh
The katib images like `gcr.io/kubeflow-images-public/katib/tfevent-metrics-collector:v0.4.0` uses sub namespace `kubeflow-images-public/katib` in `gcr.io`, but it's not supported by other docker image repo. We need to consider how to support it in other docker repos.
We will use the environment variable `DOCKER_REGISTRY_KATIB_NAMESPACE ` to replace `kubeflow-images-public/katib` if the variable is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2237)
=> Fix katib repo for the docker registry which doesn't support sub namespace

kubeflow/argo/argo.libsonnet, kubeflow/argo/prototypes/argo.jsonnet
Now Argo deployed with  with `kfctl.sh` cannot handle workflows with artifactory configuration.
This PR updating Argo ksonnet configuration to include s3 minio repository in workflow controller configmap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2238)
=> argo s3 artifact repository configuration added

bootstrap/Dockerfile, bootstrap/DockerfileDebug
DockerfileDebug should be for debug only and always executed manually on local
Example build cmd:
```
docker build -f DockerfileDebug --build-arg KFCTL_IMAGE=XXXX -t gcr.io/kubeflow-images-public/bootstrapperdebug:test0 .
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2242)
=> split debug case into separate docker file so we don't expose port unnecessary

bootstrap/Dockerfile, bootstrap/cmd/bootstrap/app/ksServer.go
We have lots dependencies which alpine doesn't include, so actually could be easier use golang:1.11.2 as base. Increase image size by 300M but build faster and test simpler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2258)
=> use golang:1.11.2 as base image; more ksonnet 0.13.1 API change

kubeflow/pipeline/pipeline-apiserver.libsonnet
Avoid using job to load samples into pipeline system. 
The K8s Job doesn't work well because it's immutable once created, ksonnet throw an error of "merging object with existing state failure" in case of upgrading the system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2254)
=> remove load sample job from pipeline config

components/gcp-click-to-deploy/src/DeployForm.tsx, kubeflow/registry.yaml
Shall we add test for ghost registries?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2265)
=> remove ghost registries; make kf version env var on deploy app

dependencies/istio/README.md, dependencies/istio/README.yaml, dependencies/istio/install/README.md, dependencies/istio/install/crds.yaml, dependencies/istio/install/istio-noauth.yaml
We need 1.1 for JWT's trigger rule (excluded_paths: /healthz)
The manifest are from Istio pre-release 1.1-20190111-09-15.
Changed:
- policy is disabled instead of enabled (see README for explanation)
- istio-ingressgateway type is NodePort not LoadBalancer
/cc @kunmingg 
related: #1907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2259)
=> use istio 1.1

kubeflow/nvidia-inference-server/README.md, kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet
TensorRT Inference Server requires new handling starting with the 18.11 release. The current README only works with older versions of the server and so needs this update to be relevant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2279)
=> Update README for newer TRTIS releases

scripts/gke/util.sh
Creates GCP service account secrets even when IAP oAuth credentials are not supplied
Associated issue: https://github.com/kubeflow/kubeflow/issues/2284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2313)
=> create secrets before checking for oauth env vars

kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/nfs.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet
- Add in-cluster NFS that uses default storageclass in the cluster.
- switch minio to use in-cluster NFS
NFS ensure that the nfs-pvc is a RWM PVC that can be reused for other pipeline components to mount PV in the future. This will be the first step to deprecate minio in favor of K8s PV.
TODO: Since we don't expose functionality to allow user specify permanent storage, we use the default storageclass. The data will still be gone if cluster is deleted. As next step, expose this configuration as parameter to kfctl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2328)
=> add in-cluster nfs 

kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/mysql.libsonnet, kubeflow/pipeline/nfs.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet, kubeflow/pipeline/storage.libsonnet
This change provides following options for pipeline storage
- Use GCE PD
- Use a pre-created PV in cluster
- Use default StorageClass (default)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2335)
=> add condition to create pv and pvc for kubeflow pipeline

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2299)
=> add pipeline team to the owner file

scripts/gke/delete_deployment.sh, scripts/gke/delete_role_bindings.py, scripts/kfctl.sh
* Take named command line arguments rather than positional arguments
* Add and use delete_role_bindings.py to delete all bindings associated
with the service accounts. This way we don't depend on the IAM patch
file being present. That only works if you have the kfctl app directory.
* Set exit status explicitly.
Related to: #953 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2344)
=> Improve the delete_deployment script.

releasing/sync_images.py
As discussed at https://github.com/kubeflow/kubeflow/pull/2230#issuecomment-452423892 Python 3 will treat TabErrors as syntax errors.
TabError: inconsistent use of tabs and spaces in indentation
@cheyang Your review please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2240)
=> Fix TabError in sync_images.py

kubeflow/katib/README.md
I added some information inside Katib package README. 
How to deploy Katib not in GKE if you don't have StorageClass inside your cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2260)
=> Extend Katib documentation to use not in GKE

bootstrap/build_image.sh, testing/test_deploy_app.py, testing/workflows/components/click_deploy_test.jsonnet
- Change the srcDir and set GOPATH in click_deploy_test.jsonnet so that we can build with go modules
- update build_image.sh
- test_deploy_app.py also does cleanup first in e2e mode
For https://github.com/kubeflow/kubeflow/issues/2364
For https://github.com/kubeflow/testing/issues/301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2400)
=> fix click_deploy_test

bootstrap/Dockerfile, bootstrap/build_image.sh, bootstrap/cmd/bootstrap/app/ksServer.go, testing/workflows/components/click_deploy_test.jsonnet
- make `copy-artifacts` not depend on `deploy-delete` so that even delete failed we still have artifacts. @kunmingg Is this ok?
- when GetDeploymentStatus failed, retry
- update go version, and print out go version
for https://github.com/kubeflow/kubeflow/issues/2364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2431)
=> fix click_to_deploy test

kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/storage.libsonnet
NFS will be deployed only when explicitly set nfsPvName or nfsPd. 
By default NFS won't be deployed. Minio will use minioPvName, minioPd or PVC provisioned by default storageclass.
fix https://github.com/kubeflow/kubeflow/issues/2443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2446)
=> Deploy NFS only when explicitly set the nfs parameter

kubeflow/gcp/basic-auth-ingress.libsonnet, kubeflow/gcp/prototypes/basic-auth-ingress.jsonnet, kubeflow/gcp/update_backend.sh
Create new entry for basic auth ingress on GCP.
How to use:
Apply both:
```
gcp/basic-auth-ingress
common/basic-auth
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2438)
=> ingress entry for basic auth

scripts/kfctl.sh
Regex is causing some issues on OSX , so, skipping the check on OSX for now until the new go binary is out which will solve this for good
Related to: #1948
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2453)
=> Skipped context check on OSX

testing/workflows/components/click_deploy_test.jsonnet
junit_kubeflow-deploy-bootstrapper.xml is at wrong location.
```
gsutil ls gs://kubernetes-jenkins/logs/kubeflow-riodic-master/761
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/build-log.txt
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/finished.json
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/junit_kubeflow-deploy-bootstrapper.xml
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/started.json
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/artifacts/
gsutil ls gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/artifacts
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/artifacts/junit_jsonnet-test-suite.xml
gs://kubernetes-jenkins/logs/kubeflow-periodic-master/761/artifacts/junit_jupyter-test.xml …
```
=> fix artifact dir

prow_config.yaml, testing/test_tf_serving.py, testing/workflows/components/click_deploy_test.jsonnet, testing/workflows/components/kfctl_test.jsonnet, testing/workflows/components/params.libsonnet, testing/workflows/components/tfserving.libsonnet, testing/workflows/components/workflows.jsonnet, testing/workflows/components/workflows.libsonnet
for https://github.com/kubeflow/testing/issues/301
The test name on testgrid has requirement:
1. kfctl and kfctl-beta both running at the same time, the test name cannot collide
2. cannot use the name of workflow which is specific per run, e.g. kubeflow-presubmit-kubeflow-e2e-minikube-2447-0c1503a-5646-cec4
So I am creating a new param, workflowName, for each e2e test. kfctl and kfctl-beta will have different workflowName with this.
/cc @jlewi 
/cc @richardsliu 
/hold
waiting for the presubmit result
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2462)
=> fix test name on testgrid

kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet, kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet
Meet this problem when I  `yaml.Unmarshal(manifest, &mpiJob)`
```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Container.command of type []string"
```
MPI job spec template uses corev1.PodTemplateSpec. Commands and Args are both `[]string` type. 
https://github.com/kubernetes/api/blob/369c77d0cd027d5cb8eebabebfb64d38b21538a0/core/v1/types.go#L2065-L2080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2434)
=> Use command array in mpi job prototype

kubeflow/pipeline/minio.libsonnet
Otherwise I saw 
```
ERROR handle object: patching object from cluster: merging object with existing state: Deployment.apps "minio" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"minio"}: `selector` does not match template `labels`
```
when doing upgrade
Ref https://stackoverflow.com/questions/48582951/deployment-invalid-spec-template-metadata-labels-invalid-value
/assign @neuromage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2466)
=> add selector for minio deploy

kubeflow/kubebench/kubebench-rbac.libsonnet
Grant kubebench service account permission to operate mpijobs and fetch pod logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2442)
=> Add mpijobs and pods/log in kubebench rbac

kubeflow/spark/README.md, kubeflow/spark/all.libsonnet, kubeflow/spark/parts.yaml, kubeflow/spark/prototypes/spark-job.jsonnet, kubeflow/spark/prototypes/spark-operator.jsonnet, testing/workflows/components/kfctl_test.jsonnet, testing/workflows/components/workflows.libsonnet
Initial work in progress attempt at adding Spark to kubeflow using the spark-on-k8s-operator as a base starting point. This is super early but I'd love peoples feedback on the direction with this.
cc @texasmichelle 
Known TODOs:
- Tests that run on more than just my specific directory layout
- Documentation
- Cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1467)
=> Add Spark Job

bootstrap/config/kfctl_basic_auth.yaml, bootstrap/config/kfctl_iap.yaml
Define ksonnet app used by kfctl to deploy kubeflow on GCP
Provide 2 entries:
* IAP
* Basic Auth
File can be loaded as [KsonnetSpec](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go#L201)
Package is not provided as [default pkg set](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go#L63) should be good now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2482)
=> add config file entries for deployment on GCP

kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
Just built an image for it and updating config to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2493)
=> update jupyter-web-app image path

bootstrap/test_delete.sh, prow_config.yaml
Also, make test_delete catch error on delete namespace (which happens when previous step failed and namespace is not created)
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2492)
=> fix workflow name

components/jupyter-web-app/default/kubeflow/jupyter/static/js/notebooks.js, components/jupyter-web-app/rok/kubeflow/rokui/static/js/notebooks.js, kubeflow/jupyter/jupyter-web-app.libsonnet
Following on changes from #2463, the UI must redirect to `/notebook/<namespace>/<name>`. Also a small fix in the `.libsonnet`, needed for #2481.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2490)
=> Update Jupyter WebApp redirect URL and libsonnet

bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go, components/jupyter-web-app/OWNERS
Fix for #2481 
`make test-known-platforms-generate` from bootstrap creates the kubeflow apps with `jupyter-web-app` component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2500)
=> Add jupyter-web-app to kfctl

kubeflow/common/ambassador.libsonnet, kubeflow/common/prototypes/ambassador.jsonnet
Used to set the ambassador service nodePort only when ambassadorServiceType is NodePort and ambassadorNodePort is within the valid range [30000-32767]. By default this parameter is set to 0. If ambassadorServiceType is NodePort and ambassadorNodePort is outside the valid range, then Kubernetes will automatically assign an available nodePort.
Contributes to closing the following issues:
#630
#1525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2511)
=> Add optional parameter ambassadorNodePort

components/gcp-click-to-deploy/src/DeployForm.tsx
This requires click-to-deploy app backend version to be at least 
https://github.com/kubeflow/kubeflow/pull/2504
and ksonnet registry version to be at least 
https://github.com/kubeflow/kubeflow/pull/2425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2504)
=> create permanent storage from click-to-deploy app

testing/workflows/components/click_deploy_test.jsonnet
two deploy app were having the same name and one would fail.
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2519)
=> Fix periodic test

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet, kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet, kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Adding Pytorch v1beta2 CRD with status sub resource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2532)
=> Pytorch v1beta2 support

kubeflow/common/prototypes/centraldashboard.jsonnet
Fixes: #2524 
Child of #2359
##About
This change just updates the default image for the dashboard to the version build from #2359.
/cc @abhi-g 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2540)
=> Update dashboard image to point to newest build

components/centraldashboard/make-win.ps1
Just here in case, someone finds a use for it. I rewrote the makefile to work in a windows environment portably including environment level checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2518)
=> Added a windows equivalent script for the makefile for central-dashboard

testing/workflows/components/workflows.libsonnet
This is a temporary change so that we could merge [this PR](https://github.com/kubeflow/tf-operator/pull/945), which renames python top level package in tf-operator repo.  Once merged, it likely breaks kubeflow checkout tests since the tf-operator imports in external repos no longer are correct. 
To avoid this probelm, we temporarily pin checkout test to the latest tf-operator commit and will resume it once all import renaming in external repos are resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2555)
=> Temporary change to pin kubeflow to the latest verified tf-operator commit 

components/tensorflow-notebook-image/Dockerfile
tested locally and on k8s.
Related to: #2593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2591)
=> Turnning off jupyter images authentication

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Prune is removed for enabling subresource field in CRD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2598)
=> Removing prune for Subresource field in CRD

kubeflow/jupyter/config.yaml
tested images locally and on jupyter spwnner of  kubeflow-dev environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2611)
=> Updated jupyter spawning options to the latest images. 

kubeflow/pytorch-job/pytorch-operator.libsonnet, kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet, kubeflow/tf-training/tests/tf-job_test.jsonnet, kubeflow/tf-training/tf-job-operator.libsonnet
Display status field for kubectl get tfjobs/pytorchjobs. This outputs the type from the last condition in the status field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2609)
=> Adding additional printer columns to display status

components/notebook-controller/pkg/controller/notebook/notebook_controller.go, kubeflow/jupyter/prototypes/notebook_controller.jsonnet
- Use EnvVar `NB_PREFIX` for base_url
/cc @jlewi @zabbasi @kimwnasptd 
related to #2590, #2595
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2620)
=> Fix ambassador route and base_url in notebook controller

components/tensorflow-notebook-image/Dockerfile
Addressing [this issue](https://github.com/kubeflow/kubeflow/issues/2595). Tested an image locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2627)
=> Setting the base_url flag of Jupyter images

kubeflow/jupyter/config.yaml
Paths are updated following [this pr](https://github.com/kubeflow/kubeflow/pull/2627)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2638)
=> Updated jupyter image paths to point to the latest ones

bootstrap/cmd/bootstrap/app/ksServer.go
Add retry around init to retry on ```pulling k8s open api from Github```
since Github flaky still happening.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2643)
=> add retry around ks init

scripts/azure/util.sh, scripts/kfctl.sh
kfctl.sh will be going away eventually, so this is just a stop gap to support Azure until the go client kfctl is ready for other cloud providers.
@jlewi @kkasravi PTAL 
cc @sozercan @aronchick
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2557)
=> Add Azure support for kfctl.sh

bootstrap/api/swagger.yaml
New deployment API supports 2 types of entries:
* config entry
each entry maps to a set of config files stored in source repo or Github which can fully define a deployment entry. 
* deployment entry
each entry maps to a kubeflow instance on GCP which include resources like GKE, Endpoint, Storage, Service Account, IAM bindings. Deployment entry is created following definition in the corresponding config entry.
Goals of new API include simplify reuse configs and support configs customization. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2564)
=> new deploy API following Open API format

kubeflow/tensorboard/aws.libsonnet, kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet, kubeflow/tensorboard/tests/tensorboard-aws_test.jsonnet
Allowing the use of [AWS EFS](https://aws.amazon.com/efs/) for the Tensorboard deployment on AWS.
Previously, only S3 parameters were available.
With these changes, provided you have a Persistent Volume Claim with an EFS resource on your cluster (using [efs-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs)), you can make Tensorboard read from EFS.
You can still use S3, of course. They are not mutually exclusive (use the flags `efsEnabled` and `s3Enabled`, both can be `true` at the same time).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2569)
=> Enabling EFS on AWS for Tensorboard

components/tensorflow-notebook-image/versions/1.11.0/version-config.json, components/tensorflow-notebook-image/versions/1.11.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.12.0/version-config.json, components/tensorflow-notebook-image/versions/1.12.0gpu/version-config.json
Addressing [this issue](https://github.com/kubeflow/kubeflow/issues/2551)
Built and tested the images locally. Jupyter notebook of Python 2 could successfully import TFMA and TFDV packages. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2666)
=> Updated TFMA and TFDV versions of Jupyter images

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet, kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet, kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Serve both v1beta1 and v1beta2 crd of Pytorch operator. v1beta2 is made as default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2677)
=> Serve Pytorch v1beta2 and v1beta1 crd

kubeflow/common/centraldashboard.libsonnet
This enables the Central Dashboard to list namespaces and also retrieve events from those namespaces to display on the Activities tab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2684)
=> Add ClusterRole and ClusterRole

ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2669)
=> Update the ROADMAP with more details about how we are approaching 1.0

bootstrap/pkg/client/gcp/gcp.go
Fixes #2701
`useBasicAuth` is not an option in `kfctl generate`.  it's available in app spec, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2702)
=> Fix param set on ipName and hostname

prow_config.yaml, testing/workflows/components/kfctl_test.jsonnet, testing/workflows/components/workflows.libsonnet
* Don't try to apply the spark-operator until after calling kfctl apply k8s
because the ksonnet environment gets created during the step.
Fix #2693 
* Disable argo deploy test because it is flaky #1407 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2694)
=> Attempt to fix spark-operator and argo-deploy test flakiness.

kubeflow/argo/argo.libsonnet, kubeflow/argo/tests/argo_test.jsonnet, kubeflow/common/ambassador.libsonnet, kubeflow/common/tests/ambassador_test.jsonnet, kubeflow/pipeline/pipeline-viewercrd.libsonnet
Running 
```
kfctl init ~/kubeflow
cd ~/kubeflow
kfctl generate all
cd ks_app
ks show default -c application -c metacontroller >default.yaml
kubectl apply -f default.yaml
```
will return validation errors of misplaced or incorrect yaml specs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2674)
=> fixes 'kfctl generated yaml fails validation #2653'

components/centraldashboard/package-lock.json, components/centraldashboard/public/components/activity-view.js, components/centraldashboard/public/components/main-page.css, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/namespace-selector.js, kubeflow/common/prototypes/centraldashboard.jsonnet
- List box text was not visible in blue toolbar mode
- Colors adjusted for clearer viewing of namespace selector
- Made the message much easier to read and made it an empty state message
/assign @avdaredevil @prodonjs 
/review @prodonjs 
/priority p0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2733)
=> Polish changes:

kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet
The container entrypoint must run to ensure driver compatibility is
enabled correctly. Fix spec to not use "command" so that container
launch runs entrypoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2726)
=> Launch trtserver so that CUDA driver compatibility is enabled

bootstrap/Dockerfile, bootstrap/Makefile, bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/gcpUtils_test.go, bootstrap/cmd/bootstrap/app/ksServer.go, bootstrap/cmd/bootstrap/app/server.go, bootstrap/go.mod, bootstrap/go.sum, bootstrap/pkg/kfapp/gcp/gcp.go, bootstrap/pkg/utils/iamutils.go, bootstrap/pkg/utils/iamutils_test.go
1. go binary need to import k8s 1.13.4 (kustomize) and 1.10.4 (ksonnet)
2. set IAM policy need to follow read/modify/write mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2751)
=> fix make build; set IAM policy following read/modify/write

bootstrap/pkg/kfapp/gcp/gcp.go
fixes #2707 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2718)
=> fixes 'kfctl creates invalid IAM policy binding file if email not set'

bootstrap/pkg/kfapp/coordinator/coordinator.go, bootstrap/pkg/kfapp/ksonnet/ksonnet.go
fixes #2761
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2763)
=> fixes 'kfctl Incorrect ksonnet OptionServer is specified when no platform is provided'

bootstrap/config/kfctl_basic_auth.yaml, bootstrap/config/kfctl_iap.yaml, bootstrap/pkg/kfapp/gcp/gcp.go, bootstrap/pkg/kfapp/ksonnet/ksonnet.go, kubeflow/gcp/gpu-driver.libsonnet, kubeflow/gcp/prototypes/gpu-driver.jsonnet
The goal is to avoid shell out and run ```kubectl apply```:
To use gcp.go/ksonnet.go as a library, it need to support concurrent run and cannot use local kubeconfig. 
For stackdriver, will config with gcp/prometheus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2772)
=> replace download k8s manifest with ksonnet entry

bootstrap/pkg/apis/kferrors.go
Relates #2712
We will use this error interface to carry error information and status code used for monitoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2769)
=> Adds Kferror interface

components/centraldashboard/.eslintrc.json, components/centraldashboard/Dockerfile, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/webpack.config.js
*Fixes last open item on #2512* 
This change adds an additional variable defined at build time by webpack based on the value of the `BUILD_VERSION` environment variable. When building the Docker container via `make`, the `kubeflowversion` argument is already set to the most recent tag in the repository. This change assigns that build-time argument to the environment variable and the container and uses it to display the Kubeflow version. If the environment variable is not set, the dashboard's version from package.json is shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2779)
=> Obtain build version from ENV

kubeflow/mpi-job/mpi-operator.libsonnet
mpi controller does getOrCreate pdb [here](https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/mpi_job_controller.go#L601) and the clusterrole doesn't have the rule to list/create/watch pdb.
`reflector.go:134] k8s.io/client-go/informers/factory.go:132: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:kubeflow:mpi-operator" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
`
This PR is to add create/list/watch rule for policy group and poddisruptionbudgets resource.
--- …
=> Add pdb to mpi-operator clusterrole

components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug
- Namespace selector now only show on `Activity` and are disabled everywhere else
/assign @avdaredevil @prodonjs 
/cc: @rileyjbauer 
/priority p1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2788)
=> Namespace selector now only shows up when on activity page

kubeflow/mpi-job/mpi-operator.libsonnet
mpi-operator doesn't log to std by default, this `kubectl logs` doesn't retrieve the logs. 
See `alsologtostderr` flag is also set in [mpi-operator.yaml](https://github.com/kubeflow/mpi-operator/blob/master/deploy/3-mpi-operator.yaml#L23).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2793)
=> Add missing alsologtostderr flag to mpi-operator args

bootstrap/config/kfctl_basic_auth.yaml, bootstrap/config/kfctl_default.yaml, testing/kfctl/kfctl_go_test.py
* Fix #2796; stop installing the jupyter component (jupyterhub) and
trying to set parameters on that component.
* In presubmits we need to pull the config file listing the ksonnet packages,
and components to configure from the PR branch and not master.
* To support local running of the test, only activate the service account if
GOOGLE_APPLICATION_CREDENTIALS is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2798)
=> Stop setting JupyterHub parameters and pull config from PR branch.

testing/kfctl/conftest.py, testing/kfctl/kf_is_ready_test.py, testing/kfctl/kfctl_delete_test.py, testing/kfctl/kfctl_go_test.py, testing/wait_for_kubeflow.py, testing/workflows/components/kfctl_go_test.jsonnet, testing/workflows/components/workflows.libsonnet, testing/workflows/environments/kubeflow-testing/params.libsonnet
* Adds the component tests but not the spark operator tests.
* Related to #2610 E2E test for go binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2795)
=> E2E kfctl go test should verify that Kubeflow is deployed.

bootstrap/pkg/apis/apps/kfdef/v1alpha1/application_types.go, bootstrap/pkg/kfapp/coordinator/coordinator.go
fixes #2826
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2827)
=> fixes 'kfctl attribute deleteStorage is appearing in app.yaml when platform is not gcp'

kubeflow/mpi-job/mpi-operator.libsonnet
This is required if gang scheduling is enabled. See MPI-Operator's RBAC [here](https://github.com/kubeflow/mpi-operator/blob/master/deploy/2-rbac.yaml#L52) that requires "update" for pdb resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2792)
=> Add "update" verb to pdb resource of mpi-job

bootstrap/pkg/kfapp/ksonnet/ksonnet.go, testing/kfctl/kfctl_go_test.py
fixes #2791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2813)
=> fixes 'kfctl apply fails to create k8s resources; tries to deploy to 127.0.0.1'

kubeflow/registry.yaml
Need cherry pick to v0.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2840)
=> remove openmpi from registry file

prow_config.yaml, testing/kfctl/conftest.py, testing/kfctl/kf_is_ready_test.py, testing/kfctl/kfctl_go_test.py, testing/workflows/components/kfctl_go_test.jsonnet, testing/workflows/components/params.libsonnet, testing/workflows/components/util.libsonnet
Related to #2610 E2E test for go binary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2814)
=> Add kfctl E2E test on GCP with IAP

bootstrap/pkg/kfapp/coordinator/coordinator.go, bootstrap/pkg/kfapp/ksonnet/ksonnet.go
fixes #2809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2810)
=> fixes 'kfctl delete fails when no platform or minikube is specified'

bootstrap/cmd/bootstrap/app/k8sUtil.go
Otherwise rerun `kfctl apply` will fail at installing istio.
/cc @kunmingg @gabrielwen 
Tested I can rerun  `kfctl apply` with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2839)
=> make createResourceFromFile check first, then create

bootstrap/config/kfctl_basic_auth.yaml, bootstrap/config/kfctl_default.yaml, bootstrap/config/kfctl_iap.yaml, bootstrap/pkg/apis/apps/group.go, bootstrap/pkg/kfapp/coordinator/coordinator.go, bootstrap/pkg/kfapp/gcp/gcp.go, bootstrap/pkg/kfapp/ksonnet/ksonnet.go, bootstrap/pkg/utils/gcputils.go, bootstrap/pkg/utils/iamutils.go, bootstrap/pkg/utils/k8utils.go, testing/workflows/components/kfctl_go_test.jsonnet
* remove gcloud dependency from gcp.go,
* remove kubectl dependency from ksonnet.go,
* parameterize auth method for gcp.go and ksonnet.go.
so kfctl and deploy app can use same code with their own auth methdo.
New interface example:
Generate() and Apply() need to be called by deploy app, it need to satisfy:
* no dependency on ENV var
* no dependency on local config like gcloud or kube config
* need to be thread safe
* only do disk read/write within it's own app dir.
Now for kfctl we prepare auth config in GetKfApp()
Have to remove application to avoid concurrent label edit.
Will hard code label for v0.5 and use application component once kustomize.
--- …
=> kfctl interface in gcp.go/ksonnet.go for deploy app

components/centraldashboard/.eslintrc.json, components/centraldashboard/package-lock.json, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/public/components/not-found-view.js, components/centraldashboard/webpack.config.js
Fixes #2759.
This PR adds a not-found view that stylistically matches the look of the message on the Activity page before a Namespace is selected.
Here are some screencasts of the behavior:
- This shows the primary behavior running locally on the Webpack Dev Server. If a user explicitly navigates to an unknown route, the view is shown indicating that the page is invalid.
- https://screencast.googleplex.com/cast/NDc4OTAzMjM0NTE0MTI0OHxlOWI4YzdkMy0zMA
- This shows the behavior when deployed in a Kubeflow cluster on GKE. The behavior is the same.
- https://screencast.googleplex.com/cast/NjAwMjAwMzc4ODQzMTM2MHxmZDI5OWFjNC1jYw
It should no longer be possible to land on the dashboard unless using the base URL of the cluster.
With respect to the iframe-inception behavior, I believe that should …
=> Add NotFoundView to catch invalid paths

components/centraldashboard/public/styles.css
Resolves #2847. Essentially full-bleed doesn't work on firefox since `bottom: 0` on frame absolute positioning isn't defaulted to `100vh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2859)
=> Added a height change for Firefox support

bootstrap/pkg/kfapp/gcp/gcp.go, bootstrap/pkg/utils/iamutils.go, bootstrap/pkg/utils/iamutils_test.go
Choose the safe way to clean and only clean the auto-generated service accounts bindings of current deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2856)
=> use whitelist for iam policy clean

bootstrap/pkg/kfapp/gcp/gcp.go, components/notebook-controller/pkg/controller/notebook/notebook_controller.go, kubeflow/jupyter/notebook_controller.libsonnet, kubeflow/jupyter/prototypes/notebook_controller.jsonnet
Fix #2770
/cc @jlewi @zabbasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2853)
=> add labels for notebook so that gcp credentials will be injected by webhook

kubeflow/jupyter/jupyter.libsonnet, kubeflow/jupyter/tests/jupyter_test.jsonnet
The jupyter service account can already create a deployment with a
secret mounted and read it that way, so its just more of a hassle to not
let it explicitly list secrets.
Fixes https://github.com/kubeflow/kubeflow/issues/2876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2887)
=> Let jupyter service account list/get/create secret

bootstrap/Makefile, bootstrap/developer_guide.md, docs_dev/releasing.md
* Instructions for building binaries and uploading to GitHub release page.
* We need to figure out if/how we cross-compile for linux.
* Cross compiling seems to be unnecessary
* The go binaries built on linux appear to work on macosx.
Fix: #2383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2894)
=> Create a minimal release process for kfctl.

deployment/aws/infra_configs/iam_alb_ingress_policy.json, deployment/aws/infra_configs/iam_cloudwatch_policy.json, kubeflow/aws/OWNERS, kubeflow/aws/README.md, kubeflow/aws/aws-alb-ingress-controller.libsonnet, kubeflow/aws/aws-efs-pv.libsonnet, kubeflow/aws/aws-fsx-csi-driver.libsonnet, kubeflow/aws/istio-ingress.libsonnet, kubeflow/aws/parts.yaml, kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet, kubeflow/aws/prototypes/aws-efs-pv.jsonnet, kubeflow/aws/prototypes/aws-fsx-csi-driver.jsonnet, kubeflow/aws/prototypes/istio-ingress.jsonnet, kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet, kubeflow/aws/tests/aws-efs-pv_test.jsonnet, kubeflow/aws/tests/aws-fsx-csi-driver_test.jsonnet, kubeflow/aws/tests/istio-ingress_test.jsonnet, scripts/aws/delete_deployment.sh, scripts/aws/util.sh, scripts/kfctl.sh
1. Documentation will come to kubeflow/website soon.
2. This PR only includes shell scripts change to provision cluster. Go cmd is in progress. 
3. AWS use ALB ingress controller to manage external traffic. Traffic will route to istio first and then come into Ambassador. 
4. Integrate few aws services like Lustre for DL training and Cloudwatch as log backend.
4. Looks like Kubeflow will move to Istio for routing later and we install [istio](https://www.kubeflow.org/docs/components/istio/) in the progress of kubeflow provision.
5. Authentication and TLS will not be enabled by default. They needs some manual efforts from users now. This will be documented in kubeflow/website.
6. Using eksctl to provision EKS cluster.  This is added in `apply platform` phase
--- …
=> Add aws platform option

components/gcp-admission-webhook/main.go, kubeflow/gcp/prototypes/webhook.jsonnet
Fix #2896
Reference: https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/webhook.go#L377
Tested the notebook is accessible, and the volume/env are there by webhook
/cc @jlewi @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2903)
=> fix patch string for admission webhook

kubeflow/mpi-job/mpi-job.libsonnet, kubeflow/mpi-job/mpi-operator.libsonnet, kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet, kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet, kubeflow/mpi-job/prototypes/mpi-operator.jsonnet, kubeflow/mpi-job/tests/mpi-job_test.jsonnet, kubeflow/mpi-job/tests/mpi-operator_test.jsonnet
Resolve #2858 
1. Did some refactor and make mpi-job testable. Add unit tests for both mpi-job and mpi-operator
2. Add volume support for mpi-job.
I didn't change/add/remove any prototype names.  should be very safe.
This is still for v1alpha1. Notice mpi-job has v1alpha2 released and corresponding prototype should be separate tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2869)
=> Add volumn support and unit tests for mpi-job

components/jupyter-web-app/kubeflow_jupyter/common/utils.py
We could also implement this in the notebook controller, since doing it in the notebook CRD itself would allow any service account to be mounted. However, we will most likely want that behavior in the future
cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2917)
=> Use jupyter service account for notebook CRD

components/gcp-click-to-deploy/src/DeployForm.tsx
More UI update for v0.5
* make auto redirect works for v0.5 since we are deprecating jupyterhub
* make auto redirect works for basic-auth mode and avoid confusion
* make auto redirect backward-compatible with v0.4.1
* update button & messages; remove cloud-shell button to avoid confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2916)
=> deploy UI update for v0.5

components/centraldashboard/public/components/main-page.css, components/centraldashboard/public/components/main-page.pug
Just what the title says
/review @prodonjs 
/priority p1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2922)
=> Added usage reporting link

bootstrap/pkg/kfapp/gcp/gcp.go
Fixes #2824 
Currently when invoking long running API calls to GCP/k8s, we'll keep retry until exponential backoff is expired.  This PR is to fix one call that is left - `serviceusage.Enable`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2914)
=> retry for long running API enabling services

kubeflow/gcp/create_ca.sh, kubeflow/gcp/webhook.libsonnet
Previously we only patches caBundle once.
Reapply (kfctl apply) will clear the caBundle.
So now make the patch job a StatefulSet and check every 10 sec.
Fix #2897 
/cc @jlewi @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2928)
=> fix webhook cert

components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/public/components/main-page_test.js
Ensures that all links on the Central Dashboard are namespace-aware in order to preserve state and allow it to be passed down to child components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2913)
=> Central Dashboard - Add statefulness to generated links

components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
As namespaces are populated in UI, conditionally default the namespace to `kubeflow` if found in list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2941)
=> Conditionally make kubeflow the default namespace if found

components/jupyter-web-app/kubeflow_jupyter/default/app.py, components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
Hotfix for: #2937 
Now only one namespace is available: `kubeflow`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2951)
=> Notebook ui default namespace

components/tensorflow-notebook-image/Dockerfile
fixes #2945 
Use the latest release version (v0.5) of fairing in Kubeflow tensorflow images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2950)
=> Updating Fairing commit to v0.5 release of the python library

components/tensorflow-notebook-image/install.sh
This PR will address where common packages are not installed for python3 (base) environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2967)
=> fix python env for common packages

kubeflow/pipeline/pipeline-apiserver.libsonnet
Hello,
as part of our work on kubeflow/pipelines#801. we need to include a few extra permissions to the service account which runs the pipeline (`pipeline-runner`) so it can `create`, `get` and `delete` `PVC`s and `VolumeSnapshot`s.
It can already `create` and `delete` `PVC`s, so we update the rule to add the verb `get`. We also make a new rule entry referring to `VolumeSnapshot` resources with the verbs `create`, `delete` and `get`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2556)
=> Add extra permissions to ClusterRole 'pipeline-runner'

components/centraldashboard/public/components/activities-list.js, components/centraldashboard/public/components/activities-list_test.js
This adds slightly more context about the events being displayed. See the screenshots which reflect the events emitted from running the *ML - TFX - Taxi Tip Prediction Model Trainer* sample pipeline
**Current**:
**New Change**:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3001)
=> Shows involvedObject rather than Cluster Host in Activities view

kubeflow/gcp/iap.libsonnet, kubeflow/gcp/update_backend.sh
Fixes #3014 
Root cause is because of port conflict.  It seems when installing ISTIO, node port is always assigned as [31380](https://github.com/kubeflow/kubeflow/blob/cbc792bd082f1c3575a02f62faaa643cbbe198d8/dependencies/istio/install/istio-noauth.yaml#L13745).  Therefore when more than one deployments exists, update_backend.sh will not succeed when updating healthz path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3025)
=> Use exact name when updating backend healthz path

kubeflow/common/centraldashboard.libsonnet
Somehow the app itself fixed the problem:
https://github.com/kubeflow/kubeflow/pull/3037#discussion_r277376524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3076)
=> Default central dashboard URI matching to /

components/gcp-click-to-deploy/src/DeployForm.tsx
This change uses the [HTML Autofill Spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) and [TextField's API](https://material-ui.com/api/text-field/) to create an ARIA compliant autocomplete form for OAuth Client ID and Secret fields.
/priority p1
/cc @prodonjs @jlewi @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3090)
=> Added autocomple support for Deploy Form

components/jupyter-web-app/kubeflow_jupyter/default/app.py, components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html, components/jupyter-web-app/kubeflow_jupyter/rok/templates/notebooks.html
closes #3000 
(yay we reached 3000)
Allow a Notebook to be launched in any Namespace from the UI
will need to make a small follow up PR to update the image ksonnet param once the new image gets build from GCB.
cc @zabbasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3019)
=> Allow multiple namespaces

scripts/upgrade_ks_app.py
Fixes #3098, it turned out to be a tiny change. There is more info on iterating over dicts in a 2/3 agnostic way at [PEP469](https://www.python.org/dev/peps/pep-0469/). 
I wasn't sure whether to open this PR against the 0.5 branch or master so just let me know if I did the wrong thing!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3107)
=> Python 2/3 agnostic dict iteration in update_ks_app.py

kubeflow/gcp/cloud-endpoints.libsonnet, kubeflow/gcp/iap.libsonnet, kubeflow/gcp/prototypes/iap-ingress.jsonnet, kubeflow/gcp/tests/iap_test.jsonnet, scripts/gke/gcb_copy_images.jsonnet, scripts/gke/use_gcr_for_all_images.sh
* Add more images to be mirror'd when using VPC service controls
* When using VPC service controls not all GCR repos are accessible so
some images hosted in GCR need to be mirror'd
* Fix a bug in cloud-endpoints controller that prevents the image from being
overwritten by parameters
Related to #3106
Fixes to support VPC service controlls.
* ESP sample web app should get the image from ksonnet parameters so
it can be overwritten with a version from a mirror.
* To support pipelines we need to mirror a bunch of images from
gcr.io/ml-pipeline so they are accessible inside the service perimeter.
Related to kubeflow/pipelines#1203
Related to kubeflow/pipelines#1204
--- …
=> Improve the scripts for mirroing images to support VPC service controls

kubeflow/kubebench/kubebench-job.libsonnet, kubeflow/kubebench/prototypes/kubebench-job.jsonnet
I feel heavy to writer processor/reporter for different kind of models. Logs are enough for some of cases and I want to make reporter step optional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3062)
=> Make kubebench reporter optional

components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json, components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json
updated base image of jupyter notebooks of tf 1.13.1gpu and tf 2.0.0a0gpu from the following:
- [tf build configuration ](https://www.tensorflow.org/install/source#tested_build_configurations)
- [nvidia docker image tags](https://hub.docker.com/r/nvidia/cuda/tags?page=5),
- [nvidia dockerfile for nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04 ](https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/10.0/runtime/cudnn7/Dockerfile)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3117)
=> fixed based images of tf gpu notebooks

components/notebook-controller/pkg/controller/notebook/notebook_controller.go, components/notebook-controller/pkg/util/util.go, kubeflow/jupyter/notebook_controller.libsonnet
Relates to #2978
Tested through manual deployment:
1. Remove ambassador from component list.
1. Bring up KF cluster.
1. Navigate to `Notebooks` and use the UI to create a new notebook server.
1. Verify that `CONNECT` could correctly find Jupyter notebook UI page.
1. Verify that when deleting a notebook server, virtual service is gone with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3104)
=> ISTIO support for notebook controller

components/centraldashboard/Makefile, components/centraldashboard/app/api.ts, components/centraldashboard/app/k8s_service.ts, components/centraldashboard/app/k8s_service_test.ts, components/centraldashboard/package-lock.json, components/centraldashboard/public/ajax_test_helper.js, components/centraldashboard/public/components/dashboard-view.css, components/centraldashboard/public/components/dashboard-view.js, components/centraldashboard/public/components/dashboard-view.pug, components/centraldashboard/public/components/dashboard-view_test.js, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/public/components/main-page_test.js
addresses #2885 
Adds new /api/platform-info endpoint to expose provider information to allow front-end to set platform specific links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2935)
=> Use platform info to display provider-specific links.

components/profile-controller/pkg/apis/apis.go, components/profile-controller/pkg/apis/kubeflow/v1alpha1/profile_types.go, components/profile-controller/pkg/controller/profile/profile_controller.go
* fix https://github.com/kubeflow/kubeflow/issues/2601
* Create owner's default k8s rbac rolebinding for https://github.com/kubeflow/kubeflow/issues/2982
* generate service accounts for user pods
* Can be used by https://github.com/kubeflow/kubeflow/issues/2980
* fix duplicate update for newly created binding
* use k8s default role when possible
* fix go generate
Manually tested, works as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3123)
=> fix permission leak; give default admin permission for namespace owner

components/centraldashboard/README.md, components/centraldashboard/package-lock.json, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/public/components/main-page_test.js, components/centraldashboard/public/components/namespace-selector.js, components/centraldashboard/public/index_test.js, components/centraldashboard/public/library.js, components/centraldashboard/public/library_test.js, components/centraldashboard/webpack.config.js
addresses #2845 
child of #2913 
This WIP PR demonstrates a working solution for passing the active namespace to child pages. We bind to the **load** event of the iframe element and pass the active namespace (if selected) down through the message bus. We then pass the namespace to the active iframe anytime it is changed by observing a property change.
See https://screencast.googleplex.com/cast/NjUwNzg4MTA3NTU3MjczNnw5NDI1OGNjNi1jZg for a demo or pull and run it locally. Run `python -m SimpleHTTPServer` from the centraldashboard directory to run serve the test.html page included in this commit which receives the message from the parent page. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Enable iframed pages to communicate with Central Dashboard.

components/jupyter-web-app/kubeflow_jupyter/common/api.py, components/jupyter-web-app/kubeflow_jupyter/common/utils.py
Addresses the issue in the last comments of #2958 
and #3131 
Backend handles StorageClasses with no Annotations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3187)
=> Jupyter UI - Handle no Annotations

components/centraldashboard/package-lock.json, components/centraldashboard/public/components/main-page.css, components/centraldashboard/public/components/main-page.pug, components/centraldashboard/public/components/main-page_test.js, components/centraldashboard/public/components/namespace-selector.js, components/centraldashboard/public/components/namespace-selector_test.js
Addresses item 2 from #3154
Child of #3157 
Empty State:
Selected:
When viewing iframed-application:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3191)
=>  Restyles dashboard namespace selector to match UX specifications

kubeflow/pipeline/istio-service.libsonnet
Forgot to add `svc` to the service path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3192)
=> Fix pipeline viewer ISTIO rule

components/jupyter-web-app/kubeflow_jupyter/common/utils.py, kubeflow/jupyter/jupyter-web-app.libsonnet
We can migrate all user created pods to service accounts.
```default-editor```
```default-viewer```
Those accounts will be managed by profile: https://github.com/kubeflow/kubeflow/pull/3123
We can start with notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3161)
=> Grant user-created notebook namespaced default edit permission

testing/workflows/components/kfctl_go_test.jsonnet
Delete the NFS directory after running the workflow. This should help
prevent the NFS directory from filling up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3209)
=> Delete the NFS directory.

bootstrap/pkg/kfapp/ksonnet/ksonnet.go
https://github.com/kubeflow/testing/issues/361
We have testing infra resources leaked due to undeleted ingress resources. A possible cause is the ingress controller doesn't have enough time to delete the resource completely. https://github.com/kubernetes/ingress-gce/issues/136#issuecomment-417480155
[It usually takes at least 90s to delete a compute instance.](https://cloud.google.com/compute/docs/instances/deleting-instance) So this PR extends the grace period from 100s to 300s.
/cc @gabrielwen @kkasravi @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3185)
=> Extend the grace period for ksonnet.go to delete namespace

bootstrap/Dockerfile, bootstrap/Makefile
This PR adds the following functionality:
* **bootstrap/Makefile**: Target `build-kfctl-container` exports the generated kfctl binary. This gives developers a reploducible build environment to generate the kfctl binary. In addition, it only requires the user to have Docker installed.
* **bootstrap/Dockerfile**: The go.mod and go.sum files are copied in and `go mod download` is run before copying in the code. This is done because dependencies don't change often, so this lets us optimize Docker caching. After adding this, the build time for `kfctl-build-container` was cut in half (5min after vs 10min before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3189)
=> kfctl - Makefile and Dockerfile enhancements

kubeflow/gcp/create_ca.sh, kubeflow/gcp/webhook.libsonnet
#3227 
Webhook pod when created  loads the secret generated by webhook-bootstarp to communicate with mutatingWebhookConfiguration and then consumes it forever. However if webhook-bootstarp (a statefulset) is restarted, it updates the secret. Therefore we need to force webhook to upload the updated secret. To this end,we chose to restart the webhook pod upon updating the secret. 
/assign @lluunn 
tested:
-  delete webhook-bootstrap pod
-  create a new notebook
-  make sure webhook pod mutates the notebook pod correctly 
This needs to be merged to v0.5 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3229)
=> Fix webhook to read  updated secret 
