bootstrap/cmd/kfctl/cmd/apply.go

/cc @kunmingg @jlewi 
#2622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2631)

Fix typo in kfctl

---

bootstrap/cmd/bootstrap/app/ksServer.go
bootstrap/pkg/apis/apps/ksonnet/v1alpha1/application_types.go

fix https://github.com/kubeflow/kubeflow/issues/2617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2625)

store non exist parameter differently

---

bootstrap/cmd/kfctl/cmd/apply.go

#2622
/cc @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2632)

Fix kfctl: didn't pass flag client_id/secret

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2637)

update pipeline system images to 0.1.12 release

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2640)

update pipeline system images to 0.1.12 release (#2637)

---

bootstrap/config/gcp_prototype.yaml
bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/kfctl_default.yaml
bootstrap/config/kfctl_iap.yaml

profiles was added to the config files under bootstrap/config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2689)

fixes 'Install profiles CR by default'

---

bootstrap/pkg/client/gcp/gcp.go
bootstrap/pkg/utils/iamutils.go
bootstrap/pkg/utils/iamutils_test.go

fix https://github.com/kubeflow/kubeflow/issues/2659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2681)

fix IAM policy set

---

scripts/azure/util.sh
scripts/kfctl.sh

resolves #2675 by storing azure creds into a secret during setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2676)

store azure secrets to cluster during setup

---

kubeflow/pipeline/pipeline-viewercrd.libsonnet

fix clusterrole typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2683)

fix pipeline-viewer-controller access kube-apiserver 403

---

testing/test_flake8.py
testing/workflows/components/unit_tests.jsonnet

This PR should only be merged after https://github.com/kubeflow/kubeflow/pull/2247 is successfully merged.
The PR is to address https://github.com/kubeflow/kubeflow/issues/2388 (integrating test_flake8.py into the CI system).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2403)

Integrated test_flake8.py into CI system

---

prow_config.yaml
testing/kfctl/kfctl_go_test.py
testing/workflows/components/kfctl_go_test.jsonnet
testing/workflows/components/kfctl_test.jsonnet
testing/workflows/components/params.libsonnet
testing/workflows/environments/kubeflow-testing/params.libsonnet

* Create a new Argo workflow
* Add a simple python script to build the go binary.
Related to #2610  - E2E test for kfctl
Related to #2343 - Basic auth E2E test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2672)

Scaffolding for E2E test for the new kfctl go binary.

---

kubeflow/gcp/setup_backend.sh

/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2704)

Fix error in setup_backend

---

kubeflow/gcp/iap.libsonnet

fix #2642 
See https://github.com/kubeflow/kubeflow/issues/2642#issuecomment-470672714
/cc @kunmingg @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2654)

Fix iap libsonnet: avoid empty object

---

components/centraldashboard/.eslintrc.json
components/centraldashboard/app/api.ts
components/centraldashboard/app/k8s_service.ts
components/centraldashboard/app/server.ts
components/centraldashboard/package-lock.json
components/centraldashboard/package.json
components/centraldashboard/public/components/activities-list.js
components/centraldashboard/public/components/activity-view.js
components/centraldashboard/public/components/dashboard-view.css
components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/namespace-selector.js
components/centraldashboard/tslint.json

- Work in progress changes for adding events surfacing to central dashboard.
- Adds Google typescript formatting guidelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2667)

Add Namespaces and Activities from API server.

---

components/tensorflow-notebook-image/versions/1.13.1/version-config.json
components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json

#2551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2730)

Added tf 1.13 to the list of jupyter images 

---

kubeflow/modeldb/modeldb.libsonnet
kubeflow/modeldb/parts.yaml
kubeflow/modeldb/prototypes/modeldb.jsonnet

Updates to include:
- Removing MongoDB
- Rewriting API from the ground up
- Pluggable backend systems
- UI redone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2757)

ModelDB V2 support in KubeFlow

---

bootstrap/cmd/kfctl/cmd/generate.go
bootstrap/pkg/kfapp/coordinator/coordinator.go

fixes #2773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2774)

fixes 'ipName and zone are being written to app.yaml even when no platform is specified'

---

kubeflow/pipeline/pipeline.libsonnet

/assign @neuromage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2783)

update pipeline version to v0.1.13

---

kubeflow/katib/prototypes/all.jsonnet

for #2716
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2768)

update katib image for 0.5

---

deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml
deployment/gke/deployment_manager_configs/cluster.jinja

To make cluster-kubeflow.yaml a user-facing config:
* add ability to edit GPU node configs as user request to use multi GPU per pod
* fix CPU_POOL name
* add comments to guide how to customize config
* add default label ```application: 'kubeflow'``` to kubeflow clusters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2655)

update DM config file

---

scripts/setup-minikube.sh

Related to  #2735 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2737)

[KUBEFLOW-2735] Fix regex for distribution detection.

---

components/centraldashboard/package-lock.json
components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.pug
package-lock.json

- Includes link to Privacy page for Google
- CSS changes to make link match proper colors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2786)

Privacy link implemented with CSS changes

---

kubeflow/jupyter/config.yaml

built tf 2.0 and 1.13 images
retag all images to v0.5.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2805)

Retag jupyter images with tag v0.5.0

---

bootstrap/developer_guide.md

* Add instructions for how to build kfctl and deal with build errors about
/tmp/v2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2794)

Update the developer guide for kfctl.

---

components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go
components/notebook-controller/pkg/apis/notebook/v1alpha1/zz_generated.deepcopy.go
components/notebook-controller/pkg/controller/notebook/notebook_controller.go
kubeflow/jupyter/notebook_controller.libsonnet
kubeflow/jupyter/prototypes/notebook_controller.jsonnet

/cc @richardsliu @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2822)

Cherrypick #2787 into 0.5 branch

---

kubeflow/application/prototypes/application.jsonnet
kubeflow/common/prototypes/basic-auth.jsonnet
kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
kubeflow/tf-training/prototypes/tf-job-operator.jsonnet

/cc @richardsliu @kunmingg
#2716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2816)

update ks for 0.5

---

bootstrap/pkg/kfapp/coordinator/coordinator.go

Fixes #2850
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2851)

check if spec is already set

---

components/centraldashboard/README.md

closes #2836 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2865)

Update README with additional information on release/testing

---

kubeflow/katib/prototypes/all.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2875)

Update image tags for katib

---

components/centraldashboard/README.md
components/centraldashboard/public/kubeflow-palette.css

- Standard style guide added as a CSS import sheet
- Variable names can be standardized later
- Relevant docs added
/priority p1
/review @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2878)

Style guide added, with supporting docs

---

bootstrap/pkg/kfapp/gcp/gcp.go

adding actionable command to logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2873)

add auth cmd to logging

---

scripts/create_password_secret.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2662)

A script to reset the basic auth secret.

---

kubeflow/jupyter/prototypes/notebook_controller.jsonnet

/cc @abhi-g @zabbasi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2895)

update notebook controller image

---

deployment/aws/infra_configs/iam_alb_ingress_policy.json
deployment/aws/infra_configs/iam_cloudwatch_policy.json
kubeflow/aws/OWNERS
kubeflow/aws/README.md
kubeflow/aws/aws-alb-ingress-controller.libsonnet
kubeflow/aws/aws-efs-pv.libsonnet
kubeflow/aws/aws-fsx-csi-driver.libsonnet
kubeflow/aws/istio-ingress.libsonnet
kubeflow/aws/parts.yaml
kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet
kubeflow/aws/prototypes/aws-efs-pv.jsonnet
kubeflow/aws/prototypes/aws-fsx-csi-driver.jsonnet
kubeflow/aws/prototypes/istio-ingress.jsonnet
kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet
kubeflow/aws/tests/aws-efs-pv_test.jsonnet
kubeflow/aws/tests/aws-fsx-csi-driver_test.jsonnet
kubeflow/aws/tests/istio-ingress_test.jsonnet
scripts/aws/delete_deployment.sh
scripts/aws/util.sh
scripts/kfctl.sh

* Add aws platform option
* Move ingress and fsx driver to ksonnet libs
* Add istio with ingress support
* Disable Jwt token checking by default
* Add cluster provision and destroy scripts
* Correct eksctl created role name
* Clean up scripts and fix errors
* Add unit tests from aws packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2898)

Cherry-pick #2823 to v0.5 - Add aws platform option

---

kubeflow/mxnet-job/README.md
kubeflow/mxnet-job/mxnet-operator.libsonnet
kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2909)

update kubeflow mxnet integration for mxnet-operator version update (#2797)

---

bootstrap/Makefile
bootstrap/cmd/bootstrap/app/ksServer.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2899)

include spec dir to container; use remote spec when local cache doesn't exist

---

kubeflow/paddle-job/README.md
kubeflow/paddle-job/paddle-job.libsonnet
kubeflow/paddle-job/paddle-operator.libsonnet
kubeflow/paddle-job/parts.yaml
kubeflow/paddle-job/prototypes/paddle-job.jsonnet
kubeflow/paddle-job/prototypes/paddle-operator.jsonnet

The paddle-job folder contains prototypes for running Paddle jobs which are based on PaddlePaddle (PArallel Distributed Deep LEarning) framework. This framework is an easy-to-use, efficient, flexible and scalable deep learning platform, which is originally developed by Baidu scientists and engineers for the purpose of applying deep learning to many products.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2828)

add paddle-job

---

kubeflow/jupyter/ui/default/config.yaml
kubeflow/jupyter/ui/rok/config.yaml

#2901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2902)

Jupyter docker images should be updated on the 0.5 branch

---

components/gcp-click-to-deploy/app-config.yaml
components/gcp-click-to-deploy/src/DeployForm.tsx

Once deployed, we'll support all v0.5 compatible commits, plus v0.4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2879)

update frontend config to be compatible with v0.5

---

kubeflow/jupyter/jupyter-web-app.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2919)

Add jupyter notebook svc account and roles

---

components/tensorflow-notebook-image/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2918)

Update fairing to bd8313

---

bootstrap/pkg/kfapp/gcp/gcp.go

Fixes #2900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2912)

List endpoints when delete is failed

---

bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/ksonnet/ksonnet.go

* We need to retry around IAM APIs when concurrent deploys happen to same project
* ks init might timeout (quite rare)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2920)

add retry around IAM APIs and ksonnet app init

---

kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
kubeflow/kubebench/prototypes/kubebench-job.jsonnet
kubeflow/kubebench/prototypes/kubebench-operator.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2923)

Update Kubebench tags

---

components/gcp-click-to-deploy/src/App.tsx
components/gcp-click-to-deploy/src/DeployForm.tsx

Will deploy to staging so we can verify user experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2930)

update UI to include port-forward; update instructions

---

bootstrap/cmd/bootstrap/app/ksServer.go
components/gcp-click-to-deploy/src/DeployForm.tsx

* Skip password input check when choose "Setup Endpoint later"
* rename error from ```spec not found```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2939)

quick fix for deploy UI with v0.5

---

kubeflow/pipeline/pipeline.libsonnet

/assign @IronPan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2940)

Update Pipelines to version 0.1.15

---

components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.pug

- **Update for #2921** 
- **Hotfix for #2922** 
/priority p1
/review @prodonjs @rileyjbauer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2942)

[Hotfix] Usage reporting Link

---

kubeflow/pipeline/pipeline.libsonnet

/assign @IronPan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2944)

Cherry-pick: Update Pipelines to version 0.1.15 (#2940)

---

bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/kfctl_iap.yaml

/cc @abhi-g @kunmingg 
Need this for 0.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2946)

set param for notebook controller

---

kubeflow/gcp/iap.libsonnet
kubeflow/gcp/setup_backend.sh

Fixes #2550 
Use `.metadata.annotations` information in ingress service to extract exact backend service name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2938)

Extract exact backend service name

---

components/gcp-click-to-deploy/src/DeployForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2953)

add option to create permanent storage and spartakus

---

kubeflow/pipeline/pipeline.libsonnet

/assign @IronPan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2955)

Update Pipelines to version 0.1.16

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2957)

Update Pipelines to version 0.1.16 (#2955) {Cherry-pick to v0.5-branch}

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2956)

Update Pipelines to version 0.1.16 (#2955) {Cherry-pick to pipelines}

---

bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/kfctl_iap.yaml

For #2716 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2948)

Automated cherry pick of #2946: set param for notebook controller Cherry pick of #2946 on v0.5-branch. #2946: set param for notebook controller

---

kubeflow/jupyter/prototypes/notebook_controller.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2968)

set injectGcpCredentials to true by default

---

kubeflow/gcp/iap.libsonnet
kubeflow/gcp/setup_backend.sh

For #2716 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2949)

Automated cherry pick of #2938: lookup backend service full name Cherry pick of #2938 on v0.5-branch. #2938: lookup backend service full name

---

components/jupyter-web-app/kubeflow_jupyter/default/app.py
components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2966)

Automated cherry pick of #2951: Notebook ui default namespace

---

bootstrap/Makefile
bootstrap/cmd/kfctl/cmd/apply.go
bootstrap/cmd/kfctl/cmd/delete.go
bootstrap/cmd/kfctl/cmd/generate.go
bootstrap/cmd/kfctl/cmd/init.go
bootstrap/cmd/kfctl/cmd/show.go
bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/kfctl_default.yaml
bootstrap/config/kfctl_iap.yaml
bootstrap/developer_guide.md
bootstrap/pkg/kfapp/coordinator/coordinator.go
bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/ksonnet/ksonnet.go

fixes #2933
- Ordering of the components under bootstrap/config/{kfctl_default.yaml, kfctl_basic_auth.yaml, kfctl_iap.yaml} is important. Metacontroller needs to go first.
- Remove references to the "application" component in ksonnet.Delete
- Call ksonnet Delete to delete global resources
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2934)

kfctl will fail for --platform gcp if /Users/kdkasrav/.kube/config doesn't exist

---

bootstrap/config/gcp_prototype.yaml
testing/test_deploy_app.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2977)

update prober test for v0.5.0

---

components/tensorflow-notebook-image/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2972)

add zabbasi to approvers for notebook images

---

kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
kubeflow/tf-training/tests/tf-job_test.jsonnet
kubeflow/tf-training/tf-job-operator.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2960)

enable gang scheduling flag for tf-operator

---

components/contrib/kaggle-notebook-image/Dockerfile

Smoke-tested version pushed to gcr.io/kubeflow-dev/kubeflow-kaggle-notebook:latest
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2105)

Update for Kaggle Dockerfile

---

testing/test_deploy_app.py

React to cloud source repo's recent policy change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3034)

reuse source repo for continuous tests

---

components/contrib/rapidsai-notebook-image/Dockerfile

Updated to pull latest RAPIDS CUDA 9.2 image. Some minor package changes.
`gcr.io/kubeflow-dev/kubeflow-rapidsai-notebook:cuda9.2-devel-ubuntu16.04`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3010)

Update RAPIDS AI Dockerfile

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3043)

release pipeline 0.1.17

---

bootstrap/pkg/kfapp/gcp/gcp.go
kubeflow/gcp/basic-auth-ingress.libsonnet

Files is in `app_dir/gcp_config`, not `app_dir/`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3044)

fix optional deployments bug

---

kubeflow/pipeline/pipeline.libsonnet

update pipeline branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3051)

release pipeline 0.1.17 (#3043)

---

bootstrap/pkg/kfapp/gcp/gcp.go
kubeflow/gcp/basic-auth-ingress.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3050)

Automated cherry pick of #3044: fix optional deployments bug Cherry pick of #3044 on v0.5-branch. #3044: fix optional deployments bug

---

kubeflow/jupyter/jupyter-web-app.libsonnet
kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet

Relates to #2964 
Relates to #2978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3028)

Jupyter ISTIO routing rule - Ksonnet

---

kubeflow/argo/argo.libsonnet
kubeflow/argo/prototypes/argo.jsonnet

Relates to #2978 #2965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3033)

Argo ISTIO routing rule - Ksonnet

---

bootstrap/Dockerfile
bootstrap/Makefile
bootstrap/cmd/kfctl/cmd/root.go
bootstrap/cmd/kfctl/cmd/version.go
bootstrap/cmd/kfctl/main.go

fixes #2986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2988)

Value of kfctl version is hardcoded and not representative of the actual build

---

kubeflow/common/centraldashboard.libsonnet
kubeflow/common/echo-server.libsonnet
kubeflow/common/prototypes/centraldashboard.jsonnet
kubeflow/common/prototypes/echo-server.jsonnet
kubeflow/examples/prototypes/tensorboard.jsonnet
kubeflow/kubebench/kubebench-dashboard.libsonnet
kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
kubeflow/openvino/openvino.libsonnet
kubeflow/openvino/prototypes/openvino.jsonnet
kubeflow/seldon/prototypes/core.jsonnet
kubeflow/tensorboard/gcp.libsonnet
kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
kubeflow/tensorboard/tensorboard.libsonnet
kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
kubeflow/tf-training/tf-job-operator.libsonnet

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3037)

Finish all ISTIO routing rules for IAP.

---

bootstrap/cmd/kfctl/cmd/init.go
prow_config.yaml
testing/kfctl/kfctl_go_test.py

for #3007 
/cc @gabrielwen @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3072)

kfctl default use istio

---

bootstrap/config/kfctl_iap.yaml
bootstrap/pkg/kfapp/coordinator/coordinator.go

Relates to #2978 #3021 
Skip configs for basic auth for now as it's not implemented yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3075)

Add injectIstio param to kfctl configs

---

bootstrap/pkg/kfapp/gcp/gcp.go

Fix when generating manifests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3078)

iap-ingress is not used in basic auth

---

kubeflow/pipeline/istio-service.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3077)

fix typo in pipeline istio rule.

---

kubeflow/aws/OWNERS
scripts/aws/util.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3084)

Update aws OWNERS file and make ingress configurable

---

kubeflow/katib/prototypes/all.jsonnet
kubeflow/katib/vizier.libsonnet

Fixes #3046
For other components, I've already added params to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3059)

clusterDomain params adding to katib

---

bootstrap/v2/pkg/kfapp/kustomize/kustomize.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3070)

mini fix for "kfctl delete"

---

components/tensorflow-notebook-image/versions/1.13.1gpu/version-config.json
components/tensorflow-notebook-image/versions/2.0.0a0gpu/version-config.json

fixes #3094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3113)

Fix based images of tf gpus for tf 1.13 and tf 2.0

---

components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/main-page_test.js

closes #2546 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3110)

Renames Documentation link and removes it from iframe.

---

components/centraldashboard/README.md
components/centraldashboard/public/kubeflow-palette.css

Uniform color scheme from all pages thus far. Also, Primary colors updated from notebooks UI which is a good example of complementary color palettes
/cc @prodonjs 
/priority p2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3115)

Color Scheme Adjusted to incorporate a better set of colors

---

components/gcp-click-to-deploy/src/DeployForm.tsx

every time I see this label in the webapp, the sans-serif font makes me think it's 'lap' with an L.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3038)

change 'iap' case in c2d text

---

components/centraldashboard/Dockerfile
components/centraldashboard/Makefile
components/centraldashboard/make-win.ps1
components/centraldashboard/package.json
components/centraldashboard/webpack.config.js

- [Windows] make-win updated with all the relevant updates in Makefile
- Dev build is now labeled dev-build
- Dashboard version is now versioned with a commit as well
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3125)

Version Related Changes

---

kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet

allow deploying from latest jupyter-web-app in master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3153)

Update jupyter-web-app image to point to latest in master

---

kubeflow/argo/prototypes/argo.jsonnet
kubeflow/common/prototypes/centraldashboard.jsonnet
kubeflow/common/prototypes/echo-server.jsonnet
kubeflow/examples/prototypes/tensorboard.jsonnet
kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
kubeflow/katib/prototypes/all.jsonnet
kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
kubeflow/openvino/prototypes/openvino.jsonnet
kubeflow/pipeline/pipeline.libsonnet
kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet
kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
kubeflow/tf-serving/prototypes/tf-serving-aws.jsonnet
kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet
kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet
kubeflow/tf-training/prototypes/tf-job-operator.jsonnet

The original reason to make `injectIstio` to true is because not all users know to set this value to true when adding optional components.  This doesn't add too much value but will break here and there.  Revert it for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3160)

revert param true

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3121)

Update Pipelines to version 0.1.18

---

kubeflow/common/centraldashboard.libsonnet
kubeflow/common/tests/centraldashboard_test.jsonnet

Necessary to enable the functionality in #2935 which addresses #2885.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3097)

Add additional APIs to Central Dashboard roles

---

bootstrap/pkg/apis/apps/group.go

Relates to #3159 
/assign @lluunn @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3170)

default v0.5 version to v0.5-branch

---

releasing/auto-update/update_job.yaml
releasing/auto-update/update_job_cron.yaml

* Now that the code is checked in update the references to use the code
from the main repo.
* Create a cron job to generate the PRs.
Related to #2206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3146)

Update the job specs for the auto-updater.

---

components/centraldashboard/package-lock.json
components/centraldashboard/public/components/dashboard-view.js
components/centraldashboard/public/components/dashboard-view.pug
components/centraldashboard/public/components/iframe-link.js
components/centraldashboard/public/components/iframe-link_test.js
components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/main-page_test.js
components/centraldashboard/public/components/utilities-mixin.js
components/centraldashboard/public/components/utilities-mixin_test.js

Also factor out utility functions into a Mixin that can be used across components.
Addresses point 3 from #3154 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3190)

Centralize iframe link building and replace quick shortcuts links

---

components/centraldashboard/.gitattributes

Changes according to: https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/
/priority p2
/cc @prodonjs 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3195)

Change to enforce CRLF -> LF changes

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3193)

upgrade pipeline to 0.1.19

---

bootstrap/pkg/apis/apps/group.go

/cc @kunmingg @gabrielwen
For #3159 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3205)

kfctl use 0.5.1

---

bootstrap/Makefile

fix ```make build-kfctl``` on Mac.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3183)

quick fix for make build-kfctl on Macbook

---

bootstrap/OWNERS

mostly for kfctl approvals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3215)

Add kkasravi and gabrielwen to bootstrap OWNERS

---

kubeflow/katib/OWNERS
kubeflow/katib/vizier.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3200)

remove unused katib rbac

---

components/jupyter-web-app/kubeflow_jupyter/default/app.py

jupyter web app returns 400.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3224)

fix invalid access to request body.

---

bootstrap/cmd/kfctl/cmd/apply.go
bootstrap/cmd/kfctl/cmd/completion.go
bootstrap/cmd/kfctl/cmd/delete.go
bootstrap/cmd/kfctl/cmd/generate.go

fixes #2543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3067)

kfctl (golang) add bash/zsh completion

---

components/kflogin/public/index.html

Change the login page title from React App to Kubeflow Cluster Login.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3233)

Update Kflogin page title

---

kubeflow/gcp/create_ca.sh
kubeflow/gcp/webhook.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3238)

Automated cherry pick of #3229: fix for #3227 Cherry pick of #3229 on v0.5-branch. #3229: fix for #3227

---

components/notebook-controller/pkg/controller/notebook/notebook_controller.go
dependencies/istio/install/README.md
dependencies/istio/install/istio-noauth.yaml

fix https://github.com/kubeflow/kubeflow/issues/3218
and for notebooks follow https://github.com/kubeflow/kubeflow/issues/3219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3235)

enable Istio Injection in user-created namespace; notebook and Istio integration

---

bootstrap/api/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3176)

Add a README with the redoc link for the kfctl API.

---

bootstrap/config/kfctl_iap.yaml
bootstrap/pkg/kfapp/gcp/gcp.go
kubeflow/gcp/iap.libsonnet
kubeflow/gcp/prototypes/iap-ingress.jsonnet
kubeflow/gcp/tests/iap_test.jsonnet

Relates to #3122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3253)

Deploy JWT policy with ingress

---

components/jupyter-web-app/kubeflow_jupyter/common/utils.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3270)

Handle imageType error when readOnly is true.

---

ROADMAP.md
components/centraldashboard/public/components/dashboard-view.js

Add MiniKF to the central dashboard, so that the latter is consistent with the Kubeflow docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3211)

Add MiniKF to the central dashboard

---

kubeflow/pipeline/pipeline.libsonnet

/assign @neuromage @vicaire
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3263)

update kfp version

---

py/kubeflow/kubeflow/ci/update_jupyter_web_app.py

The tests keep failing for PRs created by the jupyter web app auto updater.
I think because we will git push -f the changes each time the code runs. This
means we re-trigger the tests even if a PR already exists.
Related to: #3254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3269)

Don't create the PR or push changes if the PR already exists.

---

kubeflow/pipeline/pipeline.libsonnet

/assign @gaoning777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3281)

cherrypick Pipelines v0.1.20

---

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
kubeflow/pytorch-job/pytorch-operator.libsonnet
kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet

/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3322)

Adding support for Pytorch v1 api

---

bootstrap/config/base/kfctl_default.yaml
bootstrap/config/default.yaml
bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/kfctl_default.yaml
bootstrap/config/kfctl_iap.yaml

resolves #3246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3328)

Add admission-webhook to kfctl default components

---

bootstrap/cmd/kfctl/README.md
bootstrap/cmd/kfctl/cmd/init.go
bootstrap/cmd/kfctl/cmd/root.go
bootstrap/cmd/kfctl/cmd/show.go
bootstrap/cmd/kfctl/cmd/version.go
bootstrap/pkg/kfapp/coordinator/coordinator.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3069)

mini fix for kfctl show

---

kubeflow/argo/prototypes/argo.jsonnet
kubeflow/argo/tests/argo_test.jsonnet

Pipelines are compatible: https://github.com/kubeflow/pipelines/pull/1368
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3335)

Upgraded Argo to v2.3.0

---

bootstrap/config/overlays/kustomize/kfctl_default.yaml
bootstrap/pkg/kfapp/gcp/gcp.go

Relates to kubeflow/manifests#97 kubeflow/manifests#100
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3350)

Fix pvc overlays

---

kubeflow/argo/prototypes/argo.jsonnet
kubeflow/argo/tests/argo_test.jsonnet

/assign @IronPan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3349)

Cherry-picking - Upgraded Argo to v2.3.0 (#3335)

---

components/centraldashboard/public/components/dashboard-view.css
components/centraldashboard/public/components/dashboard-view.pug
components/centraldashboard/public/components/iframe-link.js
components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/main-page_test.js
components/centraldashboard/public/components/resources/cloud-platform-data.js
components/centraldashboard/public/styles.css

- Shortens sidebar links and thins divider to 1px.
- Adds secondary text to platform links
- Fixes hover / active state for dashboard card links.
- Address a11y issue for tabbing on iframe-links.
- Fixes an invalid selector in main-page unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3356)

Address UX feedback tweaks.

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3369)

Update pipeline image version to v0.1.21

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3374)

Cherrypick: update pipeline image version to v0.1.21 (#3369)

---

kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
kubeflow/tf-training/tests/tf-job_test.jsonnet
kubeflow/tf-training/tf-job-operator.libsonnet

Please read the descriptions here:
https://github.com/kubeflow/common/issues/22
https://github.com/kubeflow/tf-operator/issues/988
https://github.com/kubeflow/tf-operator/pull/1018
/assign: @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3378)

Adds prometheus annotation and port configurations for tf-operator

---

components/centraldashboard/public/components/dashboard-view.js
scripts/aws/util.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3301)

added aws link to dashboard, fixed typo, corrected link

---

bootstrap/config/base/kfctl_default.yaml
bootstrap/config/kfctl_basic_auth.yaml
bootstrap/config/overlays/basic_auth/kfctl_default.yaml
components/notebook-controller/pkg/controller/notebook/notebook_controller.go
kubeflow/jupyter/notebook_controller.libsonnet
kubeflow/jupyter/prototypes/notebook_controller.jsonnet

Fixes #3387
Skip watching and reconcile for virtual services if not using ISTIO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3393)

Fix notebook controller for virtual service

---

bootstrap/pkg/kfapp/gcp/gcp.go

Fatalf will exit the process.
/cc @gabrielwen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3390)

fix log level

---

scripts/gke/gcb_copy_images.jsonnet
scripts/gke/use_gcr_for_all_images.sh

/assign @IronPan @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3341)

Upgraded scripts to Argo v2.3.0

---

bootstrap/cmd/kfctl/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3342)

Minor update for kfctl.

---

scripts/gke/iam_patch.py

Fixes https://github.com/kubeflow/kubeflow/issues/3006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3008)

iam_patch.py should detect errors

---

components/centraldashboard/public/components/card-styles.js
components/centraldashboard/public/components/dashboard-view.js
components/centraldashboard/public/components/resource-chart.js

Addresses issues captured on [bug bash](https://docs.google.com/spreadsheets/d/1OMbDPqTMFpt_FPlAL2RTa9RbO3cMSbhGN9ZF_xsmxEY/edit#gid=1998042520) spreadsheet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3412)

Miscellaneous improvements from team feedback

---

scripts/aws/util.sh

make istio version templatized to use KUBEFLOW_VERSION
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3340)

templatize istio k8s version for aws

---

testing/workflows/components/kfctl_go_test.jsonnet

fixes #3434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3435)

fix typo in testing/workflows/components/kfctl_go_test.jsonnet

---

deployment/aws/OWNERS
scripts/aws/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3438)

Add OWNERS file under aws components

---

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
kubeflow/pytorch-job/pytorch-operator.libsonnet
kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet

Adds annotations for Prometheus
Adds port for monitoring scraping for prometheus
Master issue: https://github.com/kubeflow/common/issues/22
PyTorch issue: https://github.com/kubeflow/pytorch-operator/issues/174
cc: @johnugeorge 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3432)

Adds service to pytorch deployment

---

scripts/aws/util.sh

Fix ISTIO version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3443)

fix aws provider istio version

---

scripts/aws/util.sh

cherry-pick 
* https://github.com/kubeflow/kubeflow/pull/3443
* https://github.com/kubeflow/kubeflow/pull/3340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3444)

cherry-pick aws istio fix

---

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
kubeflow/pytorch-job/pytorch-operator.libsonnet
kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet

Adding EnableGangScheduling to ksonnet params
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3445)

Adding gang scheduling to params

---

bootstrap/pkg/kfapp/gcp/gcp.go

fix #3265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3447)

Fix a small bug in gcp.go

---

deployment/aws/infra_configs/cluster_config.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3461)

Automated cherry pick of #3280: Upgrade eksctl api to v1alpha5

---

scripts/gke/iam_patch.py

Fixes https://github.com/kubeflow/kubeflow/issues/3006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3415)

Cherry-picking - iam_patch.py should detect errors (#3008)

---

kubeflow/aws/OWNERS
scripts/aws/util.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3460)

Automated cherry pick of #3084: Update OWNERS file and make ingress configurable 

---

kubeflow/pytorch-job/pytorch-operator.libsonnet

Util dependency is removed to make it a independent package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3480)

Removing util dependency in operator package

---

bootstrap/cmd/kfctl/cmd/init.go

fixes #3020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3483)

make kustomize the default

---

components/notebook-controller/OWNERS

should probably have 2 owners per component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3311)

add kkasravi to OWNERS

---

testing/kfctl/kfctl_go_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3493)

pin manifests to a known good version

---

bootstrap/config/overlays/gcp/kfctl_default.yaml
bootstrap/config/overlays/istio/kfctl_default.yaml
bootstrap/pkg/kfapp/gcp/gcp.go

So they become default components on GCP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3495)

add profiles / kfam to kustomize path

---

components/access-management/api/swagger.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3500)

update API spec

---

components/centraldashboard/Makefile
components/centraldashboard/make-win.ps1
kubeflow/common/prototypes/centraldashboard.jsonnet

^^
---
/cc @jlewi @prodonjs 
/priority p0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3466)

Updated master with the latest image for central-dashboard for v0.6

---

kubeflow/pipeline/pipeline.libsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3525)

update pipeline version to v0.1.22

---

bootstrap/config/overlays/application/kfctl_default.yaml

adds a [centraldashboard application CR](https://github.com/kubeflow/manifests/issues/126)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3557)

add centraldashboard application CR

---

components/tensorflow-notebook-image/Dockerfile

/assign @jlewi
Fix #3584 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3587)

Update pipeline SDK version

---

bootstrap/OWNERS
bootstrap/cmd/kfctl/OWNERS

This PR adds me (@yanniszark) to the OWNERS files of kfctl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3506)

kfctl: OWNERS: add yanniszark

---

bootstrap/v2/pkg/kfapp/kustomize/kustomize.go

* To do this we define a setter interface that will allow the K8s client to
be injected.
* We also move the initialization of the K8s clients out of GetPlatform and
into a function initK8sClients that isn't called until we actually need
the client (i.e. in apply)
* This gives callers a chance to inject the RESTConfig
* Some minor cleanup of kustomize
* Delete some unused code; like kustomize.Application
* Make KfDef a member variable rather than embedding it; this is cleaner.
* Not sure what the original impetus of embedding it was.
* Making it a member variable makes it more obvious that we are passing
around a pointer to the different KfApps that are all modifying the same
KfDef; this is important because we want to use the KfDef.Spec/Status
to pass information around.
* Replace …

kustomize should support injecting the K8s restconfig.

---

testing/kfctl/kfctl_go_test.py

Update the pinned version in kfctl go tests to [7cf5587dd9e2ec523bbdc99642d530f42fec4361](https://github.com/kubeflow/manifests/commit/7cf5587dd9e2ec523bbdc99642d530f42fec4361)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3600)

Use manifest master for tests.

---

bootstrap/config/overlays/basic_auth/kfctl_default.yaml
bootstrap/pkg/kfapp/gcp/gcp.go

Related kubeflow/kubeflow#3562 https://github.com/kubeflow/manifests/pull/204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3631)

make basic auth work with kustomize

---

components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py

closes #3556 
This PR will
* Make use of the USERID_{HEADER, PREFIX} ENV Vars
* Query kfam before making a request
If a request has set the userid headers, then the webapp will ask kfam whether this user is authorized for the specific namespace.
If the request doesn't have this header, then the webapp will just make
the needed API calls.
In both cases the webapp will make the k8s requests with its own
privileged SA.
/assign kimwnasptd
/cc lluunn 
/cc kunmingg 
/cc jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3630)

jupyter-web-app: Use kfam to check if user is authorized

---

bootstrap/config/kfctl_gcp_iap.0.6.yaml
bootstrap/config/overlays/istio/kfctl_default.yaml

For https://github.com/kubeflow/manifests/issues/115
Follow up of: https://github.com/kubeflow/manifests/pull/205
/cc @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3664)

Use the new istio pkg in manifest

---

components/centraldashboard/public/components/dashboard-view.js

fixes #3619 
Image updated:
gcr.io/kubeflow-images-public/centraldashboard:v0.6.0-rc5
/cc @IronPan 
@jlewi - Can you approve this since AP is out this week?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3622)

Correct View All Pipelines link

---

releasing/releaser/app.yaml

Fix presubmit by updating dashboard test API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3680)

update dashboard test API

---

bootstrap/config/kfctl_existing_arrikto.0.6.yaml
bootstrap/config/kfctl_gcp_iap.0.6.yaml
bootstrap/config/kfctl_k8s_istio.yaml

part of fixing https://github.com/kubeflow/metadata/issues/101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3714)

Add metadata istio overlay into bootstrap configs

---

bootstrap/config/kfctl_existing_arrikto.0.6.yaml
bootstrap/config/kfctl_gcp_iap.0.6.yaml
bootstrap/config/kfctl_k8s_istio.yaml

/assign @kunmingg @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3717)

Automated cherry pick of #3714 upstream v0.6 branch

---

bootstrap/config/overlays/istio/kfctl_default.yaml

https://github.com/kubeflow/metadata/issues/101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3732)

Fix metadata component name

---

bootstrap/config/overlays/istio/kfctl_default.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3734)

Automated cherry pick of #3732 upstream v0.6 branch

---

bootstrap/pkg/kfapp/coordinator/coordinator.go
bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/gcp/gcp_test.go
bootstrap/v2/pkg/apis/apps/group.go
bootstrap/v2/pkg/apis/apps/group_test.go
bootstrap/v2/pkg/kfapp/kustomize/kustomize.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3741)

Automated cherry pick of #3693: Create PodDefault if platform is GCP

---

bootstrap/Makefile

This isn't an issue in CI since it runs as root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3385)

Don't mutate the go installation during build.

---

bootstrap/developer_guide.md

If someone follows the guide as is it will result in a bunch of errors about missing dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3384)

Clarify the dependency build step

---

bootstrap/pkg/apis/apps/group.go
bootstrap/v2/pkg/apis/apps/group.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3745)

Change default version for v0.6.1-rc.1 release

---

bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go
bootstrap/v2/pkg/kfapp/existing_arrikto/existing_test.go

https://github.com/kubeflow/kubeflow/issues/3702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3766)

Automated cherry pick of #3760 upstream v0.6 branch

---

bootstrap/pkg/apis/apps/group.go
bootstrap/v2/pkg/apis/apps/group.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3769)

Update v0.6.1 rc2 kfctl default version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/questions.md

Signed-off-by: yeya24 <yb532204897@gmail.com>
fix #3738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3751)

add bug report issue template

---

bootstrap/pkg/apis/apps/group.go
bootstrap/v2/pkg/apis/apps/group.go

The tags are same v0.6.1-rc2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3782)

Update default v0.6.1 versions

---

bootstrap/config/kfctl_aws.yaml
bootstrap/config/kfctl_aws_cognito.yaml
bootstrap/config/kfctl_gcp_basic_auth.yaml
bootstrap/config/kfctl_gcp_iap.yaml

Partially fixes kubeflow/kubeflow#3796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3800)

Add application overlay for tf-training

---

bootstrap/config/kfctl_gcp_basic_auth.yaml
bootstrap/config/kfctl_gcp_iap.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3825)

Fix overlay name

---

bootstrap/config/kfctl_k8s_istio.yaml

Coverts kfctl v1 spec in kfctl_k8s_istio.yaml to kfctl v2.
Removes unused overlay params for mysql and minio kustomizations.
cc: @lluunn @kunmingg @johnugeorge  @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3792)

Updates kfctl_k8s_istio.yaml with kfctl v2 spec

---

components/centraldashboard/public/components/manage-users-view.css
components/centraldashboard/public/components/manage-users-view.js
components/centraldashboard/public/components/manage-users-view.pug

**_Add-On: #3758_** 
- Table left padding removed as per spec
- Headers boldened with Hacky CSS
- Updated Membership and info to be lowercase
- Updated membership table with new design
- Removed commented code
/cc @prodonjs @ajayalfred @kunmingg @abhi-g 
/priority p1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3843)

[Central-Dashboard v2] MUI Style and Nomenclature

---

components/gcp-click-to-deploy/Dockerfile
components/gcp-click-to-deploy/Makefile
components/gcp-click-to-deploy/package-lock.json
components/gcp-click-to-deploy/package.json
components/gcp-click-to-deploy/public/manifest.json
components/gcp-click-to-deploy/src/DeployForm.tsx
components/gcp-click-to-deploy/src/Utils.ts

closes #3560 
/area frontend
/platform gcp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3599)

GCP Click-to-Deploy UI changes for v0.6.x

---

bootstrap/Makefile
bootstrap/cmd/kfctlClient/README.md
bootstrap/cmd/kfctlClient/main.go
bootstrap/go.mod

* This is a simple utility to help debug click to deploy backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3830)

kfctlClient is a simple utility for sending requests to click to deploy

---

ROADMAP.md

* Provide info about the 0.6 and 0.7 releases
* Start to provide some clarity around 1.0
* The 1.0 items are largely just my oppinions and will likely go through
several rounds of iterations as people weigh in and we start to build
consensus.
* I think its useful to put a stake in the ground both with time and what
we expect to deliver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3824)

Update the Kubeflow ROADMAP

---

bootstrap/config/kfctl_gcp_basic_auth.yaml
bootstrap/config/kfctl_gcp_iap.yaml
bootstrap/pkg/kfapp/gcp/gcp.go
testing/kfctl/kf_is_ready_test.py

For GCP IAP + Basic auth
/cc @jlewi 
Fix #3079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3871)

use managed cert by default

---

components/centraldashboard/app/api_test.ts
components/centraldashboard/app/api_workgroup.ts
components/centraldashboard/app/server.ts
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/namespace-selector.js
components/centraldashboard/public/components/registration-page.css
components/centraldashboard/public/components/registration-page.js
components/centraldashboard/public/components/registration-page.pug
components/centraldashboard/webpack.config.js

- Registration View logic added for non-identity networks
- Custom note added for basic auth networks
- `/workgroup/create` is now a non-privileged route
- Privileged API error changed to make more sense, like `access denied`
- Namespace selector now has a no-namespaces state, when Σ(Name) = 0
- [BUG] Fixed character input regex to actually allow correct chars
- [BUG] Removed outdated animation for profile creation
/priority p0
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3899)

[CentralDashboard v2] Registration flow for basic auth

---

bootstrap/Makefile
bootstrap/cmd/kfctlClient/README.md
bootstrap/cmd/kfctlClient/main.go
bootstrap/go.mod
bootstrap/go.sum

* Roll forward the changes to kfctlClient
* Fix #3883
* The original PR ended up getting merged after the PR that changed the imports
to v3 but the code for kfctl client wasn't updated so post-submits ended
breaking
Fix the imports to be v3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3898)

Revert "Revert "kfctlClient is a simple utility for sending requests to click to deploy (#3830) (#3889)

---

components/gcp-click-to-deploy/src/DeployForm.tsx

- update request body based on user's selection
- refer to release branch head version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3906)

frontend update for v0.6

---

bootstrap/pkg/kfapp/coordinator/coordinator.go

Review comments from @jlewi :
Right now we periodically copy all the changes from kubeflow/kubeflow to kubeflow/kfctl. So your changes will get overwritten unless you commit this on kubeflow/kubeflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3941)

Fix the error link description when using kfctl install.

---

testing/kfctl/endpoint_ready_test.py

/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3928)

extend wait time for endpoint test from 15min to 25 min

---

deployment/existing/OWNERS

This PR adds myself as an approver, for the deployment/existing folder, which currently contains manifests for the existing_arrikto platform.
/assign @jlewi
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3946)

deployment/existing: add yanniszark as approver

---

bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml

Related to: #3868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3919)

Create a kfctl_gcp_iap file to use as an RC for 0.6.2

---

bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml

Using v0.6.2-rc.1 for both kubeflow and manifests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3969)

Update repo commit.

---

components/centraldashboard/Dockerfile
components/centraldashboard/app/api_test.ts
components/centraldashboard/app/api_workgroup.ts
components/centraldashboard/app/attach_user_middleware.ts
components/centraldashboard/app/attach_user_middleware_test.ts
components/centraldashboard/app/server.ts
components/centraldashboard/public/components/main-page.css
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/namespace-selector.js
components/centraldashboard/public/components/registration-page.css
components/centraldashboard/public/components/registration-page.js
components/centraldashboard/public/components/registration-page.pug
components/centraldashboard/public/components/utilities-mixin.js
components/centraldashboard/webpack.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3990)

 Cherry pick of #3899 #3933 #3971 #3980 on v0.6-branch.

---

components/centraldashboard/app/k8s_service.ts
components/centraldashboard/app/k8s_service_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3993)

Automated cherry pick of #3992  on v0.6-branch.

---

bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
bootstrap/config/kfctl_k8s_istio.0.6.2.yaml

comment out fields that need to be replaced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4031)

update config on v0.6 branch

---

components/gcp-click-to-deploy/package-lock.json
components/gcp-click-to-deploy/src/DeployForm.tsx

/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3947)

Remove C2D Defer IAP option for v0.6.x

---

bootstrap/cmd/bootstrap/app/kfctlClient.go
bootstrap/cmd/bootstrap/app/kfctlServer.go
bootstrap/cmd/bootstrap/app/ksServer.go
bootstrap/cmd/bootstrap/app/router.go
bootstrap/cmd/bootstrap/app/server.go
bootstrap/pkg/kfapp/kustomize/kustomize.go
components/gcp-click-to-deploy/src/DeployForm.tsx

Set up alert signals for new backend.
New backend now will collect metrics: https://github.com/kubeflow/kubeflow/blob/master/bootstrap/cmd/bootstrap/app/ksServer.go#L260
Remove unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4014)

Update monitoring signals; Remove unused code

---

bootstrap/config/kfctl_gcp_basic_auth.yaml
bootstrap/config/kfctl_gcp_iap.yaml
bootstrap/config/kfctl_k8s_istio.yaml
testing/kfctl/kf_is_ready_test.py

KFServing and Knative(dependency) is added to config files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3953)

Adding kfserving to Kfctl config

---

bootstrap/cmd/bootstrap/app/kfctlClient.go
bootstrap/cmd/bootstrap/app/kfctlServer.go
bootstrap/go.mod
bootstrap/go.sum

fix https://github.com/kubeflow/kubeflow/issues/4051
unblock PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4053)

Fix presubmit build; typo fix

---

bootstrap/go.mod
bootstrap/go.sum
bootstrap/pkg/kfapp/kustomize/kustomize.go
bootstrap/pkg/utils/k8utils.go

initial checkin
fixes #3810 
kfctl now invokes the same method kubectl does which addresses the above problems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3957)

Apply refactor

---

components/gcp-click-to-deploy/src/DeployForm.tsx

- update auto redirect target image
- check deploy name input format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4082)

update auto redirect; add name regex check

---

components/gcp-click-to-deploy/src/DeployForm.tsx

Config need to be consistent with https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#deploy-kubeflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4083)

Make config version consistent with kubeflow.org doc

---

components/gcp-click-to-deploy/src/DeployForm.tsx

For v0.5 request we need to get email from signed in identity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4089)

set email explicitly for v0.5

---

bootstrap/pkg/kfapp/kustomize/kustomize.go

fixes #3489, #3767
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4052)

provide a way to generate a name that doesn't require kubectl create

---

bootstrap/pkg/kfapp/coordinator/coordinator.go

Relates to #4056
Add a simple loop to run Apply in coordinator that keeps retry until the op succeeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4106)

Apply with strawman reconcile

---

bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml

pick up https://github.com/kubeflow/manifests/issues/345
on v0.6 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4122)

pick up manifest config fix on v0.6 branch

---

components/gcp-click-to-deploy/src/DeployForm.tsx

Will update docs as well
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4128)

pick up v0.6 head config

---

components/gcp-click-to-deploy/src/DeployForm.tsx

Delete unused logic; point to latest v0.6 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4134)

use latest config version; remove unused logic

---

components/centraldashboard/public/ajax_test_helper.js
components/centraldashboard/public/components/manage-users-view.pug
components/centraldashboard/public/components/manage-users-view_test.js
components/centraldashboard/public/components/registration-page_test.js
components/centraldashboard/public/components/utilities-mixin.js
components/centraldashboard/public/components/utilities-mixin_test.js

- Added all tests for Manage Users View:
- Error State
- Cluster Admin
- No data
- Normal View
- Add Contrib
- Remove Contrib
/priority p1
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4120)

[CentralDashboard v2] MUI Front-end tests

---

testing/test_jsonnet.py

* See #4159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4161)

Disable test_jsonnet.py because it is failing blocking presubmits.

---

components/gcp-click-to-deploy/src/DeployForm.tsx

- Estimate IAP deployment time to 30m
- Check for IAP at 30s intervals and countdown estimated time from 30m.
- Check for IAP status indefinitely (instead of 25m).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4176)

Update C2D UI to improve operation status reporting.

---

components/gcp-click-to-deploy/src/DeployForm.tsx

- Loosen logic to check for "falsy" values rather than explicit nulls/undefineds.
- Move "sleeps" outside of try block to ensure they are used in each loop iteration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4177)

C2D: Fix bugs in _enableGcpServices.

---

components/gcp-click-to-deploy/src/DeployForm.tsx

Include remaining time estimate for basic auth as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4178)

add time estimate for basic auth as well

---

components/gcp-click-to-deploy/src/DeployForm.tsx

unify auto redirect logic for all endpoint choices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4179)

unify auto redirect logic

---

components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml

/cc @jlewi @kimwnasptd 
fix #4163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4193)

jupyter webapp uses notebook v1beta1

---

components/tensorflow-notebook-image/Dockerfile

Add installation of AWS CLI in the Jupyter Dockerfile (#3725)
/cc @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4207)

Add AWS CLI

---

components/gcp-click-to-deploy/public/index.html
components/gcp-click-to-deploy/src/DeployForm.tsx

- Add a message containing the link to the deployment which shows
every 2 minutes after 20 minutes of polling.
/area frontend
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4219)

C2D: Improve the log container to be able to show links.

---

ROADMAP.md

update roadmap for pipeline 0.7 and 1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4234)

update roadmap for pipeline

---

bootstrap/cmd/kfctl/README.md
bootstrap/cmd/kfctl/cmd/set-image-name.go
bootstrap/cmd/kfctl/cmd/set-image-name_test.go

Related to #3210 
added set-image-name command
added unit tests
added documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4222)

Support custom image names for kubeflow components

---

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
kubeflow/pytorch-job/pytorch-operator.libsonnet
kubeflow/tf-training/tf-job-operator.libsonnet
py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
testing/tf_job_simple_test.py
testing/workflows/components/workflows.libsonnet

Remove v1beta2 support from job operators
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4245)

Remove support for v1beta2 in job operators

---

bootstrap/OWNERS
bootstrap/cmd/kfctl/cmd/apply.go
prow_config.yaml
py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
testing/kfctl/conftest.py
testing/kfctl/kfctl_go_test.py

Resolves: https://github.com/kubeflow/kfctl/issues/25
Resolves: https://github.com/kubeflow/kubeflow/issues/4242
Current workflow for build -> apply errors out 
```
Error: (kubeflow.error): Code 400 with message: current directory not empty, please switch directories
```
This PR is a fix for that
Adding an E2E test for this
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4232)

fix for build, apply semantics

---

components/gcp-click-to-deploy/Dockerfile
components/gcp-click-to-deploy/build_serve.sh

Run `npm run build` at pod start time in order to pick up env var attached to pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4265)

update c2d UI docker file

---

bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/gcp/gcp_test.go

fixes https://github.com/kubeflow/kubeflow/issues/3923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4263)

[kfctl] set default project and zone for GCP

---

components/access-management/Makefile
components/access-management/cloudbuild.yaml
components/profile-controller/Makefile
components/profile-controller/cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4272)

add cloud build entry for profile & kfam

---

components/centraldashboard/README.md

Minor fix to update the markdown code snippet for js, to actually use the js interpreter.
/priority p2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4268)

JS Syntax highlighting added to readme

---

components/centraldashboard/Makefile
components/centraldashboard/cloudbuild.yaml

Related to kubeflow/manifests#463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4264)

Create a GCB configuration to build the centraldashboard image.

---

bootstrap/cmd/kfctl/cmd/set-image-name.go
bootstrap/cmd/kfctl/cmd/set-image-name_test.go

Related to: https://github.com/kubeflow/kubeflow/issues/3210
/cc @xaniasd @jlewi @hemantha-kumara 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4243)

kfctl: set-image-name emits changed images in stdout

---

bootstrap/pkg/utils/k8utils.go
components/profile-controller/controllers/profile_controller.go

Resolves: #4231
/cc @johnugeorge @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4262)

Katib namespace metric collector label added to kfctl and profile-controller

---

components/notebook-controller/controllers/notebook_controller.go
components/notebook-controller/pkg/culler/culler.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Just cleanup some codes and names in notebook controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4098)

cleanup some codes in notebook controller

---

bootstrap/pkg/kfapp/kustomize/kustomize.go
bootstrap/pkg/kfapp/kustomize/kustomize_test.go

changes to cleanup kustomize.go from #4250 
/cc @gabrielwen @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4296)

cleanup kustomize

---

components/access-management/pkg/apis/kubeflow/v1beta1/register.go
components/profile-controller/api/v1beta1/groupversion_info.go
components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
components/profile-controller/config/crd/kustomization.yaml
components/profile-controller/config/crd/patches/cainjection_in_profiles.yaml
components/profile-controller/config/crd/patches/webhook_in_profiles.yaml
components/profile-controller/config/samples/profile_v1beta1_profile.yaml
components/profile-controller/controllers/profile_controller.go

related: https://github.com/kubeflow/manifests/pull/493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4299)

profile v1beta1: update group name to kubeflow.org

---

bootstrap/Makefile
bootstrap/cmd/kfdefConverter/README.md
bootstrap/cmd/kfdefConverter/cmd/root.go
bootstrap/cmd/kfdefConverter/cmd/tov1beta1.go
bootstrap/cmd/kfdefConverter/main.go

A simple CLI to convert `KfDef` from v1alpha1 to v1beta1.
Relates to #3703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4298)

Kfdef converter

---

testing/test_deploy.py

Sync up with https://github.com/kubeflow/katib/pull/876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4289)

Remove katib-manager-rest test

---

bootstrap/pkg/kfapp/existing_arrikto/existing.go

Resolves https://github.com/kubeflow/kubeflow/issues/4293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4304)

kfctl: existing_arrikto: change embedded struct to pointer

---

bootstrap/pkg/kfupgrade/kfupgrade.go

Fixes https://github.com/kubeflow/kubeflow/issues/4302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4303)

Overwrite spec.version when new KfApp config is generated for upgrade

---

components/centraldashboard/package-lock.json
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/registration-page.js
components/centraldashboard/public/components/registration-page.pug
components/centraldashboard/public/components/registration-page_test.js

Tackles P0 issue, where registration flow allows you to type or autofill incorrect values. Solution: client-side validator added :)
/priority p0
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4283)

[CentralDashboard v2] Registration dns validation fix

---

bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/v1beta1.go

forgot to copy kind to KfDef in v1beta1.
Related to #3703 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4320)

Fix KfConfig conversion bugs

---

bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/gcp/gcp_test.go

Otherwise KfDef in v1beta1 will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4328)

set gcp defaults to plugin as well

---

py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py

need to write project/email/zone in different place in v1beta1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4332)

support v1beta1 kfdef in test

---

components/centraldashboard/public/components/iframe-container.js
components/centraldashboard/public/components/iframe-container_test.js
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page_test.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4326)

[CentralDashboard v2] Fix iframe container regressions for history.

---

components/notebook-controller/controllers/notebook_controller.go
components/notebook-controller/pkg/culler/culler.go
components/notebook-controller/pkg/culler/culler_test.go
components/notebook-controller/pkg/metrics/metrics.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Add two culling metrics for notebook controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4336)

add culling metrics for notebook controller

---

bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/v1beta1.go
bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/kustomize/kustomize.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4333)

remove check on useIstio - it is always true

---

bootstrap/pkg/kfapp/kustomize/kustomize.go
bootstrap/pkg/utils/k8utils.go

Resolves https://github.com/kubeflow/kubeflow/issues/4327
/cc @krishnadurai @jlewi @gabrielwen 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4344)

kfctl: retry on apply fail

---

bootstrap/cmd/kfctl/cmd/apply.go
bootstrap/cmd/kfctl/cmd/build.go
bootstrap/cmd/kfctl/cmd/generate.go
bootstrap/cmd/kfctl/cmd/init.go
bootstrap/go.mod
bootstrap/go.sum

/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4351)

change kfctl cmd and help msgs

---

components/tensorflow-notebook-image/Dockerfile
components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
components/tensorflow-notebook-image/versions/1.15.0/version-config.json
components/tensorflow-notebook-image/versions/1.15.0gpu/version-config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4352)

Add support for Tensorflow 1.15 jupyter notebooks

---

bootstrap/pkg/kfapp/existing_arrikto/existing.go

Fixes https://github.com/kubeflow/kubeflow/issues/4239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4305)

kfctl: existing_arrikto: set repopath when it's available

---

testing/kfctl/conftest.py
testing/kfctl/kf_is_ready_test.py

And tests to check workload identity policy setup and GCP credentials insertion.
related: https://github.com/kubeflow/testing/pull/497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4350)

kf_is_ready_test: add test for workload identity and GCP credentials

---

bootstrap/pkg/kfapp/aws/aws.go

Fix #4355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4356)

Fix aws plugin not found issue

---

bootstrap/pkg/kfapp/kustomize/kustomize.go

Resolves #4247 
Handled multiple PatchesJson6902 targets with same path file in kustomize
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4260)

Addresses issue while merging multiple PatchesJson6902 targets with same path file in MergeKustomization

---

bootstrap/pkg/kfapp/kustomize/kustomize.go
bootstrap/pkg/utils/k8utils.go

Related https://github.com/kubeflow/kubeflow/issues/4327
Changes the default behavior from exit to panic.
Then recovers the panic inside the Apply function and returns an error.
Copying from the issue:
> It seems that kubectl uses os.Exit() when encountering an error, instead of returning one.
I guess that's to be expected, since it's a CLI tool.
> From comments in the code, I've seen that this behaviour can also be changed to a panic.
This could work for us. For example, the apply.Apply() function could recover the panic and return an error instead.
Will look into it soon.
/cc @krishnadurai @jlewi @kkasravi 
--- …

kfctl: fix apply retry

---

prow_config.yaml

* Related to kubeflow/testing#498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4367)

KFDef specs for gcp on v0.7-branch have a 0.7.0 suffix added.

---

bootstrap/pkg/kfapp/aws/aws.go

Resolve #4382 and part of https://github.com/kubeflow/kubeflow/issues/3767 
Make sure user delete won't have left over and cluster can be teared down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4383)

[aws] Clean up alb and istio dependencies in kfctl delete

---

bootstrap/pkg/kfapp/aws/aws.go

See issue.  https://github.com/kubeflow/kubeflow/issues/4368
Keep same flow as GCP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4390)

Fix apply overrides custom changes after Build for aws config

---

bootstrap/pkg/kfapp/aws/aws.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4392)

Cherry pick of #4390: Fix apply overrides custom changes after Build for aws config

---

bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1alpha1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/v1alpha1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/v1alpha1.go
bootstrap/pkg/apis/apps/configconverters/v1beta1.go

for https://github.com/kubeflow/kfctl/issues/62
/cc @jlewi @gabrielwen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4391)

converter preserves labels and annotations

---

components/notebook-controller/controllers/notebook_controller.go

patch from https://github.com/kubeflow/kubeflow/pull/4168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4402)

fix notebook route

---

bootstrap/pkg/kfapp/gcp/gcp.go

Verified that 2nd apply succeeded with the fix.
fix https://github.com/kubeflow/kubeflow/issues/4397
/cc @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4398)

check pod default before post request

---

bootstrap/Makefile

Resolves: https://github.com/kubeflow/kubeflow/issues/4376
/cc @Jeffwan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4406)

rename darwin binary as kfctl

---

py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py

fix https://github.com/kubeflow/testing/issues/507
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4426)

fix basic auth postsubmit

---

bootstrap/cmd/kfctl/cmd/apply.go
bootstrap/cmd/kfctl/cmd/build.go
bootstrap/pkg/apis/apps/configconverters/converters.go
bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1alpha1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/v1alpha1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/v1alpha1.go
bootstrap/pkg/apis/apps/configconverters/v1alpha1_test.go
bootstrap/pkg/apis/apps/configconverters/v1beta1.go
bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
bootstrap/pkg/apis/apps/kfconfig/types.go
bootstrap/pkg/kfapp/coordinator/coordinator.go
bootstrap/pkg/kfapp/gcp/gcp.go
bootstrap/pkg/kfapp/kustomize/kustomize.go

Include fix for [re-apply](https://github.com/kubeflow/kubeflow/issues/4397) and allow deleting application from config.
cherry pick:
#4391
#4385
#4380 
#4398
Related to: #4397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4435)

Cherry pick minor fixes on master

---

prow_config.yaml

related to #4430 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4431)

remove c2d test

---

bootstrap/cmd/kfctl/cmd/apply.go

Related to https://github.com/kubeflow/kubeflow/issues/4414
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4445)

Automated cherry pick of #4443: Add a message after kfctl apply succeeds

---

bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
bootstrap/pkg/apis/apps/configconverters/v1beta1.go
bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
bootstrap/pkg/apis/apps/kfconfig/types.go
bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
bootstrap/pkg/kfapp/gcp/gcp.go

Fixes #4439
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4448)

Automated cherry pick of #4444: Store secrets using EnvSource for basic auth

---

prow_config.yaml
py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
testing/gcp_util.py
testing/kfctl/endpoint_ready_test.py

Related to #4442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4447)

Endpoint basic auth test

---

py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py

Related: kubeflow/kfctl#71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4456)

pass app_path as args

---

py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4405)

Kfctl e2e workflow should check out main repo by default

---

testing/kfctl/endpoint_ready_test.py

Used the wrong names...
Related: #4442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4470)

fix json field names

---

components/tensorflow-notebook-image/versions/1.14.0gpu/version-config.json

Related to #4471 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4478)

Fix a minor bug in the jupyter GPU image name

---

testing/gcp_util.py

Related: #4442 
Sorry the var names are wrong...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4479)

Fix var name error

---

bootstrap/Dockerfile
bootstrap/Makefile
bootstrap/cmd/bootstrap/app/kfctlServer.go

update dockerfile & makefile; fix some corner cases
* remove entry for kfctl
* delete unused registry local cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4522)

update dockerfile & makefile

---

components/profile-controller/controllers/profile_controller.go
components/profile-controller/controllers/profile_controller_test.go

1. This PR is used to sync up with https://github.com/kubeflow/kfserving/pull/571
2. Fixes: #4532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4533)

Add kubeflow labels into namespace by profile-controller

---

components/profile-controller/Dockerfile

to be consistent with https://github.com/GoogleContainerTools/distroless/blob/master/examples/go/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4628)

change profile image base to gcr.io/distroless/base

---

components/notebook-controller/Dockerfile

- Copy third_party licenses into docker image.
- Use distroless:debug to include Shell in the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4641)

Update notebook Controller Dockerfile

---

components/notebook-controller/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4643)

Add source code for MPL licensed library

---

OWNERS
components/profile-controller/OWNERS

/cc @jlewi 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4655)

remove lluunn from owners

---

components/profile-controller/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4657)

add hashicorp/golang-lru source code to profile controller image

---

components/jupyter-web-app/backend/third_party/license.txt
components/jupyter-web-app/backend/third_party/license_info.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4675)

Add license for cffi in Jupyter Web App

---

components/access-management/go.mod
components/access-management/go.sum
components/access-management/kfam/api_default.go
components/access-management/kfam/monitoring.go
components/access-management/kfam/routers.go

requestCounter: 
normal request count with tags: `COMPONENT, KIND, REQUSER, ACTION, PATH`
requestErrorCounter:
failed request count with tags: `COMPONENT, KIND, REQUSER, ACTION, PATH, SEVERITY`
serviceHeartbeat:
counter that increase value by 1 every 10 seconds, indicating the kfam backend is alive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4674)

kfam: prometheus monitoring integration

---

components/profile-controller/controllers/moniotring.go

Remove unused tags from metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4682)

profile controller: remove unused tag

---

docs_dev/releasing.md

* Related to kubeflow/testing#450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4688)

Add release instructions for using the new CD infrastructure.

---

components/centraldashboard/public/components/iframe-container.js
components/centraldashboard/public/components/iframe-container_test.js

Fixes https://github.com/kubeflow/kubeflow/issues/4598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4684)

[centraldashboard] Sync iframe href on hashchange too

---

docs_dev/releasing.md

This PR updates the release procedures to cater for the website updates in PR kubeflow/website#1535
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4665)

Updated website versioning procedure for new banner on archived doc branches

---

components/private-utils/Dockerfile

used by https://github.com/kubeflow/kfctl/pull/226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4756)

dockerfile for image replicate

---

components/admission-webhook/Dockerfile

This is part of an effort to reduce critical vulnerabilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4775)

Distroless latest for admission-webhook Dockerfile

---

components/admission-webhook/Makefile

Address issue #4809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4810)

Fix admission webhook build issue

---

components/static-config-server/Dockerfile
components/static-config-server/Makefile
components/static-config-server/README.md
components/static-config-server/go.mod
components/static-config-server/go.sum
components/static-config-server/main.go

Tiny server that serve static config contents within k8s cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4853)

static-config-server

---

components/centraldashboard/app/api_workgroup.ts
components/centraldashboard/app/attach_user_middleware.ts
components/centraldashboard/test/e2e.test.ts

- Fixed critical bug in identity headers isolation that broke profile-kfam
- Fixed waiting to properly wait for the page to load
- Fixed load checks
- Cleaning logic corrected
/area metadata
/priority p1
/cc @prodonjs @jlewi @kimwnasptd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4869)

[CentralDashboard] E2E Test fixes

---

docs_dev/releasing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4698)

update releasing guide.

---

components/admission-webhook/Dockerfile

/assign @jtfogarty @yanniszark @jlewi

Retains DWARF tables for golang build

---

components/gcp-click-to-deploy/src/DeployForm.tsx

add deprecation warning on kubeflow c2d

add deprecation warning on kubeflow c2d

---

ROADMAP.md

updating the Kubeflow roadmap, per issue  #4903

updated Kubeflow roadmap 

---

components/notebook-controller/controllers/notebook_controller.go

"k8s.io/api/core/v1" was imported with names "corev1" and "v1" in components/notebook-controller/controllers/notebook_controller.go

Remove duplicate import

---

components/tensorboard-controller/controllers/tensorboard_controller.go

Closes #5065
The PR also contains a minor fix related to double import of a package.

tensorboard-controller: Mount GCP secret only when accessing Google storage

---

OWNERS
docs_dev/releasing.md

related to kubeflow/website#1984

Update docs for releasing the website and prune root OWNERs file

---

components/tensorflow-notebook-image/Dockerfile

Update kubeflow-fairing version to 1.0.0 in notebook image

Update kubeflow-fairing version in notebook image

---

metric-collector/service-readiness/kubeflow-readiness.py

I improved the quality of code by removing the duplication of code.

Refactoring: Deduplication

---

components/tensorflow-notebook-image/Dockerfile

Due to the issue https://github.com/kubeflow/examples/issues/806
we need to upgrade kubeflow-fairing to v1.0.1, thanks.

Update kubeflow-fairing to avoid mismatching with kfserving

---

components/centraldashboard/OWNERS

Adding @SachinVarghese to centraldashboard reviewers list

Adding reviewer to centraldashboard OWNERS file

---

components/centraldashboard/OWNERS

Relevant discussion kubeflow/kubeflow#5151

Add StefanoFioravanzo to Centraldashboard OWNERS

---

components/notebook-controller/OWNERS

Add owners for the Notebooks Controller

---

components/crud-web-apps/tensorboards/backend/app/routes/get.py
components/crud-web-apps/tensorboards/backend/app/utils.py
components/crud-web-apps/tensorboards/backend/requirements.txt
components/tensorboard-controller/api/v1alpha1/tensorboard_types.go
components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
components/tensorboard-controller/controllers/tensorboard_controller.go

closes #5166 
This is part of my [GSoC-2020 project](https://summerofcode.withgoogle.com/projects/#4660815581413376). 
It also contains a small code that adds a PVC GET route of the Tensorboard web-app backend. 
/cc @kimwnasptd @elikatsis

Tensorboard web-app: Add functionality to inform TWA frontend about the status of Tensorboard servers

---

components/tensorboard-controller/Makefile
components/tensorboard-controller/README.md
components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
components/tensorboard-controller/config/rbac/role.yaml
components/tensorboard-controller/controllers/tensorboard_controller.go

closes #5261 
This is part of my [GSoC-2020 project](https://summerofcode.withgoogle.com/projects/#4660815581413376). 
This PR, also contains some minor modifications to the Tensorboard controller `generateVirtualService()` function, as well as a README.md file.
/cc @kimwnasptd @elikatsis

Add roles for Tensorboard controller pod

---

components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml
components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml
components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
components/jupyter-web-app/frontend/src/app/app.module.ts
components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.html
components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.spec.ts
components/jupyter-web-app/frontend/src/app/resource-form/form-affinity/form-affinity.component.ts
components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.html
components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.spec.ts
components/jupyter-web-app/frontend/src/app/resource-form/form-tolerations/form-tolerations.component.ts
components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.html
components/jupyter-web-app/frontend/src/app/utils/common.ts
components/jupyter-web-app/frontend/src/app/utils/types.ts

This PR adds support for toleration and affinity configs in the Notebook Spawner UI.
Resolves: #4433
Options presented to the user are specified inside `spawner_ui_config.yaml`. This example config allows users to ask for exclusive access to a node within node-pool called `notebook-n1-standard-2`:
```yaml
spawnerFormDefaults:
...
affinityConfig:
value: "none"
options:
- configKey: "none"
displayName: "None"
affinity: {}
- configKey: "exclusive__n1-standard-2"
displayName: "Exclusive: n1-standard-2"
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: "node_pool"
operator: "In"
values:
- "notebook-n1-standard-2"
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: …
```

Add support for Tolerations and Affinity in Notebooks

---

components/notebook-controller/OWNERS

Add MartinForReal as reviewer
related: https://github.com/kubeflow/internal-acls/pull/319

Add MartinForReal as reviewer

---

components/crud-web-apps/OWNERS
components/jupyter-web-app/OWNERS
components/notebook-controller/OWNERS

Since I am one of the leads of the Notebook Working Group, it would be helpfully if I could approve PRs.
As an example, PR #5332 is blocked by me not being able to review it right now.

Add thesuperzapper to notebook OWNERS

---

components/notebook-controller/README.md

This is not a comprehensive update to `readme`. These are some of the stuff that would I ran into as issues when trying to contribute.

Included the instructions to contribute notebook-controller.

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/README.md

Update the readme with detailed commands on how to consume the library as well as developer guidelines.
/cc @StefanoFioravanzo 
/cc @thesuperzapper 

web-apps(front): Update the README

---

components/crud-web-apps/jupyter/frontend/package.json

The updated common frontend library #5463  requires some additional npm packages to be installed.
/cc @StefanoFioravanzo 
/cc @thesuperzapper 

jwa(front): Add needed modues to package.json

---

README.md

Just starting this update as a placeholder so we can centralize contributions

Update kubeflow/kubeflow readme

---

components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/config.py
components/crud-web-apps/tensorboards/.gitignore
components/crud-web-apps/tensorboards/README.md
components/crud-web-apps/tensorboards/backend/app/__init__.py
components/crud-web-apps/tensorboards/backend/entrypoint.py
components/crud-web-apps/tensorboards/frontend/.gitignore
components/crud-web-apps/tensorboards/frontend/package.json
components/crud-web-apps/tensorboards/frontend/src/app/app.component.html
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.html
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
components/crud-web-apps/tensorboards/frontend/src/index.html

closes #5497 
This PR:
1. Updates the README with instructions on how to build and run TWA with the latest common code
2. Modifies the frontend code to work with the latest updates in the common code
/cc @kandrio 

twa: Update the build process and instructions for the Tensorboards web app

---

components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/custom_resource.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/poddefault.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/utils.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/decorators.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/handlers.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py

partially fixes #5494 
Removes the use of `f"strings"` from the common backend code.
/cc @thesuperzapper 

web-apps(back): Change the string formatting

---

components/tensorflow-notebook-image/Dockerfile

Closes: https://github.com/kubeflow/kubeflow/issues/4838.

Change default view to lab

---

components/crud-web-apps/common/backend/.gitignore

closes #5568 
We should define `__init__.py` files to denote our packages.

web-apps(back): Export package code for wheel

---

.github/ISSUE_TEMPLATE/config.yml

chore: fix issue config typo

---

components/notebook-controller/controllers/notebook_controller.go

This PR contains the notebook controller code originally found in https://github.com/kubeflow/kubeflow/pull/5601 and https://github.com/kubeflow/kubeflow/pull/5618. It allows users to configure the Istio VirtualService spec that the notebook controller creates by adding annotations to the notebook resource metadata. Specifically, two option for the VirtualService spec can be customized: the HTTP rewrite rule and request headers the Istio proxy adds to requests.
Currently, the notebook-controller configures the Istio rewrite rule according to the following example snippet:
```
http:
- match:
- uri:
prefix: /notebook/<namespace>/<notebook-name>/
rewrite:
uri: /notebook/<namespace>/<notebook-name>/
```
This is fine for applications such as Jupyter that allow you to specify (with an …

(Notebook-controller): Add `http-rewrite-uri` and `http-headers-request-set` annotations

---

prow_config.yaml
py/kubeflow/kubeflow/cd/Makefile
py/kubeflow/kubeflow/cd/config.py
py/kubeflow/kubeflow/cd/vwa.py
py/kubeflow/kubeflow/cd/vwa_runner.py
py/kubeflow/kubeflow/ci/Makefile
py/kubeflow/kubeflow/ci/vwa_tests.py
py/kubeflow/kubeflow/ci/vwa_tests_runner.py

This PR adds the CI/CD for the Volumes Web App from https://github.com/kubeflow/kubeflow/pull/5684. 

Add CI/CD for Volumes Web App

---

components/access-management/kfam/api_default.go
components/access-management/kfam/bindings.go

Closes: https://github.com/kubeflow/kubeflow/issues/5190
Recreated from https://github.com/kubeflow/kubeflow/pull/5202 due to inactivity of the contributor. 

Use informer / indexer to cache rolebindings

---

components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
components/crud-web-apps/tensorboards/Dockerfile
components/crud-web-apps/tensorboards/Makefile
components/crud-web-apps/tensorboards/backend/app/routes/get.py
components/crud-web-apps/tensorboards/backend/app/utils.py
components/crud-web-apps/tensorboards/backend/entrypoint.py
components/crud-web-apps/tensorboards/frontend/package.json
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts

These are some small fixes required for the Tensorboards web app to be able to work under a prefix and inside a container, like jupyter-web-app.
/cc @StefanoFioravanzo 
The last remaining part then will be to create the manifests for this app cc @yanniszark

Fixes in Tensorboard web app

---

components/notebook-controller/.gitignore
components/notebook-controller/config/manager/params.env
components/notebook-controller/config/manager/service-account.yaml
components/notebook-controller/config/manager/service.yaml

PR https://github.com/kubeflow/kubeflow/pull/5723 missed some files, because of a gitignore rule. Adding them in this PR.

fix notebook controller manifests

---

components/centraldashboard/manifests/base/configmap.yaml
components/centraldashboard/manifests/base/deployment.yaml
components/centraldashboard/manifests/base/kustomization.yaml

/cc @StefanoFioravanzo @kimwnasptd 
For some reason, I missed this in the first PR.

centraldashboard: Add missing links ConfigMap

---

components/tensorboard-controller/.gitignore
components/tensorboard-controller/config/base/kustomization.yaml
components/tensorboard-controller/config/base/patches/add_controller_config.yaml
components/tensorboard-controller/config/base/patches/add_service_account.yaml
components/tensorboard-controller/config/base/service_account.yaml
components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
components/tensorboard-controller/config/manager/manager.yaml
components/tensorboard-controller/config/overlays/kubeflow/kustomization.yaml
components/tensorboard-controller/config/overlays/kubeflow/patches/remove-namespace.yaml
components/tensorboard-controller/config/overlays/standalone/kustomization.yaml

Manifests for the Tensorboard Controller

Manifests for Tensorboard controller

---

components/example-notebook-servers/jupyter/Dockerfile
components/example-notebook-servers/jupyter/requirements.txt

Update notebook to the latest version that was just released and fix small formatting for consistency. 

Update notebook dependency + cleanup

---

components/centraldashboard/manifests/base/configmap.yaml

This PR enables the feature implemented in https://github.com/kubeflow/kubeflow/pull/5469

centraldashboard: Add ConfigMap flag to force iframe redirection

---

components/profile-controller/controllers/profile_controller.go
components/profile-controller/controllers/profile_controller_test.go

/assign @yanniszark @zijianjoy 
To implement https://github.com/kubeflow/kubeflow/issues/5712#issuecomment-804087910

feat(profile-controller): add pipelines.kubeflow.org/enabled label to namespaces

---

components/example-notebook-servers/codeserver/Dockerfile
components/example-notebook-servers/jupyter/Dockerfile
components/example-notebook-servers/rstudio/Dockerfile

Small update for the base images of each server type.

Update notebook server base images

---

components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt

This PR updates the tags of the base images and the python packges in the dockerfiles for the pytroch and tensorflow full images.

Update image tags and python packages in pytorch and tensorflow full dockerfiles

---

components/tensorboard-controller/controllers/tensorboard_controller.go

Cherry pick of #5819 on v1.3-branch.
#5819: tensorboard-controller: Fix scheduling unbound PVCs

Automated cherry pick of #5819: tensorboard-controller: Fix scheduling unbound PVCs

---

components/example-notebook-servers/codeserver/Dockerfile
components/example-notebook-servers/jupyter/Dockerfile
components/example-notebook-servers/jupyter/requirements.txt
components/example-notebook-servers/rstudio/Dockerfile

Update the next notebook images with the new base image and update the installed packages.

Update jupyter, rstudio and vs code notebook images + allow rstudio in iframe

---

components/crud-web-apps/jupyter/backend/apps/common/routes/delete.py
components/crud-web-apps/jupyter/backend/apps/default/routes/post.py
components/crud-web-apps/jupyter/backend/apps/rok/routes/post.py
components/crud-web-apps/jupyter/backend/entrypoint.py

Closes: https://github.com/kubeflow/kubeflow/issues/5496
Applies the changes from https://github.com/kubeflow/kubeflow/pull/5500. 

Remove the f-strings in the Jupyter web app's backend

---

components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml

This PR syncs the `spawner_ui_config.yaml` from the Jupyter Web App backend to the manifests folder to bring it up to sync.

Sync spawner yaml from source to manifests

---

ROADMAP.md

addresses #6047 
Signed-off-by: Malini Bhandaru <mbhandaru@vmware.com>

lists roadmap in reverse chronological order

---

components/notebook-controller/controllers/notebook_controller.go

This fixes issues related to not properly filtering objects cached and reconciled when they trigger delete/generic events.   Functionality wise the controller still works as we are later on filtering these in the reconcile method but this add extra load that is not really needed, and with larger clusters this load can become a performance problem, and the logs also are polluted with not real error messages.
The fixes should be refactored when the notebook-controller starts using a newer controller-runtime module version (currently using v0.2, where upstream is at >v0.8). The new controller-runtime provides tools that would make this section smaller.  I have added TODO messages to refer to that.

Correct missing predicates in controller watches. Fixes #5326

---

ROADMAP.md
components/admission-webhook/go.mod
components/admission-webhook/go.sum
components/admission-webhook/main.go
components/crud-web-apps/jupyter/backend/apps/common/form.py
components/notebook-controller/controllers/notebook_controller.go

Cherry picks commits from:
* Fix NaN in Notebooks (#6092) 
* add section for 1.4; small updates for 1.3 section (#6082) 
* Remove virtualservice timeout to prevent websocket disconnect (#6126)
* fix(admission-webhook): attach namespace to pod request if pod does not have it (#6052)

Cherry picks for RC 1

---

components/example-notebook-servers/base/Dockerfile

unblocks https://github.com/kubeflow/kubeflow/pull/6137

Fix notebook base image gpg keys

---

components/example-notebook-servers/base/Dockerfile

Cherry pick https://github.com/kubeflow/kubeflow/pull/6138
Needed for https://github.com/kubeflow/kubeflow/pull/6137
/cc @elikatsis @DavidSpek

Cherry-pick: Notebooks base gpg fix

---

components/access-management/README.md

Fix for extremely trivial typo to README.md

nit: typo in README.md

---

ROADMAP.md

corrected typo "track" to "tracked"

correct typo - track to tracked

---

OWNERS

Refer to https://github.com/kubeflow/internal-acls/pull/524

chore: remove Bobgy from OWNERS

---

ROADMAP.md

These proposed changes include: identifying that 1.4.1 has been delivered, provides themes for 1.5 and provides details of major features in 1.5 by working group.   This is an initial proposal that needs review by the working group leads.

Kubeflow Roadmap update - with 1.5 details

---

components/notebook-controller/controllers/notebook_controller.go

Closes https://github.com/kubeflow/kubeflow/issues/6336
The PR makes the Notebook Controller to:
1. Stop the reconciliation loop once it re-emitted a Pod event, to avoid trying to fetch Notebooks from a K8s event
2. Don't trigger reconciliation on delete events

notebooks: Graceful handling of events

---

ROADMAP.md

@annajung @kimwnasptd @DomFleischmann I have created this PR as a quick way to update the Kubeflow Roadmap to include KF 1.6.   My view is that we can update this in a simple way and then add more details if needed.     Please review, improve as you see needed.   Thanks.   Josh

1st update of Kubeflow Roadmap for Kubeflow 1.6

---

.github/workflows/centraldb_docker_publish.yaml
.github/workflows/jwa_docker_publish.yaml
.github/workflows/kfam_docker_publish.yaml
.github/workflows/nb_controller_docker_publish.yaml
.github/workflows/nb_server_docker_publish.yaml
.github/workflows/poddefaults_docker_publish.yaml
.github/workflows/prof_controller_docker_publish.yaml
.github/workflows/tb_controller_docker_publish.yaml
.github/workflows/twa_docker_publish.yaml
.github/workflows/vwa_docker_publish.yaml

Add GH actions to push images to a DockerHub registry after a merge

---

.github/workflows/nb_controller_docker_publish.yaml
.github/workflows/vwa_docker_publish.yaml

Refs https://github.com/kubeflow/kubeflow/issues/6502

Fix typos in GH actions that build and push Docker images

---

components/example-notebook-servers/codeserver-python/Dockerfile

Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
Fixes #6553 
- Update install command for code server extension

Update install command for code server extension

---

.github/workflows/frontend_lint.yaml
components/crud-web-apps/common/frontend/kubeflow-common-lib/.eslintrc.json
components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/types.ts
components/crud-web-apps/jupyter/frontend/package-lock.json
components/crud-web-apps/jupyter/frontend/src/app/types/affinity.ts
components/crud-web-apps/tensorboards/frontend/package-lock.json
components/crud-web-apps/volumes/frontend/package-lock.json

Fix ng lint

---

components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html

Fix(Jupyter): Fix the ImageGroup object path

---

components/notebook-controller/controllers/notebook_controller.go

Fix notebook endless restarts (#6337)

notebooks: Fix notebook endless restarts (#6337)

---

components/crud-web-apps/jupyter/backend/apps/common/form.py

Cast nvidia.com/gpu value as string respective of K8s Resource Spec

---

.github/workflows/centraldb_docker_publish.yaml
.github/workflows/jwa_docker_publish.yaml
.github/workflows/kfam_docker_publish.yaml
.github/workflows/nb_controller_docker_publish.yaml
.github/workflows/nb_server_codeserver_python_docker_publish.yaml
.github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
.github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
.github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
.github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
.github/workflows/poddefaults_docker_publish.yaml
.github/workflows/prof_controller_docker_publish.yaml
.github/workflows/tb_controller_docker_publish.yaml
.github/workflows/twa_docker_publish.yaml
.github/workflows/vwa_docker_publish.yaml

Fix the GH actions after this comment: https://github.com/kubeflow/kubeflow/pull/6631#issuecomment-1232223808

Ensure we build images for a new Version only on push events

---

components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html

Docker is dead and superseeded by OCI on all common Platforms

Docker -> OCI Update form-image.component.html

---

components/centraldashboard/public/components/iframe-container.js
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/main-page_test.js
components/centraldashboard/public/components/namespace-selector.js
components/centraldashboard/public/library.js

This PR is required for the ["Show objects from all namespaces"](https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220621-all-namespaces.md. ) proposal and introduces the changes needed in the centraldashboard.

centraldashboard: Show objects from all namespaces

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.module.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts

Create unit tests for the sorting functionality (#6460).
Related PRs: https://github.com/kubeflow/kubeflow/pull/6742, https://github.com/kubeflow/kubeflow/pull/6743

web-apps(front): Create unit tests for sorting

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts

This PR enables sorting for VWA and TWA as part of https://github.com/kubeflow/kubeflow/issues/6460.
Related PR: https://github.com/kubeflow/kubeflow/pull/6742

 Sorting support for VWA and TWA

---

components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/namespace-selector.js

Fix eslint errors in MainPage and NamespaceSelector classes.
Signed-off-by: Tasos Alexiou <tasos@arrikto.com>

centraldashboard: Fix eslint errors

---

ROADMAP.md

Updates to the v1.7 roadmap items.  Please review and provide comments and/or looks good.   thanks.
@johnugeorge @kimwnasptd @DomFleischmann @zijianjoy

Public roadmap update for v1.7

---

.github/workflows/centraldb_kind_test.yaml
.github/workflows/jwa_backend_unittests.yaml
.github/workflows/jwa_kind_test.yaml
.github/workflows/nb_controller_kind_test.yaml
.github/workflows/poddefaults_kind_test.yaml
.github/workflows/prof_controller_kind_test.yaml
.github/workflows/tb_controller_kind_test.yaml
.github/workflows/twa_kind_test.yaml
.github/workflows/vwa_kind_test.yaml
components/notebook-controller/Makefile
components/testing/gh-actions/install_istio.sh
components/testing/gh-actions/install_kind.sh
components/testing/gh-actions/kind-1-25.yaml

Updating the KinD cluster version to K8s 1.25

Use K8s 1.25 for the tests

---

.github/workflows/centraldb_angular_docker_build.yaml
components/centraldashboard-angular/Dockerfile
components/centraldashboard-angular/Makefile
components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html

This is part of the [Rewrite the Central Dashboard in Angular](https://github.com/kubeflow/kubeflow/issues/6000) effort and creates Docker and Make files for building the new centraldashboard's container.

centraldashboard-angular: Create Docker and Make files

---

components/admission-webhook/manifests/base/deployment.yaml
components/admission-webhook/manifests/base/kustomization.yaml
components/centraldashboard/manifests/base/deployment.yaml
components/centraldashboard/manifests/base/kustomization.yaml
components/crud-web-apps/jupyter/manifests/base/deployment.yaml
components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
components/crud-web-apps/volumes/manifests/base/deployment.yaml
components/crud-web-apps/volumes/manifests/base/kustomization.yaml
components/notebook-controller/config/base/kustomization.yaml
components/notebook-controller/config/manager/manager.yaml
components/profile-controller/config/base/kustomization.yaml
components/profile-controller/config/manager/manager.yaml
components/profile-controller/config/overlays/kubeflow/kustomization.yaml
components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
components/tensorboard-controller/config/base/kustomization.yaml
components/tensorboard-controller/config/manager/manager.yaml
releasing/update-manifests-images

Cherry-picking the changes we made during:
- https://github.com/kubeflow/kubeflow/pull/6548
Refs: https://github.com/kubeflow/kubeflow/issues/6766

Cherry-pick commits for using DockerHub for all images

---

.github/workflows/jwa_frontend_tests.yaml

This PR adds formatting and linting to `jwa_frontend_tests` workflow.

jwa(front): Add formatting/linting to JWA's frontend workflow

---

.github/workflows/vwa_frontend_tests.yaml
components/crud-web-apps/volumes/frontend/src/app/app.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pods-mock.ts

This PR adds formatting and linting to `vwa_frontend_tests` workflow.

vwa(front): Add formatting/linting to VWA's frontend workflow

---

.github/workflows/twa_frontend_tests.yaml
components/crud-web-apps/tensorboards/frontend/package-lock.json
components/crud-web-apps/tensorboards/frontend/package.json
components/crud-web-apps/tensorboards/frontend/scripts/check-format-error.js
components/crud-web-apps/tensorboards/frontend/src/app/app.component.spec.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.spec.ts

In this PR:
- Install Prettier
- Format code
- Add formatting/linting to `twa_frontend_tests` workflow

twa(front): Install prettier and add gh action

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/content-list-item/content-list-item.component.spec.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/index.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/link-value.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/property-value.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/status-icon/status-icon.component.spec.ts
components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
components/crud-web-apps/jupyter/frontend/src/app/types/notebook.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
components/crud-web-apps/volumes/frontend/src/app/types/backend.ts

In this PR we make the links of our table component actual links, so that to be able to use `Open Link in New Tab` and `Ctrl+click` to open a link in a new tab.

[wa-actual-links-in-tables] Make links in our table component actual links

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.ts

This PR fixes a bug introduced in this PR https://github.com/kubeflow/kubeflow/pull/6749#issuecomment-1381764826 related to how we extract the ENV vars from PodDefaults in a notebook's details page.

jwa(front): Fix ENV vars bug in details page

---

components/profile-controller/controllers/profile_controller.go

Fix the bug of ResourceQuota removal (#6188)

---

components/centraldashboard/public/components/activities-list_test.js

centraldashboard: Fix failing test  (#6959)

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/component-value/component-value.component.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
components/crud-web-apps/volumes/backend/apps/common/utils.py
components/crud-web-apps/volumes/backend/apps/default/routes/get.py
components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
components/crud-web-apps/volumes/backend/apps/rok/utils.py
components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
components/crud-web-apps/volumes/frontend/src/app/app.module.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/columns.module.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.html
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.html
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.scss
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.spec.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
components/crud-web-apps/volumes/frontend/src/app/types/backend.ts

vwa(front): Prevent PVCs from being deleted when there is a corresponding notebook

---

components/centraldashboard/Dockerfile
components/centraldashboard/public/components/logout-button.js
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug

Fix the logout button to work with the recent version of `oidc-authservice`

---

components/crud-web-apps/tensorboards/backend/app/routes/get.py
components/crud-web-apps/tensorboards/backend/app/routes/post.py
components/crud-web-apps/tensorboards/backend/app/utils.py
components/crud-web-apps/tensorboards/deploy/app-rbac.yaml
components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.html
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.spec.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.component.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form-configurations/form-configurations.module.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.html
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.spec.ts
components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
components/crud-web-apps/tensorboards/frontend/src/app/types.ts
components/crud-web-apps/tensorboards/manifests/base/cluster-role.yaml

Support Pod Defaults in Tensorboard Web App (#6924)

---

components/centraldashboard/Makefile

centraldashboard(make): Use correct dir (#6960)

---

components/centraldashboard/app/k8s_service.ts
components/centraldashboard/app/k8s_service_test.ts
components/centraldashboard/manifests/base/deployment.yaml
components/centraldashboard/public/components/logout-button.js
components/centraldashboard/public/components/main-page.js
components/centraldashboard/public/components/main-page.pug
components/centraldashboard/public/components/namespace-selector.js

centraldashboard: Support dynamic logout URL (#6945)

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/index.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/memory-value.ts
components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts

In this PR, we format the long memory values into human-readable ones so that users can easily parse them.
Previous state:
Current state:

jwa(front): JWA shows a weird long value for memory when restoring notebook from snapshot 

---

components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
components/crud-web-apps/tensorboards/frontend/i18n/fr/messages.fr.xlf
components/crud-web-apps/tensorboards/frontend/i18n/messages.xlf
components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts

This PR fixes typos in JWA and TWA.

web-apps(front): Fix typos

---

components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/events.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py

This PR:
1.  Introduces a `list_events(namespace, field_selector)` function in `events.py` for listing events of each resource.
2.  Utilizes `list_events` function for listing notebook events in `notebook.py`.
3. Utilizes `list_events` function for listing pvc events in `pvc.py`.

web-apps(back): Fetch resources events

---

components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt

Update requirements.txt (#7050)

---

.github/workflows/profiles_kfam_intergration_test.yaml
components/access-management/Makefile
components/profile-controller/Makefile

Adding changes to build profile-controller and admission-webhook images on pull_request.

---

components/access-management/kfam/api_default.go

closes https://github.com/kubeflow/kubeflow/issues/7199

fix(api_default.go): resolve write response call order

---

components/profile-controller/README.md
components/profile-controller/config/samples/_v1beta1_profile.yaml

Fixes: https://github.com/kubeflow/kubeflow/issues/7243

Fix Profile-controller README file & sample files

---

ROADMAP.md

Add 1.8 roadmap
Fixes kubeflow/community#624
TODO:

docs: add 1.8 roadmap

---

components/crud-web-apps/volumes/manifests/base/deployment.yaml
components/crud-web-apps/volumes/manifests/base/viewer-spec.yaml
components/pvcviewer-controller/README.md

See https://github.com/kubeflow/kubeflow/pull/7230

Cherry-Pick #7230 into v1.8-branch

---

components/centraldashboard/README.md

Fix typo in centraldashboard/README.md

---

components/crud-web-apps/jupyter/backend/apps/common/status.py

This change fixes an error 500 on notebook creation
(cherry picked from commit b0886c4d13c723c47addd460e78a61ff0dfd0f5d)

fix: KeyError and line length

---

components/crud-web-apps/jupyter/backend/apps/common/utils.py

Cherry-pick #7260
* Only load spawner_ui_config.yaml once every 10 minutes.
* Update cache to 60 seconds

Cherry-pick: Only load spawner_ui_config.yaml once every 10 minutes. closes #7259

---

components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss

Cherry-picks #7341
/assign @orfeas-k

Cherry-pick: Make the background white of all webapps (#7341)

---

components/crud-web-apps/jupyter/backend/apps/common/status.py

fix: local var shadowing import

---

components/pvcviewer-controller/controllers/pvcviewer_controller.go

Cherry pick of bc28331
cc: @kimwnasptd

feat: make pvcviewer istio gateway configurable (#7351)

---

.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml

ci: fix version tagging of notebook server images (#7386)

---

components/example-notebook-servers/codeserver-python/Dockerfile
components/example-notebook-servers/codeserver-python/requirements.txt
components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
components/example-notebook-servers/jupyter-scipy/requirements.txt
components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
components/example-notebook-servers/jupyter/Dockerfile
components/example-notebook-servers/rstudio/Dockerfile

Cherry pick 1b2448c into v1.8-branch

fix: downgrade jupyterlab to 3.6.6 (#7398)

---

.github/workflows/centraldb_angular_docker_publish.yaml
.github/workflows/centraldb_docker_publish.yaml
.github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
.github/workflows/jwa_docker_publish.yaml
.github/workflows/kfam_docker_publish.yaml
.github/workflows/nb_controller_docker_publish.yaml
.github/workflows/poddefaults_docker_publish.yaml
.github/workflows/prof_controller_docker_publish.yaml
.github/workflows/pvcviewer_controller_docker_publish.yaml
.github/workflows/tb_controller_docker_publish.yaml
.github/workflows/twa_docker_publish.yaml
.github/workflows/vwa_docker_publish.yaml

Cherry pick 16ae921 into v1.8-branch
cc: @thesuperzapper @kimwnasptd

ci: prevent triggering release builds accidentally (#7401)

---

components/centraldashboard/app/api_workgroup.ts

Closes #5004 
- added Regex validation as suggested by @thesuperzapper  https://github.com/kubeflow/kubeflow/issues/5004#issuecomment-1979776882
None

fix: email validation parity for profile creation

---

ROADMAP.md

Add Kubeflow 1.10 Roadmap
