kubeflow/kubeflow

- OWNERS
* @ellis-biegelow and @texasmichelle  are being assigned a lot of reviews because we are hitting
the root OWNERs file; these reviews shouldn't be assigned to them. 
* Removing them from root OWNERs file is a partial fix; the other part is to create finer grained OWNERs files with better a set of users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3231)
> Prune root OWNERs file to better assign reviews.

- components/centraldashboard/public/components/main-page.css
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
Matches the updated [UX specification](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZYbjDGnaKqEC/files/MCEJu8Y2hyDScWR0uwkSmYmqTA1fRs4iJFc) and addresses item 6 from #3154.
Also cleans some superfluous styles from main-page component CSS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3241)
> Moves view tabs from header to content pane

- releasing/auto-update/update_job.yaml
- releasing/auto-update/update_job_cron.yaml
* We use environment variables to set git email and author name so that
CLA check will pass.
Related to #3155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3258)
> Fix PRs created by auto-updater so that CLA checks pass.

- kubeflow/pipeline/pipeline-ui.libsonnet
I copied the "crd" section to pipeline-ui.libsonnet from pipeline-viewercrd.libsonnet, in order for ml-pipeline-ui service in our pipeline deployment to list/create tensorboard crd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3255)
> Add permssion for ml-pipeline-ui account to access pod resources

- bootstrap/config/base/kfctl_default.yaml
- bootstrap/config/overlays/basic_auth/kfctl_default-patch.yaml
- bootstrap/config/overlays/basic_auth/kfctl_default.yaml
- bootstrap/config/overlays/gcp/kfctl_default-patch.yaml
- bootstrap/config/overlays/gcp/kfctl_default.yaml
- bootstrap/config/overlays/ksonnet/kfctl_default.yaml
- bootstrap/config/overlays/ksonnet/kustomization.yaml
Fixes #3273 
Relates to #3282 
Root cause of failure is because #3283 changed parameter from `useIstio` to `injectIstio` so that istio related flags can be unified and flipped by this line:
https://github.com/kubeflow/kubeflow/blob/a70c866ee7811ec907c63368a43703447348d99f/bootstrap/pkg/kfapp/coordinator/coordinator.go#L292
However, #3108 changed kubeflow app config to use kustomize but overlay didn't include this parameter.  And thus for all ISTIO deployments `iap-ingress` will always be deployed as if it's not for ISTIO.  This PR adds back this flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3283)
> Fix overlay for app.yaml

- components/jupyter-web-app/releaser/components/params.libsonnet
Fix no response when click Spawn button on creating notebook servers by specify jupyter-web-app:v0.5.0. #3168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3169)
> Fix no response when click Spawn button on creating notebook servers.

- kubeflow/aws/istio-ingress.libsonnet
- kubeflow/aws/prototypes/istio-ingress.jsonnet
- kubeflow/aws/tests/istio-ingress_test.jsonnet
I noticed that only Cognito is supported by kubeflow AWS setup, but we want to use OIDC and thus I added a few new optional parameters to the `istio-ingress` component that allows to enable OIDC and define the required parameters. I think this could also be helpful for other kubeflow users.
Additionally I enhanced the test to ensure that the default params that are defined in the prototype will be used for all available test-case parameter sets.
I wasn't sure if you need an issue in advance, so please let me know if I should create one.
Let me know if I should change something. I was able to test my changes with our kubeflow setup on AWS EKS.
--- …
> Add AWS ALB OIDC support

- kubeflow/pipeline/pipeline-apiserver.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3293)
> Cherry-pick pipeline-runner ClusterRole changes (#2556) to pipelines branch

- scripts/download.sh
We had the need to use the download script for my fork as long as this one is different than the official kubeflow repository.
Therefore I did a small change in the `download.sh` script that allows defining the repository in a `KUBEFLOW_GH_REPO` env-variable.
I think this could also be helpful for other forks in the future and doesn't have any drawbacks for the official repository as this one will by default still be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3291)
> Allow defining kubeflow repo in download script

- kubeflow/gcp/google-cloud-filestore-pv.libsonnet
- kubeflow/gcp/tests/google-cloud-filestore-pv_test.jsonnet
- testing/kfctl/kf_is_ready_test.py
Related to: #2475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3268)
> Need to set storageClassName of the persistent volume used with cloud filestore

- scripts/aws/util.sh
As discussed in #3259 I changed the namespace label in the AWS setup for the kubeflow namespace, so that istio injection is by-default disabled.
Fixes #3259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3289)
> #3259 AWS: Disable istio-injection by default in kubeflow ns

- components/access-management/README.md
- components/access-management/api/swagger.yaml
- components/profile-spawner/api/swagger.yaml
Define kubeflow access management API which serves following need:
* fulfill user-facing CUJs
* self-register
* access sharing
* user / namespace listing
* provide endpoint for central dashboard and other components to fulfill ```list``` verb
* query users that can access an namespace
* query namespaces that accessible from a user
API doc:
https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/kubeflow/kubeflow/89be54122464e5b033e7b1d192dc8f0e057f1a42/components/access-management/api/swagger.yaml
Note:
* this API will only accept request from Istio and require user identity in coming request
Once we locked down the APIs we can implement frontend & backend components.
--- …
> define kubeflow Access Management API

- kubeflow/aws/istio-ingress.libsonnet
See comment by @Jeffwan on https://github.com/kubeflow/kubeflow/pull/3272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3302)
> Use empty list when OIDC not being used

- deployment/aws/infra_configs/cluster_config.yaml
Address https://github.com/kubeflow/kubeflow/issues/3223 https://github.com/kubeflow/website/issues/714
1. Talk with maintainer in eksctl community, it will has older version backward compatibility in the future releases.  https://github.com/weaveworks/eksctl/issues/797
2. May get ride of fixed version later. Since we use basic and stable apis of eksctl, we may generate config in runtime based on user's eksctl version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3280)
> Upgrade eksctl api version to v1alpha5

- kubeflow/aws/aws-alb-ingress-controller.libsonnet
- kubeflow/aws/prototypes/aws-alb-ingress-controller.jsonnet
- kubeflow/aws/tests/aws-alb-ingress-controller_test.jsonnet
In case ec2metadata is not available for the alb-ingress-controller pod it is required to configure the VPC id and region.
We had this need and thus I enhanced the `aws-alb-ingress-controller` component to support defining these values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3292)
> Allow defining VPC id and region for AWS alb-ingress-controller

- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
paired with [manifests/#77](https://github.com/kubeflow/manifests/pull/77)
fixes #3303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3304)
> iap-ingress is missing parameters used in ksonnet

- kubeflow/katib/studyjobcontroller.libsonnet
Just keep consistent with https://github.com/kubeflow/katib/pull/550
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3314)
> Add command field for defaultMetricsColloctor deployment

- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
`yaml.Unmarshal` is not replacing content of output, it's merging it with `src`.  Plus placing `o` in the scope outside of the loop isn't doing anything.  Making it in the same scope as the applying loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3321)
> Fix manifest rewritten in error during apply

- prow_config.yaml
Since kfctl-go-iap does not install istio it fails to deploy the componnets whcih have dependency on istio (e.g., notebook-controller). We can remove it. kfctl-go-iap-istio already covers what kfctl-go-iap  does. #3306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3307)
> Remove kfctl-go-iap workflow test

- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
if the parent kustomization does not define conflicting commonLabels or commonAnnotations, its ok to copy the overlay ones to the parent when mixing in overlays
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3325)
> allow commonlabels, commonannotations to be copied to parent kustomization.yaml

- bootstrap/config/overlays/kustomize/kfctl_default.yaml
To match naming convention in KSONNET.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3360)
> MINIO PVC names

- components/centraldashboard/package-lock.json
- components/centraldashboard/package.json
- components/centraldashboard/public/components/dashboard-view.css
- components/centraldashboard/public/components/dashboard-view.js
- components/centraldashboard/public/components/dashboard-view.pug
- components/centraldashboard/public/components/dashboard-view_test.js
- components/centraldashboard/public/components/namespace-selector.js
- components/centraldashboard/public/components/resource-chart.js
- components/centraldashboard/public/components/resource-chart_test.js
- components/centraldashboard/public/components/resources/cloud-platform-data.js
Adds charts to display the past hour of CPU resource utilization at the Node level and the top 5 Pods.
Backend implementation is in #3251 
Closes #3225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3326)
> Resource charts for CPU Utilization

- components/centraldashboard/public/components/main-page.css
- components/centraldashboard/public/components/main-page.pug
The old responsive threshold for collapsing sidebar was 900px (when dashboard was 2 columnar) now it's 1270px
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3372)
> Collapse sidebar threshold updated from 900px to 1270px

- components/centraldashboard/.eslintrc.json
- components/centraldashboard/public/components/iframe-link.js
- components/centraldashboard/public/components/iframe-link_test.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
- Removes redundant forwarder for iframe-links. This was resulting in pushing
the same state to history twice, which would require the user to issue two
back button clicks in their browser if they wished to return to the previous URL.
- In addition, we now set the iframe's location programmatically rather than by
changing the src attribute, which could also result in history states being
pushed inadvertantly.
- We also avoid passing the ns query parameter down to avoid unncessary reloads
of iframed-content in favor of using our message passing library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3402)
> Fix multiple iframe-link behaviors.

- kubeflow/jupyter/prototypes/README.md
I think, here: https://github.com/kubeflow/kubeflow/tree/master/kubeflow/jupyter/prototypes#design yaml structure is incorrect.
According to this: https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3004:
1. `securityContext` is not a list.
2. `PodSpec` doesn't have `ttlSecondsAfterFinished` field.
/assign @kkasravi @lluunn 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3308)
> Fix notebook example

- kubeflow/tf-training/prototypes/tf-job-operator.jsonnet
- kubeflow/tf-training/tests/tf-job_test.jsonnet
- kubeflow/tf-training/tf-job-operator.libsonnet
Moves port config to tf-operator service instead of deployment
Moves Prometheus config to service as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3408)
> Adds new service config for tf-operator

- components/contrib/kaggle-notebook-image/Dockerfile
- components/contrib/kaggle-notebook-image/README.md
- components/contrib/rapidsai-notebook-image/Dockerfile
- components/contrib/rapidsai-notebook-image/README.md
Refresh of RAPIDS and Kaggle contrib notebooks after some GKE smoke testing.
```
gcr.io/kubeflow-dev/kubeflow-rapidsai-notebook:latest 
gcr.io/kubeflow-dev/kubeflow-kaggle-notebook:latest 
```
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3423)
> Contrib notebook refresh

- components/centraldashboard/public/components/main-page.js
As requested by @jlewi, this PR removes TF Jobs UI from Central-Dashboard, on account of it being very deprecated and not used.
---
/cc @prodonjs @jlewi 
/area central-dashboard
/priority p2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3424)
> Removed TF-Job link from Central-Dashoard

- components/centraldashboard/app/api.ts
- components/centraldashboard/app/api_test.ts
- components/centraldashboard/app/server.ts
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
- components/centraldashboard/public/components/namespace-selector.js
- components/centraldashboard/public/components/namespace-selector_test.js
- Eliminates separate call to fetch namespaces.
- Retrieves user email address from deployments secured by IAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3420)
> Consolidate initial state retrieval and retrieve user email from IAP headers

- components/jupyter-web-app/kubeflow_jupyter/default/templates/notebooks.html
- components/jupyter-web-app/kubeflow_jupyter/rok/templates/notebooks.html
- The SDK was only changing the value of the selector, however, the view depends on a change event.
- We fire a change event when the value for namespace selector is updated now
---
/priority p0
/cc @prodonjs @kimwnasptd 
/area jupyter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3427)
> Fixes Jupyter Web App SDK namespace change doesn't trigger view update

- components/tensorflow-notebook-image/Dockerfile
Fixes  https://github.com/kubeflow/kubeflow/issues/3016
#added emacs to list of packages installed by apt-get 
Related to the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3089)
> Add emacs package to the Jupyter Image

- bootstrap/pkg/kfapp/coordinator/coordinator.go
This commit fixes a minor bug in the Sprintf function, where wrong
arguments are passed.
It also caused the `kfctl-container-build` Makefile target to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3365)
> kfctl: fix minor bug in Sprintf

- deployment/aws/OWNERS
- scripts/aws/OWNERS
Have 1-2 aws related PRs need to cherry-pick back to v0.5.1. 
I added owners files to master and like to cherry-pick back to v0.5.1 and then I can approve that PRs. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3457)
> Automated cherry pick of #3438: Add OWNERS file under aws components 

- testing/kfctl/kfctl_go_test.py
Now our presubmit run with kustomize, 
katib hasn't migrate to kustomize yet so remove test steps to verify katib controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3474)
> fix pre-submit

- bootstrap/config/kfctl_iap.yaml
- bootstrap/pkg/kfapp/gcp/gcp.go
- kubeflow/jupyter/prototypes/notebook_controller.jsonnet
With this one, kfctl will deploy profile and kfam API by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3473)
> add profile and kfam API to kfctl default component

- kubeflow/pytorch-job/pytorch-operator.libsonnet
Empty list added to cluster role if gang scheduling not enabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3486)
> Fix error if gang scheduling not enabled

- bootstrap/cmd/kfctl/cmd/init.go
- bootstrap/go.mod
- bootstrap/go.sum
- bootstrap/pkg/apis/apps/group.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
As per the discussion in #3419, it seems that we want to move to an approach where:
* Each platform specifies its own set of static yamls files for the KfDef config.
* A user can specify a KfDef config to use, which should give us reproducibility, easy sharing of configs and is in-line with the GitOps philosophy.
This PR adds the `--config` flag to `kfctl`.
When set, `kfctl` will read the KfDef from the specified file instead of generating it using kustomize.
Platforms can also override this option and specify their own static file.
Partially related to: #2831 support pulling from a local repository
* This will pull the config from a local repository but we still have to support adding and pulling
all of the repos/manifests on which we depend from a local repo.
Signed-off-by: Yannis …
> kfctl: add --config flag for specifying a static config file

- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Fixes: #3426 
This PR makes kfctl with kustomize fail in generate and apply when a component is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3488)
> kfctl: kustomize: fail when a component is missing

- components/jupyter-web-app/kubeflow_jupyter/default/app.py
- components/jupyter-web-app/kubeflow_jupyter/rok/app.py
In order to communicate the namespace with the dashboard, we disable the namespace input.
The backend should be able to deduce the namespace from the route and use it when necessary 
/assign kimwnasptd
/assign jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3507)
> jupyter-web-app: Fix 400 error

- components/centraldashboard/public/components/pipelines-card.js
Fixes console error when trying to map on a non-existent array property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3522)
> Account for optional pipelines/runs property in Pipelines card responses

- components/centraldashboard/Dockerfile
- components/centraldashboard/Makefile
- components/centraldashboard/karma.conf.js
This ensures that all unit tests are run during the image build process, which is invoked during pre/post submit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3541)
> [CentralDashboard] Update Dockerfile to run all tests apart from built image

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/fake/fake.go
- bootstrap/pkg/kfapp/gcp/fake/fake.go
* To support unittesting of the click to deploy server we create a fake
implementation of coordinator.KfApp
* We also define the Builder interface so we can inject a constructor
that will create a fake as opposed to real implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3570)
> Create a fake coordinator to support unittesting.

- bootstrap/v2/pkg/apis/apps/kfdef/v1alpha1/application_types.go
* Application is intended as a replacemnt for the fields packages, components,
componentParams.
* See #3491; discovery logic for kustomize is broken.
* The new Application type allows us to specify in the YAML spec the
repository and path within the repository of the kustomize package to use
* This will allow us to address that issue because we will be able to
stop relying on the discovery logic and instead just specify the packages
in the app.yaml that we need.
* This PR just defines the type
* Forthcoming PRs
* A PR to backfill Application based on packages, components & componentParams
so that we don't break compatibility with existing specs.
* Update kustomize.go to use Application
--- …
> Add a list of Applications to KfDef.

- components/centraldashboard/public/components/dashboard-view.js
- components/centraldashboard/public/components/main-page.js
/area frontend
**Artifact store** was the name for the link in @ajayalfred 's [mocks](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZYbjDGnaKqEC/files/MCEJu8Y2hyDScRKM1oyOOWQSEJJUv10bnK4)
/cc @rileyjbauer 
/cc @zhenghuiwang 
Hold until manifests changes are ready with the cluster-level route to Metadata-UI working.
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3569)
> Add Metadata UI links to Central Dashboard

- bootstrap/pkg/utils/logging.go
- bootstrap/v2/pkg/apis/kferrors.go
- bootstrap/v2/pkg/utils/logging.go
* Define a PrettyPrint function based on serializing to json.
* Define a helper method for KfErrors to combine an existing error with
a message.
* This is related to #3593; there are lots of places in GCP.go where
we assume an error is of type KfError without asserting whether that's
true
* This helper method will help us fix those locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3595)
> Some error and logging utilities.

- bootstrap/v2/pkg/kfapp/existing_arrikto/existing.go
- bootstrap/v2/pkg/kfapp/existing_arrikto/existing_test.go
- deployment/existing/auth_oidc/authservice.tmpl
- deployment/existing/auth_oidc/dex.tmpl
- deployment/existing/auth_oidc/envoy-filter.yaml
- deployment/existing/auth_oidc/gateway.yaml
- deployment/existing/istio/istio-noauth.yaml
This PR adds self-signed HTTPS certificates to secure the Istio gateway.
Currently, these certificates are for the LoadBalancer IP.
In the near future, it will be possible to use a DNS domain and trusted certificates.
Some remarks:
* The AuthService and Istio Gateway Deployment now live in the same namespace (istio-system) in order to share the cert secret.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3598)
> kfctl: existing_arrikto: add self-signed https certificates

- deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
closes #3597 
Enables utilization graphs to show on Central Dashboard for GKE deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3533)
> Add monitoring.viewer role to enable dashboard utilzation graphs

- bootstrap/go.mod
- bootstrap/go.sum
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
- bootstrap/v2/pkg/kfapp/kustomize/kustomize_test.go
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role-binding.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/cluster-role.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/config-map.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/deployment.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/kustomization.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/params.env
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service-account.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/base/service.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/expected/kustomization.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/application.yaml
- bootstrap/v2/pkg/kfapp/kustomize/testdata/kustomizeExample/pytorch-operator/overlays/application/kustomization.yaml
Fix #3558 
Generate now only copies the pkg dir to kustomize/
Apply will call GenerateKustomizationFile to get the manifest.
```
kf0702/kustomize$ ls
api-service         cert-manager-crds   jupyter-web-app     minio               profiles            tf-job-operator
application         cloud-endpoints     katib-controller    mysql               pytorch-job-crds    webhook
application-crds    gpu-driver          katib-db            notebook-controller pytorch-operator
argo                iap-ingress         katib-manager       persistent-agent    scheduledworkflow
bootstrap           istio               katib-ui            pipelines-runner    spartakus
centraldashboard    istio-crds          metacontroller      pipelines-ui        suggestion
cert-manager        istio-install …
```
> keep manifest in kfctl directory as kustomize pkg

- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
The default storage class detection code has a bug.
The bug causes it to not check for the `storageclass.kubernetes.io/is-default-class` annotation.
/assign @kimwnasptd 
cc @ioandr @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3647)
> jupyter-web-app: backend: fix default storage class detection

- scripts/setup-minikube.sh
The minikube setup script infers the amount of disk that's available. It does so through a `dd -h`. This can produce fractions, which will make the code fail. E.g. when i have `1.7Tb` free, the value will be `1.7`, which will be compared to `40`, which will break, like so, as bash cannot perform floating point arithmetic.
```
((: 1.7 < 40: syntax error: invalid arithmetic operator (error token is ".7 < 40")
```
The patch here makes sure that `df` only returns integers in Gigabytes.
I have proposed a patch for this in this PR, but in general, I think the current approach taken, where we check the last mount's free space using `tail -1` is not a good approach at all. I would even consider removing the test, and make it configurable.
I think the above concern is to address later, and get …
> Fix minikube setup script's df inference

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
- bootstrap/pkg/kfapp/gcp/gcp.go
* coordinator go was dynamically recreating the KfApp for the package manager whenever the
actions init/generate/apply/delete were called.
* This prevents storing state in the KfApp's representing the platform and package manager.
* Coordinator also stores maps Coordinator.platforms and Coordinator.packageManagers so why not
just get them from there?
* I suspect this was legacy code and might have been required when we were embedding the KfDef inside
the Kustomize/Ksonnet/Gcp structs rather than just storing a pointer.
* As a result I think we had to dynamically recreate them in order to pick up the changes to KfDef.
* Change the code so KfApps are constructed once in LoadCfgAppFile and after that we get them
from the appropriate fields in Coordinator.
* Move the code in GetKfApp to …
> coordinator should load packagemanagers and platform KfApps once at construction time

- kubeflow/pytorch-job/pytorch-operator.libsonnet
- kubeflow/pytorch-job/tests/pytorch-job_test.jsonnet
Configmaps are not used in operator anymore. Unnecessary rules are also removed
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3564)
> Removing unnecessary rbac authorization for pytorch operator

- kubeflow/tf-training/tests/tf-job_test.jsonnet
- kubeflow/tf-training/tf-job-operator.libsonnet
Configmaps are not used in operator anymore. Unnecessary rules are also removed
/hold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3565)
> Removing unnecessary rbac authorization for tf operator

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
- bootstrap/v2/pkg/kfapp/kustomize/kustomize_test.go
* kustomize module should use KfDef.Applications to get information about each
application to install
* Each Application refers to a kustomize package to build and install
* To provide backwards compatibility, kustomize.go will convert the old style
kfDef.componentParams, kfDef.components to kfDef.Applications
Related to #2152
Related to #3491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3668)
> kustomize.go should use KfDef.Applications

- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/gcp/gcp_test.go
- bootstrap/pkg/kfapp/gcp/util.go
* We want to migrate to using KfDef.Application to store application parameters
* The GCP module needs to set some of the application parametes
we use the KfDef helper routines to set application parameters
* The helper routines are compatible with both KfDef.Applications and the
older KfDef.component parameters.
* Add KfDef.labels to the deployments that get created
* Fix some unsafe code in gcp.go; some of the code was assuming errors were of
type KfError without testing the assertion
* Add an IsValid method to test the GCP config
* Gcp should use the KfDef WriteConfigFile method and not define its own method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3669)
> gcp should support KfDef.Application

- releasing/releaser/app.yaml
Get rid of deprecated dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3682)
> fix auto release for central dashboard

- bootstrap/config/overlays/istio/kfctl_default.yaml
- bootstrap/pkg/kfapp/gcp/gcp.go
As of today basic auth will be for single user or demo purpose.
Will turn off isolation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3675)
> turn off Istio isolation for basic auth

- bootstrap/pkg/apis/apps/group.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
- bootstrap/v2/pkg/apis/apps/group.go
So on v0.6 branch kfctl will use v0.6.0 config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3692)
> set kfctl default version to v0.6

- bootstrap/Makefile
- bootstrap/cmd/bootstrap/app/gcpUtils.go
- bootstrap/cmd/bootstrap/app/kfctlClient.go
- bootstrap/cmd/bootstrap/app/kfctlServer.go
- bootstrap/cmd/bootstrap/app/kfctlServer_test.go
- bootstrap/cmd/bootstrap/app/kfctlUtil.go
- bootstrap/cmd/bootstrap/app/kfctl_test.go
- bootstrap/cmd/bootstrap/app/ksServer.go
- bootstrap/cmd/bootstrap/app/router.go
- bootstrap/cmd/bootstrap/app/server.go
- bootstrap/cmd/bootstrap/app/sourceRepos_test.go
- bootstrap/cmd/bootstrap/app/tokenSource.go
- bootstrap/cmd/bootstrap/app/util.go
* Delete the method DeployWithKfctl
* kfctlServer will handle the create requests
* CreateDeployment should take a KfDef as the payload and return a kfDef
* kfctlServer - handleDeployment - add the logic necessary to handle deployment
* router - add an IAM access check to see if the request is authorized
Related to: #2152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3652)
> KfctlServer should take KfDef as the request payload.

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/gcp/gcp_test.go
- bootstrap/v2/pkg/apis/apps/group.go
- bootstrap/v2/pkg/apis/apps/group_test.go
- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
Fixes #3640 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3693)
> Create PodDefault if platform is GCP

- components/centraldashboard/public/components/namespace-selector.js
- Paper-Menu-Button had the dropdown aligned `right`. This would allow it to flow into the sidebar, the new config should not let this happen
/priority p0
/cc @prodonjs @paveldournov
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3742)
> Paper-menu-dropdown is aligned left

- bootstrap/config/kfctl_gcp_basic_auth.yaml
- bootstrap/config/kfctl_gcp_iap.yaml
- bootstrap/v2/pkg/kfapp/kustomize/kustomize.go
GCP credential
The overlay is at https://github.com/kubeflow/manifests/pull/245, but we should submit this before the overlay.
for #3638 . 
Certificate
Overlay at https://github.com/kubeflow/manifests/pull/246. For https://github.com/kubeflow/kubeflow/issues/3079
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3779)
> Add gcp-credential and cert overlay

- bootstrap/pkg/kfapp/aws/aws.go
- bootstrap/pkg/kfapp/gcp/gcp.go
Fix the error messages provided to clarify when the error is not being able to
read the input file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3801)
> [KUBEFLOW-3797] When copying files fails provide correct error message

- components/centraldashboard/app/api.ts
- components/centraldashboard/app/api_contributors.ts
- components/centraldashboard/app/api_test.ts
- components/centraldashboard/app/server.ts
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
- components/centraldashboard/public/components/manage-users-view.css
- components/centraldashboard/public/components/manage-users-view.js
- components/centraldashboard/public/components/manage-users-view.pug
- components/centraldashboard/public/components/namespace-selector.js
- components/centraldashboard/public/components/registration-page.css
- components/centraldashboard/public/components/registration-page.js
- components/centraldashboard/public/components/registration-page.pug
- components/centraldashboard/public/components/resources/md2-input/md2-input.css
- components/centraldashboard/public/components/resources/md2-input/md2-input.js
- components/centraldashboard/public/components/resources/md2-input/md2-input.pug
- components/centraldashboard/public/components/resources/paper-chip.js
- components/centraldashboard/public/components/utilities-mixin.js
- Vaadin charts and paper-toast added
- Profile Controller promise handler created
- `/get-contributors` api route created
- Namespace icon added
- Manage Users page added
- Dashboard made aware of cluster admin status and `isolationMode`
- `Manage Users` sidebar entry only when isolationMode is multi
- New `empty` macro added to utilities mixin
- Paper-chip element added
- TSLint remove any warnings
- Updated failing api_tests.ts
- Corrected the fields being used to/from server for registration
- Corrected sidebar entries for Manage-Users
- Manage Users contrib action color now toggles based on status (error support)
- Rollback errors when successfully added contributor
- Paper-chip border-color updated
- Paper-chip ripple updated to accent color
--- …
> Multi-User Isolation 2.0 - Manage Users

- components/centraldashboard/app/api.ts
- components/centraldashboard/app/api_test.ts
- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/app/server.ts
**_Add-on to #3758_** 
**_Resolves #3836_**
- Added support for communicating with Profile Controller for namespaces
- Renamed api_contributors to api_workgroup
- Updated nomenclature, removed unnecessary deps
- Fixed tests to work with new response structure
/cc @prodonjs @kunmingg @abhi-g 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3842)
> [Central-Dashboard v2] MUI Basic Auth Support

- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
closes #3770 
If the `desc` field is not present in the PodDefault, show the CR's name
instead in the UI.
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3845)
> jupyter-web-app: Use PodDefault's name as backup

- bootstrap/config/kfctl_aws.yaml
- bootstrap/config/kfctl_aws_cognito.yaml
- bootstrap/config/kfctl_existing_arrikto.0.6.yaml
- bootstrap/config/kfctl_gcp_iap.0.6.yaml
- bootstrap/config/kfctl_k8s_istio.yaml
cc @abhi-g @jlewi @lluunn 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3867)
> kfctl: pin configs to v0.6-branch

- bootstrap/pkg/kfapp/existing_arrikto/existing.go
- bootstrap/pkg/kfapp/existing_arrikto/existing_test.go
**Fixes:**
https://github.com/kubeflow/kubeflow/issues/3764
```bash
git clone https://github.com/kubeflow/kubeflow.git
KF_REPO="$(pwd)/kubeflow"
cd $KF_REPO 
git fetch upstream pull/<PR_NUMBER>/head:kfctl-platform-existing
git checkout kfctl-platform-existing
```
Go into the bootstrap folder and build the kfctl binary.
The resulting binary is available inside the bin folder.
```bash
cd $KF_REPO/bootstrap
mkdir -p bin
make build-kfctl-container
```
Follow the instructions from [the corresponding docs PR](https://github.com/kubeflow/website/blob/4ff9e654c14670a035070898ae049012187e219a/content/docs/started/getting-started-k8s.md).
--- …
> kfctl: existing_arrikto: fix ip discovery and cert creation on AWS for existing_arrikto config

- bootstrap/config/kfctl_existing_arrikto.0.6.yaml
- bootstrap/config/kfctl_gcp_basic_auth.yaml
- bootstrap/config/kfctl_gcp_iap.yaml
- bootstrap/config/kfctl_k8s_istio.yaml
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
Related to #3859.
We don't want people deploying with kfctl to pick up changes to the manifests
until they've been tested.
kfctl should be pointing at the KFDef specs on the v0.6-branch.
So we need to pin the commits it points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3894)
> Pin kubeflow/manifests and kubeflow/kubeflow commits on the v0.6-branch

- bootstrap/config/kfctl_gcp_basic_auth.yaml
- bootstrap/config/kfctl_gcp_iap.yaml
* Comment out lines setting default values and provide comments explaining how
they should be set.
* We don't want to set values because the behavior in kfctl init/generate is
to try to automatically set intelligent default values but only if no
value is set. So explicitly setting default values inhibits that behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3912)
> Don't set dummy values for project, email, or hostname in kfctl_gcp iap.yaml

- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/gcp/gcp_test.go
* The generated PodDefaults is not correct; various fields are top level and not in the spec.
Related to #3924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3926)
> Fix the default poddefaults add-gcp-secret in v0.6-branch

- deployment/existing/auth_oidc/gateway.yaml
Fixes https://github.com/kubeflow/kubeflow/issues/3805
Right now, the following problem exists:
* Kubeflow VirtualServices get traffic from all ports.
* Dex VirtualService only gets traffic from 5556 AND prefix /dex.
* That way, if user hits :5556/, they will get the CentralDashboard page without logging in.
This PR fixes that by making sure all traffic to port 5556 goes to Dex.
cc @Jeffwan @tlkh @jlewi @kunmingg 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3885)
> kfctl: existing_arrikto: direct all 5556 traffic to Dex

- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/app/server.ts
- components/centraldashboard/public/components/main-page.css
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/utilities-mixin.js
- Promise rejection from `/api/workgroup/exists` now caught
- All unhandled promises are printed
- Error handling logic added to main-page
- Error toast added, available for all components to use
- [intuititve] added a close button to toast since it's persistent
/priority p1
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3933)
> [CentralDashboard v2] Error surfacing for profile controller errors

- bootstrap/config/kfctl_existing_arrikto.0.6.yaml
Incorrect indentation at line 106 in kfctl_existing_arrikto.0.6.yaml causing deployment to fail when using this config.
Resubmitting PR to fix issues with CLA bot detecting my email on commit correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3961)
> Fixed indentation in kfctl_existing_arrikto.0.6.yaml in v0.6-branch 

- bootstrap/config/kfctl_k8s_istio.yaml
https://github.com/kubeflow/kubeflow/issues/3876
kfctl_k8s_istio doesn't have authentication, disable authorization to make user visit notebook they created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3877)
> Disable istio authorization in kfctl_k8s_istio

- components/centraldashboard/Dockerfile
- components/centraldashboard/app/server.ts
Added production env var in docker file, and statement print in server init.
/priority p1
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3971)
> [Centraldashboard v2] Env vars added to dockerfile

- bootstrap/config/kfctl_k8s_istio.yaml
- bootstrap/pkg/kfapp/kustomize/kustomize.go
* Always create a default profile by setting a default "anonymous" value for user id so that a profile would be created for user "anonymous"
* Turn off ISTIO RBAC in kfctl_k8s_istio because this config won't have the user's identity or JWTs so  ISTIO can't do service Authz.
related: https://github.com/kubeflow/kubeflow/issues/3893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3959)
> always create default profile; turn off istio rbac for kfctl_k8s_istio

- components/centraldashboard/app/attach_user_middleware.ts
- components/centraldashboard/app/attach_user_middleware_test.ts
- components/centraldashboard/app/server.ts
Added a `/debug` route to the dashboard for python e2e from Kubeflow
/priority p0
/cc @prodonjs @gabrielwen @jlewi @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3980)
> [Centraldashboard v2] Added a /debug route to dashboard for python e2e from Kubeflow

- bootstrap/config/kfctl_existing_arrikto.yaml
- bootstrap/config/kfctl_gcp_basic_auth.yaml
- bootstrap/config/kfctl_gcp_iap.yaml
- bootstrap/config/kfctl_k8s_istio.yaml
This is a partial reverts commit c3199d931b9b82c8717057c7aca883d76bb5e1d5.
Updating the configs on the v0.6.2 branch is not safe right now because our
v0.6.1 instructions may not be telling users to pin to a specific commit.
They may be pulling in the latest configs from the branch. So they
might be prematurely exposed to changes.
To be safe we should revert the changes to the YAML files. We can keep the .go changes. We can also keep the 0.6.2rc.yaml files.
We can then roll forward these changes by create ".0.6.2.yaml" versions of
the files with these changes.
Revert some files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3987)
> Revert "Update cofig file versions (#3978)"

- components/centraldashboard/app/k8s_service.ts
- components/centraldashboard/app/k8s_service_test.ts
Scan for Kubeflow application and fetch version from that resource
/priority p1
/cc @prodonjs @gabrielwen @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3992)
> [Centraldashboard v2] Correctly update Kubeflow Dashboard version from Kubeflow Resource

- bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml
- bootstrap/config/kfctl_gcp_iap.0.6.2.yaml
* This should pull in the fix to #3986 (centraldashboard not set with userid correctly).
* We are only changing the GCP configs because that is the only thing I have manually tested and verified.
* Now that we cherrypicked #302 onto the v0.6-branch of manifests; we need to
set userid-prefix and userid-header parameters for the applications
jupyter-webapp, profiles, and centraldashboard in the IAP config.
Otherwise we end up setting those to the empty string and it thinks we
are an anonymous user.
Related to: kubeflow/kubeflow#3986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3994)
> Set userid prefix and header for IAP and pull in the latest fixes to the applications repo for GCP configs

- bootstrap/config/kfctl_existing_arrikto.yaml
- deployment/existing/auth_oidc/authservice.tmpl
- deployment/existing/auth_oidc/envoy-filter.yaml
- deployment/existing/istio/istio-noauth.yaml
Depends on https://github.com/kubeflow/manifests/pull/274
* Update `kfctl_existing_arrikto.yaml` to use the applications spec. 
* The AuthService adds the header `kubeflow-userid` in every request.
* Parameters are added to each application so that it looks for the `kubeflow-userid` header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3904)
> kfctl: existing_arrikto: update config and enable multi-user identity awareness

- bootstrap/Dockerfile
- bootstrap/cmd/bootstrap/app/kfctlServer.go
- bootstrap/pkg/kfapp/kustomize/kustomize.go
- bootstrap/pkg/utils/k8utils.go
After https://github.com/kubeflow/kubeflow/pull/3957, `kustomize apply` use `kubectl apply` directly.
This PR make sure `kustomize apply` pick up config provided by `SetK8sRestConfig()` in kfctl server case (local `kube/config` file is not available):
- Within `kustomize apply`, `kubectl apply` will take host, token and cert as CLI flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4054)
> kfctl server integrate new kustomize apply

- bootstrap/config/kfctl_gcp_iap.yaml
* When using IAP, we need to configure various applications to look at
the correct header and prefix so that they get the identity correctly.
Related to #3986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/3996)
> Set userid prefix and header for IAP.

- py/kubeflow/kubeflow/ci/application_util.py
- releasing/auto-update/README.md
- releasing/auto-update/base/params.env
- releasing/auto-update/base/params.yaml
- releasing/auto-update/overlays/cron/kustomization.yaml
- releasing/auto-update/overlays/cron/update_job_cron.yaml
- releasing/auto-update/overlays/job/kustomization.yaml
- releasing/auto-update/overlays/job/update_job.yaml
Fix a bunch of issues with CD for the jupyter web app
* Update jupyter web-app CD scripts to run in the kf-releasing namespace
* Fix a bug in applicaiton_util; open temporary file in write mode
* Clone the repos in full depth so that we properly compute the last commit
that modified the jupyter web app.
* Requires building a new docker image using kubeflow/testing#458 which
has an updated version of checkout_repos.sh
* Related to: #3829
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4029)
> * Update jupyter web-app CD scripts to run in the kf-releasing namespace

- bootstrap/go.mod
- bootstrap/go.sum
* Related to kubeflow/kubeflow#4095
* There is a problem with the thrift dependency so we need to update go.mod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4097)
> Fix broken kfctl build on v0.6-branch

- docs_dev/releasing.md
Corrected the format of the version name (v0-6 not v0.6) and added some info that I had to go looking for when following the instructions.
Removed the instruction to add a domain alias for `www.kubeflow.org`, because I got an error message "Another site is already using this domain" when I tried to do this step.
Removed the instruction to cherry pick the version number changes from master to the new branch, as that doesn't seem necessary (we have the `master` link link in the menu) and it doesn't look as if anyone else has done it.
Changed the internal pantheon link to the cloud console link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4127)
> Updated the guide to releasing the website

- bootstrap/config/kfctl_gcp_iap.0.6.2.yaml
Part 2 of https://github.com/kubeflow/kubeflow/pull/4122
So config version is consistent on GCP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4130)
> pick up manifest config fix on v0.6 branch

- bootstrap/cmd/bootstrap/app/kfctlClient.go
- bootstrap/cmd/bootstrap/app/kfctl_test.go
* createDeployment is used inside the kfctl router to handle requests.
This function should return in a reasonable time as determined by the context;
otherwise the user is stuck waiting on a response.
* #4014 increased the backoff and retry period for up to 30 minutes as
part of the monitoring story. It looks like this was done so createDeployment
would wait to see if the kubeflow deployment was created successfully and
then report it.
* This has the side effect of blocking the response to the request which
is why kfctl_test was failing
* I think the monitoring and incrementing of counters should happen instead
in handleDeployment in kfctlServer
* This PR however fixes the test by setting the backoff and retry period
based on the context which allows the test to set an appropriately
short …
> kfctlClient createDeployment should respect the deadline set in the context

- bootstrap/Makefile
Not sure why tests didn't catch this...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4165)
> Fix v1beta1 deepcopy rule

- bootstrap/pkg/kfapp/aws/aws.go
- bootstrap/pkg/kfapp/existing_arrikto/existing.go
* kubeflow/manifests#353 moved the additional configuration files into the
kubeflow/manifests repo
* The AWS and existing_arrikto plugins should pull the additional configuration
files from that repo rather than the kubeflow/kubeflow repo
* There are lot of reasons for doing this but a big one is downloading
a single repository. Furthermore the kubeflow/kubeflow repo takes 100+M
because we have vendored a bunch of dependencies into it.
* The existing_arrikto and AWS plugins are currently hard coding the paths
so this PR just updates the paths to the new locations.
* The better directoin long term is to define Plugin specs for each of
these plugins and specify the location as part of the KFDef like we
do for GCP see: kubeflow/kubeflow#4118
* Related to kubeflow/manifests#241
---
This …
> Arrikto and AWS plugins should pull additional configuration files from kubeflow/manifests

- bootstrap/pkg/kfapp/gcp/gcp.go
- go.mod
- prow_config.yaml
- py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
- testing/kfctl/conftest.py
- testing/kfctl/kfctl_go_test.py
* We need to write an E2E test for kfctl upgrade (kubeflow/kfctl#35).
Before we do that we want to remove ksonnet from our existing E2E test.
The E2E test for upgrades will be very similar to the kfctl E2E test
so it makes sense to convert that test to python before writing
the upgrade test.
* Related to kubeflow/kubeflow#3035 migrate e2e tests off ksonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4148)
> Use python to define the E2E test workflow for kfctl.

- testing/README.md
Fixes https://github.com/kubeflow/kubeflow/issues/1398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4206)
> Fixed the deprecated proxy URL

- bootstrap/pkg/kfapp/coordinator/coordinator.go
This reverts commit 9a25c2bc72190fa2a5e68398cedf4b4a95ccb4db.
* The strawman reconcile (#4106) leads to a bug where we try to deply K8s
resources even though cluster creation failed (#4195)
* This is because the strawman implementation of reconcile uses errors
to determine whether to keep retying or whether deployment is done.
* I think the way to fix this is to use conditions which is blocked on updating
the code to use v1beta1.
* The various plugins should use appropriate conditions (e.g. failed,
succeeded, running) to signal to the apply function in coordinator.go
whether apply.go should keep going, report a failure, etc...
* Related to #4056 - Implement reconcile semantics
* Related to #4195 - kfctl keeps going even though cluster creation failed
--- …
> Revert "Apply with strawman reconcile (#4106)"

- prow_config.yaml
- py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
- testing/kfctl/endpoint_ready_test.py
* We need to use self.workflow.
* This was causing postsubmits to fail because self.workflow is undefined.
* Add a presubmit test that runs with test_endpoint=true in the event the
E2E workflow is modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4201)
> Fix test_endpoint.

- components/centraldashboard/app/stackdriver_metrics_service.ts
- components/centraldashboard/app/stackdriver_metrics_service_test.ts
- components/centraldashboard/package-lock.json
- components/centraldashboard/package.json
- components/centraldashboard/public/components/resources/cloud-platform-data.js
- components/centraldashboard/tsconfig.json
Fixes #3535
- Uses new kubernetes.io metrics https://cloud.google.com/monitoring/api/metrics_kubernetes
- Metrics charts now link the new Kubernetes metrics dashboard in Stackdriver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4220)
> Centraldashboard: Updates Stackdriver metrics and links for GKE deployments

- py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
* The test needs to modify workingDir before running jupyter_test.py
otherwise we get an error (see #4221)
* There was a bug in the code and we weren't actually setting workingDir on
the argo template. That's because argo_build_util.add_task_to_dag makes
a copy of the template before adding the template to the graph.
* So we need _build_step to refetch the template so we get an actual pointer
to the template.
* Related to #4221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4224)
> Correctly set workingDir for jupyter_test

- bootstrap/pkg/apis/apps/group.go
Removed the GetK8sConfig function in Platform interface
/cc @jlewi @kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4236)
> remove redundant function used by ksonnet

- bootstrap/pkg/kfapp/kustomize/kustomize.go
Resolves #4136 
Creating different patch files for each PatchesJson6902 ops instead of aggregatepatch in single patch file.
Creating new PR due to some issues(notebook-test failure which is unrelated to kfctl chanegs-might be due to rebase) with PR #4137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4225)
> Addresses PatchesJson6902 patches issue while merging multiple targets

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/existing_arrikto/existing.go
Some minor bug fixes for kfctl:
1. Call SyncCache() when retrieving the KfApp. existing_arrikto was broken because GetPlaform() depended on the cache being ready. Plus it makes sense to sync the cache at that time.
2. Default to kustomize if a package manager isn't given. We only support kustomize so it makes the most sense.
/assign @swiftdiaries 
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4244)
> kfctl: minor bug fixes

- components/profile-controller/controllers/plugin_workload_identity.go
- components/profile-controller/controllers/plugin_workload_identity_test.go
- components/profile-controller/controllers/profile_controller.go
Since profile v1beta1, we support adding custom plugins as:
```
type Plugin interface {
// Called when profile CR is created / updated
ApplyPlugin(*ProfileReconciler, *profilev1beta1.Profile) error
// Called when profile CR is being deleted
RevokePlugin(*ProfileReconciler, *profilev1beta1.Profile) error
}
```
This PR enables finalizer to execute `RevokePlugin`
- `RevokePlugin` should undo all changes outside k8s cluster made by `ApplyPlugin`.
- For example `RevokePlugin` of `workload_identity` will undo bindings to GCP service account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4235)
> Enable finalizer to call RevokePlugin() during profile deletion

- bootstrap/pkg/kfapp/gcp/gcp.go
- py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Fixes: https://github.com/kubeflow/kubeflow/issues/4240
The E2E test was previously ignoring GCP creds set in the KFDef. This reverts that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4252)
> reverts gcp config from env vars for E2E test

- components/profile-controller/controllers/plugin_workload_identity.go
- components/profile-controller/controllers/plugin_workload_identity_test.go
- components/profile-controller/controllers/profile_controller.go
- components/profile-controller/main.go
profile controller now has new flag `--workload-identity`
If it is not "", controller will patch it as default `workloadIdentity plugin` to all profiles who don't have `workloadIdentity plugin` in spec.
Cluster admin can still change GCP identity of certain profile later by editing the profile CR directly.
This PR is from https://github.com/kubeflow/kubeflow/pull/4258.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4261)
> profile controller: enabling patch default workload identity plugins to all profiles.

- bootstrap/cmd/kfctl/cmd/apply.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/gcp/gcp.go
- testing/kfctl/kf_is_ready_test.py
* Related to kubeflow/kfctl#49
* Delete NewKfapp its not being called from anywhere.
Refactor NewLoadKfAppFromURI and LoadKfAppCfgFile
* We should only call CreateCfgFile and do the directory check if using a
remote URI
* For a local path we already have an appfile so we don't need to recreate
the CreateCfgFile
* Calling CreateCfgFile for local paths was a major source of friction
because it ends up checking if the directory is empty.
* But when invoking kfctl on a local file we don't need to check if
the directory is empty because we can assume that's the correct
${KFAPP}.
* Once we have a local config file we can treat the two cases the same
* Fix error propogation in apply.go; if BuildKfAppFromURI returns an
error we want to return that error so it ends up being printed out.
Otherwise …
> Improve kfctl semantics and ability to rerun app.yaml

- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/go.sum
Fix for #3945.
`notebook-controller` checks if `ISTIO_GATEWAY` environment variable is set. If it is, it will use its value as gateway. If empty, it will default to `kubeflow/kubeflow-gateway`, which was the previously hardcoded value.
I will also make a PR on `kubeflow/manifests` in order to add the Kustomize config for this environment variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4216)
> [3945] Configurable Istio Gateway for Notebook Controller

- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
- components/gatekeeper/go.mod
- testing/kfctl/kf_is_ready_test.py
- testing/kfctl/kfctl_delete_test.py
* This matches 0.6 semantics by defaulting.
* More importantly this enables a user to do
mkdir ${KFAPP}
kfctl apply -V -f https://...
* Related to kubeflow/kfctl#52
* #4275 needs to be merged first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4287)
> Kubeflow deployment name should default to the directory name.

- testing/kfctl/kfctl_delete_test.py
* See kubeflow/kfctl#56 the test is flaky
* More importantly if the test fails we end up blocking the uploading of
junit files and we lose signal.
* So to prevent that we mark it as expected to fail. This way the step
won't exit with non-zero exit code and the cleanup will continue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4313)
> Mark kfctl_delete_test as expected to fail

- bootstrap/pkg/apis/apps/group.go
- bootstrap/pkg/apis/apps/group_test.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/gcp/gcp_plugin.go
- bootstrap/pkg/kfapp/gcp/gcp_test.go
- bootstrap/pkg/kfapp/kustomize/kustomize.go
- bootstrap/pkg/utils/k8utils.go
- update workload identity permission setup
- apply format check on profile name
- set params for profile controller and default profile
- keep poddefault for backward compatibility?
This PR setup params for https://github.com/kubeflow/kubeflow/issues/3822
And cover https://github.com/kubeflow/kfctl/issues/46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4309)
> refactor profile & workload identity setup

- bootstrap/pkg/kfapp/gcp/gcp.go
Returned the wrong variable and causing nil pointer exception from time to time.
Related to #3703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4319)
> fix error population

- py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
* See kubeflow/testing#489 we want to support having run_e2e_workflow.py
pass extra arguments to the workflow. To do that we need to update the
test to first accept unknown arguments so we don't break once
run_e2e_workflow.py starts adding extra arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4335)
> Support extra arguments in kfctl_e2e_workflow.py

- prow_config.yaml
- testing/kfctl/endpoint_ready_test.py
* See kubeflow/kfctl#57 kfctl testing is overly reliant on expensive, flaky
E2E tests; right now we aren't testing kfctl so much as all of Kubeflow.
* This is cauing a lot of pain and negatively impacting velocity of kfctl.
* Right now we are running multiple variants of the same expensive e2e
tests on presubmits.
* These additional tests are providing minimal additional coverage on
presubmit but the flakiness is a major drag on velocity
* Don't run kfctl-gcp-basic-auth on presubmit; this provides minimal
additional coverage on presubmit
* Delete kfctl-go-build-deploy - the difference between this test
and the other e2e tests is that it was invoking kfctl build followed by
kfctl apply rather than just apply.
* This provides minimal additional coverage
* Instead just always run the 2 step …
> Drastically reduce the presubmits triggered for kfctl to reduce pain.

- testing/kfctl/kf_is_ready_test.py
v1beta1 KfDef doesn't have `spec.platform`, inferring platform from plugins instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4346)
> is_ready testing add support to v1beta1 kfdef

- bootstrap/go.sum
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/utils/k8utils.go
- bootstrap/pkg/utils/k8utils_test.go
use neturl.Parse instead of ParseRequestURI because the latter only works with abs path.
https://golang.org/pkg/net/url/#ParseRequestURI
/cc @jlewi @richardsliu 
https://github.com/kubeflow/kfctl/issues/49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4331)
> kfctl support relative path 

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
Fixes #4334
This ensures that embedded apps like Pipelines and Metadata which
use hash-based routing reload when the user navigates away and comes
back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4341)
> [centraldashboard] Clear iframe state when user navigates away.

- prow_config.yaml
* Now that we have cut v0.7-branch of kubeflow/manifests we want to
start periodicially testing kfctl with the v0.7-branch of manifests.
* We don't have a v0.7-branch yet for kfctl so for now we test against
kubeflow/kubeflow master which is still where we are for kfctl.
* Related to kubeflow/testing#498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4361)
> Define some postsubmit and periodic jobs for the v0.7-branch

- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/public/ajax_test_helper.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/registration-page.js
Correctly waits on ajax requests to complete so that the application state is in sync with the front-end app, and we don't make requests faster than the ops taking place in the backend. Updated the test framework to support said behavior.
/priority p0
/cc @prodonjs @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4364)
> [CentralDashboard v2] Registration dns validation fix hotfix - AJAX Waiting / Yielding

- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/kustomize/kustomize.go
Related: #4368 
Decision:
1. Skip `kustomize.Generate` if the folder `kustomize/` already exists.
1. Skip `gcp.Generate` if the folder `gcp_configs/` already exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4369)
> Fix apply overrides custom changes after Build

- bootstrap/cmd/kfctl/cmd/apply.go
- bootstrap/cmd/kfctl/cmd/build.go
- bootstrap/cmd/kfctl/cmd/delete.go
- bootstrap/cmd/kfctl/cmd/show.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
- bootstrap/pkg/kfapp/coordinator/coordinator_test.go
- bootstrap/pkg/kfapp/gcp/gcp.go
https://github.com/kubeflow/kfctl/issues/55
- commands (build, apply) call NewLoadKfAppFromURI as entrypoint
- move steps in LoadKfAppCfgFile to NewLoadKfAppFromURI, and delete LoadKfAppCfgFile
- createKfAppCfgFile is now private
/cc @gabrielwen @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4370)
> cleanup coordinator interface

- bootstrap/cmd/kfctl/cmd/build.go
- bootstrap/pkg/apis/apps/configconverters/converters.go
Fixes https://github.com/kubeflow/kubeflow/issues/4371
As a temporary fix, we don't allow deploying Kubeflow 0.6 using latest kfctl + 0.6 configs
Tested it locally:
```
INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml to /var/folders/1k/m148sdcd2szf5j5zdnbzq0c4006c2s/T/773576815/tmp_app.yaml  filename="configconverters/converters.go:71"
Error: failed to build kfApp from URI https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6-branch/bootstrap/config/kfctl_gcp_basic_auth.0.6.2.yaml:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file:  (kubeflow.error): Code 400 with message: KfDef version v1alpha1 is not supported by this binary. Please use configs at …
```
> Add a check for not allowing deploying v1alpha1 config

- bootstrap/cmd/kfctl/cmd/apply.go
Related to https://github.com/kubeflow/kubeflow/issues/4373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4395)
> Fix example paths in help messages

- bootstrap/pkg/apis/apps/configconverters/converters.go
- bootstrap/pkg/apis/apps/configconverters/v1alpha1.go
- bootstrap/pkg/apis/apps/configconverters/v1alpha1_test.go
- bootstrap/pkg/apis/apps/configconverters/v1beta1.go
- bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
- bootstrap/pkg/kfapp/coordinator/coordinator.go
AppDir and ConfigFileName is set in configConverters.LoadConfigFromURI
/cc @gabrielwen @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4385)
> ToKfConfig doesn't need to take appdir

- bootstrap/cmd/kfctl/cmd/apply.go
Fixes https://github.com/kubeflow/kubeflow/issues/4373
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4404)
> Automated cherry pick of #4395: fix example path in help messages Cherry pick of #4395 on v0.7-branch. #4395: fix example path in help messages

- bootstrap/cmd/kfctl/cmd/apply.go
- bootstrap/cmd/kfctl/cmd/build.go
- bootstrap/pkg/apis/apps/kfconfig/types.go
- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/kustomize/kustomize.go
* SetApplicationParameter will not throw error if application not found.
* application might be deleted from config file on purpose
* For same reason we print warnings instead of error when default namespace not found.
* Also update cmd help messages to include local config example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4380)
> fix kfctl corner cases

- components/centraldashboard/public/ajax_test_helper.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/registration-page.js
- components/centraldashboard/public/components/registration-page.pug
- components/centraldashboard/public/components/registration-page_test.js
- Registration polling added to check for a profile before running env-info
- Nits tackled
- Removed an unnecessary wait
/priority p1
/cc @prodonjs @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4384)
> [CentralDashboard v2] Polling for profile state (for 20 seconds) to allow a transition to dashboard

- testing/test_deploy.py
`katib-manager` depends on `katib-db`, so if `katib-manager` is ready, `katib-db` must be ready, too.
so we should  check`katib-db` is ready or not before `katib-manager`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4407)
> Reorder katib service available check

- bootstrap/pkg/kfapp/kustomize/kustomize.go
During apply failure, kustomize.Apply() retries application warning the user about currently encountered error. This error is printed as <nil> as the variable is set is incorrect.
```
WARN[0016] Encountered error during apply: <nil>         filename="kustomize/kustomize.go:183"
WARN[0016] Will retry in 13 seconds. 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4417)
> Fix: error isn't logged before retry

- prow_config.yaml
- py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
the basic auth flag is now in gcp plugin
for https://github.com/kubeflow/testing/issues/507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4420)
> Fix postsubmit/periodic basic auth test

- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/app/api_workgroup_test.ts
- Fixes issue by giving /exists a hasWorkgroup condition for non-identity cluster
/priority p0
/cc @prodonjs @jlewi @krishnadurai
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4425)
> Add a `hasWorkgroup` condition for `/api/workgroup/exists` when in Non-Identity Clusters

- py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
* When triggering tests on kubeflow/manifests we need to modify the
KFDef spec to change the URI of the kubeflow/manifests repo in the
KFDef spec.
* There was a bug in the code where we were checking the URI to decide
whether to override it or not. This code assumed we were on the master
branch so presubmits on the kubeflow/manifests v0.7-branch weren't using
the correct commit.
* This change fixes this PR to properly set repos in the KFDef when
triggering on kubeflow/manifests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4416)
> Fix bug preventing presubmits on kubeflow/manifests branches from using correct commit of kubeflow/manifests

- bootstrap/pkg/kfapp/gcp/gcp.go
- bootstrap/pkg/kfapp/gcp/gcp_plugin.go
- bootstrap/pkg/kfapp/gcp/gcp_plugin_test.go
related to https://github.com/kubeflow/kubeflow/issues/4421
needs cherry-pick later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4436)
> Add a check if hostname is too long for GCP endpoint

- bootstrap/cmd/kfctl/cmd/apply.go
Some steps in `kfctl apply` output warning messages, which confuses the user whether `apply` succeeds or not.
This PR adds a message to make it clear.
Related to: #4414 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4443)
> Add a message after kfctl apply succeeds

- bootstrap/pkg/apis/apps/configconverters/testdata/kfconfig_v1beta1.yaml
- bootstrap/pkg/apis/apps/configconverters/testdata/v1beta1.yaml
- bootstrap/pkg/apis/apps/configconverters/v1beta1.go
- bootstrap/pkg/apis/apps/configconverters/v1beta1_test.go
- bootstrap/pkg/apis/apps/kfconfig/types.go
- bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go
- bootstrap/pkg/kfapp/gcp/gcp.go
#4439 
Makes suggested changes in https://github.com/kubeflow/kubeflow/issues/4439#issuecomment-548375713
- Use EnvSource instead of HashSource for secrets
- fix Json name for env secret name 
- remove literal secret from yaml file
- Change `buildBasicAuth` encode the plain text secret to base64
Testing:
- `kfctl apply -f https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_gcp_basic_auth.0.7.0.yaml` works.
- second run `kfctl apply` with generated local yaml works too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4444)
> Store secrets using EnvSource for basic auth

- components/notebook-controller/Dockerfile
- components/profile-controller/Dockerfile
- components/tensorboard-controller/Dockerfile
Referencing [comment ](https://github.com/kubeflow/kubeflow/issues/2337#issuecomment-524690065)and issue [#2337](https://github.com/kubeflow/kubeflow/issues/2337)
We are working on Kubeflow supporting arm64 platform. We now rebuilt some images and installed Kubeflow on arm64, and hence contribute the Dockerfile.
including:
- notebook controller
- profile controller
- tensorboard controller
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4438)
> Add arm64 support for controllers

- bootstrap/pkg/kfapp/kustomize/kustomize.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4452)
> Automated cherry pick of #4417: Fix: error isn't logged before retry Cherry pick of #4417 on v0.7-branch. #4417: Fix: error isn't logged before retry

- components/centraldashboard/Dockerfile
Referencing [comment ](https://github.com/kubeflow/kubeflow/issues/2337#issuecomment-524690065)and issue [#2337](https://github.com/kubeflow/kubeflow/issues/2337)
We are working on Kubeflow supporting arm64 platform. We now rebuilt some images and installed Kubeflow on arm64, and hence contribute the Dockerfile.
1. Add arm64 support for centraldashboard, tested on both arm64 and x86_64 machines.
2. Refer to [issue](https://github.com/Zenika/alpine-chrome/issues/39), fix chromium@edge version cannot start bug.
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4422)
> Add arm64 support for centraldashboard and Fix chromium@edge version cannot start bug

- testing/kfctl/endpoint_ready_test.py
* We are already skipping the test in presubmits
* using xfail prevents the results from showing up in test grid and we'd like to see results in test grid.
Related: kubeflow/kfctl#42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4458)
> remove xfail for endpoint_is_ready test

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
Fixes #4446 
Switches to using `history.replaceState` to fix the issue of back-button/in-page navigation not working properly for KFP or Katib. 
[Screencast](https://screencast.googleplex.com/cast/NjIyMjQyODM2OTg0NjI3Mnw0M2VmOWU5ZS1lYw)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4454)
> Use replaceState instead of pushState to track iframe navigation

- prow_config.yaml
- py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Related: kubeflow/kfctl#71
- Use config_spec to access config info.
- Include `py/kubeflow/kubeflow/ci/*` to all E2E tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4459)
> Refactor kfctl_go_test_utils codes

- testing/gcp_util.py
Related: #4442
Needs to catch exception.  When endpoint is not ready, http raise exception instead of returning non-200 response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4475)
> catch http connection error when endpoint is not ready

- py/kubeflow/kubeflow/ci/kfctl_e2e_workflow.py
- py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py
Needs to point to kfctl repo instead of using kubeflow/kubeflow/bootstrap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4493)
> Fix KFCTL e2e test build path

- docs_dev/releasing.md
In the release procedures, split out the steps for updating version numbers in master website and creating a new website branch. Added a number of steps to the section on updating version numbers in various files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4489)
> Added website versioning steps to the release procedures

- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/main.go
This PR is a partial fix of https://github.com/kubeflow/kubeflow/issues/3772. The notebook-controller creates notebook events by propagating both StatefulSet and Pod events. The UI should fetch these events to determine the status of the notebook server (see complete discussion in the linked issue).
How `kubectl -n kubeflow get events --sort-by=.metadata.creationTimestamp` looks like for different scenarios.
**A. Happy path (pod can be scheduled)**
A.1 Notebook Server creation
```text
LAST SEEN   TYPE     REASON                  OBJECT                                          MESSAGE
7s          Normal   ProvisioningSucceeded   persistentvolumeclaim/workspace-everything-ok   Successfully provisioned volume pvc-7701080a-f089-485b-beef-e62b610bee81
7s          Normal   Provisioning …
```
> [3772][notebook-controller] Reissue pod and sts events as notebook events

- components/gcp-click-to-deploy/src/DeployForm.tsx
- components/gcp-click-to-deploy/src/Gapi.ts
* C2D v0.7: build kfdef obejct on backend side, frontend use new light-weighted request body: `C2Drequest` Related: https://github.com/kubeflow/kubeflow/pull/4399
* Add name length check for cert domain name length restriction
* Automate API enabling for `cloudresourcemanager.googleapis.com` and `iam.googleapis.com`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4487)
> C2D UI: add option for v0.7 and deprecate v0.5

- .github/workflows/triage_issues.yaml
Related to kubeflow/community#27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4526)
> Add a github action to add/remove issues from the needs triage Kanban board

- .github/workflows/triage_issues.yaml
* The name of the input containing the secret is GITHUB_PERSONAL_ACCESS_TOKEN
https://github.com/kubeflow/code-intelligence/blob/ea1e5995d7e9bc8e6326c1adf9c5149af2294ced/py/issue_triage/triage_for_action.py#L11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4531)
> Fix the GitHub action workflow to add issue triage issues

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
We are working on supporting multi user mode for pipelines in Kubeflow.
Show the selector so it becomes visible.
I would also want to add a "pipelines multi user" feature flag that can turn this on/off. Can someone point me to the right direction?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4518)
> Show namespace selector when choosing pipelines

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
- components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
This copies labels and annotations from the PodDefault's metadata field
to pods.
This closes #4502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4539)
> Add metadata field to PodDefaults

- components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
Closes #4547 
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4548)
> Use v1alpha1 for poddefaults instead of v1beta1

- components/jupyter-web-app/backend/Makefile
- components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
- components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
- components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
closes #2981 
With this PR Jupyter Web App will use k8s `SubjectAccessReviews` to check whether a user is authorized to perform an action on the k8s api server.
This PR should be merged after [manifests/655](https://github.com/kubeflow/manifests/pull/655) is merged, which gives permissions to JWA's ServiceAccount to use SubjectAccessReviews.
/cc @yanniszark 
/cc @kunmingg 
/cc @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4556)
> jupyter-web-app: Use SubjectAccessReviews instead of KFAM

- components/common/go.mod
- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/go.mod
- components/notebook-controller/go.sum
- components/tensorboard-controller/go.mod
- components/tensorboard-controller/go.sum
* The jupyter docker image isn't building because it now depends on code
in components/common
* To make this work we need to configure it as a multi module package
and modify go.mod to redirect to a local path.
* Ref: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
* Replaces PR #4583
Related to #4582 - Jupyter image doesn't build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4631)
> Fix notebook controller and tensorboard controller  docker image build.

- components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
closes #4069 
* For readiness the backend will need to be able to connect to the
k8s API
* For liveness the backend will only need to be able to respond to new
requests. Thus it will be only returning a 200 status code response
/cc @lluunn @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4626)
> JWA: Add readiness/liveness probes

- components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
Partial fix of https://github.com/kubeflow/kubeflow/issues/3772. Depends on https://github.com/kubeflow/kubeflow/pull/4139 (must be merged first).
https://github.com/kubeflow/kubeflow/pull/4139 reissues pod and sts events as notebook events. This is useful since some information is not present as sts or pod status, for example:
```
2s          Warning   FailedCreate            statefulset/test-nb-server                                       create Pod test-nb-server-0 in StatefulSet test-nb-server failed error: pods "test-nb-server-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
```
In the previous scenario, the sts status would only show `createdReplicas = 0`, which may very well be that the sts is waiting for the pod …
> [3772][jupyter-web-app] Surface notebook events as extra information

- components/access-management/Dockerfile
`hashicorp/golang-lru` is licensed under the Mozilla Public License.
Add it's source code under kfam image `third_party/library`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4640)
> add hashicorp/golang-lru source code to kfam image

- components/jupyter-web-app/backend/Makefile
- components/jupyter-web-app/backend/kubeflow_jupyter/common/auth.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/base_app.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/settings.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml
- components/jupyter-web-app/backend/kubeflow_jupyter/default/app.py
- components/jupyter-web-app/backend/kubeflow_jupyter/rok/app.py
- components/jupyter-web-app/backend/main.py
- components/jupyter-web-app/frontend/.prettierrc
- components/jupyter-web-app/frontend/package.json
- components/jupyter-web-app/frontend/src/app/app.module.ts
- components/jupyter-web-app/frontend/src/app/resource-form/form-advanced-options/form-advanced-options.component.html
- components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.html
- components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.scss
- components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.spec.ts
- components/jupyter-web-app/frontend/src/app/resource-form/form-gpus/form-gpus.component.ts
- components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.html
- components/jupyter-web-app/frontend/src/app/utils/common.ts
- components/jupyter-web-app/frontend/src/app/utils/types.ts
closes #4288 
Instead of having an `Extra Resources` field we allow the user to select the number and vendor of GPUs for a Notebook.
/cc @lluunn 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4614)
> Jupyter-Web-App: Support for selecting GPUs

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/namespace-selector.js
- components/centraldashboard/public/components/namespace-selector_test.js
This PR introduces a validation layer into the namespace selector (anytime namespaces or selected is changed):
- Defaulting logic added for Namespace selector:
- If namespace selected is valid, keep
- If there is an owned namespace, use that
- If not, go for `kubeflow` if available
- If not, leave unselected
- Invalidate a namespace that's not part of `namespaces` and use the logic defined above
/priority p1
/cc @kwasi @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4659)
> [CentralDashboard] Namespace defaulting and validation

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
Fix for my broken implementation in #4539 /cc @jlewi 
Before we used the annotations/labels from PodDefaults's embedded
ObjectMeta instead of the correct Annotations/Labels field of the
PodDefaultSpec.
This also adds tests for the (SafeTo)ApplyPodDefaultsOnPod function to
that uncovered the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4544)
> Fix annotation/label injection in admission hook

- components/profile-controller/Dockerfile
- components/profile-controller/controllers/moniotring.go
- components/profile-controller/controllers/profile_controller.go
requestCounter:
normal reconcile count with tags: `COMPONENT, KIND`
requestErrorCounter:
failed reconcile count with tags: `COMPONENT, KIND, SEVERITY`
serviceHeartbeat:
counter that increase value by 1 every 10 seconds, indicating controller is alive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4676)
> add prometheus metrics for profile controller

- components/profile-controller/controllers/moniotring.go
- components/profile-controller/go.mod
Profile controller metrics registry should use controller-runtime metrics registry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4683)
> use controller runtime metrics registry

- components/jupyter-web-app/backend/kubeflow_jupyter/common/api.py
* Events are cluster scoped resources. Users are only granted access
to specific namespaces though.
* So we can't do a subject access review check for events.
* Should fix kubeflow/kubeflow#4699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4710)
> Remove authorization check for events (kubeflow/kubeflow#4699)

- components/centraldashboard/app/server.ts
**_update for #4718_**
This PR introduces a `/healthz` route to the dashboard to allow scripts to probe Central-Dash for liveness.
/priority p0
/cc @kwasi @jlewi @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4722)
> [CentralDashboard] Added a root level `healthz` api call for liveness checks.

- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
Jupyter UI should show the event's message for any `WARNING` event. The UI should not display an error ❌ next to the affected notebook since it is difficult to distinguish which of these errors are temporary.
Related to: #4705
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4729)
> Jupyter displays Warn event message when hover over the spinner

- docs_dev/releasing.md
* The big change is that we instead of creating new Netlify sites
for each version of the website we will take advantage of Netlify's
ability to automatically deploy branches.
* Using branch deploys has two many advantages
1. Managing multiple Netlify sites is an administrative challenge.
* In particular, when the new site is created the creator needs to
ensure they create it under the kubeflow-team otherwise it will
be private to them.
* This has not been happening. Only the v0.5 and www.kubeflow.org sites
are currently under the kubeflow-team in Netlify.
* We have no easy way to track down the owner of the individual sites
or gain access if they are unavailable
2. Using branch deploys should be much simpler than setting up a new
Netlify site.
* In addition we can take advantage of …
> Update the documentation for how to publish/release the website.

- components/profile-controller/controllers/plugin_workload_identity.go
- components/profile-controller/controllers/profile_controller_test.go
This PR is trying to address https://github.com/kubeflow/kubeflow/issues/4749. @kunmingg 
We can use the project id from the default credentials for the identity namespace when we config the workload identity. This is more reliable than using the project id from the user sa, which can be in a different gcp project.  
Please let me know if this makes sense. I'm happy to help fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4754)
> Use project id from the default credentials for identity namesapce

- docs/gke/tf_serving_iap.md
This is part of fix for [website issue #240](https://github.com/kubeflow/website/issues/240).
The content in the [kubeflow repo](https://github.com/kubeflow/kubeflow/blob/430d4f7ae16af389ac570182af519f6571f160cf/docs/gke/tf_serving_iap.md) is removed and link to[ website doc](https://www.kubeflow.org/docs/components/serving/tfserving_new/#sending-prediction-request-through-ingress-and-iap) instead.
/cc @sarahmaddox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4760)
> Move info about IAP and TFServing to the docs website

- components/tensorflow-notebook-image/Dockerfile
Updates the Dockerfile for the TF notebook images to install Fairing from PyPI, instead of installing Fairing v0.5 from a GitHub commit.
This change fixes [Kubeflow/Kubeflow #4551](https://github.com/kubeflow/kubeflow/issues/4551).
This change should help fix:
-  [Kubeflow/Website #1428](https://github.com/kubeflow/website/issues/1428)
-  [Kubeflow/Fairing #381](https://github.com/kubeflow/fairing/issues/381): This issue describes that they couldn't run the Kubeflow Notebook example because the notebook was running an old release of Fairing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4645)
> Updates to install Fairing from PyPI

- components/notebook-controller/README.md
- components/notebook-controller/controllers/notebook_controller.go
Allowing for an env var ADD_FSGROUP to be set to false to suppress the automatic addition of fsGroup: 100 in the pod's security context.
If the env var is not specified or set to true, the current behaviour will be unchanged.
This addresses issue #4617.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4713)
> Adding env var to suppress automatic additon of fsGroup in notebook pod

- components/notebook-controller/loadtest/jupyter_pvc.yaml
- components/notebook-controller/loadtest/jupyter_test.yaml
- components/notebook-controller/loadtest/start_notebooks.py
Fixes #4019
Add a Python script & crd templates for starting load test for notebook controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4779)
> Add load test for notebook controller

- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/controllers/notebook_controller_test.go
Related to #4776
@jlewi should we close #4776 when this is merged, or wait for the manifests as well?
This PR fixes event filtering/reconciling for the notebook controller.
- Add check to avoid crashing if the notebook name doesn't contain a dash ("-").
- Fix reconciliation based on events.
/cc @jlewi @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4777)
> Fix notebook controller event filtering

- README.md
According to @jlewi this is the preferred way to check which PR needs attention, so I think there should be a link to it in the README.
For reference: https://github.com/kubeflow/kubeflow/pull/4544#issuecomment-576803193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4785)
> README.md: Add Link to PR dashboard

- components/centraldashboard/public/components/dashboard-view.js
In latest release Katib, Katib had renamed `StudyJob` to `Experiment`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4669)
> Fix dashboard wrong katib hyperlink name

- components/tensorflow-notebook-image/Dockerfile
This pull requests adds the Azure CLI to the Tensorflow Jupyter Image per the official instructions at:
https://docs.microsoft.com/cli/azure/install-azure-cli-linux?view=azure-cli-latest
The Tensorflow Jupyter Image currently contains the GCP, AWS CLIs. Just like the AWS CLI the Azure CLI is not a precompiled standalone binary and therefore needs to be installed in the Docker image itself.
For some context why this CLI is needed see my MNIST Azure E2E example. Currently to complete this tutorial one has to switch back and forth between local terminal and Kubeflow environment, manually copying values back and forth. I would like to reduce friction for Kubeflow users on Azure.
https://github.com/kubeflow/examples/tree/master/mnist#azure
See also this discussion: …
> Add the Azure CLI to Tensorflow Jupyter Image

- bootstrap/developer_guide.md
New to kubeflow but I hope I will help in improving and contributing whenever I can.
The fix in this PR is to rectify the `https` git clone link, with `:` in url it will fail the clone with message like this: `'https://github.com:kubeflow/kubeflow/': URL using bad/illegal format or missing URL` 
* Fix is to rectify the https url to this; `https://github.com/kubeflow/kubeflow`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4814)
> Fix the kubeflow git link for clone.

- components/profile-controller/Dockerfile
- components/profile-controller/skaffold.yaml
* The profile kustomize deployments rely on a brittle pattern for
substitution in parameters into the command line.
https://github.com/kubeflow/manifests/blob/9e6ef8681003c195560fb7b3b75211830c19b7a0/profiles/base/deployment.yaml#L16
* The current pattern is to define kustomize vars and a custom
configuration (https://github.com/kubeflow/manifests/blob/master/profiles/base/params.yaml) that does substitution of specific containers and their arguments
based on position.
* A much better pattern is to
* Define environment variables based on a configmap
* Run the command via a shell that can evaluate the environment variables.
* To do that we need to put a shell into the container since the distroless
images don't have one.
* We pick the dash shell. It is a little lighter weight then bash and …
> Add dash (a shell) the profile-controller docker image.

- components/tensorflow-notebook-image/Dockerfile
Issue #4878 mentions that we want to add `$HOME/.local/bin` into `PATH`. Thus, we don't have to explicitly use `$HOME/.local/bin/cmd` to invoke the cmd located in the `$HOME/.local/bin`.
I add a `ENV` layer in the `DockerFile` of `tensorflow-notebook-image` for this functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4879)
> Add $HOME/.local/bin into PATH

- components/centraldashboard/public/components/registration-page.js
There should be no delay in registration flow retry if an error comes back early. This PR fixes that
/priority p1
/cc @kwasi @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4662)
> [CentralDashboard] Registration flow onError delay removed

- components/access-management/Dockerfile
- components/admission-webhook/Dockerfile
This commit adds container building support for ingress_setup, kfam, and admission_webhook on arm64.
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
> Enable kfam, admission_webhook on arm64

- docs_dev/releasing.md
This needs to be `gcloud auth login` to open the browser automatically for authentication as mentioned in the instruction.
> Add missing `login` command for gcloud authentication

- components/access-management/kfam/bindings.go
- components/access-management/kfam/bindings_test.go
Updating the getBindingName to not ignore the digits in the email while creating a binding name. This is my first ever pull request. Apologies for lot of spaces with no real changes in the file.
```go
//getBindingName returns bindingName, which is combination of user kind, username, RoleRef kind, RoleRef name.
func getBindingName(binding *Binding) (string, error) {
// Only keep lower case letters, replace other with -
reg, err := regexp.Compile("[^a-z0-9]+")
if err != nil {
return "", err
}
nameRaw := strings.ToLower(
strings.Join([]string{
binding.User.Kind,
url.QueryEscape(reg.ReplaceAllString(binding.User.Name, "-")),
binding.RoleRef.Kind,
binding.RoleRef.Name,
}, "-"),
)
return reg.ReplaceAllString(nameRaw, "-"), nil
}
```
> Pr/email escape (issue 4970)

- components/access-management/OWNERS
Adding `yanniszark` to access-management, profile-controller components.
I am familiar with the codebase and they are also directly related with the multi-user cuj, which I'm very familiar with.
This way, I can be of help to people contributing fixes to these components.
/cc @jlewi 
> Add yanniszark to access-management, profile-controller

- components/gcp-click-to-deploy/src/DeployForm.tsx
fix https://github.com/kubeflow/kubeflow/issues/4921
Print out original error message from GCP API as error title.
> print orignial error when failed enabling GCP APIs

- components/jupyter-web-app/frontend/src/app/resource-form/resource-form.component.ts
- components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.html
- components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.ts
- components/jupyter-web-app/frontend/src/app/uis/rok/utils/common.ts
- components/jupyter-web-app/frontend/src/app/utils/common.ts
- components/jupyter-web-app/frontend/src/app/utils/types.ts
closes #4906 
Right now the UI will completely ignore the `class` field of a volume in
the config received from the backend.
We want the UI to:
* Respect that field from the config
* Disable the `New` option in the volume type if
a. The volume class is `{none}` (default SC) and
b. No default storage class is set in the cluster
Else the UI should allow the user to create a new volume and the UI will
use the storage class received from the config.
/cc @avdaredevil 
/cc @kunmingg 
> JWA: Fix UI handling of default StorageClass

- components/notebook-controller/controllers/notebook_controller.go
[make manifest](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/Makefile#L48) for `notebook-controller` doesn't seem to generate the rbac files as described [here](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L75). Adding a new line after the gen markers seems to solve this problem!
> Fix notebook controller rbac gen

- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/app/api_workgroup_test.ts
- components/centraldashboard/app/server.ts
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
This PR will address issue: https://github.com/kubeflow/kubeflow/issues/4889
**Description:**
The modification of this PR only take effect when we set REGISTRATION_FLOW = "false", which will disable the namespace creation when a new user is authenticated. 
**Internal Tests:**
I've tested this on our dev cluster with Istio + Dex 1.0.2, on the following scenarios: 
- REGISTRATION_FLOW = "false" - New users are not given a registration flow
- REGISTRATION_FLOW = "falser" - New users are  not given a registration flow
- REGISTRATION_FLOW = "true" - New users are given a registration flow
- REGISTRATION_FLOWS = "false" - New users are given a registration flow
**How this is intended to be used:**
- Admins that disable the registration flow will need to manage the registration and contributors …
> env variable driven registrationFlow

- components/notebook-controller/controllers/notebook_controller.go
This PR allows passing through a clusterDomain via an environment variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4468)
> notebook_controller.go: make clusterDomain an option

- testing/kfctl/conftest.py
It is more intuitive not to use else in Early Return Pattern. Thank you.
> Refactoring: Early Return Pattenr (if else -> if return)

- CONTRIBUTING.md
Similar vain as: https://github.com/kubeflow/community/pull/185
Following the link from the `k8s-ci-robot` suggesting to join the community links (see https://github.com/kubeflow/pipelines/pull/4228#issuecomment-659685533) to this page but this page doesn't actually have any instructions on how to join the community!
> Deduplicate contributing docs

- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
- components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.html
- components/jupyter-web-app/frontend/src/app/main-table/resource-table/resource-table.component.ts
- components/jupyter-web-app/frontend/src/app/utils/types.ts
- prow_config.yaml
Resolves issue #5073 
Current Notebook server dashboard displays CPU, Memory and Image name but not the GPUs used. Displaying GPUs used by notebook servers help avoid confusion with in a project team on whether the resources are still available to use. This pull request adds both GPUs as well as GPU tooltip.
Screenshot
> Added gpu details to the notebook server table

- components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.html
- components/jupyter-web-app/frontend/src/app/resource-form/volume/volume.component.ts
- prow_config.yaml
Resolves issue #4883 
This PR enhances two things
1. Shows all Existing PVCs in the profile as a dropdown while creating a new notebook server under both workspace / data volumes when type drop down selected as "Existing"
2. Hide Mode and Size form fields under volumes when selected existing PVCs so that its not confusing
Follow are the screenshots of before and after
**Before the fix**
**After the fix**
> show all existing PVCs as dropdown under volumes for a new notebook server

- components/centraldashboard/app/api.ts
- components/centraldashboard/app/k8s_service.ts
- components/centraldashboard/config/centraldashboard-links-config.yaml
- components/centraldashboard/public/components/dashboard-view.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
Related Issue #3576
This PR moves the central dashboard links to a dynamic config map in the `kubeflow` namespace.
> Rendering centraldashboard links from a configmap

- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
- components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml
Fix #4842 - issue was closed earlier, but not solved within Kubeflow repo by author
Sets CPU and memory limits of Notebooks equal to requests. This prevents
- out of memory problems due to over-provisioning
- users using more resources than they should
> Fix #4842 Pod resources limit

- components/centraldashboard/Dockerfile
When building current master branch central dashboard on arm64, error message `Segmentation fault (core dumped)` will occur. By bumping base image node version to 10.13, this error can be fixed.
I also tested this commit on x86_64 machine to make sure this will not break current x86_64 build.
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
> Bumping central dashboard node version to v12.18.3

- components/tensorboard-controller/OWNERS
We need to have an OWNERs file for the Tensorboard Controller
Since me, @elikatsis and @kandrio98 have taken an extensive look on the inner workings of the tensorboard controller, as part of the [GSoC Project](https://summerofcode.withgoogle.com/projects/#4660815581413376) , I'll add us to this file. 
@jlewi @quanjielin please take a look and tell me if the proposed roles are OK with you.
/cc @jlewi @quanjielin 
> Add OWNERs file to tensorboard controller

- components/crud-web-apps/common/README.md
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/custom_resource.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/namespace.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/poddefault.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/secret.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/storageclass.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/utils.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/config.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/decorators.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/handlers.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/errors/utils.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/probes.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/requirements.txt
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/rok/routes.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/routes/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/routes/get.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/serving.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/status.py
- components/crud-web-apps/common/backend/setup.py
Right now JWA's backend is written in Python Flask. We also have the [Tensorboards web app](https://github.com/kubeflow/kubeflow/issues/3578) whose backend will also be written in Python and Flask. Lastly, the [Volumes web app](https://github.com/kubeflow/kubeflow/issues/4758), that we'd like to contribute, will be also written with the same technologies.
I think it would be a good next step to create a common python codebase/library that all these apps could use, at some extend. This common code will include:
* How we handle exceptions in the backend
* Common routes for serving static files and their cache control policy
* Authorization checks with SubjectAccessReview
* Authentication checks on the Kubeflow headers
* Common helper functions for dates, yaml parsing etc
* health/liveness …
> Common code between the different python backends

- components/jupyter-web-app/backend/kubeflow_jupyter/common/utils.py
- components/jupyter-web-app/frontend/src/app/uis/rok/rok-resource-form/rok-jupyter-lab-selector/rok-jupyter-lab-selector.component.ts
See: #5111 
It trims the whitespace around custom images to avoid pod creation failures. It does so in the backend and Rok template, where `customImage` is explicitly set.
---
Note: I tried running both the frontend and backend on my own machine but could not make it work. Perhaps the instructions for npm and Flask are outdated. I ran Flask in a fresh virtual environment.
NPM:
```
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
v8::String::Utf8Value string(value);
^      ~~~~~
```
Flask:
```
2020-07-07 13:43:47,944 | kubeflow_jupyter.default.app | INFO | Sending file 'index.html'
127.0.0.1 - - [07/Jul/2020 13:43:47] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
File …
```
> Fix #5111: Trim whitespace from custom images

- docs_dev/releasing.md
Adds step to release guide that instructs how to run the script that will add the outdated banner to documentation that hasn't been recently updated.
> Add step for outdated banner to release guide

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/helpers.py
- components/crud-web-apps/tensorboards/backend/Makefile
- components/crud-web-apps/tensorboards/backend/app/__init__.py
- components/crud-web-apps/tensorboards/backend/app/routes/__init__.py
- components/crud-web-apps/tensorboards/backend/app/routes/delete.py
- components/crud-web-apps/tensorboards/backend/app/routes/get.py
- components/crud-web-apps/tensorboards/backend/app/routes/post.py
- components/crud-web-apps/tensorboards/backend/app/utils.py
- components/crud-web-apps/tensorboards/backend/entrypoint.py
This PR contains the code for the Tensorboard web-app backend, which includes routes for `GET`, `POST` and `DELETE` requests.
This is actually part of my [GSoC-2020 project](https://summerofcode.withgoogle.com/projects/#4660815581413376).
The backend is created with Python/Flask, so it also uses the common code from `kubeflow.kubeflow.crud_backend`.
As a result, this PR should be merged after [#5164](https://github.com/kubeflow/kubeflow/pull/5164).
/cc @jlewi @kimwnasptd @elikatsis 
> tensorboard web-app: Create Tensorboard web-app backend

- components/admission-webhook/OWNERS
Fixes https://github.com/kubeflow/kubeflow/issues/5220
Add an OWNERS file for the PodDefaults admission webhook.
/cc @jlewi @discordianfish 
> poddefaults: Add OWNERS file

- components/tensorboard-controller/controllers/tensorboard_controller.go
- components/tensorboard-controller/main.go
closes #5039
The added scheduling feature is disabled by default. 
It is enabled only if the `RWO_PVC_SCHEDULING` env var is set to `true` when running the Tensorboard controller.
/cc @jlewi @kimwnasptd @elikatsis
> Tensorboard controller: Add scheduling functionality for Tensorboard servers that use RWO PVCs as log storages

- components/tensorboard-controller/README.md
- components/tensorboard-controller/config/manager/manager.yaml
This is part of my [GSoC-2020 project](https://summerofcode.withgoogle.com/projects/#4660815581413376). 
The value of the `RWO_PVC_SCHEDULING` env var is set to "false", so the scheduling functionality will be set to off by default.
This PR also contains an update to the README.md file of the Tensorboard controller.
/cc @kimwnasptd @elikatsis
> Add RWO_PVC_SCHEDULING env var to the Tensorboard Controller deployment

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
- components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
I want to add tolerations to the pods for my Jupyter server.
I am able to inject other things like Labels and Annotations,
this would allow me to also use PodDefault to inject tolerations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/4852)
> Add Tolerations to PodDefault

- components/notebook-controller/main.go
The default leader election  ID is `controller-leader-election-helper` which could conflict when multiple controllers run within the same namespace. This is a required field in later versions of controller-runtime.
More details on this https://github.com/kubernetes-sigs/controller-runtime/pull/446
> Fixes the default leader election ID

- components/profile-controller/controllers/profile_controller.go
We have strict RBAC authorization enabled by default for all user traffic. This gives problems when a user deploys an app or database in their namespace. Connections will be terminated due to missing authorization (in our case a valid JWT).
We would like to make an exception for traffic in the user's own namespace, which the following property takes care of.
> Allow intra namespace traffic by default

- components/access-management/OWNERS
- components/admission-webhook/OWNERS
- components/centraldashboard/OWNERS
- components/jupyter-web-app/OWNERS
- components/profile-controller/OWNERS
- components/tensorflow-notebook-image/OWNERS
Update OWNERS files for subprojects that belong to `wg-notebooks` and add relevant people to each subproject's OWNERS files.
/cc @kimwnasptd @StefanoFioravanzo @elikatsis @thesuperzapper @jlewi
> wg-notebooks: Update OWNERS files

- components/profile-controller/main.go
The default leader election ID is `controller-leader-election-helper` which could conflict when multiple controllers run within the same namespace. This is a required field in later versions of controller-runtime.
More details on this kubernetes-sigs/controller-runtime#446
Similar to https://github.com/kubeflow/kubeflow/pull/5374
> Fixes the leader election ID

- components/centraldashboard/README.md
The current README for local development environment of the central dashboard misses the reverse proxy part. See #5347 and #4482.
> Fix development README for central dashboard

- components/centraldashboard/config/centraldashboard-links-config.yaml
There's a discussion that metadata HTTP deployment and UI will be deprecated. Instead, KFP team will enhance inside KFP page and we don't need two UIs.
/cc @Bobgy @PatrickXYS @jlewi 
https://github.com/kubeflow/metadata/issues/250
https://github.com/kubeflow/manifests/pull/1638
> Remove metadata link from centraldashboard

- components/notebook-controller/go.mod
Makes the notebook controller API importable for 3rd party applications. 
See #5308
> Use valid commit for kubeflow/components/common module.

- components/centraldashboard/OWNERS
Add @yanniszark and remove @avdaredevil , @prodonjs, and @swiftdiaries from the approvers list of the OWNERS file to reflect the recent formation of the Notebooks Working Group, and the fact that Centraldashboard is part of the Notebooks WG going forward.
https://github.com/kubeflow/community/blob/master/wg-notebooks/
For reference, the above is stated in the [charter](https://github.com/kubeflow/community/blob/master/wg-notebooks/charter.md#in-scope) of the WG.
> Centraldashboard: Clean up OWNERS file

- components/centraldashboard/app/api.ts
- components/centraldashboard/app/k8s_service.ts
- components/centraldashboard/config/centraldashboard-config.yaml
- components/centraldashboard/public/library.js
**Problem statement**:
Centraldashboard provides a shared JS library that Kubeflow apps can use
to get the selected namespace. This PR extends this shared lib by allowing
apps to redirect themselves under a Centraldashboard iFrame, if they are
not iFramed. This is particularly useful when one open a KF app link in a
new tab, thus losing the `/_/` iFrame prefix and consequently not seeing
anymore the Centraldashboard sidebar.
**Solution**:
* Implement a new `dashboard-settings` API which returns the `settings`
field of the Centraldashboard ConfigMap.
* Extend the shared lib to call the settings endpoint if the app
is not iFramed. If `DASHBOARD_FORCE_IFRAME` in the settings is set to
`true`, then redirect the app under the `/_/` prefix.
* An app can opt out from the global config by setting …
> centraldashboard: redirect non-iframed apps

- components/crud-web-apps/common/README.md
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/__init__.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/csrf.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/serving.py
closes #5461
This is the backend PR. In order to fully close the issue we also need to merge #5463 
I also added some small changes wrt:
* parsing strings. We should gradually move away from `f"strings"` 
* allow the backend to skip the Subject Access Review check in some cases
> web-apps(back): Add CSRF protection mechanisms to the backends

- components/notebook-controller/controllers/notebook_controller.go
The Notebook Controller doesn't set the `ContainerState` of the CR correctly. In some cases the first container is the istio-sidecar which results in an incorrect state being shown to the Notebook CR. This is fixed now by showing the `ContainerState` of Notebook container to the Notebook CR `ContainerState`. 
The Notebook container is selected by matching with [the name of the notebook](https://github.com/kubeflow/kubeflow/blob/7f5e242f4671f453eaee72e4319a5f7f190f7725/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/notebook.yaml#L14). A warning is logged in case no container is found.
This PR fixes #5282.
> Correct ContainerStatus of Notebook CR

- components/notebook-controller/Dockerfile
- components/notebook-controller/Makefile
- components/notebook-controller/README.md
- components/notebook-controller/go.mod
The `go`  compiler `1.12` and `1.11` are no more supported.  
>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).
https://golang.org/doc/devel/release.html
Go also guarantees backward compatibility https://golang.org/doc/go1compat
> Upgrading the `go` compiler version.

- components/centraldashboard/public/components/dashboard-view.js
- components/centraldashboard/public/components/dashboard-view.pug
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/pipelines-card.js
- components/centraldashboard/public/components/pipelines-card_test.js
This PR improves and fixes how Centraldashabord handles namespace selection:
- Correctly track the selected namespace when it is changed in the namespace select box
- Use the tracked namespace in the homepage cards
- Call Kubeflow Pipelines API using the namespace filter
Closes #5484
/cc @StefanoFioravanzo
> Centraldashbaord: Fix namespace navigation

- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
closes #5529 
This PR a sibling of #5528. The Tensorboards web app's frontend will also need this type definition in order to build.
/cc @DavidSpek 
/cc @kandrio 
> twa(front): Fix the type issue with table config

- components/crud-web-apps/jupyter/Dockerfile
- components/crud-web-apps/tensorboards/Dockerfile
The docs specify that the crud-web-apps use node 12 in multiple places. However, the Dockerfiles use node 10 for the build. This PR updates the Dockerfiles to use node 12
> Use node:12 as specified in the docs

- components/crud-web-apps/jupyter/Dockerfile
- components/crud-web-apps/tensorboards/Dockerfile
Closes: https://github.com/kubeflow/kubeflow/issues/5552
Reduced the image size of the JWA from 928 MB to 163 MB. Similarly, the TWA image is now 162 MB.
> Move JWA python images to slim-buster

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/routes/get.py
- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/details-list/details-list-item/details-list-item.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/step-info/step-info.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/step-info/step-info.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/step-info/step-info.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/step-info/step-info.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/submit-bar/submit-bar.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/submit-bar/submit-bar.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/submit-bar/submit-bar.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/submit-bar/submit-bar.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/types.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/utils/kubernetes.model.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/variables.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
This PR introduces various fixes into both the common frontend and backend code. 
Since there are a lot of small ones I didn't create separate issues for each one of them, but here's a list of what's included:
Backend:
* Allow backend to skip authz checks when listing Pods
* Add ability to fetch pod logs
* Correctly calculate the default storage class
Frontend:
* Global SCSS classes for common types
* Export common modules to be used from the apps without requiring explicit imports
* Make the backgrounds of the apps white, and not grey due to CentralDashboard
* Move the toolbar buttons to the right, like the Pipelines UI
* Create a component for showing explanatory text. This will be useful for forms
* Create a component for a bottom bar for submitting CRs in forms
The bulk of the code is …
> web-apps: Fixes to the common code

- components/OWNERS
In this PR I add the [tech leads](https://github.com/kubeflow/community/blob/master/wgs.yaml#L232-L245) from the Notebook WG as owners of the `components` directory since it contains the source code from artifacts owned by the Notebooks WG.
/cc @Bobgy
> Add Notebooks WG leads as owners of components

- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/karma.conf.js
A first stop for adding a presubmit #5482 job for running unit tests in the common front end code.
The presubmit tests will run inside a container, as an Argo task/step. In order to run the tests inside a container, without any interactions, we will need to make the following changes:
1. Run a headless version of Chrome, to run the tests
2. Don't run the testing process, `ng test`, in watch mode. By default watch mode is on, in order for the process to track changes and run the tests while code is modified.
With the above changes we can run the tests of the common frontend code by navigating to the frontent code, where the `package.json` lives, and running:
```bash
docker run --rm -t \
-v $(pwd):/mnt/project \
--user 1000:1000 \
--workdir /mnt/project \
-e NG_CLI_ANALYTICS='false' \ …
```
> web-apps(front): Make the library tests run in CI

- py/OWNERS
Create an initial OWNERS file for the `testing` dir. Adding myself and @PatrickXYS for now since we are actively working on it for now. 
/cc @Bobgy 
> Add initial owners for testing dir

- py/kubeflow/kubeflow/ci/Makefile
- py/kubeflow/kubeflow/ci/shared_ui_tests.py
- py/kubeflow/kubeflow/ci/shared_ui_tests_runner.py
- py/kubeflow/kubeflow/ci/workflow_utils.py
A first Argo Worflow generator script which can be used as a Prow presubmit Job. This is a first step for #5482.
This workflow runs two basic tests on the common frontend code:
1. it runs it's unittests #5564 
2. checks if the npm module, from the common code, can be build
@PatrickXYS since the [run_e2e_workflow.py](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py#L232) imports the pythonpaths from the workflow jobs, defined in the `prow_config.yaml`, I made all the imports in my code to use packages like `kubeflow.testing` and `kubeflow.kubeflow.ci` [and no relative imports].
I also defined a file with common code, since some of this logic will be needed for future workflows. Again I think we shouldn't have a problem with imports but please take a …
> Add initial python files for CI

- .github/ISSUE_TEMPLATE/config.yml
**What issue it solves**
Help https://github.com/kubeflow/community/issues/476
**What change it makes**
Add redirection links to kubeflow application repos which are sponsored by WG. 
When users create an issue in kubeflow/kubeflow, they will be able to be redirected to disired repo and create issue there.
/cc @Bobgy @kubeflow/wg-notebooks-leads
> Add redirection links to kubeflow app repo

- components/notebook-controller/config/base/cluster-role-binding.yaml
- components/notebook-controller/config/base/cluster-role.yaml
- components/notebook-controller/config/base/crd.yaml
- components/notebook-controller/config/base/deployment.yaml
- components/notebook-controller/config/base/deployment_patch.yaml
- components/notebook-controller/config/base/kustomization.yaml
- components/notebook-controller/config/base/params.env
- components/notebook-controller/config/base/service-account.yaml
- components/notebook-controller/config/base/service.yaml
- components/notebook-controller/config/base_v3/deployment_patch.yaml
- components/notebook-controller/config/base_v3/kustomization.yaml
- components/notebook-controller/config/overlays/application/application.yaml
- components/notebook-controller/config/overlays/application/kustomization.yaml
- components/notebook-controller/config/overlays/istio/deployment.yaml
- components/notebook-controller/config/overlays/istio/kustomization.yaml
- components/notebook-controller/config/overlays/istio/params.env
Resolves: https://github.com/kubeflow/kubeflow/issues/5592
This PR copies the manifests for application `Notebook Controller`
from path `apps/jupyter/notebook-controller/upstream` of kubeflow/manifests to path
`components/notebook-controller/config` of the upstream repo (https://github.com/kubeflow/kubeflow).
> Notebook Controller: Move manifests development upstream

- prow_config.yaml
As part of setting up our CI/CD #5482 we want to extend the prow config to also run the unittests of the shared ui as a presubmit job.
/cc @PatrickXYS
> Include workflow for ui lib unittests

- prow_config.yaml
- py/kubeflow/kubeflow/ci/Makefile
- py/kubeflow/kubeflow/ci/common_ui_tests.py
- py/kubeflow/kubeflow/ci/common_ui_tests_runner.py
- py/kubeflow/kubeflow/ci/shared_ui_tests.py
right now the PR's tests fail, for the common code, because the name of the workflow is not DNS1123 compatible 
https://github.com/kubeflow/kubeflow/pull/5642#issuecomment-786877663
This is needed to fix our CI tests #5482 
I'll use this PR to fix the test-case. I also introduced a test file just to trigger the tests. Once we ensure the CI works as expected then I'll push a commit to delete it
/cc @PatrickXYS
> CI: Correct the name of the workflow

- components/crud-web-apps/jupyter/Dockerfile
Closes: https://github.com/kubeflow/kubeflow/issues/5552
More specifically, this addresses the absence of `make` in the buster-slim version of the images. As described [here](https://github.com/kubeflow/kubeflow/issues/5552#issuecomment-769792232). 
> Fix entrypoint of crud-jwa

- components/centraldashboard/manifests/base/clusterrole-binding.yaml
- components/centraldashboard/manifests/base/clusterrole.yaml
- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/manifests/base/deployment_patch.yaml
- components/centraldashboard/manifests/base/kustomization.yaml
- components/centraldashboard/manifests/base/links-configmap.yaml
- components/centraldashboard/manifests/base/params.env
- components/centraldashboard/manifests/base/params.yaml
- components/centraldashboard/manifests/base/role-binding.yaml
- components/centraldashboard/manifests/base/role.yaml
- components/centraldashboard/manifests/base/service-account.yaml
- components/centraldashboard/manifests/base/service.yaml
- components/centraldashboard/manifests/base_v3/deployment_patch.yaml
- components/centraldashboard/manifests/base_v3/kustomization.yaml
- components/centraldashboard/manifests/overlays/application/application.yaml
- components/centraldashboard/manifests/overlays/application/kustomization.yaml
- components/centraldashboard/manifests/overlays/istio/kustomization.yaml
- components/centraldashboard/manifests/overlays/istio/params.yaml
- components/centraldashboard/manifests/overlays/istio/virtual-service.yaml
- components/centraldashboard/manifests/overlays/stacks/deployment_kf_config.yaml
- components/centraldashboard/manifests/overlays/stacks/kustomization.yaml
Resolves: https://github.com/kubeflow/kubeflow/issues/5594
This PR copies the manifests for application `Central Dashboard`
from path `apps/centraldashboard/upstream` of kubeflow/manifests to path
`components/centraldashboard/manifests` of the upstream repo (https://github.com/kubeflow/kubeflow).
> Central Dashboard: Move manifests development upstream

- components/admission-webhook/manifests/bootstrap/base/cluster-role-binding.yaml
- components/admission-webhook/manifests/bootstrap/base/cluster-role.yaml
- components/admission-webhook/manifests/bootstrap/base/config-map.yaml
- components/admission-webhook/manifests/bootstrap/base/kustomization.yaml
- components/admission-webhook/manifests/bootstrap/base/params.env
- components/admission-webhook/manifests/bootstrap/base/params.yaml
- components/admission-webhook/manifests/bootstrap/base/service-account.yaml
- components/admission-webhook/manifests/bootstrap/base/stateful-set.yaml
- components/admission-webhook/manifests/bootstrap/overlays/application/application.yaml
- components/admission-webhook/manifests/bootstrap/overlays/application/kustomization.yaml
- components/admission-webhook/manifests/webhook/base/cluster-role-binding.yaml
- components/admission-webhook/manifests/webhook/base/cluster-role.yaml
- components/admission-webhook/manifests/webhook/base/crd.yaml
- components/admission-webhook/manifests/webhook/base/deployment.yaml
- components/admission-webhook/manifests/webhook/base/kustomization.yaml
- components/admission-webhook/manifests/webhook/base/mutating-webhook-configuration.yaml
- components/admission-webhook/manifests/webhook/base/params.env
- components/admission-webhook/manifests/webhook/base/params.yaml
- components/admission-webhook/manifests/webhook/base/service-account.yaml
- components/admission-webhook/manifests/webhook/base/service.yaml
- components/admission-webhook/manifests/webhook/overlays/application/application.yaml
- components/admission-webhook/manifests/webhook/overlays/application/kustomization.yaml
- components/admission-webhook/manifests/webhook/overlays/cert-manager/certificate.yaml
- components/admission-webhook/manifests/webhook/overlays/cert-manager/deployment.yaml
- components/admission-webhook/manifests/webhook/overlays/cert-manager/kustomization.yaml
- components/admission-webhook/manifests/webhook/overlays/cert-manager/mutating-webhook-configuration.yaml
- components/admission-webhook/manifests/webhook/overlays/cert-manager/params.env
- components/admission-webhook/manifests/webhook/overlays/cert-manager/params.yaml
- components/admission-webhook/manifests/webhook/v3/kustomization.yaml
Resolves: https://github.com/kubeflow/kubeflow/issues/5596
This PR copies the manifests for application `PodDefaults Webhook`
from path `apps/admission-webhook/upstream` of kubeflow/manifests to path
`components/admission-webhook/manifests` of the upstream repo (https://github.com/kubeflow/kubeflow).
> PodDefaults Webhook: Move manifests development upstream

- components/profile-controller/config/base/README.md
- components/profile-controller/config/base/cluster-role-binding.yaml
- components/profile-controller/config/base/crd.yaml
- components/profile-controller/config/base/deployment.yaml
- components/profile-controller/config/base/kustomization.yaml
- components/profile-controller/config/base/params.env
- components/profile-controller/config/base/params.yaml
- components/profile-controller/config/base/service-account.yaml
- components/profile-controller/config/base/service.yaml
- components/profile-controller/config/base_v3/deployment_patch.yaml
- components/profile-controller/config/base_v3/kustomization.yaml
- components/profile-controller/config/overlays/application/application.yaml
- components/profile-controller/config/overlays/application/kustomization.yaml
- components/profile-controller/config/overlays/debug/deployment.yaml
- components/profile-controller/config/overlays/debug/kustomization.yaml
- components/profile-controller/config/overlays/debug/params.env
- components/profile-controller/config/overlays/debug/params.yaml
- components/profile-controller/config/overlays/devices/deployment.yaml
- components/profile-controller/config/overlays/devices/kustomization.yaml
- components/profile-controller/config/overlays/istio/kustomization.yaml
- components/profile-controller/config/overlays/istio/params.yaml
- components/profile-controller/config/overlays/istio/virtual-service.yaml
- components/profile-controller/config/overlays/test/app_test.yaml
- components/profile-controller/config/overlays/test/kustomization.yaml
Resolves: https://github.com/kubeflow/kubeflow/issues/5595
This PR copies the manifests for application `Profiles   KFAM`
from path `apps/profiles/upstream` of kubeflow/manifests to path
`components/profile-controller/config` of the upstream repo (https://github.com/kubeflow/kubeflow).
> Profiles   KFAM: Move manifests development upstream

- components/crud-web-apps/jupyter/manifests/base/cluster-role-binding.yaml
- components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/deployment.yaml
- components/crud-web-apps/jupyter/manifests/base/deployment_patch.yaml
- components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/base/params.env
- components/crud-web-apps/jupyter/manifests/base/params.yaml
- components/crud-web-apps/jupyter/manifests/base/role-binding.yaml
- components/crud-web-apps/jupyter/manifests/base/role.yaml
- components/crud-web-apps/jupyter/manifests/base/service-account.yaml
- components/crud-web-apps/jupyter/manifests/base/service.yaml
- components/crud-web-apps/jupyter/manifests/base_v3/deployment_patch.yaml
- components/crud-web-apps/jupyter/manifests/base_v3/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/overlays/application/application.yaml
- components/crud-web-apps/jupyter/manifests/overlays/application/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/overlays/aws/config-map.yaml
- components/crud-web-apps/jupyter/manifests/overlays/aws/deployment-aws-patch.yaml
- components/crud-web-apps/jupyter/manifests/overlays/aws/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/params.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/virtual-service.yaml
Resolves: https://github.com/kubeflow/kubeflow/issues/5593
This PR copies the manifests for application `Jupyter Web App`
from path `apps/jupyter/jupyter-web-app/upstream` of kubeflow/manifests to path
`components/jupyter-web-app/manifests` of the upstream repo (https://github.com/kubeflow/kubeflow).
> Jupyter Web App: Move manifests development upstream

- prow_config.yaml
- py/kubeflow/kubeflow/cd/Makefile
- py/kubeflow/kubeflow/cd/config.py
- py/kubeflow/kubeflow/cd/jwa.py
- py/kubeflow/kubeflow/cd/jwa_runner.py
- py/kubeflow/kubeflow/ci/__init__.py
- py/kubeflow/kubeflow/ci/workflow_utils.py
This is part of our effort to use the Optional-test infra for 1.3 going forward #5482 
This PR introduces the following assumptions:
1. The produced Argo Workflow will **not** try to push the produced image to a registry [ `--no-push` Kaniko arg] if the code is not run in the upstream AWS cluster [ `LOCAL_TESTING=True` env var ]. This will make it easier for more people to run the code in their Kubernetes cluster with Argo installed
2. We expect some workflows to not have an `exit dag`. This is the case for now at least, where the CD only builds our public images and pushes them to the registry
3. We will be using `gcr.io/kaniko-project/executor:v1.5.0`. This is a newer version from what's used from [KFServing](https://github.com/kubeflow/kfserving/blob/ec9e8ca569ea173de3717a41130e37cfb756 …
> First iteration and common utils for Jupyter web app CD

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
Currently, build & test fails on the admission webhook component.
```sh
$ make build
go build -gcflags 'all=-N -l' -o bin/webhook .
./main.go:120:25: cannot use &pd.Spec.Tolerations (type *[]"k8s.io/api/core/v1".Toleration) as type *"k8s.io/api/core/v1".Toleration in assignment
./main.go:128:40: cannot use defaultTolerations (type []*"k8s.io/api/core/v1".Toleration) as type []*v1alpha1.PodDefault in argument to mergeTolerations
./main.go:392:22: cannot use &pd.Spec.Tolerations (type *[]"k8s.io/api/core/v1".Toleration) as type []*"k8s.io/api/core/v1".Toleration in assignment
./main.go:406:47: cannot use defaultTolerations (type []*"k8s.io/api/core/v1".Toleration) as type []*v1alpha1.PodDefault in argument to mergeTolerations
Makefile:7: recipe for target 'build' failed
make: *** [build] …
```
> Fix build failure on admission webhook component

- components/tensorboard-controller/api/v1alpha1/tensorboard_types.go
- components/tensorboard-controller/api/v1alpha1/zz_generated.deepcopy.go
- components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
- components/tensorboard-controller/controllers/tensorboard_controller.go
The status of `Tensorboard` should be a subresource of the CRD, which is like [`Notebook`](https://github.com/kubeflow/kubeflow/blob/743310d977f6dbac55a0676c94ce645b0276d05f/components/notebook-controller/api/v1/notebook_types.go#L62). Therefore, when updating the instance, we use `r.Status().Update(ctx, instance)` instead of `r.Update(ctx, instance)`.
> Tesorboard-Controller: use updateStatus instead of update

- py/kubeflow/kubeflow/cd/config.py
This PR fixes the ECR prefix for the OCI image artifacts to the new folder structure from https://github.com/kubeflow/kubeflow/issues/5675 as the registries have been created.
> Fix ECR registry to add /notebooks prefix

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
- components/centraldashboard/public/components/pipelines-card.js
This PR fixes two bugs resulting in Centraldashboard not showing an active menu item:
When refreshing the page, the main page fetches menu links by calling the `/api/dashboard-links` endpoint. The callback of this endpoint fires *after* the callback for URL changes, which in turn triggers the activation of the selected menu item. This results in no active menu link. The first commit fixes this by adding an observer to the list of menu items and forcing the activation of one of them, based on the URL.
We were taking into consideration Apps that do hash-based routing, so URLs with path-based routing would not be matched against the correct menu item. The second commit handles this.
---
This PR also introduces some unit tests to make sure that the selection of the active menu item happens as …
> Centraldashboard: Fix active menu item for path-based URLs

- py/OWNERS
Updates the new testing OWNERS file with leads of the Notebook Working Group, (and changes to indented list format).
> update testing OWNERS with Notebook WG leads

- components/admission-webhook/main.go
- components/admission-webhook/manifests/webhook/base/service.yaml
@DavidSpek @yanniszark i had to rebase because of too many fundamental changes. For example the service.yaml file did not exist in that place 4 days ago, so it was not in my branch.
Never ever use ports below 1024. It prevents runasnonroot.
General effort to run kubeflow rootless
kubeflow/manifests#1756
> Rebase Fix wrong port in admission-webhook-controller #5637

- py/kubeflow/kubeflow/cd/access_management.py
- py/kubeflow/kubeflow/cd/kaniko_builder.py
- py/kubeflow/kubeflow/ci/access_management_tests.py
- py/kubeflow/kubeflow/ci/workflow_utils.py
The Kaniko build process for access-management has a tendency to get OOMKilled (see https://github.com/kubeflow/kubeflow/pull/5673). This PR makes the `memory` and `activeDeadlineSeconds` configurable for workflows and increases the memory limit from 4Gi to 6Gi for building the Kaniko image. The `activeDeadlineSeconds` is not used in this PR specifically, but is used in other PRs I have open so adding it in here will make the large amount of rebasing I am going to need to do a little easier.
> Fix access-management OOMKilled during container build

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authn.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/authz.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/settings.py
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/enums/dashboard.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
Partially fixes #5566 
This PR makes the following changes:
* Introduce a new `APP_NO_AUTHNZ` env var that configures the app to completely skip authnz checks
* Extend the Namespace Service to expose if the Central Dashboard is found
With these changes the admin could configure the apps to skip any authnz checks, which is the case for standalone mode as we've described in #5566.
The next step will be to make our different web apps use the updated `NamespaceService` to understand if the Central Dashboard is present. In that case they should show the namespace selector, which was previously found in the Dashboard.
> web-apps: Extend common code for the apps to work in standalone mode

- components/centraldashboard/manifests/base/configmap.yaml
This PR updates the Centraldashboard ConfigMap to populate the sidebar menu. As part of Kubeflow 1.3 we want to make Centraldashboard the unified place for navigating between Kubeflow components. We have been discussing this in the context of the Web Apps here https://github.com/kubeflow/kubeflow/issues/5566#issue-796194300.
Quoting the relevant passage:
> Kubeflow mode
> When we say that an app is deployed alongside Kubeflow this means the following things:
>
> 1. [...]
> 2. There is a CentralDashboard which:
- decides what Namespaces to show to the user and feeds to the app the selected Namespace
- **has a left hand sidebar, which can have subsections https://github.com/kubeflow/kubeflow/pull/5474. This side bar can be used for navigating the user between different pages of the …
> Centraldashboard: update menu items in manifests

- prow_config.yaml
After realizing that @Bobgy would need to approve each of the PRs for the new notebook images due to the `prow_config.yaml` being edited, I thought it would be best to move those changes to a dedicated PR so @thesuperzapper and I can work more quickly when merging the notebook image PRs. 
@kimwnasptd can you also read over this quickly, as it is essential for being able to move fast with the other PRs and getting the images built.
> Add prow config for new notebook servers

- components/crud-web-apps/tensorboards/manifests/base/cluster-role-binding.yaml
- components/crud-web-apps/tensorboards/manifests/base/cluster-role.yaml
- components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
- components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
- components/crud-web-apps/tensorboards/manifests/base/params.env
- components/crud-web-apps/tensorboards/manifests/base/params.yaml
- components/crud-web-apps/tensorboards/manifests/base/service-account.yaml
- components/crud-web-apps/tensorboards/manifests/base/service.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/kustomization.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/params.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/virtual-service.yaml
Manifests for the Tensorboards web app.
The app will be exposed under the `/tensorboards` prefix. The next step will now be to include it in the dashboard.
cc @kubeflow/wg-notebooks-leads 
> Manifests for Tensorboards web app

- components/crud-web-apps/volumes/manifests/base/cluster-role-binding.yaml
- components/crud-web-apps/volumes/manifests/base/cluster-role.yaml
- components/crud-web-apps/volumes/manifests/base/deployment.yaml
- components/crud-web-apps/volumes/manifests/base/kustomization.yaml
- components/crud-web-apps/volumes/manifests/base/params.env
- components/crud-web-apps/volumes/manifests/base/params.yaml
- components/crud-web-apps/volumes/manifests/base/service-account.yaml
- components/crud-web-apps/volumes/manifests/base/service.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/kustomization.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/params.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/virtual-service.yaml
Manifests for the Volumes web app #4758.
The app will be exposed under the `/volumes` prefix. The next step will now be to include it in the dashboard.
> Manifests for the Volumes web app

- components/example-notebook-servers/OWNERS
- components/example-notebook-servers/base/Dockerfile
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_base.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_base_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_base_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_base_tests_runner.py
This PR adds the Web-IDE base image from https://github.com/kubeflow/kubeflow/pull/5582 that will serve as the base image for all Jupyter, R-Studio and Code-Server (VS-Code) images downstream. More details about the downstream use of this image can be seen in the PR linked above. 
Initial image was built and pushed to test CI/CD and facilitate downstream testing:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/base:master-9d688f73
/cc @kubeflow/wg-notebooks-leads @thesuperzapper
> Add notebook-server-base dockerfile and CI/CD

- components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
- py/kubeflow/kubeflow/cd/kaniko_builder.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_full_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_full_tests_runner.py
This PR adds the PyTorch Jupyter opinionated images from #5582 that will serve as a starting point for (new) users and projects by adding an opinionated set of common tools. It uses https://github.com/kubeflow/kubeflow/pull/5626 as the base image. These images also serve as important examples for people that would like to customize the PyTorch base image for their distinct needs. More details about the downstream use of this image can be seen in the PR linked above. 
Initial images were built and pushed to test CI/CD:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full:master-28af7716
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:master-28af7716
/cc @kubeflow/wg-notebooks-leads @thesuperzapper
> Add notebook-server-jupyter-pytorch-full dockerfiles and CI/CD

- components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
This fix is needed so that the JWA is able to detect which GPU vendors are available in the cluster. Without it an error will be displayed to the users. 
/cc @kimwnasptd @yanniszark
> Add listing nodes to JWA ClusterRole for GPU vendor detection

- components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow_full.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_tensorflow_full_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_full_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_tensorflow_full_tests_runner.py
This PR adds the TensorFlow Jupyter opinionated images from #5582 that will serve as a starting point for (new) users and projects by adding an opinionated set of common tools. It uses https://github.com/kubeflow/kubeflow/pull/5627 and https://github.com/kubeflow/kubeflow/pull/5628 as the base images. These images also serve as important examples for people that would like to customize the TensorFlow base image for their distinct needs. More details about the downstream use of this image can be seen in the PR linked above. 
Initial images were built and pushed to test CI/CD:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:master-28af7716
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full:master-28af7716
/cc …
> Add notebook-server-jupyter-tensorflow-full dockerfiles and CI/CD

- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_scipy.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_scipy_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_scipy_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_scipy_tests_runner.py
Part of https://github.com/kubeflow/kubeflow/issues/5575.
Initial images were built and pushed to test CI/CD and facilitate downstream testing:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-28af7716
> Add notebook-server-jupyter-scipy dockerfile and CI/CD

- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/codeserver-python/requirements.txt
- components/example-notebook-servers/codeserver-python/s6/cont-init.d/02-conda-init
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver_python.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_codeserver_python_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_python_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_codeserver_python_tests_runner.py
Part of #5575.
Initial images were built and pushed to test CI/CD and facilitate downstream testing:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:master-28af7716
> Add notebook-server-codeserver-python dockerfile and CI/CD

- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/jupyter/s6/cont-init.d/02-conda-init
Due to how the Linux shells are being started by JupyterLab, the Conda environment wasn't being properly activated in the terminals started within JupyterLab. This PR fixes this. 
> Fix conda activation in notebook-server-base for JupyterLab

- components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
Changes the base images of the PyTorch, TensorFlow and SciPy images to the new Jupyter image that fixes the conda environment activation. 
> Fix conda activation for JupyterLab + cleanup

- components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
Changes the base images of the PyTorch, TensorFlow and SciPy images to the new Jupyter image that fixes the conda environment activation.
> Fix conda activation for JupyterLab in full images + cleanup

- components/tensorboard-controller/config/base/kustomization.yaml
Right now we specifically use `namespace: system` in the [base manifests](https://github.com/kubeflow/kubeflow/blob/0cb715bec96528ff7af66fcd8b15d347e6eec077/components/tensorboard-controller/config/base/kustomization.yaml#L34). This results in the ClusterRoleBindings to be set to the `tensorboard-controller` service account that lives in the `system` namespace.
We should remove these lines and let namespace transformer to inject the correct values for the Namespace.
> Tensorboards web app manifests: Don't use specific namespace in base

- components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/deployment.yaml
- components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/base/params.env
This PR updates the manifests of the Jupyter web app to work with the latest AWS image.
The used image also contains the code from #5646 and config contains the currently built and merged notebook server images https://github.com/kubeflow/kubeflow/issues/5575#issuecomment-804021135. Once https://github.com/kubeflow/kubeflow/pull/5624 and https://github.com/kubeflow/kubeflow/pull/5711 are merged we will also make a new PR to add the RStudio images to the web app's config.
cc @thesuperzapper @DavidSpek 
> Update the manifests for the Jupyter web app

- components/example-notebook-servers/rstudio/Dockerfile
set TZ in rstudio notebook image, needed for R (e.g. tidyverse) to not try and use `timedatectl`
> set TZ in rstudio notebook image

- components/example-notebook-servers/rstudio-tidyverse/Dockerfile
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_rstudio_tidyverse.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_rstudio_tidyverse_runner.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_rstudio_tidyverse_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_rstudio_tidyverse_tests_runner.py
Part of #5575.
Initial images were built and pushed to test CI/CD:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-87b7d015
> Add notebook-server-rstudio-tidyverse dockerfile and CI/CD

- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
This PR updates the `spawner_ui_config.yaml` to have the latest image tags for the new images, and adds the missing RStudio image that has (finally) been merged and built. 
/cc @yanniszark @kimwnasptd
> (JWA): update manifests with latest notebook image tags

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/server-type/server-type.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index.module.ts
- components/crud-web-apps/jupyter/frontend/src/assets/jupyter-icon.svg
As per the guideline: `Identification of source the first time the Licensed Mark is displayed in connection with the Services or in materials advertising or promoting the Services:`. The Spawner UI is the first time users come into contact with the RStudio logo. As such, they need to be informed of the trademark usage: `RStudio® and the RStudio logo are registered trademarks of RStudio, PBC`. 
This PR adds this as a tool tip to the button toggle that uses the RStudio logo for lack of a better way to fix this so quickly. 
/cc @kimwnasptd @yanniszark
> (JWA): Add RStudio trademark statement in Notebook Spawner UI

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/csrf.py
- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/settings.py
- components/crud-web-apps/jupyter/backend/Makefile
- components/crud-web-apps/tensorboards/backend/Makefile
- components/crud-web-apps/volumes/backend/Makefile
closes #5763 
In this PR I:
1. Introduce a new `APP_SECURE_COOKIES` as described in the issue above
2. Switched the CSRF check orderings. It's misleading for the app to first report that the CSRF header is missing when the cookie is missing as well. In that case the end user might believe that the cookie is there, which could not be the case.
3. Extended the makefiles to use this env var when we run the backends in dev mode, since in that case the apps are exposed over http
/cc @yanniszark @elikatsis 
> web-apps: Introduce an APP_SECURE_COOKIES env var

- components/admission-webhook/manifests/base/deployment.yaml
- components/admission-webhook/manifests/base/kustomization.yaml
- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/manifests/base/kustomization.yaml
- components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
- components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
- components/crud-web-apps/volumes/manifests/base/kustomization.yaml
- components/notebook-controller/config/base/kustomization.yaml
- components/notebook-controller/config/manager/manager.yaml
- components/profile-controller/config/base/kustomization.yaml
- components/profile-controller/config/manager/manager.yaml
- components/profile-controller/config/overlays/kubeflow/kustomization.yaml
- components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
- components/tensorboard-controller/config/base/kustomization.yaml
Some of the manifests were still using gcr and didn't contain an `images:` section in the `kustomization.yaml` making it more difficult to update the image tags when new ones are pushed (Renovate can do this as well). This PR fixes the manifests so all components are using ECR, have an `images:` section in the `kustomization.yaml` and have the current latest image tags. 
I've added a fix to this PR changes `fieldPath` to `fieldpath` in the `kustomization.yaml` files according to the Kustomize reference docs: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/
/cc @kimwnasptd @yanniszark
> Update manifests to use ECR and fix fieldPath in kustomization files

- components/centraldashboard/config/centraldashboard-config.yaml
- components/centraldashboard/manifests/base/configmap.yaml
The Tensorboards and Volumes Web Apps haven't been added to the Central Dashboard. This PR adds them to them to the Central Dashboard in preparation for the upcoming release.
/cc @StefanoFioravanzo @kimwnasptd
> Add Tensorboards and Volumes to central-dashboard

- releasing/OWNERS
cc @Bobgy 
This is in order to be able to release new manifests / image versions for the notebooks wg.
> releasing: Add WG-Notebooks leads to release owners

- components/tensorboard-controller/config/default/kustomization.yaml
Currently, no labels are being set for the tensorboard-controller. Without these labels, the selector for the deployment and service of the tensorboard-controller are generic and will cause compatibility problems with other KubeBuilder based controllers if they are in the same namespace. This PR adds the labels `app: tensorboard-controller` and `kustomize.component: tensorboard-controller` to the manifests so that specific selectors are used. 
> Specify commonLabels for tensorboard-controller

- OWNERS
Removing myself as an owner. This should lead to better auto-assignment of code reviews.
> Remove jlewi as an approver

- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
- components/example-notebook-servers/rstudio-tidyverse/Dockerfile
Updates the downstream notebook server images to the tags created after merging https://github.com/kubeflow/kubeflow/pull/5804. Also updates some python packages in the scipy notebook server image. 
@kimwnasptd if you could quickly give your blessing on this PR I can move on to the last layer of downstream images (tensorflow and pytorch full).
> Update second layer docker images to new tags and some python deps

- components/tensorboard-controller/controllers/tensorboard_controller.go
When the TB controller attempts to schedule a RWO PVC it checks its
accessModes in the PVC status. The controller panics if the list is
empty.
This commit adds a check to ensure the list is not empty.
Signed-off-by: Ilias Katsakioris <elikatsis@arrikto.com>
/cc @kubeflow/wg-notebooks-leads 
/assign @StefanoFioravanzo
> tensorboard-controller: Fix scheduling unbound PVCs

- components/crud-web-apps/jupyter/backend/apps/common/form.py
- components/crud-web-apps/jupyter/backend/apps/common/yaml/notebook_template.yaml
- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
- components/crud-web-apps/jupyter/frontend/src/app/types.ts
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
Closes: https://github.com/kubeflow/kubeflow/issues/5814
This PR makes it possible for admins to set a factor that gets multiplied against the resource request of a notebook to set a limit for the resource. According to the above issue,  it is not possible to create notebooks when profiles have resourcequotas  and no resource limit is set. 
By default, the limit of a notebook server is set to 20% more than the request. This gives users that might not expect a Pod to get killed if the memory limit is reached a buffer.
/cc @kimwnasptd I think we need to get this merged quickly as without it current installations will break with the new web app. The fix is quite small luckily.
> Make notebook limits configurable with a multiplication factor

- components/example-notebook-servers/jupyter/requirements.txt
Closes: https://github.com/kubeflow/kubeflow/issues/5843
This PR updates the JupyterLab packages and adds the JupyterLab-Git extension package to the Jupyter notebook server image. For the JupyterLab-Git extension to work properly it must be installed before running JupyterLab. Given the popularity of this extension (it is mention in the [charter](https://github.com/kubeflow/community/blob/master/wg-notebooks/charter.md#code-web-apps-controllers-and-services) of the working group depending on how you interpret it), it makes sense to install it in the notebook server images.
> notebook-servers: Update JupyterLab and add Git Extension

- components/example-notebook-servers/rstudio/Dockerfile
Add a reference to license which R-Studio is currently using.
> chore: Add comment to reference RStudio license.

- py/kubeflow/kubeflow/ci/admission_webhook_tests.py
- py/kubeflow/kubeflow/ci/central_dashboard_tests.py
- py/kubeflow/kubeflow/ci/jwa_tests.py
- py/kubeflow/kubeflow/ci/notebook_controller_tests.py
- py/kubeflow/kubeflow/ci/profile_controller_tests.py
- py/kubeflow/kubeflow/ci/tensorboard_controller_tests.py
- py/kubeflow/kubeflow/ci/twa_tests.py
- py/kubeflow/kubeflow/ci/vwa_tests.py
This PR adds CI tests to build the manifests with `kustomize build`. 
> CI/CD: add kustomize build tests

- components/tensorboard-controller/config/crd/bases/tensorboard.kubeflow.org_tensorboards.yaml
- components/tensorboard-controller/controllers/tensorboard_controller.go
Part of https://github.com/kubeflow/kubeflow/issues/5938
This PR adds the `--bind_all` argument for tensorboard, solving the problem described in the issue mentioned above, as well as fixing support for Istio 1.10.
> tensorboard-controller: fix binding issue

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
Fix
#5863
This PR make it possible to add namespaced items on side bar menu.
The users can define the side bar menu as below.
```
{
"type": "item",
"link": "/pipeline/#/artifacts",
"text": "Artifacts",
"icon": "editor:bubble-chart"
},
{
"type": "item",
"link": "/pipeline/#/executions",
"text": "Executions",
"icon": "av:play-arrow"
},
{
"type": "item",
"link": "/myapp1/{ns}/",
"text": "MyApp1",
"icon": "icon"
},
{
"type": "item",
"link": "/myapp2/{ns}/",
"text": "MyApp2",
"icon": "icon"
},
```
{ns}s are replaced by current namespace. The full URL should be https://gateway/myapp1/workspace1/ (when ns=workspace1) or https://gateway/myapp1/workspace2/ (when ns=workspace2).
This feature help cluster admin to add own apps for each namespace.
> Make it possible to add Namespaced menu items

- components/crud-web-apps/jupyter/backend/apps/common/form.py
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
@DavidSpek 
The following line https://github.com/kubeflow/kubeflow/blob/c3d97bb125fa4b828bfa59cd427d5cba96952ee6/components/crud-web-apps/jupyter/backend/apps/common/form.py#L279
produces nvidia.com/gpu: 1 instead of nvidia.com/gpu: '1' which lets the pod fail with 
```
2021-05-03 11:31:24,011 | apps.default.routes.post | INFO | Creating Notebook: {'apiVersion': 'kubeflow.org/v1beta1', 'kind': 'Notebook', 'metadata': {'name': 'test1', 'namespace': 'admin', 'labels': {'app': 'test1'}, 'annotations': {'notebooks.kubeflow.org/server-type': 'jupyter'}}, 'spec': {'template': {'spec': {'serviceAccountName': 'default-editor', 'containers': [{'name': 'test1', 'image': '...', 'volumeMounts': [{'mountPath': '/dev/shm', 'name': 'dshm'}], 'env': [], 'resources': {'requests': {'cpu': '0.1', 'memory': …
```
> FIX The number of gpu must be set as string in Kubernetes/Openshift

- components/example-notebook-servers/base/Dockerfile
This PR adds an comment so that dependency updates for the S6-overlay can be automated with Renovate. It also updates kubectl and configures the default shell to `bash` so that all the downstream images use the same shell while being built. This PR is the first step in the process of updating the packages in all the notebook images for the upcoming 1.3.1 release, solving the dependency conflicts between the KFP and KFServing SDKs.
> Update base notebook for Renovate compatibility

- components/centraldashboard/public/components/main-page.css
- components/centraldashboard/public/components/main-page.pug
Fix
#5963 
This PR makes it possible to scroll the menu bar.
It was available in KF1.2 but it is **not** available in KF1.3. That's why the title of this PR is `Make menu bar scrollable again`.
As an attached image, the laptop users will be able to scroll the side bar.
The style of scroll bar is suitable to kubeflow UI enough.
ref) This tip is written in official document of PolymerElements.<br>https://github.com/PolymerElements/app-layout/tree/master/app-drawer
```
To make the contents of the drawer scrollable, create a wrapper for the scroll content, and apply height and overflow styles to it.
<app-drawer>
<div style="height: 100%; overflow: auto;"></div>
</app-drawer>
```
> Make menu bar scrollable again

- components/crud-web-apps/jupyter/backend/apps/default/routes/post.py
At jupyter-web-app's backend's source code, workspace volume path was fixed with "/home/jovyan"
Thus, when I changed my jupyter-web-app-config's data (mountPath) to "/home/jovyan/workspace":
Thus, the UI (jupyter-web-app's frontend) shows the mountPath correctly like:
Also, the POST /notebook API was sent with correct path like:
However, spawned notebook's mountPath was fixed with "/home/jovyan":
Thus, corresponding statefulset and pod's mountPath was all fixed with "/home/jovyan"
---
As you can see easily, workspace volume path was fixed with "/home/jovyan" at jupyter-web-app's backend's source code.
So, change it to parse from config file
---
- public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.3.0-rc.1
> [fix]: Make jupyter-web-app parse workspace volume MountPath

- components/example-notebook-servers/README.md
Closes: https://github.com/kubeflow/kubeflow/issues/5904
There is a common but sporadic problem where the kernel in JupyterLab is stuck in a `connecting` state (see https://github.com/kubeflow/kubeflow/issues/5904). This problem is not related to Kubeflow, but rather originates in the user's browser. It can be identified by looking in the browser logs in the developer tools where there will be errors related to problems connecting to the websocket. The fix for this is restarting the browser (refreshing usually doesn't work) or (temporarily) using a different browser if the current one cannot be restarted. This PR adds a common problems and solutions sections to the notebook image README that explains this issue and the solution.
> Notebook servers: Add explanation about kernel not connecting

- components/profile-controller/controllers/profile_controller.go
This PR fixes the KNative's `activator` and `controller` probes on `/healthz`, `/metrics` paths on workloads for KFServing
/assign @yanniszark
> fix(profile-controller): KNative probes

- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/frontend/package-lock.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/types.ts
Closes https://github.com/StatCan/kubeflow/issues/51
In the notebook server creation view, the fully qualified name of available images is currently displayed as:
- gcr.io/kubeflow-images-public/tensorflow-1.5.1-notebook-cpu:v0.5.0
We implemented an optional feature to hide the registry and tag in the image dropdown list as the names can get unwieldly when the registry domain is much longer than, for example, `gcr.io`. Tags can also be the same (e.g. for organizations that use full commit SHAs for tags). 
This is an optional feature for a more approachable and understandable list, with the new images displayed in the form:
- kubeflow-images-public/tensorflow-1.5.1-notebook-cpu
This PR adds two new configuration options to the `crud-web-apps/jupyter-web-app` supported …
> feat(jupyter): Support hiding image registry/tag

- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/codeserver-python/requirements.txt
- components/example-notebook-servers/jupyter-pytorch/cpu-requirements.txt
- components/example-notebook-servers/jupyter-pytorch/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch/cuda-requirements.txt
- components/example-notebook-servers/jupyter-pytorch/cuda.Dockerfile
- components/example-notebook-servers/jupyter-pytorch/requirements-cpu.txt
- components/example-notebook-servers/jupyter-pytorch/requirements-cuda.txt
- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/cpu-requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow/cuda-requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/cuda.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow/requirements-cpu.txt
- components/example-notebook-servers/jupyter-tensorflow/requirements-cuda.txt
- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/rstudio-tidyverse/Dockerfile
- components/example-notebook-servers/rstudio/Dockerfile
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_full_tests.py
- py/kubeflow/kubeflow/ci/notebook_servers/notebook_server_jupyter_pytorch_tests.py
This PR updates the codeserver-python, jupyter-pytorch, jupyter-scipy, jupyter-tensorflow and rstudio-tidyverse dokerfiles to include the latest packages and make them compatible with Renovate.
> Update dockerfiles and make compatible with Renovate

- .github/OWNERS
This PR adds an OWNERS file to the `.github` folder so that admins don't need to be bothered with merging PRs related to updating the Renovate configuration or other workflows (such as GitHub actions).
/cc @kubeflow/wg-notebooks-leads @Bobgy
> Create OWNERS file in .github folder for Renovate config + workflows

- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch.py
- py/kubeflow/kubeflow/cd/notebook_servers/notebook_server_jupyter_pytorch_full.py
Pushing relatively large images to ECR is very slow, which is why the TensorFlow notebook server images with CUDA support required the default timeout of the Argo Workflow task to be increased. At first this was not necessary for the PyTorch notebook server images. However, with the latest version the PyTorch job is cancelled before the image push is completed ([see here](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-postsubmit-nb-j-pt-e9324d3-7920-7ad4?tab=workflow&nodeId=kubeflow-kubeflow-postsubmit-nb-j-pt-e9324d3-7920-7ad4-3401172493)).
This PR extends the timeout period for the PyTorch build jobs so they are the same as the TensorFlow notebook images.
> Extend deadline for PyTorch image building

- components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-full/cpu.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/cuda.Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
This is the last PR to update the notebook server dockerfiles so they include the latest packages. After this PR, the `spawner_ui_config.yaml` needs updating so the new images are included for the upcoming 1.3.1 release of Kubeflow.
> Update last batch of notebook server Dockerfiles

- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
This PR updates the notebook server image tags in the `spawner_ui_config.yaml` to reflect the latest versions. It also updates the images in the `spawner_ui_config.yaml` used in the manifests.
> Update spawner_ui_config.yaml with new tags

- components/example-notebook-servers/rstudio/Dockerfile
As seen [here](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-nb-rstudio-6007-10af3fc-1328-1171?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-nb-rstudio-6007-10af3fc-1328-1171-4006263469), the PGP server used to validate the RStudio binary is down, which is causing the image build to fail and as a consequence blocking the 1.3.1 release.
To solve this, this PR adds the PGP keyserver `pgp.surfnet.nl` as a secondary option. SURFnet is an organization that develops, implements and maintains the national research and education network in The Netherlands, which is why I believe it is a good candidate (at least for now). I also tested `pgp.mit.edu` which did not work for me.
> notebooks: Add additional PGP server for RStudio package validation

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
- components/admission-webhook/manifests/base/crd.yaml
- components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
The admission-webhook CRD appears to define support for the `serviceAccountName`, however, the code didn't actually read it. I've added support for both `serviceAccountName` and `automountServiceAccountToken` fields since my organization needs those.
Also, this is the first contribution from Signifyd, Inc. We should have a CLA on file as of about a week ago.
> Add support for ServiceAccountName and AutomountServiceAccountName to admission-webhook

- components/crud-web-apps/jupyter/frontend/src/app/app.module.ts
- components/crud-web-apps/tensorboards/frontend/src/app/app.module.ts
- components/crud-web-apps/volumes/frontend/src/app/app.module.ts
fixes #6033 
The web apps should use the relative path `static/assets/il8n/` to fetch the translation files. This way the browser will construct the correct path, by using the `<base href="...">` element, even if the app lives under a prefix.
/cc @tasos-ale 
/assign @StefanoFioravanzo
> WA: Use relative paths for fetching translation files

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page_test.js
Fix
#5994 
This PR enables namespaced menu items to interact with the namespace selector.
It means the URL of namespaced menu items will follow the selection of namespace selector.
The feature of namespaced menu items is merged by #5871, and described in [here](https://www.kubeflow.org/docs/components/central-dash/customizing-menu/) .
When the user chooses namespace=workspace1, the URL well be `https://gateway/_/mlflow/workspace1/?ns=workspace1`. If he chooses namespace=workspace2 later, the URL will change into `https://gateway/_/mlflow/workspace2/?ns=workspace2` dynamically.
/cc @kimwnasptd @DavidSpek
> Interact with the namespace selector

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
closes #6057 
This PR also blocks the form from automatically updating the limits fields if they are dirty. If the user had defined custom values for the limits then the form should not automatically override them.
Also the form will not submit any fields, in the POST json body, for limits if no value is provided.
/cc @tasos-ale 
> fix(jwa): Fix limits calculation when limitFactor is none

- components/crud-web-apps/jupyter/backend/apps/common/form.py
This PR fixes an issue with the Jupyter Web App creating invalid notebook configuration with CPU and Memory set as:
- CPU: NaN
- Memory: NaNGI.
This happens with jupyter-web-app-config when limit factor is set to None and non-default resource value is set.
```yaml
limitFactor: "none"
```
I am not familiar with npm used in the frontend so I am not sure if this is the best way to fix it, hence I sent in a patch to the backend which should fix the issue.
fixes #5985
> Fix NaN in Kubeflow Notebooks

- components/notebook-controller/controllers/notebook_controller.go
In the existing version, the 'timeout: 300s' added to the notebook's virtual service would cause websockets to disconnect at the 5 minute mark, causing the Jupyter Notebook web terminal function to hang. This is described in https://github.com/kubeflow/kubeflow/issues/6124.
> Remove virtualservice timeout to prevent websocket disconnect

- components/admission-webhook/go.mod
- components/admission-webhook/go.sum
- components/admission-webhook/main.go
Fixes #6027
When pod is deployed via `Deployment` object, namespace can be missing on `Pod` object in admission review request.
In this case, `PodDefault` can not be attached to pods since they do not have a namespace, 
and filtered by `filterPodDefaults` like below.
- https://github.com/kubeflow/kubeflow/blob/66bf469afdc1fc6bfc887c8c823234cc2b70a5d6/components/admission-webhook/main.go#L84
Since admission review request itself contains a namespace field, we can avoid problem above by attaching namespace to pod request if pod does not have it. I verified that `PodDefault` works correctly on deploying pod via `Deployment` object.
Also I just ran `go mod tidy` for cleaning unused dependencies.
Please take a look, thanks.
> fix(admission-webhook): attach namespace to pod request if pod does not have it

- README.md
update the quick links in readme, pointing to the `optional-test-infra`
> update links for new testing infra

- components/example-notebook-servers/README.md
This PR addresses some common issues with the README for `components/example-notebook-servers`:
1. List & describe all the images we provide
2. Link to the ECR Gallery website for each image (and provide example image tags)
3. Cleanup headers (it was very hard to read before)
4. General cleanup
> Improve README for example-notebook-servers

- components/crud-web-apps/jupyter/README.md
- components/crud-web-apps/jupyter/frontend/package.json
- components/crud-web-apps/volumes/frontend/package.json
Partial #5566
During standalone JWA deployment, js files are referenced with `/jupyter` prefix, instead it should be relative to `--base-href` parameter.
> fix(web-apps): Use relative path for --deploy-url build. #5566

- docs_dev/releasing.md
1. Now we have updated website to point to master by default, the process to make new release is simplified.
2. Document permission required to cut a new branch on Netlify.
3. Reorder instruction for better understanding.
4. Added instruction for maintaining dropdown menu.
> Document for cutting Kubeflow website release.

- components/tensorboard-controller/config/rbac/role.yaml
I have added the necessary permission.
https://github.com/kubeflow/kubeflow/blob/0c6c738efb95fbd320dc425c56c91fd6bcef5418/components/tensorboard-controller/controllers/tensorboard_controller.go#L148 tries to own the deployment but tensorboards/finalizers are not in the role
So you will get an error message similar to 
```
2021-11-05T12:02:24.832Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "tensorboard", "request": "dev-1/workspace-kulius-1", "error": "deployments.apps \"workspace-kulius-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```
> fix(backend): tensorboard-controller does not work because of missing permissions

- components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
- components/crud-web-apps/jupyter/frontend/i18n/messages.xlf
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-data-volumes/form-data-volumes.component.html
This PR adds i18n localize FR translations.
Related to #6042
Translates all crud-web-apps/jupyter/frontend literals in French.
To test this feature:
`ng serve --configuration=fr`
> add(web-apps): i18n Fr translations

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/positive-number-input/positive-number-input.component.html
Current positive_number_input_component's error message was just saying it's negative.
However many web apps use such components with `min` as `1`.
So when user enter the number in a range (0, 1), such number was not a negative number but the error message was fixed.
Therefore I think we should change the error msg. (but I'm afraid then this component's naming became somewhat weird.)
Also, Since I'm not familiar with frontend, I'm not sure if I should manually change these i18n related files or not:
https://github.com/kubeflow/kubeflow/blob/ea5c89110971c7dc3141cfdc10a479358a3d7b9f/components/crud-web-apps/jupyter/frontend/i18n/messages.xlf#L42
Please let me know, If I should update those files too. Thanks in advance.
- Volumes web app Page
- Jupyter web app Page
> web-apps(front) : change error msg for min

- ROADMAP.md
3 changes - Add info on Kubeflow 1.5 and 1.4.1.   Update roadmap to show that Kubeflow 1.4 was delivered.
> Short term updates to Published Kubeflow Roadmap

- components/centraldashboard/app/api_workgroup.ts
- components/centraldashboard/app/server.ts
Currently, the central-dashboard sends EVERY client header passed to its `/add-contributor/xxx` and `/remove-contributor/xxx` APIs on to kfam's `/kfam/v1/bindings` API. 
_(NOTE: these APIs are used in the "manage contributor" page to add/remove contributors)_
This means central-dashboard sends requests to `/kfam/v1/bindings` with invalid `:authority` headers (with the hostname of the istio gateway, rather than the internal kfam Service). 
This causes significant issues when you enable istio-sidecars on the kfam Pods, as istio will reject the "invalid" HTTP request, preventing you from adding/removing contributors.
---
This PR is very simple, it defines a list of "auth headers" which are safe to pass on, and deletes all others before forwarding to `/kfam/v1/bindings`.
_(NOTE: The only …
> fix dashboard sending malformed headers to kfam

- components/centraldashboard/Dockerfile
closes #6259 
In this PR I'm:
* Updating the node version to `v12.22.8`
* Using the `latest-stable` instead of `edge`
NOTE: I also updated the node version because I was seeing some `UNTRUSTED signature` errors when fetching alpine packages. Could be because of an old openssl package in the base image, but I'm not 100% sure.
The tests for the dashboard should be now passing
> centraldashboard: Update node and use latest-stable

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/main-page_test.js
- components/centraldashboard/public/components/namespace-needed-view.js
Fix
#6118
Although namespaced menus items will be available for KF1.4 (#5871), there is room for improvement.
@munagekar pointed out the message that is shown for the user when he tries to access the namespaced item without  namespace selection.
This PR makes it possible to show the user-friendly message "Please select a namespace from the top bar" for such users.
@munagekar I appreciate if you help discussions for this PR.
/cc @kimwnasptd @jbottum @munagekar
> Tell user to select a namespace to access namespaced menu item

- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/manifests/overlays/istio/authorizationpolicy.yaml
- components/centraldashboard/manifests/overlays/istio/kustomization.yaml
- components/profile-controller/config/overlays/kubeflow/authorizationpolicy.yaml
- components/profile-controller/config/overlays/kubeflow/kustomization.yaml
- components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
Solves: https://github.com/kubeflow/kubeflow/issues/6228
This PR secures access to KFAM so it is not accessible to users.
> Secure access to KFAM

- components/notebook-controller/config/manager/manager.yaml
- components/profile-controller/controllers/profile_controller.go
Hi 
This fixed #5128 according to the guidelines of this comment: https://github.com/kubeflow/kubeflow/issues/5128#issuecomment-859814573 . I wasn't sure where to place the `AuthorizationPolicy`, I think it belongs in the `overlays/kubeflow` directory, as istio is only used in combination with kubeflow. In addition it needs to be created in the `istio-system` namespace and not in the `kubeflow` namespace. Therefore I separated the manifests in `overlays/kubeflow` into a `kubebflow/` and `istio-sytem/` directory, representing the namespaces of the manifests in both directories. Of course, please let me know if you have any better location/setup for this file.
Looking forward to your feedback!
> fix(notebooks) make culling work with multi-user (#5128)

- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/config.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/property-value.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
- components/crud-web-apps/jupyter/frontend/angular.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-rok/form-rok.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.module.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.html
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
A first step for https://github.com/kubeflow/kubeflow/issues/6315
Extend the frontends of our web apps to instead use responsive tables, to be more inline with what Pipelines are doing.
Here the new look of the apps
> frontend: Use responsive tables instead of cards

- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/pkg/culler/culler.go
Closes #6337 
The changes in the PR fixed the endless restarts for me. I'm very confident that this is related to https://github.com/kubeflow/kubeflow/issues/5982, due to how we handle K8s events after a Notebook is deleted. But I wont' close that one unless we've confirmed its root cause.
> notebooks: Fix endless restarts

- components/common/reconcilehelper/util.go
error comparison between pointer and pointer in "CopyStatefulSetFields"
fix https://github.com/kubeflow/kubeflow/issues/6194
> fix error comparison between pointer and pointer in "CopyStatefulSetFields"

- components/centraldashboard/manifests/overlays/kserve/kustomization.yaml
- components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
Refs https://github.com/kubeflow/manifests/issues/2112#issuecomment-1055693752
Add an overlay in the dashboard for using the KServe models web app, instead of the KFServing one. The KServe app is using a different prefix https://github.com/kserve/models-web-app/pull/27.
> centraldashboard: Add KServe overlay

- components/notebook-controller/controllers/notebook_controller.go
Refs https://github.com/kubeflow/kubeflow/issues/6382
The PR updates the controller to never trigger the `Reconcile()` function when any K8s Event gets deleted, whether it belonged to a Notebook or not.
This should resolve logs we saw in #6382 like:
```
2022-03-01T14:08:50.378Z	ERROR	controllers.Notebook	unable to fetch Notebook	{"notebook": "kube-system/istio-cni-node-854fq.16d83d225eab3a57", "error": "Notebook.kubeflow.org \"istio-cni-node-854fq.16d83d225eab3a57\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/kubeflow/kubeflow/components/notebook-controller/controllers.(*NotebookReconciler).Reconcile
/workspace/notebook-controller/controllers/notebook_controller.go:125 …
```
> notebooks: Don't reconcile on Events deletion

- components/crud-web-apps/common/backend/setup.py
We've just upgraded Kubeflow 1.5 (from 1.3) and have seen a similar issue raised by https://github.com/kubeflow/kubeflow/issues/6419.
On inspecting the error message:
```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
2022-03-29 03:03:18,481 | apps.common.utils | INFO | Using config file: /etc/config/spawner_ui_config.yaml
2022-03-29 03:03:18,492 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
2022-03-29 03:03:18,498 | apps.common.utils | INFO | Using config file: /etc/config/spawner_ui_config.yaml
2022-03-29 03:03:18,492 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Invalid value for `type` (FrequentContainerdRestart), must be one of ['DiskPressure', 'MemoryPressure', 'NetworkUnavailable', …
```
> Fix kubernetes python client to v22.6.0

- components/centraldashboard/Dockerfile
With the current `latest-stable` `v3.16` version of the alpine package repository, an attempt to build a central dashboard image fails with:
```
=> ERROR [build 3/7] RUN apk add --no-cache bash@stable chromium@stable nss@stable     freetype@stable     harfbuzz@stable     ttf-freefont@stable     libstdc++@stable                                        4.4s
------
> [build 3/7] RUN apk add --no-cache bash@stable chromium@stable nss@stable     freetype@stable     harfbuzz@stable     ttf-freefont@stable     libstdc++@stable:
#7 0.940 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
#7 1.239 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
#7 1.803 fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz …
```
> Pin alpine repository version

- components/crud-web-apps/jupyter/backend/apps/common/utils.py
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
We want to extend JWA to have a column for showing the `Last activity` of a Notebook CR. This is the last piece for making the changes from the [idleness proposal](https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220121-jupyter-notebook-idleness.md) visible to users.
Refs #6463 
Refs https://github.com/kubeflow/kubeflow/issues/6461
cc @athamark
> jwa: Expose a last-activity column

- components/proposals/20220621-all-namespaces.md
Extend the CentralDashboard and Jupyter/TensorBoards/Volumes web apps for showing all namespaces. This allows users to view and interact with objects in all namespaces.
Initially we'll start with only the above list of apps, but we can then extend it to the rest of the Kubeflow web apps.
cc @kubeflow/wg-notebooks-leads @johnugeorge @zijianjoy
> proposals: Show objects from all namespaces

- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
- components/admission-webhook/manifests/base/crd.yaml
- components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
Closes #2208, closes #3838.
This PR extends `PodDefault` to provide a capability to set a custom `command` and `args` for Notebook servers.
- Create the following PodDefaut in the user's namespace:
```
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
name: custom-entrypoint
spec:
selector:
matchLabels:
custom-entrypoint: "true"
desc: "Lauch as Jupyter Lab"
command:
- jupyter
args:
- lab
- --notebook-dir=/workspace
- --ip=0.0.0.0
- --no-browser
- --allow-root
- --port=8888
- --NotebookApp.token=''
- --NotebookApp.password=''
- --NotebookApp.allow_origin='*'
- --NotebookApp.base_url=$(NB_PREFIX)
```
- In notebook form, select "Custom image" and set the image you want to run (e.g. nvcr.io/nvidia/tensorflow:22.05-tf1-py3.)
- Under configuration, select "Launch as Jupyter Lab" …
> Add support for `command` and `args` in `PodDefault`

- components/notebook-controller/controllers/notebook_controller.go
Fix typo in error msg at `notebook-controller/controller/notebook_controller.go`
`Statefulset` -> `Service`
> Fix typo in notebook_controller.go

- components/crud-web-apps/tensorboards/README.md
- components/crud-web-apps/volumes/README.md
The code has upgraded to Python 3.8 while the doc keeps legacy information.
https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/tensorboards/Dockerfile#L2
https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/volumes/Dockerfile#L2
> Fix legacy of Python version information in README files.

- components/centraldashboard/Dockerfile
- components/centraldashboard/package-lock.json
- components/centraldashboard/third_party/license.txt
- components/centraldashboard/third_party/license_info.csv
- Updating json-schema version to 0.4.0 to patch/fix [this CVE](https://github.com/advisories/GHSA-896r-f27r-55mw) (had to update `jsprim` to version 1.4.2)
- Updating node linux version (in the dockerfile) to `node:12.22.12-alpine` to patch [this CVE](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28391)
> Update few packages and images to fix critical CVEs in centraldashboard component

- components/crud-web-apps/jupyter/Dockerfile
- components/crud-web-apps/jupyter/README.md
1. There is no common breaking change from 3.7 to 3.8.
2. All other apps under https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps have been upgraded and better to align with them.
> Bump Jupyter web app to Python 3.8.

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html
Fix a typo on the new notebook page
“Volume that will be mounted in you home directory” -> “Volume that will be mounted in your home directory”
First kubeflow PR!
> Fix #6616: Typo on New Notebook page

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-image/form-image.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts
This PR is a fix for images groups one and two not showing in JWA's New notebook page.
**Context**
The issue was created by this PR https://github.com/kubeflow/kubeflow/pull/6482/ , which was attempted to be fixed also by this later PR https://github.com/kubeflow/kubeflow/pull/6596 . Also currently, this PR-fix is under review https://github.com/kubeflow/kubeflow/pull/6599/ .
**Solution**
The fix proposes a straightforward solution utilising the `FormControl`'s `.disabled` attribute and `disable()` function.
> JWA(front): Fix image group one and two not showing

- .github/workflows/prof_controller_unit_test.yaml
- components/profile-controller/README.md
- components/profile-controller/config/samples/_v1_profile.yaml
- components/profile-controller/config/samples/_v1_profile_aws_iam.yaml
- components/profile-controller/controllers/plugin_iam.go
- components/profile-controller/controllers/profile_controller.go
- components/profile-controller/controllers/profile_controller_test.go
Resolves: #6618
Description of changes:
- As described in https://github.com/kubeflow/kubeflow/issues/6618#issuecomment-1223404464, profile plugins functionality broke when the yaml package was changed as part of #6491. Since the structs have JSON tags, we can safely serialize and deserialize the structs using Go's JSON library.
- Added unit tests to prevent this from happening in future.
- Added a validation in the plugin to error out if the role value is missing because golang json library will create the struct even if the value is missing. Since the struct is small at this point, I have added a simple validation but this solution is not great if the struct is complex.
- Added samples which were deleted.
Testing:
- Ran unit tests
- Tested with and without the AWS plugin by running the …
> fix Profile Plugins functionality

- .github/workflows/notebook_controller_unit_test.yaml
- components/notebook-controller/Makefile
- components/notebook-controller/controllers/notebook_controller.go
- components/notebook-controller/controllers/notebook_controller_test.go
The root cause of this error is race conditions when updating the various status fields of a Notebook CR.
More specifically, I found that it is possible for the reconciliation loop to be slow enough so that both the `ContainerState` in the Pod has changed (i.e waiting, running) and the `status.ReadyReplicas` field of the STS has also changed (from 0 to 1) and so a `Status().Update()` (from this [code line](https://github.com/kubeflow/kubeflow/blob/806d32bd1252a59d8ae13e6dc4ab0143c7525fdc/components/notebook-controller/controllers/notebook_controller.go#L213)) is performed before the controller being able to update the Notebook CR's `Status.Conditions` field accordingly, which remains with the default null value. Thus, the controller ends up applying an instance with `nil` conditions and …
> Fix #6056: Update Notebook status properly

- components/profile-controller/config/manager/manager.yaml
This fixes a currently invalid, but working, on early kustomize, yaml for the profile-controller manager manifests.
In [this PR](https://github.com/kubeflow/kubeflow/pull/6491/files#diff-a6712d4f1fc4fbc5bcaa8ff94677bc6c423e6b4ef894bb9590e0c591389a5158) duplicated entries for ports and livenessProbe.
Removing the previous items makes no changes to the output so this change is no-op for early kustomize versions, but it actually allows newer kustomize versions to work, they currently break.
tests:
* Used kustomize-3.8.10 to generate template from master with and without the patch and the output is identical
* Used kustomize-4.5.5 to generate template from master and it breaks without the patch but produces identical output to 3.8.10 with the patch in
```
❯ ( git co master && cd …
```
> Fix invalid kustomization patch introduced for profile-controller manager

- .github/stale.yml
This PR updates the stablebot configs to prevent active issues from being closed.
There are now 3 ways to prevent an issue from being closed (in addition to the `lifecycle/frozen` label):
1. Add them to a GitHub project board
1. Add them to a GitHub milestone
2. Apply a priority label: `priority/p0`, `priority/p1`, `priority/p2`, `priority/p3`
> update stablebot configs

- components/notebook-controller/controllers/notebook_controller.go
This PR fixes: kubeflow#6648
The notebook controller writes the last-activity annotation before culling the Notebook, however, doesn't remove this annotation before start. This causes the Notebook to be culled again before is has a chance to start.
Changes:
* calculate correctly the podFound variable and ensure its value its true only if the Pod is actually found. This way the culling annotation will be removed when there is no Pod.
Signed-off-by: Apostolos Gerakaris <apoger@arrikto.com>
> Fix notebook culling

- components/crud-web-apps/jupyter/backend/apps/common/yaml/notebook_template.yaml
We have a problem, when creating notebooks with namepace name, which include only numbers like "6132435". But this commit should solve this problem.
> Add quotes to notebook_template.yaml namespace field.

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.html
The Angular code for `<app-form-data-volumes>` was missing `.value`.
This error resulted in the name of new data volumes being injected with `[object Object]` instead of the corresponding notebook server name.
More information can be found here: https://github.com/StatCan/jupyter-apis/issues/168.
> fix(volume name): update formCtrl.get()

- components/admission-webhook/main.go
Previously the webhook listened on a fixed port, 4443, which can clash
with other services when the webhook is run on the host network in
Kubernetes, which is required when using some CNI implementations,
notably Calico on EKS [1].
Enable configuration of the webhook listen port via the program flags.
[1] https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking
Signed-off-by: Steve Larkin <steve.larkin@gmail.com>
> Make admission-webhook port number configurable

- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
In this PR:
- Rename `Age` header to `Created at` in WAs.
- Right-align all date columns in WAs.
Here's a screenshot of how it will look like:
Signed-off-by: Elena Zioga [elena@arrikto.com](mailto:elena@arrikto.com)
> [wa-age-column-improvements] Improvements in the web app's age column

- components/crud-web-apps/jupyter/frontend/package-lock.json
- components/crud-web-apps/jupyter/frontend/package.json
- components/crud-web-apps/jupyter/frontend/tsconfig.json
- components/crud-web-apps/tensorboards/frontend/package-lock.json
- components/crud-web-apps/tensorboards/frontend/package.json
- components/crud-web-apps/tensorboards/frontend/tsconfig.json
- components/crud-web-apps/volumes/frontend/package-lock.json
- components/crud-web-apps/volumes/frontend/package.json
- components/crud-web-apps/volumes/frontend/tsconfig.json
In this PR:
- Upgrade `@kubernetes/client-node` module, so that to include `quantityToScalar` function directly from kubernetes js module in WAs.
- Set `allowSyntheticDefaultImports` flag to `true` to allow `'import x  from y'` when a module doesn't have a default export in WAs.
Signed-off-by: Elena Zioga [elena@arrikto.com](mailto:elena@arrikto.com)
> [wa-upgrade-k8s-client] Upgrade @kubernetes/client-node in wa frontends

- components/crud-web-apps/jupyter/manifests/base/deployment.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/authorization-policy.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/destination-rule.yaml
- components/crud-web-apps/jupyter/manifests/overlays/istio/kustomization.yaml
- components/crud-web-apps/tensorboards/manifests/base/deployment.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/authorization-policy.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/destination-rule.yaml
- components/crud-web-apps/tensorboards/manifests/overlays/istio/kustomization.yaml
- components/crud-web-apps/volumes/manifests/base/deployment.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/authorization-policy.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/destination-rule.yaml
- components/crud-web-apps/volumes/manifests/overlays/istio/kustomization.yaml
This PR fixes #6702.
The volumes, tensorboards and jupyter web app are vulnerable to user impersonation attacks, as any user can send HTTP requests to these services while freely setting the `kubeflow-userid` header. A malicious user may exploit this to impersonate any other user and create notebooks, tensorboard etc. on their behalf. 
Since the web apps are currently not part of the istio mesh, there is no instance overwriting or validating this header.
Remove the disable sidecar annotations and configure istio using authorizationpolicies.
> Adding web apps to istio service mesh

- components/crud-web-apps/jupyter/manifests/base/kustomization.yaml
- components/crud-web-apps/tensorboards/manifests/base/kustomization.yaml
- components/crud-web-apps/volumes/manifests/base/kustomization.yaml
This PR fixes the change made in https://github.com/kubeflow/kubeflow/pull/6395, because it did not tell the Kustomize manifests to treat `TWA_APP_SECURE_COOKIES` as a variable in `ConfigMap/parameters`.
This causes the current manifests for Kubeflow 1.6.1 to set the [`APP_SECURE_COOKIES` env-var](https://github.com/kubeflow/kubeflow/blob/17740d765223ef054229631ea327dfee87956f99/components/crud-web-apps/tensorboards/manifests/base/deployment.yaml#L24-L25) as the literal value `"$(TWA_APP_SECURE_COOKIES)"`, rather than `"true"` or `"false"`.
> fix APP_SECURE_COOKIES manifest parameters

- components/crud-web-apps/jupyter/backend/apps/common/utils.py
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
Instead of parsing the date in the backend we should use our common UI date component, in order to show dates in a uniform way.
Relevant PR https://github.com/kubeflow/katib/pull/1989
/cc @elenzio9 @tasos-ale
> jwa: Use common date component for age

- components/tensorboard-controller/controllers/tensorboard_controller.go
tensorboard-controller: Fix tensorboard endless restarts
tensorboards-web-app deletes objects using foreground deletion policy, Tensorboard CR will stay until all owned objects are deleted reconcile loop might keep on trying to recreate the resources that the API server tries to delete. so when Tensorboard CR is terminating, reconcile loop should do nothing
This commit allow manager to skip reconcile while Tensorboard CR is deleting.
> tensorboard-controller: Fix tensorboard endless restarts

- components/crud-web-apps/common/frontend/kubeflow-common-lib/angular.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/poller.service.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/poller.service.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/jupyter/frontend/angular.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.ts
- components/crud-web-apps/tensorboards/frontend/angular.json
- components/crud-web-apps/tensorboards/frontend/package.json
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
- components/crud-web-apps/tensorboards/frontend/src/proxy.conf.json
- components/crud-web-apps/volumes/backend/Makefile
- components/crud-web-apps/volumes/frontend/angular.json
- components/crud-web-apps/volumes/frontend/package.json
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.ts
- components/crud-web-apps/volumes/frontend/src/proxy.conf.json
- components/crud-web-apps/volumes/frontend/src/proxy.conf.rok.json
While working on the [all-namespaces support](https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220621-all-namespaces.md), follow up of https://github.com/kubeflow/kubeflow/pull/6706, I noticed that we currently don't cancel inflight requests.
This means that if a user changes the namespace, and there's delay in the requests, then they will keep seeing objects from the previous namespace. Then once new requests succeed the data will be updated accordingly.
To reproduce this you can set a `2s latency` in the DevTools and try to switch namespace. 
This PR creates a common Angular Service for polling that:
1. Handles exponential polling
2. Uses RxJS observables to handle the requests. This way when we unsubscribe the requests get cancelled
/cc @tasos-ale
> web-apps: Ensure in-flight requests are cancelled 

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/logs-viewer/logs-viewer.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
This PR introduces a Logs Viewer component in order to be able to **show an object's logs in our WAs**. This component is identical to the one we use in Models Web app.
This PR is required for efforts that are going to introduce a Details page for Notebooks, Volumes and TensorBoards  https://github.com/kubeflow/kubeflow/issues/6707, since an essential part of the Details page will be the `LOGS` tab.
> web-apps(front): Introduce Logs Viewer component

- components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/.eslintrc.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/karma.conf.js
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/README.md
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/editor.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/editor/interfaces/monaco.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/frontend/editor-loader.service.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.html
In a lot of our KF web apps we have a YAML editor/shower. Initially we had used [ng2-ace-editor](https://github.com/fxmontigny) but there are some problems with this `npm` module:
1. It is heavily unmaintained
2. A lot of people have reported issues with Angular Ivy, which is the new ViewEngine for Angular
https://github.com/fxmontigny/ng2-ace-editor/issues/118
https://github.com/fxmontigny/ng2-ace-editor/issues/141
This PR replaces the old editor with a new component that wraps and integrates [Monaco Editor](https://github.com/microsoft/monaco-editor) as an AMD module. This component is introduced as part of the Kubeflow Common Library, thus will be accessible to all WAs.
>  web-apps(front): Introduce new Editor component

- .github/workflows/frontend_lint.yaml
- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/backend/backend.service.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/types.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/tsconfig.lib.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/tsconfig.json
- components/crud-web-apps/jupyter/frontend/package-lock.json
- components/crud-web-apps/jupyter/frontend/package.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/tensorboards/frontend/package.json
- components/crud-web-apps/volumes/frontend/package-lock.json
- components/crud-web-apps/volumes/frontend/package.json
Follow up of review comments in https://github.com/kubeflow/kubeflow/pull/6706
In this PR I've moved to the common code:
1. Dynamically showing the `Namespace` column, in the common table component, if all-namespaces is selected
2. Common handlers for creating the multiple http calls, for all namespaces
3. The logic for resetting the polling if the data received is different
* We now always expect that the received objects are K8s objects with `.metadata.name` fields
Lastly I've modified the code of the JWA to use this common code for showing objects from all-namespaces.
/cc @tasos-ale 
if we are OK with these changes I can then send a follow-up PR for adding this functionality to the rest of the web apps
> web-apps: Common code for all-namespaces

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
This PR:
- Introduce the sorting functionality in the common code.
- Enable sorting in JWA.
A screenshot of how it will look like:
The plan is to make VWA and TWA support sorting as well.
Related issue: https://github.com/kubeflow/kubeflow/issues/6460
> Sorting support for JWA

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/namespace-selector.js
When visiting Kubeflow, [the first owned namespace is selected automatically](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/public/components/namespace-selector.js#L168).
As a user, this annoys me when: 
- I don't own a namespace and am only a contributor to namespaces. In this case, no namespace is selected, and I need to make a selection each time I visit Kubeflow.
- There are multiple namespaces available, as a "random" selection will be made for me.
In this PR, I've integrated the local storage to save the user's last selection. When visiting Kubeflow without the namespace being part of the URL, the local storage is prompted, and - if possible - the user's previous selection restored.
> Remember the most recently selected namespace

- components/centraldashboard/public/components/iframe-container.js
- components/centraldashboard/public/components/iframe-container_test.js
- components/centraldashboard/public/library.js
- components/centraldashboard/public/library_test.js
A Kubeflow app can communicate with the dashboard using a Pub/Sub mechanism. In order for this to work, the app should live in the dashboard's `iframe`. 
But if we want to open a Kubeflow app [programmatically](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) from the dashboard or from another app, the communication does not work. The current implementation requires an `iframe` to bridge the communication and in this PR we extend it and use the dashboard's window as an alternative bridge.
> centraldashboard: Add support for apps in new windows

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/kubeflow.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
This PR adds the filtering functionality in the web apps. 
Here some screenshots of how it looks like:
Related issue: https://github.com/kubeflow/kubeflow/issues/6462
> Filtering support for the web apps

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/utils.ts
This PR enables sorting in namespace column when displayed.
Related issue: https://github.com/kubeflow/kubeflow/issues/6460
Related PRs: https://github.com/kubeflow/kubeflow/pull/6742, https://github.com/kubeflow/kubeflow/pull/6743
Signed-off-by: Elena Zioga <elena@arrikto.com>
> web-apps(front): Enable sorting in namespace column

- components/centraldashboard/README.md
- components/centraldashboard/webpack.config.js
**Context**
Currently, running the Central dashboard locally and accessing  in-cluster services of K8s fails. With `kubectl proxy` and using [routes ](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/webpack.config.js#L199)like `/api/v1/namespaces/<ns>/*services*/<svc>/proxy`, what we actually do is sending our requests to the K8s service by passing via the K8s API Server (which we proxy with `kubectl proxy`). But this fails, since the K8s API Server is not allowed to talk to the services (Istio). 
**Change**
This PR fixes the proxies and instructions in order to run the app locally. What we propose essentially is to access a Kubenetes service with `kubectl port-forward -n kubeflow svc/<service-name> <service-proxy-port>:<service-port>` e.g. `kubectl …
> centraldashboard: Fix how the app is ran locally

- components/crud-web-apps/jupyter/README.md
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/types/notebook.ts
This PR resolves https://github.com/kubeflow/kubeflow/issues/6182.
Previously, the JWA UI threw an error when when `gpus.readOnly` was true, because of trying to access `num` when `gpus` was undefined in `NotebookFormObject`.
It also fixes the README for the JWA to show the correct build commands for local development.
> fix setting readOnly on gpus

- components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/help-popover/help-popover.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
In this PR, we introduce the following changes that will be needed in a follow-up PR that makes trials table support pagination/sorting/filtering (https://github.com/kubeflow/katib/issues/1441):
- Adjust filtering tooltip to expose info only for the existing columns.
- Extend table component to be able to highlight a row.
- Fix autocomplete dropdown bug.
Signed-off-by: Elena Zioga <elena@arrikto.com>
> web-apps(front): Changes needed for trials table

- components/crud-web-apps/jupyter/frontend/angular.json
- components/crud-web-apps/jupyter/frontend/package-lock.json
- components/crud-web-apps/jupyter/frontend/package.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/existing/existing-volume.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume/new/new.module.ts
This PR imports new Editor component from Kubeflow Common Library in JWA and replaces all instances of the previous Ace Editor. It is a follow up PR to this one https://github.com/kubeflow/kubeflow/pull/6733.
> jwa(front): Use new Editor component

- components/centraldashboard/public/components/namespace-selector.js
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/namespace-select/namespace-select.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.html
- components/crud-web-apps/jupyter/frontend/cypress/fixtures/notebook.ts
- components/crud-web-apps/jupyter/frontend/cypress/fixtures/settings.ts
- components/crud-web-apps/jupyter/frontend/cypress/integration/main-page.spec.ts
- components/crud-web-apps/jupyter/frontend/cypress/support/commands.ts
- components/crud-web-apps/jupyter/frontend/cypress/support/index.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/form/form.component.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
- components/crud-web-apps/tensorboards/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
- components/crud-web-apps/volumes/frontend/src/app/services/backend.service.ts
This should be the last work item for supporting all-namespaces for the web apps https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220621-all-namespaces.md
This PR:
* Adds support to the Volumes web app for all namespaces
* Adds support to the TensorBoards web app for all namespaces
* Updates the CentralDashboard to have the `All namespaces` option for the JWA, VWA and TWA
* Adds some e2e helpers (attribute selectors) and tests
> web-apps: Add support for all-namespaces in the Volumes and TensorBoards web apps

- components/crud-web-apps/jupyter/manifests/base/cluster-role.yaml
As part of the effort for the new Notebook details page in JWA, update the manifests for jwa's cluster role in order for JWA's service account to be able to **list pods and get pods/log** resources . This is part of [this effort](https://github.com/kubeflow/kubeflow/issues/6707).
> jwa: Update manifests to access Pods and Pods/log

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pod.py
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/logs/logs.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/jupyter/frontend/src/app/types/responses.ts
This PR adds a LOGS tab to the new JWA details page. It is part of [this effort](https://github.com/kubeflow/kubeflow/issues/6707) and a follow-up PR to [this PR](https://github.com/kubeflow/kubeflow/pull/6769). 
- In the case there is no Pod, we show a message that no logs are currently present. 
- We also show another tip/info that the Notebook is stopped, so that it's clear to the user why they don't see the logs
> jwa(front): Add LOGS tab to the notebook details page

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/notebook.py
- components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/config.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/events.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/jupyter/frontend/src/app/types/event.ts
- components/crud-web-apps/jupyter/frontend/src/app/types/responses.ts
This PR adds an EVENTS tab to the new JWA details page. It is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and a follow-up PR to [this](https://github.com/kubeflow/kubeflow/pull/6779). The goal of this tab is to present `Events` as we view them with `kubectl describe notebook <notebook-name> -n <namespace>`.
> jwa: Add EVENTS tab to Notebook details page

- .github/workflows/nb_controller_docker_publish.yaml
- components/notebook-controller/Makefile
* the  Build & Publish Notebook Controller  github workflow only releases docker image for linux-amd64 
*  Adding linux-ppc64le arch in workflow to release the docker image for ppc64le arch 
*  Using docker buildx and qemu to build the multi-arch docker images
> Adding multi-arch support for linux-ppc64le in CI for notebook-controller

- components/crud-web-apps/.gitignore
This PR creates a `.gitignore` file to ignore `web-apps-dev` files generated during the virtual env creation.
Signed-off-by: Elena Zioga <elena@arrikto.com>
> web-apps: Create .gitignore file to ignore web-apps-dev files

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/pvc.py
- components/crud-web-apps/volumes/backend/apps/default/routes/get.py
- components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
- components/crud-web-apps/volumes/frontend/src/app/app-routing.module.ts
- components/crud-web-apps/volumes/frontend/src/app/app.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.scss
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/link-groups-table.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/link-groups-table/types.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.scss
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.module.ts
- components/crud-web-apps/volumes/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/volumes/frontend/src/app/types/backend.ts
This PR is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and we used as a guideline what we 've done for [JWA ](https://github.com/kubeflow/kubeflow/pull/6769). It creates **a new volume details page where a user can navigate and see key information about each volume**. More specifically, it includes important information of the PVC focusing on `.spec` and `.status` fields. These can be _Access Modes, Size, Storage Class, OwnerReferences, Pods using the PVC._* 
Regarding Pods using the PVC, these will be grouped into "Pod types". As a first iteration, we will only include the following groups: `Notebook` and `InferenceService` since the rest of them require too many requests to deduce about the higher up owning …
> VWA: Create Volume details page

- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/yaml/yaml.module.ts
- components/crud-web-apps/jupyter/frontend/src/styles.scss
This PR adds a YAML tab to the new JWA details page. It is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and a follow-up PR to [this](https://github.com/kubeflow/kubeflow/pull/6782). This tab presents to the user the full YAML both from the Notebook and from its underlying pod, when there is one.
> jwa(front): Add YAML tab to Notebook details page

- .github/workflows/kfam_docker_publish.yaml
- components/access-management/Makefile
* the workflow "Build & Publish KFAM Docker" releases docker image for linux-amd64 
*  Added docker-build-multi-arch and build-push-multi-arch targets in Makefile  of access-management component 
*  Dropping docker-build and docker-push from workflow 
*  Keeping these steps will increase the workflow runtime 
*  docker-build-push-multi-arch builds and pushes the images for linux-amd64 and linux-ppc64le
> Adding support for linux-ppc64le in CI for kfam multi-arch docker image

- components/crud-web-apps/volumes/manifests/base/cluster-role.yaml
This is a complimentary PR to this https://github.com/kubeflow/kubeflow/pull/6788 and part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort. We need this in order to be able to show notebooks related to a PVC inside VWA.
> vwa: Update cluster role to list notebooks

- .github/workflows/prof_controller_docker_publish.yaml
- components/profile-controller/Makefile
* Adding support for linux-ppc64le in CI for profile-controller to release multi-arch-docker image
* Dropping the build profile-controller and push profile-controller from the workflow
*  Added build-multi-arch and build-push-multi-arch steps in workflow to build and push the multi-arch docker images for linux/amd64 and linux/ppc64le
*  Made the required changes in makefile for the same.
> Adding support for linux-ppc64le in CI for profile-controller

- .github/workflows/poddefaults_docker_publish.yaml
- components/admission-webhook/Makefile
• the workflow "Build & Publish PodDefaults Docker image          " releases docker image for linux-amd64
• Added docker-build-multi-arch and build-push-multi-arch targets in Makefile of admission-webhook component
• Dropping docker-build and docker-push from workflow
• Keeping these steps will increase the workflow runtime
•  "build-multi-arch" make rule builds the multi-arch docker image  and stores it in to build cache 
• docker-build-push-multi-arch  uses build cache and builds and pushes the images for linux-amd64 and linux-ppc64le
please review and merge.
> Adding support for linux-ppc64le in CI for admission-webhook multi-arch docker image

- .github/workflows/tb_controller_docker_publish.yaml
- components/tensorboard-controller/Makefile
- The workflow "TB_Controller_Docker_Publish" releases docker image for Linux-amd64.
- Added docker-build-multi-arch and build-push-multi-arch targets in the Makefile of the Tensorboard-controller component.
- Dropping docker-build and docker-push from the workflow.
- Keeping these steps will increase the workflow runtime.
- Docker-build-push-multi-arch builds and pushes the images for Linux-amd64 and Linux-ppc64le
- Below are the link to the workflow running from my fork and the published images.
Build Result Link:- https://github.com/amitmukati-2604/kubeflow/actions/runs/3619078575
Publish image Link:- https://hub.docker.com/r/amitmukati2604/tensorboard-controller/tags
> Adding support for linux/ppc64le in CI for tensorboard-controller multi-arch docker images.

- .github/workflows/twa_docker_publish.yaml
- components/crud-web-apps/tensorboards/Makefile
- The workflow "Twa_Docker_Publish" releases docker image for Linux-amd64.
- Added docker-build-multi-arch and build-push-multi-arch targets in the Makefile of the Tensorboard-web-app component.
- Dropping docker-build and docker-push from the workflow.
- Keeping these steps will increase the workflow runtime.
- Docker-build-push-multi-arch builds and pushes the images for Linux-amd64 and Linux-ppc64le.
- Below are the link to the workflow running from my fork and the published images.
Build Result Link:- https://github.com/amitmukati-2604/kubeflow/actions/runs/3629023139
Publish image Link:- https://hub.docker.com/r/amitmukati2604/tensorboards-web-app/tags
> Adding support for linux/ppc64le in CI for tensorboard-web-app multi-arch docker images.

- components/crud-web-apps/volumes/frontend/angular.json
- components/crud-web-apps/volumes/frontend/karma.conf.js
- components/crud-web-apps/volumes/frontend/package-lock.json
- components/crud-web-apps/volumes/frontend/package.json
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/yaml/yaml.module.ts
This PR is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and a follow-up PR to [this](https://github.com/kubeflow/kubeflow/pull/6806). It adds a tab to show the full `yaml` file of the PVC.
> vwa(front): Add YAML tab to Volume details page

- components/crud-web-apps/jupyter/frontend/angular.json
- components/crud-web-apps/tensorboards/frontend/angular.json
- components/crud-web-apps/volumes/frontend/angular.json
In this PR, we enable source maps for all scripts, styles and node modules in both development and production in WAs.
> web-apps(front): Enable source maps in WAs

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/form.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.scss
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/form/section/section.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-cpu-ram/form-cpu-ram.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-image/form-image.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-name/form-name.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-name/form-name.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.scss
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.module.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-workspace-volume/form-workspace-volume.component.html
- components/crud-web-apps/jupyter/frontend/src/app/shared/utils/volumes/panel.ts
This PR reworks JWA's create page by performing the following changes:
- Remove the `namespace` input field
- Have the icon buttons with the logos of the IDEs on top, and hide the image customization into a collapsible section
- Expanding the `Custom Notebook` panel allows two different actions:
- To select among a list of pre-configured images of each type
- To configure a completely custom image. By checking the `Custom Image` checkbox, a new `Custom Image` field appears and the `Image` field is disabled
- CPU/RAM
-  Rename `Requests CPUs` to `Minimum CPU`, `Requested memory in Gi` to `Minimum Memory Gi`, `CPU Limit` to `Maximum CPU`, and `Memory limit in Gi` to `Maximum Memory Gi`
- Volumes
- Limit to just one workspace volume:
- Hide the add buttons when one workspace volume is …
> jwa(front): Rework the create page

- .github/workflows/vwa_frontend_tests.yaml
- components/crud-web-apps/volumes/frontend/.eslintrc.json
- components/crud-web-apps/volumes/frontend/package.json
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/overview.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pods-mock.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/pvc-mock.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/volume-details-page.component.ts
This PR is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and a follow-up PR to [this](https://github.com/kubeflow/kubeflow/pull/6823). This adds:
- Query parameter handling for each tab in order for the user to be able to navigate directly to the tab of choice inside the Volume details page.
- Unit tests for `volume-details-page` component and `overview` component
- GH action that runs the unit tests on each PR.
> vwa(front): Handle query parameters and add unit tests 

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/conditions-table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/config.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/backend/backend.service.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/title-actions-toolbar/title-actions-toolbar.component.scss
- components/crud-web-apps/jupyter/frontend/.eslintrc.json
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-rok/index-rok.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-mock.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/notebook-page.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/overview/overview.component.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/pod-mock.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/actions.service.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/actions.service.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/backend.service.ts
- components/crud-web-apps/jupyter/frontend/src/app/services/config.ts
This PR is part of the [Details page for each Notebooks/Volumes/TensorBoards](https://github.com/kubeflow/kubeflow/issues/6707) effort and a follow-up PR to [this](https://github.com/kubeflow/kubeflow/pull/6790). It introduces:
- Buttons in the Notebook details page for **Connect, Start/Stop and Delete** actions.
- Query parameter handling for each tab in order for the user to be able to **navigate directly to the tab of choice** inside the Notebook details page.
- A fixup in Conditions table sorting functionality by adding default values to each column.
- **Unit tests for notebook-page component**. More specifically, tests check that the page
- Shows only the proper tab according to query parameters passed.
- Switches tabs according to query parameters passed.
- Updates disabled field of …
> jwa(front): Add details page functionalities & unit tests

- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.html
- components/crud-web-apps/tensorboards/frontend/src/app/pages/index/index.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
**Context**
Fix a bug in the namespace selectors of JWA, VWA and TWA. In order to show the namespace selector, they only checked if there is no `env.production` variable available. This resulted in the selector not showing even if there was no dashboard which is not expected. 
**Solution**
We will just copy what we do in KWA https://github.com/kubeflow/katib/blob/master/pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.html#L3-L6
> web-apps(front): Fix namespace selector bug

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/conditions-table/config.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/types/table.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/notebook-page/events/config.ts
- components/crud-web-apps/volumes/frontend/src/app/app.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/form/form-rok/form-rok.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/index-rok.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/events/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pod-groups-mock.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/volume-details-page/overview/pods-mock.ts
**Context**
In our WAs' details pages, we keep tables exposing events and conditions of each object in order to help the user have a better overview of its state and be able to troubleshoot problems that may arise. However, all tables are sorted by default according to their **Name** column. This feels counterintuitive since both events and conditions are attributes that expose the history of what has happened with the object. Thus, we would like to expose them by default sorted by timestamp.
**Changes**
- Configure tables to accept input for which column & direction they should sort during initialization
- Implement this functionality in tables with events and conditions in our WAs, in order to initialize these tables based on timestamp.
> web-apps(front): Sort events & conditions tables by date

- .github/workflows/nb_server_codeserver_python_docker_publish.yaml
- .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
- .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
- .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
- .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
- components/example-notebook-servers/Makefile
- components/example-notebook-servers/base/Makefile
- components/example-notebook-servers/codeserver-python/Makefile
- components/example-notebook-servers/codeserver/Makefile
- components/example-notebook-servers/jupyter-pytorch-full/Makefile
- components/example-notebook-servers/jupyter-pytorch/Makefile
- components/example-notebook-servers/jupyter-scipy/Makefile
- components/example-notebook-servers/jupyter-tensorflow-full/Makefile
- components/example-notebook-servers/jupyter-tensorflow/Makefile
- components/example-notebook-servers/jupyter/Makefile
- components/example-notebook-servers/rstudio-tidyverse/Makefile
- components/example-notebook-servers/rstudio/Makefile
This is a follow-up PR to address https://github.com/kubeflow/kubeflow/pull/6854#discussion_r1053260293 and is part of https://github.com/kubeflow/kubeflow/issues/6766
Changes:
- Fix Makefiles to use a `REGISTRY` env var to set registry prefix when building/pushing notebook-server images
- Fix publish workflows to Build/Push notebook-server images via `docker-build` & `docker-push` Makefile rules with appropriate tags:
- Always Build/Push notebook-server images with `TAG=$(shell git describe --tags --always --dirty)`
- Build/Push notebook-server images with `TAG=latest` only when the target branch is master
- Build/Push notebook-server images with `TAG=$(cat releasing/version/VERSION)` when
Version changes
- Update KF manifests to use `latest` tag for notebook-server images
> Fix Makefiles/Workflows/Manifests for the example-notebook-server images

- .github/workflows/centraldb_angular_docker_publish.yaml
- .github/workflows/centraldb_docker_publish.yaml
- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/nb_server_codeserver_python_docker_publish.yaml
- .github/workflows/nb_server_jupyter_pytorch_full_docker_publish.yaml
- .github/workflows/nb_server_jupyter_scipy_docker_publish.yaml
- .github/workflows/nb_server_jupyter_tf_full_docker_publish.yaml
- .github/workflows/nb_server_rstudio_tidyverse_docker_publish.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/vwa_docker_publish.yaml
This is a follow up PR to address https://github.com/kubeflow/kubeflow/pull/6860#issuecomment-1360960463 and is part of https://github.com/kubeflow/kubeflow/issues/6766
- Revert changes introduced in https://github.com/kubeflow/kubeflow/pull/6849 regarding fetching all history for all tags and branches when workflows run. This is because the images end up having a tag for `RC0` of `v1.5` from the main branch.
- The workflows build/push images with hash commit tags.
Signed-off-by: Apostolos Gerakaris <apoger@arrikto.com>
> gh-actions: Revert changes for fetching full git history in the workflows

- components/centraldashboard-angular/Dockerfile
- components/centraldashboard-angular/frontend/.eslintrc.json
- components/centraldashboard-angular/frontend/angular.json
- components/centraldashboard-angular/frontend/package-lock.json
- components/centraldashboard-angular/frontend/package.json
- components/centraldashboard-angular/frontend/proxy.conf.json
- components/centraldashboard-angular/frontend/public/library.js
- components/centraldashboard-angular/frontend/tsconfig.json
- components/centraldashboard-angular/frontend/webpack.config.js
This PR is part of the [Central Dashboard Rewrite effort](https://github.com/kubeflow/kubeflow/issues/6000). 
- Enable **source maps** for all scripts, styles and node modules in both development and production.
- Configure ESLint
- Import `libary.js` file from the old centraldashboard project into `frontend/public` directory. Built it using webpack exporting the built file under `dist/public`, and use a `glob` to copy it into assets for serving. For local development, create a proxy route for the `dashboard.lib.js` file in order to fetch this from the backend. (We will also need an entry for the /api route in the future)
> centraldashboard-angular(front): Add library.js, source-maps & ESLint

- .github/workflows/centraldb_angular_frontend_test.yaml
- components/testing/gh-actions/resources/test-notebook.yaml
- components/testing/gh-actions/resources/user-profile.yaml
In this commit we extend workflow for running CDB (Angular) frontend tests. For the CentralDashboard (Angular) tests we also need to ensure some underlying apps are proxied.
In this commit we extended the dedicated workflow for the frontend tests by:
1. Applying the necessary KF Controllers (Profiles, Notebooks)
2. Applying the JWA manifests and port-forward its k8s Service
3. Applying the VWA manifests and port-forward its k8s Service
4. Creating a user namespace (kubeflow-user) via a Profile
5. Creating a test Notebook, with a PVC, in that namespace
Next steps will be to run the Cypress tests of the CDB (Angular) that will be using the proxied apps.
/cc @orfeas-k 
/cc @tasos-ale 
/cc @apo-ger
> gh-actions: Create testing setup for CDB tests

- components/crud-web-apps/jupyter/frontend/cypress/integration/form-page.spec.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-data-volumes/form-data-volumes.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/mount/mount.component.html
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/mount/mount.component.ts
- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/volume/new/name/name.component.html
- components/crud-web-apps/jupyter/frontend/src/app/shared/utils/volumes/forms.ts
Fix an issue in JWA's form and change the volume's mount path when the volume's name changes. This feature is already working for workspace volumes. Also, add one more e2e test for the volume's mount path.
> jwa(front): Auto update mount path

- components/centraldashboard-angular/README.md
- components/centraldashboard-angular/frontend/proxy.conf.json
- components/centraldashboard-angular/frontend/src/app/app-routing.module.ts
- components/centraldashboard-angular/frontend/src/app/app.module.ts
- components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.html
- components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.spec.ts
- components/centraldashboard-angular/frontend/src/app/pages/home-page/home-page.component.ts
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.html
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.spec.ts
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
- components/centraldashboard-angular/frontend/src/app/pipes/safe.pipe.spec.ts
- components/centraldashboard-angular/frontend/src/app/pipes/safe.pipe.ts
This PR is part of the [Central Dashboard Rewrite effort](https://github.com/kubeflow/kubeflow/issues/6000) and it implements the functionality described in detail in this [comment](https://github.com/kubeflow/kubeflow/issues/6000#issuecomment-1341254207). In short, our goal is have an Iframe that will contain the KF web apps, detect changes in the Iframe's internal URL and reflect those changes in the browser's URL.
In more detail, functionalities that are implemented in this PR are:
- Detect changes in `iframe`'s internal URL by checking in time intervals. Upon change, modify the browser's (Router) URL to be the same as the `iframe`'s one.
- Update `iframe`'s `src` property based on route events.
- Send manually a postMessage with a hardcoded namespace `'kubeflow-user'` in order to be …
> centraldashboard-angular(front): Sync Browser and Iframe URLs

- components/admission-webhook/examples/poddefault-inject-containers.yaml
- components/admission-webhook/main.go
- components/admission-webhook/main_test.go
- components/admission-webhook/manifests/base/crd.yaml
- components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
This PR resolve https://github.com/kubeflow/kubeflow/issues/6745
> add support of initContainers and sideCars in poddefault

- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.html
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.scss
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
Style the dashboard and the iframe in order for the iframe to be responsive, fit in the screen and not exceed it. 
This resolves the issue from the comment here https://github.com/kubeflow/kubeflow/pull/6856#issuecomment-1381649212 and is part of the [Central Dashboard Rewrite effort](https://github.com/kubeflow/kubeflow/issues/6000).
cc @kimwnasptd
> cdb-angular(front): Fix Iframe's sizing to fit to screen

- components/profile-controller/controllers/plugin_iam.go
- components/profile-controller/controllers/plugin_iam_test.go
AWS IAM service account profile plugin mutates the trust relationship in the iam role specified in the spec. 
Customers have different ways to manage roles and their company policies might not allow Kubeflow profile controller to allow changing the trust relationship. 
Adding a boolean variable to the AwsIAMForServiceAccount struct to enable users to specify if they want AnnotateOnly which will cause IAM roles and policy will not be mutated.
This change will not effect existing users who do not have the boolean field in their yaml files.
> [Profile controller IAM plugin] Support annotation only

- components/example-notebook-servers/rstudio/Dockerfile
Update the RStudio image to be able to handle multiple values in the `X-Forwarded-{Proto,Host}` headers. The server should care about the first values which are the ones the user's browser is using.
The fixes for these have been integrated in https://github.com/rstudio/rstudio/issues/11010 and https://github.com/rstudio/rstudio/issues/10965
Note, to bump into this you need to have at least 2 proxies that handle the `X-Forwarded-*` headers. In our case we had both an ALB loadbalancer and an NGINX in front of the ingressgateway, and that's why we bumped into this.
> rstudio: Update version to properly handle X-Forwarded headers

- components/tensorboard-controller/config/base/kustomization.yaml
- components/tensorboard-controller/controllers/tensorboard_controller.go
This PR adds functionality for adding pod default related labels for tensorboard pods in tensorboard controller.  This can be used for various things like configuring cloud storage parameters using environment variables(#6493), service account, tolerations etc.
User experience:
1. User creates a tensorboard CR with required labels (`metadata.labels`)
2. Controller will create the deployment with labels on the pod copied from the tensorboard CR
3. Admission webhook will take care of injecting necessary configurations according to poddefault
Updated the image version because v2.1.0 did not work with IAM roles. Using the latest version would require building and maintaining an image because some functionality is moved out to a different package(tensorflow-io). This package is not installed …
> Support Pod Defaults in Tensorboard controller

- components/Makefile
- components/example-notebook-servers/Makefile
- components/example-notebook-servers/codeserver-python/Makefile
- components/example-notebook-servers/codeserver/Makefile
- components/example-notebook-servers/jupyter-pytorch-full/Makefile
- components/example-notebook-servers/jupyter-pytorch/Makefile
- components/example-notebook-servers/jupyter-scipy/Makefile
- components/example-notebook-servers/jupyter-tensorflow-full/Makefile
- components/example-notebook-servers/jupyter-tensorflow/Makefile
- components/example-notebook-servers/jupyter/Makefile
- components/example-notebook-servers/rstudio-tidyverse/Makefile
- components/example-notebook-servers/rstudio/Makefile
This PR addresses https://github.com/kubeflow/kubeflow/issues/6872
Currently there is a single [build-all](https://github.com/kubeflow/kubeflow/blob/1fe6dbcd0882cc645fe079c0c70dbf9d63aa87e8/components/Makefile#L4-L35) rule in the `top-level Makefile` under components/ dir that calls all sub-makefiles for building all KF images in a serial manner. This makes the whole process very time-consuming as we can't use the `-j` option of `make` to run jobs in parallel.
Changes to the `top-level Makefile` for building all KF images:
- Create a single rule for each directory containing a sub-makefile
- Have each directory rule as a dependency to the build-all rule in the central Makefile
This way every directory rule can run in parallel with other rules.
Similarly, the [central …
> make: Build KF images in parallel

- components/centraldashboard/Dockerfile
* changing  the base node image to node:12.22.12-bullseye  as it has required 'chromium' pkg for amd64, pc64le and arm64  architectures.
* build-test the dockerfile on amd64 and ppc64le 
please review and merge.
> Updating central-board Dockerfile for multi-arch support

- components/centraldashboard/manifests/base/configmap.yaml
- components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
This PR renames `Models` to `Endpoints` in the central dashboard.
Related issue: https://github.com/kserve/kserve/issues/2534
Related PR: https://github.com/kserve/models-web-app/pull/57
>  centraldashboard: Rename Models to Endpoints

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/component-value/component-value.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/resource-table.module.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.html
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.ts
- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/public-api.ts
- components/crud-web-apps/volumes/backend/apps/common/utils.py
- components/crud-web-apps/volumes/backend/apps/default/routes/get.py
- components/crud-web-apps/volumes/backend/apps/rok/routes/get.py
- components/crud-web-apps/volumes/backend/apps/rok/utils.py
- components/crud-web-apps/volumes/frontend/cypress/fixtures/pvcs.json
- components/crud-web-apps/volumes/frontend/src/app/app.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/columns.module.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/delete-button/delete-button.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.html
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.scss
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.spec.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/columns/used-by/used-by.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/config.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-default/index-default.component.ts
- components/crud-web-apps/volumes/frontend/src/app/pages/index/index-rok/config.ts
- components/crud-web-apps/volumes/frontend/src/app/types/backend.ts
Right now, VWA checks whether a PVC is mounted to a Pod. If not, then it allows users to delete the PVC. When a user stops a notebook server, then the notebook Pod gets deleted. Thus, VWA will allow a user to delete a PVC that used to be mounted to the notebook. This results in the corresponding notebook not being able to start.
We want to prevent a user from being able to delete a PVC, even when the corresponding notebook is stopped and there is no Pod currently mounted to it.
The ideal UX would be to check for all PVCs which of them can be deleted and **disable the delete buttons for the ones that the user cannot delete**, so they cannot click an action that we are able to know beforehand it will fail. However, **checking if a PVC can be deleted requires checking for mounted pods, as …
> vwa(front): Prevent PVCs from being deleted when there is a corresponding notebook

- components/testing/gh-actions/install_cert_manager.sh
This PR is based on the initial work of @kimwnasptd: https://github.com/kubeflow/kubeflow/pull/6921
This should fix the problem we bumped into with using cmctl to generate the manfiests
```
chart requires kubeVersion: >= 1.21.0-0 which is incompatible with Kubernetes v1.20.0
```
We've seen this error in a couple of PRs https://github.com/kubeflow/kubeflow/pull/6893 https://github.com/kubeflow/kubeflow/pull/6917
Instead we'll use the generated cert-manager.yaml file that comes with each Cert Manager release. I.e.
https://github.com/cert-manager/cert-manager/releases/tag/v1.11.0
> Update GH Action script for installing Cert Manager

- .github/workflows/centraldb_angular_intergration_test.yaml
- .github/workflows/centraldb_intergration_test.yaml
- .github/workflows/jwa_intergration_test.yaml
- .github/workflows/nb_controller_intergration_test.yaml
- .github/workflows/poddefaults_intergration_test.yaml
- .github/workflows/profiles_kfam_intergration_test.yaml
- .github/workflows/tb_controller_intergration_test.yaml
- .github/workflows/twa_intergration_test.yaml
- .github/workflows/vwa_intergration_test.yaml
This PR addresses https://github.com/kubeflow/kubeflow/pull/6916#issuecomment-1408865920 and is part of https://github.com/kubeflow/kubeflow/issues/6766
Right now, the KF integration tests do not work when we update the manifests for RCs. The `sed` command does not work since it tries to replace the `latest` tag, which doesn't exist in the release branches.
Changes:
* Update the workflows to use the `kustomize edit image <curr_img>=<new_img>:<tag>` command (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md) to set the appropriate tag in the manifests before they are applied . 
Signed-off-by: Apostolos Gerakaris <apoger@arrikto.com>
> gh-actions: Fix KF intergration tests for release branches

- .github/workflows/centraldb_angular_frontend_test.yaml
- components/centraldashboard-angular/backend/package.json
- components/centraldashboard-angular/frontend/.gitignore
- components/centraldashboard-angular/frontend/README.md
- components/centraldashboard-angular/frontend/cypress.config.ts
- components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
- components/centraldashboard-angular/frontend/cypress/fixtures/example.json
- components/centraldashboard-angular/frontend/cypress/support/commands.ts
- components/centraldashboard-angular/frontend/cypress/support/e2e.ts
- components/centraldashboard-angular/frontend/package-lock.json
- components/centraldashboard-angular/frontend/package.json
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
- components/centraldashboard-angular/frontend/src/app/shared/utils.ts
This PR is part of the [CentralDashboard Rewrite effort](https://github.com/kubeflow/kubeflow/issues/6000) and adds UI tests with Cypress for the CentralDashboard-angular component. The tests are about functionalities introduced in the [sync browser and iframe URLs PR](https://github.com/kubeflow/kubeflow/pull/6856).
- User navigates to pages inside the WA they 're already in by clicking links.
- User navigates to another WA from the one they were previously in e.g. from JWA details page, they click to the corresponding PVC.
- User clicks and affects only the query parameters of the current URL e.g. navigates to another tab inside a WA's details page
In all of the above, we need to make sure that the browser's URL always corresponds to the page the user currently views.
Some details on …
> cdb-angular(front): Add UI tests

- components/centraldashboard/Dockerfile
- components/centraldashboard/public/components/logout-button.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
Required as a part of https://github.com/kubeflow/manifests/pull/2150
Fixes the logout button in the Central Dashboard to work with the recent versions of the `oidc-authservice` (tested with `gcr.io/arrikto/kubeflow/oidc-authservice:e236439` image version)
Changes:
* Pin alpine repository version
* Introduce a new LogoutButton component
> Fix the logout button to work with the recent version of `oidc-authservice`

- components/profile-controller/controllers/profile_controller.go
> Fix the bug of ResourceQuota removal

- components/crud-web-apps/common/frontend/OWNERS
- components/crud-web-apps/jupyter/frontend/OWNERS
- components/crud-web-apps/tensorboards/frontend/OWNERS
- components/crud-web-apps/volumes/frontend/OWNERS
Making a PR to update the OWNERS for the frontend code of our `crud-web-app`. It had taken me way to long to send this PR, and thus I'm adding new approvers and not going gradually via first assigning reviewers.
Both @orfeas-k and @elenzio9 have both a ton of PRs for the frontends and also reviewed a lot of the PRs. Listing some for completeness:
For @orfeas-k: https://github.com/kubeflow/kubeflow/commits?author=orfeas-k
* https://github.com/kubeflow/kubeflow/pull/6899
* https://github.com/kubeflow/kubeflow/pull/6822
* https://github.com/kubeflow/kubeflow/pull/6788
* https://github.com/kubeflow/kubeflow/pull/6862
For @elenzio9: https://github.com/kubeflow/kubeflow/commits?author=elenzio9
* https://github.com/kubeflow/kubeflow/pull/6826
* https://github.com/kubeflow/kubeflow/pull/6742
* …
> Add approvers to the frontends

- components/centraldashboard/public/components/activities-list_test.js
Fix `Activities list` test that was failing because `new Date()` added whitespace that was not equal to the space character during comparison. 
Link to related PR https://github.com/kubeflow/kubeflow/pull/6945#issuecomment-1431257676 cc @kimwnasptd
> centraldashboard: Fix failing test 

- components/centraldashboard/Makefile
Previously the app would not use the correct directory when running the docker buildx command, which resulted in the image to fail to get built.
I also realized that we are not testing the `docker buildx` flow in each PR, this is why this was never caught in https://github.com/kubeflow/kubeflow/pull/6923. We'll need to extend the current actions to use the same build process to ensure we catch this in a timely manner. 
I'll ping on the corresponding issue
/cc @elikatsis
> centraldashboard(make): Use correct dir

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/resource-table/table/table.component.spec.ts
This fixes a flaky unit test regarding filter. This PR is cherry-picked from commit `15ed6eb1cb0a8a4523e8fcac968be82c0e02890c` in this [PR](https://github.com/kubeflow/kubeflow/pull/6918).
> web-apps(front): Fix flaky filtering unit test

- components/centraldashboard/app/k8s_service.ts
- components/centraldashboard/app/k8s_service_test.ts
- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/public/components/logout-button.js
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
- components/centraldashboard/public/components/namespace-selector.js
Use dynamic URL for the logout button that can be set by the `LOGOUT_URL` ENV variable in the deployment of the app. If it is unset, a default '/logout' string is passed from the backend to the frontend.
I documented in the issue [here ](https://github.com/kubeflow/kubeflow/issues/6940#issuecomment-1427637200)details on how I dealt with binding data between Polymer elements.
During this PR, we also had to fix a test that was broken. It seems that the test was failing because `new Date ()` added whitespace that was not equal to the space character during comparison. Instead of comparing objects of type `Date` and `string` in the expect statement, we went with comparing `Date` objects in order to ensure comparison in a uniform and type-strict way.
> centraldashboard: Support dynamic logout URL

- releasing/README.md
Add the release process to the `/releasing` README with reference to the release handbook
- Resolves https://github.com/kubeflow/kubeflow/issues/6900
- Replaces https://github.com/kubeflow/community/pull/603 and https://github.com/kubeflow/community/pull/601 (Discussed with @jbottum and the CNCF transition members in the last meeting)
/hold for https://github.com/kubeflow/community/pull/610
cc @kimwnasptd @jbottum
> Document the release process for Notebooks

- components/centraldashboard/public/components/namespace-selector.js
In this PR, we enable all-namespace support in KWA by displaying the `All namespaces` option in the dashboard.
Related PR: https://github.com/kubeflow/katib/pull/2119
> centraldashboard: Allow all-namespaces option for kwa

- components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
- components/centraldashboard-angular/frontend/cypress/fixtures/dashboardlinks.json
- components/centraldashboard-angular/frontend/cypress/fixtures/envinfo.json
- components/centraldashboard-angular/frontend/cypress/support/commands.ts
- components/centraldashboard-angular/frontend/cypress/support/e2e.ts
- components/centraldashboard-angular/frontend/src/app/pages/iframe-wrapper/iframe-wrapper.component.ts
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.html
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.scss
- components/centraldashboard-angular/frontend/src/app/pages/main-page/main-page.component.ts
- components/centraldashboard-angular/frontend/src/app/services/backend.service.ts
- components/centraldashboard-angular/frontend/src/app/shared/utils.ts
- components/centraldashboard-angular/frontend/src/app/types/dashboard-links.ts
This PR is part of the [Rewrite the Central Dashboard in Angular effort](https://github.com/kubeflow/kubeflow/issues/6000) and implements the following two functionalities:
- Fetch the left sidebar links
Here, we also had to handle the until now unhandled **fragment/hash** in links. For that, we decided to always split links to its sub-parts (`path`, `queryParams`, `fragment`) and use the `fragment` option in `router.navigate`.
- Automatically change selected link from the sidebar
We couldn't go only with `routerLinkActive` for this and used a custom implementation instead since we need the `path + fragment` combination to be a subset of the browser's URL. In this implementation, we also added an explicit condition for checking when the user is in Recurring Runs WA since the KFP removes …
> cdb(front): Fetch left sidebar links

- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
This PR significantly cleans up (but does not change) the default `spawner_ui_config.yaml` to make it much easier to understand and customize.
---
The only change to default values is that I have removed the default `gpus.value.vendors` list, and left the previous values as a commented example, as most clusters don't have GPUs, so there is no reason to include them by default.
I have also updated the examples for `affinityConfig` and `tolerationGroup` to demonstrate how a user can cause Notebook to be scheduled on exclusive Nodes (no other Notebooks), using the new [`namespaceSelector` for pod-anti-affinity added in K8S 1.22](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#namespace-selector).
> clean up default `spawner_ui_config.yaml`

- components/profile-controller/controllers/profile_controller.go
profile controller does not work on the clusters which have a custom cluster domain because of the hardcoded "Principals".  
- https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/controllers/profile_controller.go#L466-L472 
Original code: 
```go
From: []*istioSecurity.Rule_From{
{
Source: &istioSecurity.Source{
Principals: []string{"cluster.local/ns/kubeflow/sa/notebook-controller-service-account"},
},
},
},
```
This PR adds support for arbitrary cluster domains by using the `CLUSTER_DOMAIN` environment variable.  
The environment variable `CLUSTER_DOMAIN` is optional, so the profile controller uses "cluster.local" as is when not set.  
Kindly review this PR.
> profile-controller: Support custom cluster domain other than cluster.local

- components/crud-web-apps/jupyter/backend/apps/common/form.py
Fixes: #6457 
Description: Trims the whitespace around custom images to avoid pod creation failures.
> Fix: Strip unwanted space in custom image name

- .github/workflows/centraldb_angular_docker_publish.yaml
It looks like after when the PR of mine [Show KF Version](https://github.com/kubeflow/kubeflow/pull/6918) was merged, the [Build & Publish CentralDashboard-Angular Docker image](https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/centraldb_angular_docker_publish.yaml) GH action started [failing](https://github.com/kubeflow/kubeflow/actions/runs/4165479958/jobs/7208537657). 
This PR fixes the issue which was caused due to shallow clone of the repo. This means that during the clone, git skips cloning the whole history and thus the following `docker build` command results with an empty `kubeflowversion` which is defined by this command `kubeflowversion=$(shell git describe --abbrev=0 --tags)`
```
docker build  -t centraldashboard-angular:intergration-test -f Dockerfile .. \ …
```
> gh-actions(cdb): Fix Build and Publish action

- components/centraldashboard/public/components/namespace-selector.js
In this PR, we enable all-namespace support in MWA by displaying the `All namespaces` option in the dashboard.
Related PR: https://github.com/kserve/models-web-app/pull/68
> centraldashboard: Allow all-namespaces option for mwa

- components/centraldashboard/app/k8s_service.ts
- components/centraldashboard/manifests/base/deployment.yaml
Fixed https://github.com/kubeflow/kubeflow/issues/7063
> centraldashboard: namespace value coming from env variable. Fixes #7063

- components/proposals/20230130-pvcviewer-controller.md
Provide a design doc as a proposal for introducing a PVCViewer Controller in Kubeflow. PVCViewers enable users to open a web app UI on arbitrary persistent volume claims, letting them inspect, download, upload and manipulate data.
Our proposal is in markdown format and follows the guidelines of the [kubeflow/components/proposal/README.md](https://github.com/kubeflow/kubeflow/blob/master/components/proposals/README.md) guide.
On-going effort: https://github.com/kubeflow/kubeflow/pull/6876
> proposal: Introduce a PVCViewer Controller in Kubeflow

- .github/workflows/centraldb_docker_publish.yaml
- .github/workflows/centraldb_intergration_test.yaml
- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/vwa_docker_publish.yaml
/kind feature
**Why you need this feature:**
Support for ARM VMs
With KF 1.7 we have Istio 1.16 which supports ARM,  **but** sadly kubeflow images don't have an ARM platform build so that one can run kubeflow locally on Apple M1 Mac **or**  on cloud  ARM based nodes  such as AWS Graviton
**Describe the solution you'd like:**
Updated github actions section that uses multi arch docker publish steps to support linux/arm64 platform
**Anything else you would like to add:**
I have tested it locally by building and pushing docker to my personal repo at https://hub.docker.com/repositories/vinaychandran 
It would be great if docker hub registry that kubeflow uses by default had these ARM variants.
> ARM docker images for kubeflow components

- .github/workflows/pvcviewer_controller_intergration_test.yaml
As discussed in https://github.com/kubeflow/kubeflow/pull/6876, we're adding a GH action that integration tests the pvcviewer controller / its manifests.
The Action is untested and was copied off the notebook controller which works the same way.
This PR is part of three pvcviewer controller workflows. The others are: 
* #7173
* #7174
> Add GH action integration testing pvcviewer controller

- components/admission-webhook/Makefile
- components/notebook-controller/Makefile
- components/pvcviewer-controller/Makefile
- components/tensorboard-controller/Makefile
According to [Deprecation of 'go get' for installing executables](https://go.dev/doc/go-get-install-deprecation), `go-get-tool` will not work after 1.18. So changed to `go install` in advance.
> fix: deprecation of 'go get' for installing modules

- components/centraldashboard/public/components/main-page.css
When we have a lot of item, on the maindrawer, the scrollbar appear, and the default one is pretty ugly and take a lot of space.
I simply copy past the style from kubeflow/pipeline elements and change the color to match the text.
| before | after |
|---|---|
| ![image](https://github.com/kubeflow/kubeflow/assets/42176370/c0897396-4bc1-4e3b-8c38-fd261257ecd0) | ![image](https://github.com/kubeflow/kubeflow/assets/42176370/607168c7-24ee-4379-be1f-c0b4c23469d2) |
> (frontend): Adding style for main drawer scrollbar

- components/access-management/kfam/bindings.go
- components/profile-controller/controllers/profile_controller.go
This is similar to this kerve issue https://github.com/kserve/kserve/issues/2197#issue-1248404440. Users can be impersonated without authentication by attaching the header `kubeflow-userid: ` with a valid profile contributor name to a request going to any namespace within the mesh.
```sh
(base) jovyan@tensorflow-0:~$ curl -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Tue, 07 Mar 2023 04:02:17 GMT
server: envoy
x-envoy-upstream-service-time: 4
(base) jovyan@tensorflow-0:~$ curl -H "kubeflow-userid: user@example.com" -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-exampl …
```
> Profile controller and KFAM allow unauthenticated in-cluster traffic

- .github/workflows/pvcviewer_controller_unit_test.yaml
As discussed in https://github.com/kubeflow/kubeflow/pull/6876, we're adding a GH action that runs the pvcviewer controller's unit tests.
The Action is untested and was copied off the notebook controller which works the same way.
This PR is part of three pvcviewer controller workflows. The others are:
* #7173
* #7175
> Add GH action unit testing pvcviewer controller

- .github/workflows/pvcviewer_controller_docker_publish.yaml
As discussed in #6876, we're adding a GH action that builds and pushes the pvcviewer controller docker image.
The Action is untested and was copied off the notebook controller which works the same way.
This PR is part of three pvcviewer controller workflows. The others are:
* #7174
* #7175
> Add GH action building pvcviewer controller

- components/notebook-controller/controllers/notebook_controller.go
Added Annotation propagation logic to notebook controllers. This will help to  propagate custom annotations like kiam to notebook pods from notebook custom resource. 
This pr fixes issue https://github.com/kubeflow/kubeflow/issues/6677
Results:
Annotation on Notebook CR:
Annotation on Notebook Pod:
> feat(notebooks): propagate annotations from notebook cr to pods

- components/pvcviewer-controller/config/crd/bases/kubeflow.org_pvcviewers.yaml
- components/pvcviewer-controller/config/default/cainjection_patch.yaml
- components/pvcviewer-controller/config/default/dnsnames_patch.yaml
- components/pvcviewer-controller/config/default/kustomization.yaml
- components/pvcviewer-controller/config/default/kustomizeconfig.yaml
- components/pvcviewer-controller/config/rbac/role.yaml
- components/pvcviewer-controller/config/rbac/role_binding.yaml
- components/pvcviewer-controller/config/webhook/manifests.yaml
* roleRef.name now matches role.metadata.name. 
Without this change, kustomize build doesn't correctly bind the resulting clusterrolebinding.
* Remove creationTimestamp: null as noted by @axel7083 
* Use commonLabels over labels to comply with old kustomize version. Also, I had to introduce the deprecated vars feature as replacements aren't supported with the current kustomize version used by the build pipeline
See #6876 for initial PR.
> Update  PVCViewer manifests

- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/pvcviewer_controller_docker_publish.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/vwa_docker_publish.yaml
Currently, all docker build pipelines are broken and GH actions are failing. Some examples:
* https://github.com/kubeflow/kubeflow/actions/runs/5717365930/job/15490946498
* https://github.com/kubeflow/kubeflow/actions/runs/5717283772/job/15490688661
* https://github.com/kubeflow/kubeflow/actions/runs/5718096836/job/15493211609
The error messages read: 
```
docker buildx build --platform linux/amd64, linux/ppc64le --tag kubeflownotebookswg/kfam:e706807 --push .
ERROR: "docker buildx build" requires exactly 1 argument.
```
Clearly, there's a superfluous space in `--platform`, which was, among others, just recently introduced in [3733989](https://github.com/kubeflow/kubeflow/commit/3733989a62b92b0751abef2c9da87f758128d487).
This PR removes the spaces.
The actions run fine in my repo after …
> fix: remove superfluous space in docker builds

- components/crud-web-apps/volumes/manifests/base/deployment.yaml
- components/crud-web-apps/volumes/manifests/base/viewer-spec.yaml
- components/pvcviewer-controller/README.md
The [pvcviewer pipeline](https://github.com/kubeflow/kubeflow/actions/workflows/pvcviewer_controller_docker_publish.yaml) has not yet run successfully.
Thus, there is no public image that could be used to test the manifests.
As far as I can tell, this should be the last effort to get the volumes viewer working. 
Also, I snuck in another commit, fixing two fields of the viewer-spec.yaml
> fix: viewer-spec.yaml and trigger build

- .github/workflows/centraldb_angular_intergration_test.yaml
- .github/workflows/centraldb_intergration_test.yaml
- .github/workflows/jwa_intergration_test.yaml
- .github/workflows/nb_controller_intergration_test.yaml
- .github/workflows/poddefaults_intergration_test.yaml
- .github/workflows/profiles_kfam_intergration_test.yaml
- .github/workflows/pvcviewer_controller_intergration_test.yaml
- .github/workflows/tb_controller_intergration_test.yaml
- .github/workflows/twa_intergration_test.yaml
- .github/workflows/vwa_intergration_test.yaml
Supersedes https://github.com/kubeflow/kubeflow/pull/7252
Fixes https://github.com/kubeflow/kubeflow/pull/7234
This PR does the following:
- ensures that only one instance of the integration test jobs can run at a time (per pr)
- replaces all redundant references like `${{env.TAG}}`, with their safer equivalents in bash, e.g. `${TAG}`
- fixes how we are replacing images, to support arbitrary tags, rather than assuming they are `latest`:
- this was causing https://github.com/kubeflow/kubeflow/pull/7234 to fail its tests
> ci: fix test image replacement

- components/crud-web-apps/volumes/manifests/base/deployment.yaml
Cloudflare users are having issues with the newest filebrowser release.
This PR downgrades filebrowser to v2.23.0 have uploads work for everyone. 
Unfortunately, this removes chunked uploads until we're upgrading to a fixed filebrowser version.
> fix: downgrade filebrowser to v2.23.0

- components/profile-controller/Makefile
- components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
Replacement of https://github.com/kubeflow/manifests/pull/2509, due to https://github.com/kubeflow/manifests/ is a mirror of part of this repo.
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/kubeflow/issues/7041, https://github.com/GoogleCloudPlatform/kubeflow-distribution/issues/431
**Description of your changes:**
When deploying KF 1.7 on GCP, this line,
```
creationTimestamp: null
```
caused the following error in deployment:
```
error: unable to decode "apps/profiles/build/apiextensions.k8s.io_v1_customresourcedefinition_profiles.kubeflow.org.yaml": parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
```
This seems to be due to golang being unable to handle `null` when unmarshalling timestamp. Currently, users have …
> fix: remove creationTimestamp line

- .github/workflows/centraldb_angular_integration_test.yaml
- .github/workflows/centraldb_integration_test.yaml
- .github/workflows/jwa_integration_test.yaml
- .github/workflows/nb_controller_integration_test.yaml
- .github/workflows/poddefaults_integration_test.yaml
- .github/workflows/profiles_kfam_integration_test.yaml
- .github/workflows/pvcviewer_controller_integration_test.yaml
- .github/workflows/tb_controller_integration_test.yaml
- .github/workflows/twa_integration_test.yaml
- .github/workflows/vwa_integration_test.yaml
Wait for deployment state instead of pod during test execution.
Relates #7251
> ci: wait for deployment instead of pods for test execution

- components/crud-web-apps/jupyter/backend/apps/common/utils.py
The process_gpus function calls load_spawner_ui_config for every notebook in a namespace when the get_notebooks endpoint is called. This change updates so the call is made once every 10 minutes. 
I was unsure if the expectation with this component is that users will be able to change the configmap without restarting the deployment. If not it would be better to load this config once at initialization. 
If that route is preferred I'd be happy to update this PR with those changes.
> Only load spawner_ui_config.yaml once every 10 minutes. closes #7259

- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
The change introduced by kubeflow/kubeflow#6736 removed the default GPU vendors list, which causes an issue when trying to select a vendor from the dropdown menu if the vendors list is not configured.
This commit can be reverted if proper documentation is provided for users/distributions to configure the dropdown menu.
Fixes #7273 in v1.8-branch
cc: @kimwnasptd @thesuperzapper
> fix: set default GPU vendors list

- .github/workflows/prof_controller_unit_test.yaml
- components/access-management/kfam/bindings.go
- components/access-management/kfam/utils.go
- components/profile-controller/config/manager/kustomization.yaml
- components/profile-controller/controllers/profile_controller.go
This is a follow-up to address https://github.com/kubeflow/kubeflow/pull/7032#issuecomment-1682614698
This PR will make all principals in Profile Controller configurable, so they should be changed from any distribution that deploys the components in different namespaces.
> Make principals dynamic in Profiles Controller

- components/crud-web-apps/jupyter/backend/apps/common/status.py
- components/crud-web-apps/jupyter/backend/apps/common/utils.py
This change fixes an error 500 on notebook creation in Kubeflow 1.8.
Background: the frontend may be faster accessing the status of the newly created Notebook than the controller can create it. This causes the user to see an empty Notebook page and an error 500.
> fix: KeyError on KF 1.8

- .github/workflows/poddefaults_unit_test.yaml
- components/admission-webhook/go.mod
During https://github.com/kubeflow/kubeflow/pull/7322 the tests were not triggered so we missed the failing unit-tests action. We found this out during cherry-picking https://github.com/kubeflow/kubeflow/pull/7337
This is because it needed golang at least 1.20 during the unit tests, to install one of the dependencies.
I also went and updated the golang version of the component and am testing to make sure we didn't miss something
/assign @tzstoyanov @thesuperzapper
> poddefaults: Bump golang to 1.20

- components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/styles/styles.scss
Right now the web-apps all become grey, because of a transparency change introduced by d4b6dff8
/assign @thesuperzapper
> wa(front): Make the background white of all webapps

- .github/workflows/centraldb_docker_publish.yaml
- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/pvcviewer_controller_docker_publish.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/vwa_docker_publish.yaml
https://github.com/kubeflow/kubeflow/pull/7333 made the CI to only build the images for different archs, but not push for the tag value of the commit.
This is because the code replaced
```bash
ARCH=amd64 make docker-build-multi-arch
```
While pushing the `latest` tag or a release version tag will work we still want to ensure we push an image with a tag.
You can find a [docker image](https://hub.docker.com/layers/kimwnasptd/notebook-controller/cb2590a/images/sha256-88e7248ee86db27f78b14537bcb1820de74881f37996839bc73f314d266ef5c6?context=repo) built with the above action , and the workflow that produced it in 
https://github.com/kimwnasptd/kubeflow/actions/runs/6526089745/job/17719463473
> ci: Push the multi-arch image for specific tag

- .github/workflows/notebook_controller_unit_test.yaml
Bump golang version in ci runners to correctly run tests. See https://github.com/kubeflow/kubeflow/pull/7338 for a similar issue.
This unblocks the CI for #7347
> ci: bump golang version 1.17->1.20

- components/centraldashboard-angular/frontend/cypress/e2e/url-syncing.cy.ts
- components/centraldashboard-angular/frontend/src/styles/styles.scss
It seems like the path to this file recently changed by #7062, which is now preventing the centraldashboard Docker image to build wich fails with a SassError when trying to import fonts.scss. This commit points to the right path.
Error log for reference:
```
#27 90.64 ./src/styles/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
#27 90.64 ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
#27 90.64 SassError: Can't find stylesheet to import.
#27 90.64    ╷
#27 90.64 11 │ @import '~kubeflow/lib/fonts.scss';
#27 90.64    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
#27 90.64    ╵
#27 90.64   src/styles/styles.scss 11:9  root stylesheet
```
See [this build](https://github.com/kubeflow/kubeflow/actions/runs/6531881 …
> fix: point to ~kubeflow/styles/fonts.scss

- components/pvcviewer-controller/controllers/pvcviewer_controller.go
Allows the user to specify an optional controller env var "ISTIO_GATEWAY", which allows for other istio gateways than "kubeflow/kubeflow-gateway".
See https://github.com/kubeflow/kubeflow/issues/7283
> feat: make pvcviewer istio gateway configurable

- components/profile-controller/config/manager/kustomization.yaml
The ISTIO_INGRESS_GATEWAY_PRINCIPAL and NOTEBOOK_CONTROLLER_PRINCIPAL had an extra ) at the end of the value.
Fixes #7374 in master
> fix: remove extra ) from env variables

- .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
There was a small bug in the CI from https://github.com/kubeflow/kubeflow/pull/7357, which cause the release version tags to not be created (when the `releasing/version/VERSION` file is updated).
It was simply doing the `cd` too early, so the relative path was not correct.
We will probably need to quickly do a `1.8.0-rc.5` after cherry-picking this pr into the `v1.8-branch`.
> ci: fix version tagging of notebook server images

- components/crud-web-apps/volumes/manifests/base/deployment.yaml
Filebrowser recently [released v2.25.0](https://github.com/filebrowser/filebrowser/releases/tag/v2.25.0).
Until now, we couldn't use v2.24.0, which brings chunked uploads, due to an issue with Cloudflare environments.  This got fixed in v2.25.0, so that chunked uploads should now work for every user.
> chore: update default filebrowser version

- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/codeserver-python/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/rstudio/Dockerfile
Follow up to https://github.com/kubeflow/kubeflow/pull/7357
This PR downgrades JupyterLab to 3.6.6 and Jupyter Notebooks to 6.5.6.
This is to ensure compatibility with JupyterLab extensions which have not supported JupyterLab 4.0 yet.
I have also re-added the `jupyterlab-git` extension, as this was one of the plugins that did not support 4.0.
Finally, I have updated the `kfp` version to `2.4.0`, as this version fixes a bug uncovered in Kubeflow 1.8.0-rc.4.
> fix: downgrade jupyterlab to 3.6.6

- .github/workflows/centraldb_angular_docker_publish.yaml
- .github/workflows/centraldb_docker_publish.yaml
- .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/pvcviewer_controller_docker_publish.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/vwa_docker_publish.yaml
There is currently a serious bug in the CI which may result in image tags being re-pushed post-release.
The issue is that our current system to detect when the `releasing/version/VERSION` file has changed (and thus a new "release" image tag needs to be created) will trigger 100% of the time.
This is because, by default, the [`dorny/paths-filter@v2`](https://github.com/dorny/paths-filter) will compare against `master`, even if the push was to the `v1.8-branch`, and there will always be a different on the `releasing/version/VERSION` between master and release branches.
This PR simply uses `${{ github.ref }}` as the base of comparison, as [suggested by the author of `dorny/paths-filter`](https://github.com/dorny/paths-filter#change-detection-workflows) for long-lived branches.
> ci: prevent triggering release builds accidentally

- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run
resolves #7370
This PR fixes a longstanding issue in the JupyterLab images, which can cause them to fail to start if the PVC mounted to the home directory has incorrect file permissions for the `/home/jovyan/.local/share/jupyter/runtime` folder. 
This issue often happens for NFS-based PVCs because they typically do not support Unix file permissions, so they often present everything as 755.
The runtime files should not be persisted between restarts, so this PR makes them be stored in the `/tmp` directory.
---
It also adds the `--ServerApp.allow_remote_access=True` argument, which is unrelated, but a good idea to prevent proxy issues.
> fix: jupyterlab runtime volume permissions

- components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
- components/crud-web-apps/jupyter/backend/apps/common/utils.py
The node.status.capacity attribute can be None. In this event the call to /api/gpus fails with Nonetype does not have keys attribute. This results in the entire request failing if a single node in the cluster doesn't have the node.status.capacity attribute defined. This happens in situations where a node reaches a bad state (very rare). 
My proposed solution checks if node.status.capacity is defined for a node and then adds capacity keys to the list of vendors. In the event that node.status.capacity is not defined for a node a warning message is logged to inform the user that the node.status.capacity for node.metadata.name is not available.
> Handle edge case when node capacity is undefined gracefully. Closes #7280.

- components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-new/form-new.component.ts
If the custom image has extra white space, the status is always pending on the web page.
> Trim the custom Jupyter image string

- .github/OWNERS
- components/OWNERS
- components/access-management/OWNERS
- components/admission-webhook/OWNERS
- components/centraldashboard-angular/OWNERS
- components/centraldashboard/OWNERS
- components/crud-web-apps/OWNERS
- components/crud-web-apps/common/frontend/OWNERS
- components/crud-web-apps/jupyter/frontend/OWNERS
- components/crud-web-apps/tensorboards/frontend/OWNERS
- components/crud-web-apps/volumes/frontend/OWNERS
- components/example-notebook-servers/OWNERS
- components/notebook-controller/OWNERS
- components/profile-controller/OWNERS
- components/tensorboard-controller/OWNERS
- py/OWNERS
- releasing/OWNERS
- testing/gh-actions/OWNERS
This PR is an important cleanup of the OWNERS files.
It will reduce the project's exposure to potentially compromised GitHub accounts by removing access from users who no longer need it.
I have removed reviewers and approvers who have not interacted with the `kubeflow/kubeflow` repo in the last year, or who are no longer associated with the project due to moving companies.
To pay respect to historical approvers, I have moved them to the `emeritus_approvers` section, which does not convey any permission, but denotes that they once had approver access. (Read more about this in the [Kubernetes OWNERs docs](https://www.kubernetes.dev/docs/guide/owners/#emeritus)).
---
This PR will also reduce the frustration of people who make PRs because it will prevent inactive members from being …
> chore: cleanup inactive owners

- components/crud-web-apps/jupyter/backend/apps/common/yaml/notebook_template.yaml
In order to maintain consistency and compatibility, explicitly convert the 'username' variable to a string using the str() function before returning it. This ensures that the function consistently provides a string representation of the username, addressing potential variations in the original data type.
https://github.com/kubeflow/kubeflow/issues/7456
Update notebook_template.yaml
> fix: :label: Ensure username is returned by `get_username` as a string

- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/manifests/base/kustomization.yaml
- components/centraldashboard/manifests/overlays/istio/kustomization.yaml
- components/centraldashboard/manifests/overlays/istio/virtual-service.yaml
- components/centraldashboard/manifests/overlays/kserve/kustomization.yaml
FIX: https://github.com/kubeflow/manifests/pull/2589
While the command is running:
```
kustomize build apps/centraldashboard/upstream/overlays/kserve
```
A warning appeared:
```
```
I used the command:
```
kustomize edit fix --vars
```
And also corrected errors received when executing this command. Manifests are now generated without warnings.
Please note that this PR should not affect the manifests themselves in any way, only the warning is removed.
So, when correcting errors, an error appears and manifests stop working:
```
kustomize edit fix --vars
2024/01/03 11:36:03 well-defined vars that were never replaced: CD_CLUSTER_DOMAIN,CD_NAMESPACE
Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements
Warning: 'Fixed' …
```
> chore (manifests): Fixes centraldashboard for kustomize 5

- README.md
Add badges recommended by CLOMonitor, a tool by CNCF that periodically checks open source projects repositories to verify they meet certain project health best practices, to the repository’s README file
Ref: https://clomonitor.io/projects/cncf/kubeflow#kubeflow
> Add CLOMonitor badges to project's README.md

- components/crud-web-apps/jupyter/backend/apps/common/routes/get.py
Fixes #7441
* Corrected node status reference
* Converted string to f-string
Previous known working version
https://github.com/kubeflow/kubeflow/blob/0c0c76300d8df28f0b7cac95099c286e4dab3288/components/crud-web-apps/jupyter/backend/apps/common/routes/get.py#L117
> fix(crud-web-apps/jupyter): dict variable reference for `node.status.capacity`

- components/notebook-controller/README.md
It looks like the notebook images no longer rely on start.sh.
It looks like the Docker images now use the init system to run jupyterlab with the correct arguments https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/jupyter/Dockerfile
I could find no start.sh script in the repo
> docs: update example notebooks spec

- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
This PR improves Centraldashboard by adding a possibility to parse Kubeflow namespaces with default selector (`{ns}`) in `externalLinks` when the element is not an `iframe`.
For example, this can be seamless for someone to dynamically pass a profile to an external service that uses Kubeflow-related features in that profile/namespace.
> feat(dashboard): allow using `{ns}` template in `externalLinks`

- components/centraldashboard/config/centraldashboard-config.yaml
- components/centraldashboard/manifests/base/configmap.yaml
- components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
- components/centraldashboard/public/components/main-page.css
- components/centraldashboard/public/components/main-page.js
- components/centraldashboard/public/components/main-page.pug
This PR does the following things:
1. __Updates the homepage links:__
- Removes all 404 links to the Kubeflow website
- Adds docs links for all Kubeflow components
1. __Updates the sidebar links:__
- Groups all Kubeflow Pipelines links into one collapsable "section" 
- Removes the "Privacy Policy" and "Usage Reporting" links as these are from many years ago when there was an optional usage reporting system, which no longer exists. Also, the "Usage Reporting" link was 404.
1. __Improves the styling of the sidebar links:__
- Fixes an issue with the "section" `menuLinks` type where clicking on the icon would not collapse the section
- De-indents the "section" elements slightly
- Ensures that all "external" (i.e. non-iframe) links have an indicator ![Screenshot 2024-05-20 at 21 46 …
> feat: update dashboard styles and links

- components/notebook-controller/config/crd/kustomization.yaml
- components/notebook-controller/config/crd/patches/validation_patches.yaml
Closes #6886
- Added json6902 patch for adding cel validation on notebooks crd to avoid
- empty image names
- at least 1 container objects in container array
Tested locally by running kustomize locally
> fix(notebooks): add CRD validation for empty image and container

- components/crud-web-apps/volumes/backend/apps/common/status.py
In some cases, a PVCViewer object has no status as it was just created or is having issues starting a pod.  In those cases, we should rather return waiting than uninitialized, which would appear to the users as if no viewer was started.
> fix: return waiting on no pvcviewer status

- components/centraldashboard-angular/manifests/base/deployment.yaml
- components/centraldashboard/manifests/base/deployment.yaml
fix env name mismatch
https://github.com/kubeflow/kubeflow/blob/d1c40f916225ecb40826400595ea99096a2adbb7/components/centraldashboard/app/k8s_service.ts#L4-L7
https://github.com/kubeflow/kubeflow/blob/d1c40f916225ecb40826400595ea99096a2adbb7/components/centraldashboard-angular/backend/app/k8s_service.ts#L4-L9
> fix: incorrect references `DASHBOARD_LINKS_CONFIGMAP` env-var

- components/crud-web-apps/common/backend/setup.py
- components/crud-web-apps/jupyter/backend/apps/common/status.py
- components/crud-web-apps/jupyter/backend/apps/common/status_test.py
Fixes https://github.com/kubeflow/kubeflow/issues/7454
Update the backend code to gracefully handle the containerState and `message`, when it doesn't exist.
I also unpinned the `gevent` package, since it introduces a CVE in all the web apps.
> fix(notebooks): correctly handle `status.containerState` messages

- components/notebook-controller/Makefile
Closes #7588
Flooring envtest version (release-0.14) to avoid https://github.com/golang/go/issues/61888 and to match go version.
None
> fix: specify envtest version to avoid golang version format

- components/profile-controller/Makefile
- components/profile-controller/api/v1/groupversion_info.go
- components/profile-controller/api/v1beta1/groupversion_info.go
- components/profile-controller/config/crd/bases/kubeflow.org_profiles.yaml
- components/profile-controller/controllers/plugin_iam_test.go
This is a follow-up from
https://github.com/kubeflow/kubeflow/pull/7589
Which should also unblock the following PRs
- https://github.com/kubeflow/kubeflow/pull/7586
- https://github.com/kubeflow/kubeflow/pull/7152
In this PR we pin the `env-test` to `release-0.12`, which reflects the `controller-runtime` version in this component
> Pin env-test for Profiles Controller

- components/centraldashboard/manifests/overlays/kserve/patches/configmap.yaml
This is a follow-up to https://github.com/kubeflow/kubeflow/pull/7583.
I incorrectly put the link for the "KServe models-web-app" as `/models/` when it's `/kserve-endpoints/` which made that UI inaccessible. 
See here for the relevant manifests:
- https://github.com/kserve/models-web-app/blob/v0.10.0/config/base/istio.yaml#L14
> fix: kserve models link in sidebar of dashboard

- components/example-notebook-servers/base/Dockerfile
- components/example-notebook-servers/base/s6/cont-init.d/01-copy-tmp-home
- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/codeserver/Dockerfile
- components/example-notebook-servers/codeserver/s6/services.d/code-server/run
- components/example-notebook-servers/jupyter-pytorch-cuda-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-cuda/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch/Dockerfile
- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-cuda-full/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-cuda/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow/Dockerfile
- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run
- components/example-notebook-servers/rstudio/Dockerfile
- components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix
- components/example-notebook-servers/rstudio/s6/services.d/rstudio/finish
- components/example-notebook-servers/rstudio/s6/services.d/rstudio/run
resolves https://github.com/kubeflow/kubeflow/issues/5808
This PR makes the following changes to the `example-notebook-servers`:
- updates the version of [`s6-overlay`](https://github.com/just-containers/s6-overlay) to [`v3.2.0.0`](https://github.com/just-containers/s6-overlay/releases/tag/v3.2.0.0)
- changes the primary GID of the `jovyan` user from `100` to `0`: 
- for backwards-compatibility, `jovyan` is still a member of `100`
- fixed the fact that the IDEs could fail to start, but the container would stay running:
- sets `S6_BEHAVIOUR_IF_STAGE2_FAILS` to `2` 
- fixed the fact that the STDERR of the IDEs was not being captured in the Pod logs:
- runs `exec 2>&1` in the s6 `run` scripts
- fixed the fact that RStudio would not print its logs to the container:
- set `RS_LOGGER_TYPE` to …
> fix: notebook server images with non-root SecurityContext

- .github/workflows/example_notebook_servers_publish.yaml
- components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
- components/crud-web-apps/jupyter/manifests/base/configs/spawner_ui_config.yaml
- components/example-notebook-servers/Makefile
- components/example-notebook-servers/README.md
- components/example-notebook-servers/jupyter-pytorch-gaudi-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-gaudi-full/Makefile
- components/example-notebook-servers/jupyter-pytorch-gaudi-full/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-gaudi/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-gaudi/Makefile
- components/example-notebook-servers/jupyter-pytorch-gaudi/README.md
closes: https://github.com/kubeflow/kubeflow/issues/7541
Hello,
This pull request adds initial support for Intel Gaudi use with Kubeflow's notebooks. The patches add two things:
1) Intel Gaudi option to the Notebook creation UI
2) Intel Gaudi pytorch jupyter Dockerfiles
The Gaudi containers downgrade the python version from `3.11` to `3.10` as the Habana pytorch stack does not yet support `3.11`. Support for `3.11` is planned and we will update the Dockerfiles once the `3.11` version is released.
> feat: add Intel Gaudi example notebook images

- components/centraldashboard/README.md
- components/centraldashboard/manifests/base/deployment.yaml
- components/centraldashboard/public/components/logout-button.css
- components/centraldashboard/public/components/logout-button.js
As suggested by @thesuperzapper [here ](https://github.com/kubeflow/manifests/issues/2895#issuecomment-2427184722) changed the login method to GET.  
Should fix #7624 and [Manifests #2895](https://github.com/kubeflow/manifests/issues/2895)
Testing:
- Built docker image for the dashboard
- Loaded the new image to kind cluster
- Changed name of docker image for central dashboard deployment to newly loaded image
- Tested logout functionality and it is working
> fix: logout button for oauth2-proxy

- components/crud-web-apps/jupyter/backend/apps/common/status.py
Fixes https://github.com/kubeflow/notebooks/issues/64
Notebook events are not currently returned resulting in the generic error message `Couldn't find any information for the status of this notebook.` when unsuccessfully creating a notebook. 
This is because the error message from notebook events is currently being overridden by the generic error message.
> fix: return notebook events error message

- components/example-notebook-servers/codeserver/s6/services.d/code-server/run
Currently, the code-server notebook image (VSCode) will not work properly when behind a proxy that changes the hostname, as code-server requires that the x-forwarded-for match the actual HTTP host header otherwise it gives an error like this:
```text
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)
```
As documented upstream in https://github.com/coder/code-server/issues/4443, the solution is to start code-server with the `--trusted-origins "*"` parameter.
> fix: running code-server notebook behind proxy

- OWNERS
Updating to include emeritus_approvers
Follow up to https://github.com/kubeflow/kubeflow/pull/7675 in https://github.com/kubeflow/community/issues/812
> Updating to include emeritus_approvers

- components/notebook-controller/config/default/manager_auth_proxy_patch.yaml
- components/profile-controller/config/default/manager_auth_proxy_patch.yaml
- components/pvcviewer-controller/config/default/manager_auth_proxy_patch.yaml
- components/tensorboard-controller/config/default/manager_auth_proxy_patch.yaml
Resolves https://github.com/kubeflow/dashboard/issues/58
For now we are just updating the registry, but in the future it might be worth to replace it all together for https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization
> fix: stop using gcr.io registry for kube-rbac-proxy

- components/access-management/Dockerfile
- components/profile-controller/Dockerfile
- components/profile-controller/config/base/patches/manager.yaml
- components/profile-controller/config/overlays/kubeflow/patches/kfam.yaml
upstream what we have in https://github.com/kubeflow/manifests/tree/master/contrib/security/PSS to make PSS enforcable
and enjoy a rootless Kubeflow https://github.com/kubeflow/manifests/issues/2528
> fix: add container securityContext to profile-controller and kfam

- components/admission-webhook/Dockerfile
- components/notebook-controller/Dockerfile
Currently, the admission-webhook and notebook-controller don't use the standard `gcr.io/distroless/static:nonroot` image, this PR updates both of them and makes them use `nonroot`. 
The notebook-controller is using the `debug` image for some reason (which adds `bash` and is a security risk for no reason).
The `admission-webhook` (PodDefaults) is using a very outdated `debian10` image.
> feat: use rootless base image for nb-controller and pod-default

- components/example-notebook-servers/base/Dockerfile
- components/example-notebook-servers/codeserver-python/Dockerfile
- components/example-notebook-servers/codeserver-python/home/README__CODESERVER_PYTHON.md
- components/example-notebook-servers/codeserver-python/requirements.txt
- components/example-notebook-servers/codeserver/Dockerfile
- components/example-notebook-servers/codeserver/s6/services.d/code-server/run
- components/example-notebook-servers/jupyter-pytorch-cuda-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-cuda-full/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-cuda/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-full/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-gaudi-full/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-gaudi-full/requirements.txt
- components/example-notebook-servers/jupyter-pytorch-gaudi/Dockerfile
- components/example-notebook-servers/jupyter-pytorch-gaudi/README.md
- components/example-notebook-servers/jupyter-pytorch-gaudi/home/README__PYTORCH_GAUDI.md
- components/example-notebook-servers/jupyter-pytorch/Dockerfile
- components/example-notebook-servers/jupyter-scipy/Dockerfile
- components/example-notebook-servers/jupyter-scipy/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-cuda-full/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-cuda-full/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow-cuda/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/Dockerfile
- components/example-notebook-servers/jupyter-tensorflow-full/requirements.txt
- components/example-notebook-servers/jupyter-tensorflow/Dockerfile
- components/example-notebook-servers/jupyter/Dockerfile
- components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run
- components/example-notebook-servers/rstudio/Dockerfile
- components/example-notebook-servers/rstudio/s6/services.d/rstudio/run
This PR updates all the `example-notebook-servers` images.
I have tested all images locally on AMD64 and ARM (except CUDA images, which are not supported on ARM). 
I also did not test Intel's PyTorch Gaudi images, because those require custom hardware.
Once we merge this, we can rebase https://github.com/kubeflow/kubeflow/pull/7680 and ask @tkatila to test those images on their Intel hardware.
We now install the Jupyter plugin by default. Note, this requires Notebooks be accessed over HTTPS to work.
So, we have also added a warning README (that gets copied to the user's home) that explains this.
- kubectl: `1.29.9` -> `1.31.6`
- CodeServer: `4.93.1` -> `4.96.4`
- JupyterLab: `4.2.5` -> `4.3.5`
- RStudio: `2024.09.0-375` -> `2024.12.1-563`
- Python: `3.11.10` -> `3.11.11`
- Pip: `24.2` -> …
> feat: update notebook server images

- .github/workflows/centraldb_docker_publish.yaml
- .github/workflows/centraldb_multi_arch_test.yaml
- .github/workflows/example_notebook_servers_publish_TEMPLATE.yaml
- .github/workflows/jwa_docker_publish.yaml
- .github/workflows/jwa_multi_arch_test.yaml
- .github/workflows/kfam_docker_publish.yaml
- .github/workflows/kfam_multi_arch_test.yaml
- .github/workflows/nb_controller_docker_publish.yaml
- .github/workflows/nb_controller_multi_arch_test.yaml
- .github/workflows/poddefaults_docker_publish.yaml
- .github/workflows/poddefaults_multi_arch_test.yaml
- .github/workflows/prof_controller_docker_publish.yaml
- .github/workflows/prof_controller_multi_arch_test.yaml
- .github/workflows/pvcviewer_controller_multi_arch_test.yaml
- .github/workflows/tb_controller_docker_publish.yaml
- .github/workflows/tb_controller_multi_arch_test.yaml
- .github/workflows/twa_docker_publish.yaml
- .github/workflows/twa_multi_arch_test.yaml
- .github/workflows/vwa_docker_publish.yaml
- .github/workflows/vwa_multi_arch_test.yaml
- components/example-notebook-servers/README.md
There is some kind of calamity going on regarding emulated ARM64 builds, it seems like the only way to fix it is pinning QEMU to `tonistiigi/binfmt:qemu-v7.0.0-28` and Ubuntu to `22.04` (already done in https://github.com/kubeflow/kubeflow/pull/7681).
Without this change, our `example-notebook-servers` are failing to build with a segmentation fault every time:
- https://github.com/kubeflow/kubeflow/actions/runs/13365536962/job/37350738903
Upstream issues:
- https://github.com/tonistiigi/binfmt/issues/215
- https://github.com/docker/setup-qemu-action/issues/198
> ci: downgrade qemu, fix arm64 build segfaults

- components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/metrics.py
Currently you need to submit a request with a `kubeflow-userid` header to scrape web application metrics added in #7634.  Unfortunately, this makes it difficult to integrate using the existing Prometheus `PodMonitor`/`ServiceMonitor` resources as they only allow manipulation of simple HTTP authentication headers.
> fix: don't require authentication for crud-web-apps metrics endpoints

- components/crud-web-apps/volumes/manifests/base/deployment.yaml
Updating to the most recent v2.32.0. The current default image is from September 2023.
> chore: update filebrowser image to v2.32.0

- components/example-notebook-servers/README.md
Removed the extra `kubeflow` from all container registry text in the README file
> fix(notebook): fix registry names in notebook container links
