k8s-model-server/README.md, k8s-model-server/docker/Dockerfile, k8s-model-server/docker/Makefile, k8s-model-server/manifests/model-server.yaml
=> Moving TF Serving from gke-accelerators repo to kubeflow

jupyterhub/manifests/config.yaml
=> fix jupyterhub config for image selection and defaulting

README.md
cc @vishh @jlewi 
jeremy - we also need this for the operator. Is that correct?
=> Resolve TODO for RBAC on GKE 1.8+

README.md
=> Final readme fixes

README.md
=> Include Tensorboard and Docker Images

CONTRIBUTING.md, LICENSE
=> Add license and contributing.md

CONTRIBUTING.md, components/jupyterhub/docker/Dockerfile, components/jupyterhub/docker/Makefile, components/jupyterhub/manifests/config.yaml, components/jupyterhub/manifests/jupyterhub.yaml, components/jupyterhub/manifests/rbac.yaml, components/jupyterhub/manifests/service.yaml, components/k8s-model-server/docker/Dockerfile, components/k8s-model-server/docker/Makefile, components/k8s-model-server/manifests/model-server.yaml, components/tf-controller/Makefile, components/tf-controller/deploy_crd.yaml, tf-controller-examples/tf-cnn/Dockerfile.cpu, tf-controller-examples/tf-cnn/Dockerfile.gpu, tf-controller-examples/tf-cnn/Dockerfile.template, tf-controller-examples/tf-cnn/Makefile, tf-controller-examples/tf-cnn/create_job_specs.py, tf-controller-examples/tf-cnn/launcher.py, tf-controller-examples/tf-cnn/tf_job_cpu.yaml, tf-controller-examples/tf-cnn/tf_job_cpu_distributed.yaml, tf-controller-examples/tf-cnn/tf_job_gpu.yaml, tf-controller-examples/tf-cnn/tf_job_gpu_distributed.yaml
@vishh @aronchick @jlewi PTAL
Using guidelines from https://github.com/google/new-project
=> Update Contributing.md, and add license headers

.travis.yml, Makefile, build/boilerplate/boilerplate.go.txt, build/boilerplate/boilerplate.py, build/boilerplate/boilerplate.py.txt, build/boilerplate/boilerplate.sh.txt, build/check_boilerplate.sh, build/check_errorf.sh, tf-controller-examples/tf-cnn/create_job_specs.py, tf-controller-examples/tf-cnn/launcher.py
Once this PR is merged, I'll turn on Travis CI for this repo.
cc @foxish @jlewi
=> Adding licence boilerplate verification

README.md
This PR fix mailing list URL typo.
@jlewi @foxish @aronchick @vishh PTAL.
=> Fix mailing list URL typo

user_guide.md
* Originally this was #67
* I copied that PR in order to resolve out of date files.
=> Fix a typo in the README

kubeflow/registry.yaml
=> Add tf-job to registry.yaml.

components/k8s-model-server/README.md
addressing this https://github.com/google/kubeflow/issues/98
=> replace the model from tensorflow/models

kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet
* Related to https://github.com/google/kubeflow/issues/51
* Now that terminationPolicy can be used to specify a non-master chief, we no longer need to add a master to run the tf-cnn we can just use worker 0 as the chief which allows the example to run out of the box.
* Update the ksonnet to work with that
=> change kjsonnet in tf-cnn to remove not used MASTER

kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tf-job.libsonnet
* Update the Docker image to get a docker image with the dasbhoard
* Update the flags because the flag --controller-config-file was renamed.
=> Fix bugs with TfJob operator prototype

README.md
Changing some of the language on the landing page to highlight CPU / GPU computation, open-source, and integration with multiple platforms.
=> Updating the verbiage in the README to clarify project motivation.

README.md, testing/prow_artifacts.py
There is a missing argument, bucket, what will lead to KeyError.
=> fix prow_artifacts.py

components/k8s-model-server/README.md
Fix the model path for inception.
=> Fix model path.

README.md, components/jupyterhub/README.md, components/k8s-model-server/README.md, kubeflow/README.md, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/parts.yaml, kubeflow/tf-job/parts.yaml, kubeflow/tf-serving/parts.yaml, kubeflow/tf-serving/tf-serving.libsonnet, testing/README.md, testing/bootstrap.sh, testing/checkout.sh, testing/test-infra/app.yaml, testing/test-infra/vendor/kubeflow/core/jupyterhub.libsonnet, testing/test-infra/vendor/kubeflow/core/parts.yaml, testing/test_deploy.py, user_guide.md
Close #168 
PTAL @jlewi 
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> *: Update link to kubeflow/kubeflow

kubeflow/tf-job/tf-job.libsonnet
fixed typo to create the right CRD job type.
=> fixed typo TfJob -> TFJob

components/k8s-model-server/http-proxy/Dockerfile
The dockerfile was broken because of requirements location.
=> update the docker file for http proxy

kubeflow/argo/argo.libsonnet
=> fix typo for argo-ui role binding

README.md, user_guide.md
- moving the troubleshooting guide into the user_guide.
- in README update the troubleshooting information to just be a link to the relevant section in the user_guide.
- Fix #223
=> Fix userguide issue223

user_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/238)
=> Troubleshooting: Gotcha for Docker for Mac kube

docs/gke/iap.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/245)
=> Fix typos in iap.md

kubeflow/tf-job/prototypes/tf-job.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/247)
=> Fix short description typo in tf-job.jsonnet

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/248)
=> Fix link to prow jobs dashboard

user_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/256)
=> Add GPU scheduling instructions to user_guide.md

kubeflow/core/ambassador.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/269)
=> Bump Ambassador version to latest (0.26.0)

testing/workflows/components/workflows.libsonnet
* We were using the wrong directory for the ksonnet app containing the simple TFJob to run.
* We need to be using kubeflow/tf-operator.
* Fix #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/274)
=> Fix TfJob test

components/k8s-model-server/images/releaser/components/workflows.jsonnet, components/k8s-model-server/images/releaser/components/workflows.libsonnet, kubeflow/argo/prototypes/argo.jsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/iap-envoy.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/tests/util_test.jsonnet, kubeflow/seldon/core.libsonnet, kubeflow/seldon/crd.libsonnet, kubeflow/seldon/prototypes/core.jsonnet, kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet, kubeflow/tf-job/prototypes/tf-job.jsonnet, kubeflow/tf-job/tf-job.libsonnet, kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet, scripts/autoformat_jsonnet.sh, testing/workflows/components/workflows.jsonnet, testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet, testing/workflows/vendor/kubeflow/core/prototypes/all.jsonnet
Enforce consistent string quote styling
and comment styling
Autoformat all files in the project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/286)
=> Update jsonnet autoformat script

components/k8s-model-server/images/releaser/components/workflows.jsonnet, components/k8s-model-server/images/releaser/components/workflows.libsonnet, kubeflow/argo/prototypes/argo.jsonnet, kubeflow/core/ambassador.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/iap-envoy.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/tests/util_test.jsonnet, kubeflow/core/tf-job.libsonnet, kubeflow/seldon/core.libsonnet, kubeflow/seldon/crd.libsonnet, kubeflow/seldon/prototypes/core.jsonnet, kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet, kubeflow/tf-job/prototypes/tf-job.jsonnet, kubeflow/tf-job/tf-job.libsonnet, kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet, scripts/autoformat_jsonnet.sh, testing/workflows/components/.#workflows.libsonnet, testing/workflows/components/workflows.jsonnet, testing/workflows/components/workflows.libsonnet, testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet, testing/workflows/vendor/kubeflow/core/prototypes/all.jsonnet
* The latest image pulls in critical bug e.g
* Fix kubeflow/tf-operator#322
* We have moved to using kubeflow-images-staging to host our Docker images.
This is the first step in creating a more rigourous release process.
* The binary was renamed in the Docker image so we need to update the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/299)
=> Update the image used for the TFJob controller.

user_guide.md
- edits for Jupyter and JupyterHub
- minor grammar edits and typo fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/332)
=> Edit user guide links and wording for Jupyter and JupyterHub

components/jupyterhub/README.md
- Add reference to Project Jupyter a non-profit open source academic research project
- Edit text and links related to Jupyter, JupyterLab, and JupyterHub
- Correct minor typos and grammar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/333)
=> Clarify JupyterHub and Jupyter description in component readme

kubeflow/argo/README.md
Not sure about other info, links here
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/384)
=> Add pkg install step for argo README

components/k8s-model-server/http-proxy/build_image.sh, releasing/releaser/components/workflows.libsonnet
Fixed  #353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/386)
=> Build http proxy image in release workflow

docs/gke/tf_serving_iap.md
Fix #293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/392)
=> Add info about authenticate user account

docs/gke/iap.md
Closes https://github.com/kubeflow/kubeflow/issues/60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/406)
=> JWT validation works with GCP IAP - remove outdated docs

kubeflow/core/jupyterhub_spawner.py, testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet, user_guide.md
Fixes #309 
More work/investigation required of best way to parameterize the images for the UI list, for now hardcoded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/402)
=> Add HTML5 dropdown for image selector with cpu,gpu defaults

kubeflow/seldon/prototypes/serve-simple.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/420)
=> Fix the import name for seldon/serve-simple.libsonnet

kubeflow/core/all.libsonnet, kubeflow/core/tests/util_test.jsonnet, kubeflow/core/util.libsonnet, kubeflow/tf-serving/tf-serving.libsonnet, scripts/autoformat_jsonnet.sh
* All other *sonnet files are generated
* Run the autoformat script to format *sonnet files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/439)
=> Update autoformat script to only format files in kubeflow/ directory

user_guide.md
- minikube resource constraints
- proper name casing
- improved Docker for Mac context advice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/393)
=> Troubleshooting section updates

kubeflow/core/prototypes/cert-manager.jsonnet
Related to https://github.com/kubeflow/kubeflow/issues/43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/466)
=> Update cert-manager component to inherit namespace

components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
Update build.sh script to take image name and tag name separately and
also add an IS_LATEST flag.
Update buildImageTemplate to take an is_latest parameter
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/475)
=> Tag tensorflow-notebook-images with latest

components/k8s-model-server/images/releaser/components/workflows.libsonnet
related #484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/487)
=> Temporarily disable gpu test since it's flaky

releasing.md
=> Fix instructions for tensorflow-notebook release

user_guide.md
Fixes #478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/482)
=> Add Github's rate exceeded error trobuleshooting

kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet, releasing.md, user_guide.md
* Update the Jupyter notebook images used to the most recently built
Jupyter images.
* Cut a new release of TFJob operator and update the Kubeflow components to
use it; The new release fixes a bunch of bugs in the operator.
* Update the instructions for releasing.
* Related to #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/508)
=> Update images for our 0.1 release

components/k8s-model-server/images/Dockerfile.cpu, components/k8s-model-server/images/releaser/components/workflows.libsonnet
latest doesn't work as in #510 
related #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/512)
=> Pin tf serving version to 1.4

components/tensorflow-notebook-image/Dockerfile
This unblocks packages that rely on newer versions of those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/498)
=> Update the nodejs and ipywidgets dependencies.

kubeflow/core/jupyterhub_spawner.py
Changes: Use ks version 0.9.2
Related: https://github.com/kubeflow/kubeflow/pull/515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/516)
=> Update tensorflow notebook release to v20180327-6bb4058

kubeflow/tf-serving/tf-serving.libsonnet
For the 0.1 release. #506 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/510)
=> update default image for TF serving

components/k8s-model-server/README.md, kubeflow/tf-serving/tf-serving.libsonnet
- Change the flag for deploying http proxy to bool.
- Use a default image if user does not specify the image.
Fix #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/517)
=> Http proxy default image

components/centraldashboard/config/Dockerfile, components/centraldashboard/frontend/dashboard.go, components/centraldashboard/frontend/index/index.html, components/centraldashboard/frontend/index/styles.css, kubeflow/core/all.libsonnet, kubeflow/core/centraldashboard.libsonnet
Addresses issue: https://github.com/kubeflow/kubeflow/issues/141. 
Adds centraldashboard. Requires integration onto ambassador which would be addressed in the next PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/525)
=> Adds Centraldashboard (in place of #146)

kubeflow/core/jupyterhub_spawner.py
Related to https://github.com/kubeflow/kubeflow/issues/506
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/526)
=> Fix typos in tensorflow notebook images in spawner

kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/all.jsonnet, testing/workflows/components/workflows.libsonnet
* Fix typos in tensorflow notebook images in spawner (#526)
* Update the TFJob image in preparation for a new RC (#533)
Related to #506
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/540)
=> Cherrypick #526 and #533 into v0.1-branch

components/k8s-model-server/images/releaser/components/workflows.libsonnet
It's failing in presubmit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/547)
=> disable gpu test

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/543)
=> Add tf1.7 to tensorflow-notebook images

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/559)
=> Rety upto 3 times while building tensorflow notebook images

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/542)
=> add willb to approvers

docs/gke/iap.md, kubeflow/core/iap.libsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet
Fixes #569 and updates the iap.md user guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/572)
=> Moved OAuth secret from param to named secret

docs/gke/iap.md, kubeflow/core/iap.libsonnet, kubeflow/core/jupyterhub_spawner.py, kubeflow/core/prototypes/iap-ingress.jsonnet
* Moved OAuth secret from param to named secret #572
* Fixes #569 and updates the iap.md user guide.
* Update tf jupyter notebook images to include tfma (from #544) #570
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/575)
=> Cherrypick #570 and #572 into v0.1-branch

kubeflow/tf-serving/tf-serving.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/556)
=> Correct typo for param defaultHttpProxyImage

OWNERS
Per @jlewi endorsement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/565)
=> Add pdmack to OWNERS

README.md
Add the link to tf-operator in README
Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/588)
=> README: Add link for tf-operator

kubeflow/core/jupyterhub_spawner.py
Includes the following changes:
* Fix the tensorflow version in prebuilt images for python 2.7. (#580)
* Install graphviz in tensorflow notebook image (#583)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/589)
=> Update tensorflow notebook version to v20180403-1f854c44

kubeflow/core/jupyterhub_spawner.py
Includes the following changes:
* Fix the tensorflow version in prebuilt images for python 2.7. (#580)
* Install graphviz in tensorflow notebook image (#583)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/590)
=> Cherry pick : Update tensorflow notebook version to v20180403-1f854c44 (#589)

README.md, user_guide.md
* Fix #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/601)
=> Update the docs to point to the v0.1.0 release now that it is cut.

user_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/599)
=> Typo in UG

README.md, testing/vm_util.py, user_guide.md
* Increase the disk size for minikube because people have encountered
problems starting our Jupyter images.
* Explain why we use /home/jovyan for the PD
* Provide some instructions for troubleshooting problems spawning notebooks.
Related to #594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/613)
=> Improve documentation

components/jupyterhub/README.md
- Update information about JupyterHub and its configuration
- Reflow format text sections with changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/616)
=> Update and clarify JupyterHub README

components/k8s-model-server/images/releaser/components/workflows.libsonnet, testing/test_tf_serving.py
related #484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/558)
=> Enable TF serving gpu test

CONTRIBUTING.md, README.md, components/jupyterhub/README.md, components/k8s-model-server/README.md, components/k8s-model-server/http-proxy/README.md, components/k8s-model-server/images/README.md, components/k8s-model-server/test-data/README.md, docs/gke/iap.md, docs/gke/tf_serving_iap.md, docs_dev/images.md, docs_dev/ksonnet_packages.md, docs_dev/releasing.md, kubeflow/README.md, kubeflow/argo/README.md, kubeflow/core/README.md, kubeflow/tf-job/README.md, kubeflow/tf-serving/README.md, testing/README.md, testing/workflows/vendor/kubeflow/core/README.md, tf-controller-examples/tf-cnn/README.md, user_guide.md
Fix https://github.com/kubeflow/kubeflow/issues/603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/604)
=> docs(TOC): add auto-generated TOC for all docs

OWNERS
* I don't think she's been actively reviewing PRs so there's no point
auto-assigning reviews to her.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/648)
=> Remove zjj2wry as a reviewer.

OWNERS
Bump up my privileges so that I may review and tag issues. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/656)
=> Add willingc to reviewers

components/tensorflow-notebook-image/Dockerfile
/cc @jlewi 
/cc @rsepassi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/659)
=> Include tensor2tensor in jupyter notebook image

kubeflow/pachyderm/README.md, kubeflow/pachyderm/all.libsonnet
* Extend the Pachyderm Kubeflow package so that we can deploy it backed by GCS
* Related to #611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/645)
=> Add components to work with GCP

components/k8s-model-server/README.md, components/k8s-model-server/istio-integration.md
related #644 
related #496 
Also update the doc for instruction on using GPU for serving.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/678)
=> Add documentation for exposing grafana dashboard

kubeflow/openmpi/README.md, kubeflow/openmpi/assets.libsonnet, kubeflow/openmpi/assets/init.sh, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
* Add a parameter "gpus" to specify number of GPUs per worker
* Increase timeout in init.sh
* Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/685)
=> [openmpi] Add GPU support

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/693)
=> add export to ksonnet github token instructions

README.md, user_guide.md
Seems like enough Kubeflow users have been bitten by some of the ks 0.10 stuff that we should try to help them first and ksonnet second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/694)
=> Pin instructions to ks 0.9.2 (for now)

bootstrap/README.md, components/k8s-model-server/images/releaser/components/params.libsonnet, docs_dev/images.md, kubeflow/core/kubeform_spawner.py, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet, testing/workflows/vendor/kubeflow/core/jupyterhub.libsonnet
Related to https://github.com/kubeflow/kubeflow/issues/534
/cc @kunmingg 
/cc @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/695)
=> Migrate images to kubeflow-images-public

kubeflow/core/kubeform_spawner.py
/assign @ankushagarwal 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/697)
=> Update the hub spawner dropdown for latest NB images

README.md, user_guide.md
/cc @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/706)
=> Point instructions to 0.1.2 release

components/openmpi-controller/OWNERS, kubeflow/openmpi/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/711)
=> [openmpi] Add OWNERS file

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/715)
=> add kunming to reviewer

scripts/autoformat_jsonnet.sh
Adds option --all to format all files tracked by git, refs #395.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/553)
=> Reformats only modified files by default #395

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/745)
=> Add tf1.8 build to jupyter notebook images

releasing/releaser/components/params.libsonnet, releasing/releaser/components/workflows.libsonnet, testing/Dockerfile, testing/Makefile, testing/README.md, testing/run.sh, testing/test-data/successful_workflow.yaml
Related https://github.com/kubeflow/testing/issues/90
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/750)
=> Move away from mlkube-testing to kubeflow-ci

kubeflow/openmpi/service.libsonnet, kubeflow/openmpi/workloads.libsonnet
Fix #718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/756)
=> [openmpi] Support RBAC

tf-controller-examples/tf-cnn/launcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/759)
fix #760
=> Fix bytes literals in Python3

kubeflow/seldon/prototypes/core.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/776)
=> Update seldon ksonnet image versions to 0.1.6

components/README.md, components/k8s-model-server/images/versions/1.5/version-config.json
#468 
/cc @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/790)
=> Support TF serving 1.5 image

testing/test_deploy.py
Possible solution for #346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/789)
=> Checking that Ambassador started in e2e test

kubeflow/credentials-pod-preset/README.md, kubeflow/credentials-pod-preset/parts.yaml, kubeflow/credentials-pod-preset/prototypes/gcp-credentials-pod-preset.jsonnet
Create a prototype for injecting GCP Service Account Credentials
/assign @lluunn 
/cc @elsonrodriguez
Fixes https://github.com/kubeflow/kubeflow/issues/732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/782)
=> Create a ksonnet package for injecting credentials through pod presets

components/openmpi-controller/Makefile, components/openmpi-controller/controller/controller.py, components/openmpi-controller/controller/main.py, components/openmpi-controller/controller/util.py, components/openmpi-controller/requirements.txt, kubeflow/openmpi/prototypes/openmpi.jsonnet, kubeflow/openmpi/workloads.libsonnet
Fix #713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/797)
=> [openmpi] Download and upload data in the controller

components/k8s-model-server/http-proxy/server.py
Add meta data api for model metadata, which is useful for checking model info.
Related rpc service is defined here: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto#L29
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/800)
=> add meta api for serving

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja
Fix #806  #807 
https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/814)
=> deployment manager uses new stackdriver agents

kubeflow/openmpi/README.md
Ref #826
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/831)
=> [openmpi] Update README about GPU and horovod training

releasing/cron_job_release.yaml, releasing/prow_config_release.yaml
Anoother part for https://github.com/kubeflow/kubeflow/issues/666.
1. cron_job_release.yaml: 
Define cron job for daily release images
2. prow_config_release.yaml:
Workflows of images that need to be released.
For https://github.com/kubeflow/kubeflow/issues/666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/825)
=> cron job & workflow config for image release

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/839)
=> Add kunmingg as owner

components/tensorflow-notebook-image/releaser/components/params.libsonnet, releasing/cron_job_release.yaml
1. Params update to enable auto-release
2. deprecate test image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/849)
=> params update for release workflow

components/build_image.py
For #843 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/856)
=> build_image.py supports pushing images 

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja
* Use deployment manager to create a config map containing a YAML
spec that will be used to configure the ksonnet app created by the
bootstrapper.
Related to #802 Trigger bootstrapper with deployment manager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/859)
=> Use a config map to configure bootstrapper.

components/build_image.py
#843 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/864)
=> build_image.py waiting for docker daemon

components/README.md, components/tensorflow-notebook-image/versions/1.8.0/version-config.json, components/tensorflow-notebook-image/versions/1.8.0gpu/version-config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/886)
=> Add tf notebook image 1.8 version

bootstrap/Makefile, bootstrap/cmd/bootstrap/app/server.go, bootstrap/config/gcp_prototype.yaml, docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/env-kubeflow.sh
1. Add kubeflow-core to config, and fix typos.
2. Make bootstrapper image use master branch as registry, till we reelase 0.2.
3. Make bootstrapper use params from config when create components. (Some params are not optional.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/872)
=> deployment manager and prototype bug fix

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet
Based on the contents of [https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/rbac.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/rbac.yaml)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/895)
=> Restrict jupyterHubRole

kubeflow/core/ambassador.libsonnet, kubeflow/core/tests/ambassador_test.jsonnet
Update to Ambassador 0.34.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/888)
=> Update to Ambassador 0.34.0

components/image-releaser/components/tf-notebook-workflow.libsonnet, components/image-releaser/components/tf-serving-workflow.libsonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/908)
=> Update default parameters for image-releaser workflows

testing/dm_configs/cluster-kubeflow.yaml, testing/dm_configs/cluster.jinja
We will move our test infra to use deployment manager and bootstrapper
to create isolated clusters for testing. This config will be used for
bringing up these test clusters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/899)
=> Checkin the deployment manager config for running e2e-gke test

docs_dev/ksonnet_packages.md
Hit this issue and stuck for awhile. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/911)
=> Doc on adding new ksonnet package

bootstrap/build.py, bootstrap/build_image.sh, bootstrap/cmd/bootstrap/app/options/options.go, bootstrap/cmd/bootstrap/app/server.go, testing/e2e_env.yaml, testing/workflows/components/workflows.libsonnet
Unblock new e2e test workflow:
Central bootstrap image build -> distributed multi cluster test steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/913)
=> copy registry into bootstrap image during e2e test

components/build_image.py
Fixes https://github.com/kubeflow/kubeflow/issues/909
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/917)
=> Activate service account before pushing images

components/README.md, components/image-releaser/components/util.libsonnet
Also use resource requests to ensure that build containers have
3 cpu and 6Gi memory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/922)
=> Update image-releaser README

docs_dev/images.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/930)
=> fix minor typos

ack_guide.md, kubeflow/core/ambassador.libsonnet, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/kubeform_spawner.py, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tests/ambassador_test.jsonnet, kubeflow/core/tests/jupyterhub_test.jsonnet, user_guide.md
Hi,
I'm from Alibaba Cloud, and this PR is for running Kubeflow on Alibaba cloud in China.
Since it's difficult to pull image from  gcr.io and quay.io for our users, we put the docker images to Alibaba's docker image hub, and make the image is configurable. 
we will start from Jupyterhub, and hope to work closely with your guys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/914)
=> support jupyterhub in alibaba cloud

testing/workflows/components/workflows.libsonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/937)
=> Set 15 minute timeout for workflow step

user_guide.md
resolves #502.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/944)
=> Update instructions for recreating minkube with required resources.

kubeflow/core/prototypes/all.jsonnet
Running 0.34.0 ambassador is causing DNS issues. Downgrading resolves the issue.
Related https://github.com/kubeflow/kubeflow/issues/945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/946)
=> Downgrade ambassador version to 0.30.1

kubeflow/core/kubeform_spawner.py
* Updated images should include support for mounting PV at /home/joyvan.
/assign @pdmack 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/947)
=> Update the notebook images used with Jupyter.

docs_dev/releasing.md, kubeflow/automation/parts.yaml, kubeflow/automation/prototypes/release.jsonnet, kubeflow/automation/release.libsonnet, kubeflow/registry.yaml
Initial version of image release prototype.
For https://github.com/kubeflow/kubeflow/issues/941
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/948)
=> ksonnet prototype for automated image release

user_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/952)
=> Add aws cloud details

docs/gke/configs/cluster-kubeflow.yaml, docs/gke/configs/cluster.jinja
1. fix typo in cluster.jinja
2. update bootstrapper image
3. remove ```registries:``` from cluster-kubeflow.yaml since it's not needed with new image. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/982)
=> config update

kubeflow/katib/README.md
For #973 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/989)
=> Doc for katib

docs/gke/configs/deploy.sh
Also, use set +e to disable exit on error for bash
/cc @activatedgeek @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/993)
=> Enable iam api and set project flag explicitly

bootstrap/Dockerfile, bootstrap/cmd/bootstrap/app/server.go
1. update ks version in bootstrap to 0.11.0
2. run ks apply for each component following orders in config file
fix https://github.com/kubeflow/kubeflow/issues/1006.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1008)
=> update ks version; run ks apply following config order

components/README.md, components/k8s-model-server/images/versions/1.8/version-config.json, kubeflow/tf-serving/tf-serving.libsonnet
For #845
Tested that the new image works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1011)
=> Add tf serving 1.8 cpu image

bootstrap/README.md, bootstrap/bootstrapper.yaml
1. Update bootstrapper doc.
2. small fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/992)
=> bootstrapper doc update

user_guide.md
Just pops up in so many weird ways. Time to be more explicit about it IMHO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/929)
=> Add AVX to Troubleshooting

kubeflow/core/ambassador.libsonnet, kubeflow/core/prototypes/all.jsonnet
Fix #994 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1023)
=> Fix param name of ambassador

bootstrap/bootstrapper.yaml, docs/gke/configs/cluster-kubeflow.yaml, kubeflow/core/ambassador.libsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/prototypes/all.jsonnet, kubeflow/core/tests/centraldashboard_test.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1025)
=> Merge master commits to release 0.2 branch

releasing/prow_config_release.yaml
For https://github.com/kubeflow/kubeflow/issues/1020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1026)
=> fix format error for nightly release config

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
fix https://github.com/kubeflow/kubeflow/issues/1020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1034)
=> update pytorch image

kubeflow/examples/prototypes/tensorboard.jsonnet, kubeflow/examples/prototypes/tf-job-simple-v1alpha1.jsonnet, testing/tf_job_simple_test.py
* Make tf-job-simple a v1alpha2 prototype
* Rename the existing tf-job-simple-v1alpha1 prototype
* Add a prototype for tensorboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1035)
=> Update examples for 0.2.

kubeflow/core/kubeform_spawner.py
Fixes #1041 
/assign @kunmingg 
@cheyang do you have a mirror image that you want me to add here for alibaba?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1052)
=> Update default notebook image for spawner

kubeflow/core/kubeform_spawner.py
One digit wrong. Confirmed this time with pull and launch in d.k.o.
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1058)
=> Fix typo in NB image sha

kubeflow/core/kubeform_spawner.py, kubeflow/examples/prototypes/tensorboard.jsonnet, kubeflow/examples/prototypes/tf-job-simple-v1alpha1.jsonnet, kubeflow/mpi-job/mpi-operator.libsonnet, kubeflow/mpi-job/parts.yaml, kubeflow/mpi-job/prototypes/mpi-job-custom.jsonnet, kubeflow/mpi-job/prototypes/mpi-job-simple.jsonnet, kubeflow/mpi-job/prototypes/mpi-operator.jsonnet, kubeflow/registry.yaml, testing/tf_job_simple_test.py
https://github.com/kubeflow/kubeflow/issues/1024#issuecomment-399111025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1064)
=> cherry pick fixes to release branch

kubeflow/core/prototypes/all.jsonnet, kubeflow/core/prototypes/tf-job-operator.jsonnet
cherry pick 
update tf_operator image to point to tag v0.2.0 (#1062)
for rc1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1065)
=> cherry pick: update tf_operator image to point to tag v0.2.0 (#1062)

kubeflow/mpi-job/README.md
kubeflow/mpi-operator#19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1079)
=> add a readme file to the mpi-job ksonnet component

README.md, bootstrap/README.md, components/jupyterhub/README.md, components/k8s-model-server/README.md, kubeflow/README.md, tf-controller-examples/tf-cnn/README.md
fix #1075
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1077)
=> fix #1075, user_guide link is dead

kubeflow/tf-job/tf-job.libsonnet
fix https://github.com/kubeflow/kubeflow/issues/1049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1086)
=> update tf job default version

kubeflow/tf-job/tf-job.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1087)
=> cherry-pick: update tf job default version (#1086)

docs/gke/README.md, docs/gke/configs/deploy.sh
For #288 
/cc @jlewi 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1094)
=> Install gpu driver in deployment manager

docs/gke/configs/deploy.sh
* Use a single gcloud command to enable all APIs; this should be faster
than enabling APIs serially.
* Add an option to skip project setup; this can speedup deployments when project
is already setup.
* Detect if the deployment exists and issue an update rather than a create.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1093)
=> Improvements to deploy.sh

bootstrap/cmd/bootstrap/app/server.go, kubeflow/registry.yaml
To smooth user experience, including https://github.com/kubeflow/examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1098)
=> add seldon to ks config; pre install all pkg

components/gcp-click-to-deploy/src/NameForm.tsx
Fixes https://github.com/kubeflow/kubeflow/issues/1101.
/assign jlewi
/assign ankushagarwal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1105)
=> [gcp-deployer] Fix hostname typo bug

components/echo-server/Dockerfile, components/echo-server/Makefile, components/echo-server/main.py, components/echo-server/main_test.py, components/echo-server/requirements.txt, kubeflow/core/echo-server.libsonnet, kubeflow/core/prototypes/echo-server.jsonnet
* This is intended to support debugging IAP; we want to see what headers
are on resulting requests.
* See kubeflow/kubeflow#574
* While creating this I ran into an issue with ksonnet not formatting the
Ambassador mapping correctly unless we import it from a libsonnet file see
ksonnet/ksonnet#670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1097)
=> Create a version of echo-server to echo headers.

bootstrap/image_registries.yaml, kubeflow/core/tf-job-operator.libsonnet
See https://github.com/kubeflow/tf-operator/issues/701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1099)
=> Tfjob create fails in tfjob UI

components/gcp-click-to-deploy/src/App.css, components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/Gapi.ts, components/gcp-click-to-deploy/src/NameForm.tsx, components/gcp-click-to-deploy/src/Utils.ts, components/gcp-click-to-deploy/src/index.css
This adds simple log messages to track the progress of the deployment in the log area, including errors.
/assign jlewi
/assign ankushagarwal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1108)
=> [gcp-deployer] Rudimentary progress in logs

components/gcp-click-to-deploy/Dockerfile, components/gcp-click-to-deploy/Makefile
Fixes https://github.com/kubeflow/kubeflow/issues/1055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1122)
=> Add Dockerfile and Makefile to build docker images

docs/gke/configs/cluster.jinja, scripts/gke/deployment_manager_configs/cluster.jinja
So gke cluster will have read access of gcr
fix https://github.com/kubeflow/kubeflow/issues/1139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1164)
=> Make GKE VM service account storage.objectViewer

docs_dev/releasing.md, kubeflow/core/kubeform_spawner.py, releasing/README.md, releasing/apply_image_tags.py, releasing/image_tags.yaml, releasing/run_apply_image_tags.sh, releasing/update_image_tags.sh, releasing/update_images.sh, releasing/update_ksonnet.sh
* These images includes fixes to TFMA in the Jupyter images.
* Include some minor fixes to the scripts used to manage images.
* Related to #1129 - Upgrade images for 0.2.1
* Related to #1130 - Fix TFMA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1144)
=> Tag the latest Jupyter images with v0.2.1

kubeflow/core/prototypes/all.jsonnet
Related to #1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1182)
=> Cherry pick upgrading the central UI to v0.2.1

testing/vm_util.py
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1183)
=> Fix socket.Error typo

kubeflow/core/prototypes/all.jsonnet
* Related to #1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1181)
=> Update Central UI image to the v0.2.1 tag.

kubeflow/core/metric-collector.libsonnet, metric-collector/Dockerfile, metric-collector/service-readiness/kubeflow-readiness.py
fix https://github.com/kubeflow/kubeflow/issues/1142
Current attach event to Service centraldashboard.
Will attach to application instead when https://github.com/kubeflow/kubeflow/issues/1106 is in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1161)
=> Make metric collector emit k8s event

scripts/deploy.sh, scripts/deploy_test.sh, scripts/gke/deploy.sh, scripts/gke/deploy_test.sh
* It looks like GitHub is stripping out the v in the name of the top level
directory.
Related to #1193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1194)
=> Fix deploy.sh moving the unpacked repo.

scripts/gke/deploy.sh, scripts/gke/deployment_manager_configs/cluster-kubeflow.yaml, scripts/gke/deployment_manager_configs/cluster.jinja
* Update gke/deploy.sh to support Private GKE Clusters using PRIVATE_CLUSTER env variable
* Minor changes to cluster-kubeflow.yaml
/cc @lluunn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1192)
=> Support private GKE clusters in gke deploy.sh script

kubeflow/core/kubeform_spawner.py
* Align fields using <table>
* Hide advanced fields by default
* Fill in a default image for the image field
/cc @pdmack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1212)
=> Improve jupyterhub form interface

scripts/gke/deploy.sh
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1211)
=> Speed up gke script by running DM and GCFS creation in parallel

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/metric-collector.libsonnet, kubeflow/core/prometheus.libsonnet, kubeflow/core/prometheus.yml, kubeflow/core/prototypes/ambassador.jsonnet, kubeflow/core/prototypes/prometheus.jsonnet
Provide stackdriver compatible prometheus ks prototype to support monitoring within kubeflow.
For https://github.com/kubeflow/kubeflow/issues/1160
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1204)
=> prometheus prototype

kubeflow/core/kubeform_spawner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1238)
=> Update indentation issue in jupyterhub spawner ui

scripts/autoformat_jsonnet.sh, scripts/deploy.sh, scripts/deploy_test.sh, scripts/run_gofmt.sh
- Replace tab with space
- Remove redundant suffix space
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1256)
=> Scripts' code style adjustment

components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/Css.ts, components/gcp-click-to-deploy/src/DeployForm.tsx, components/gcp-click-to-deploy/src/Gapi.ts, components/gcp-click-to-deploy/src/Header.tsx, components/gcp-click-to-deploy/src/Page404.tsx, components/gcp-click-to-deploy/src/Splash.tsx, components/gcp-click-to-deploy/tslint.json
More fixes for the new design, especially around the form, removed the placeholder text, no change in functionality.
The logs area still needs to be moved outside of the `DeployForm` component in order to be a little taller and squeeze the rest of the page upward with a scrollbar. I worked around this for now by making it shorter to the bottom of the screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1260)
=> [gcp-deployer] CSS fixes, Removed Placeholder, linting

scripts/deploy.sh, scripts/gke/deploy.sh
Fix #1268 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1272)
=> Deploy argo in deploy.sh

kubeflow/core/prototypes/tf-job-operator.jsonnet
* I verified the UI works behind IAP now (see #574)
* See #574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1265)
=> Update TFJob image to include the fixes to make the UI work with IAP.

bootstrap/README.md, components/jupyterhub/README.md, components/k8s-model-server/README.md, kubeflow/README.md, tf-controller-examples/tf-cnn/README.md
Fixes issue #1300.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1301)
=> Fixed broken links (to user_guide)

scripts/gke/deploy.sh, scripts/gke/deployment_manager_configs/cluster.jinja
Reverting #1252 
Our certManager is not working with K8s 1.10
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1307)
=> revert to k8s 1.9

kubeflow/core/prototypes/ambassador.jsonnet
Related to https://github.com/kubeflow/kubeflow/pull/1096
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1324)
=> Update ambassador to 0.37.0

docs_dev/releasing.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1352)
=> Add README steps for releasing website

scripts/gke/deployment_manager_configs/cluster.jinja, testing/dm_configs/cluster.jinja
For #1348 
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1355)
=> upgrade gke version for v0.2

bootstrap/cmd/bootstrap/app/ksServer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1361)
=> add optionsHandler for OPTIONS request from browser

kubeflow/tf-serving/tf-serving.libsonnet
Fix #1299 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1370)
=> use tf serving image

scripts/deploy.sh, scripts/gke/deploy.sh
* This is better UX since we want the deploy script to be in sync with
the version of the configs.
Related to #1348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1378)
=> Change the default branch used for the configs to v0.2-branch and not master

kubeflow/core/prototypes/tf-job-operator.jsonnet, testing/workflows/components/workflows.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1391)
=> Cherry-pick: Update TFJob operator to the latest image

ack_guide.md, kubeflow/core/kubeform_spawner.py, scripts/kfctl.sh, scripts/util.sh
Follow up with #1298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1388)
=> support customized image in ACK and update the document

components/gcp-click-to-deploy/src/configs/cluster.jinja, kubeflow/core/prototypes/metric-collector.jsonnet, scripts/gke/deploy.sh, scripts/gke/util.sh
/assign @danisla 
Related https://github.com/kubeflow/kubeflow/pull/1327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1405)
=> Update various scripts to use lowercase clientid/secret

kubeflow/core/ambassador.libsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/prototypes/ambassador.jsonnet, kubeflow/core/prototypes/centraldashboard.jsonnet
Fix #1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1399)
=> Fix annotations in ambassador and centraldashboard

kubeflow/mxnet-job/README.md, kubeflow/mxnet-job/mxnet-operator.libsonnet, kubeflow/mxnet-job/parts.yaml, kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet, kubeflow/mxnet-job/prototypes/mxnet-operator.jsonnet, kubeflow/registry.yaml
Add MXNet operator into kubeflow repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1392)
=> Add mxnet operator (https://github.com/kubeflow/community/issues/136)

scripts/gke/use_gcr_for_all_images.sh
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1404)
=> Fix use_gcr_for_all_images.sh

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1424)
=> Add texasmichelle to OWNERS

kubeflow/seldon/prototypes/abtest-v1alpha1.jsonnet, kubeflow/seldon/prototypes/abtest-v1alpha2.jsonnet, kubeflow/seldon/prototypes/mab-v1alpha1.jsonnet, kubeflow/seldon/prototypes/mab-v1alpha2.jsonnet, kubeflow/seldon/prototypes/outlier-detector-v1alpha1.jsonnet, kubeflow/seldon/prototypes/outlier-detector-v1alpha2.jsonnet, kubeflow/seldon/prototypes/serve-simple-v1alpha1.jsonnet, kubeflow/seldon/prototypes/serve-simple-v1alpha2.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1431)
=> Add imagePullSecret to Seldon Prototypes

scripts/setup-minikube.sh
Needs to point to the parent of kubeflow dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1439)
=> Fix KUBEFLOW_REPO dir pointer.

components/gcp-click-to-deploy/README.md
/cc @kunmingg 
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1445)
=> Fix readme for local run

testing/test_jsonnet.py
Fix #1453 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1456)
=> Fix presubmit unit test

components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/DeployForm.tsx
/cc @kunmingg 
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1449)
=> Click to deploy ui: remove ipName and make hostName optional

bootstrap/cmd/bootstrap/app/gcpUtils.go
See previous PR:
https://github.com/kubeflow/kubeflow/pull/1458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1460)
=> implement gcpUtils which takes care of integrating deployment manager API (part of PR 1458)

components/contrib/kaggle-notebook-image/Dockerfile
Enables downloading kernels and datasets from within our Kubeflow image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1469)
=> Update Kaggle Dockerfile to add their API package

scripts/gke/deployment_manager_configs/cluster.jinja, testing/test_jsonnet.py
* This is needed to pull images from private GCR.
* Cherry pick the fix into the v0.2-branch
* Related to #1432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1468)
=> Add storage read scope to VM scopes; v0.2-branch (#1466)

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet
Similar to tf-operator, added namespace scope to pytorch-operator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1465)
=> Adding namespace scope to pytorch operator

components/tensorflow-notebook-image/Dockerfile
Fixes #1438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1470)
=> Ensure jovyan has site-packages perms

components/gcp-click-to-deploy/src/App.tsx, components/gcp-click-to-deploy/src/DeployForm.tsx
Also add link to client ID.
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1490)
=> click to deploy: remove default project name

scripts/gke/deployment_manager_configs/cluster.jinja
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1494)
=> update gke to 1.10.7-gke.1

kubeflow/argo/argo.libsonnet, kubeflow/argo/prototypes/argo.jsonnet, kubeflow/core/ambassador.libsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/cert-manager.libsonnet, kubeflow/core/cloud-endpoints.libsonnet, kubeflow/core/echo-server.libsonnet, kubeflow/core/google-cloud-filestore-pv.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/jupyterhub.libsonnet, kubeflow/core/metric-collector.libsonnet, kubeflow/core/prometheus.libsonnet, kubeflow/core/prototypes/ambassador.jsonnet, kubeflow/core/prototypes/centraldashboard.jsonnet, kubeflow/core/prototypes/cert-manager.jsonnet, kubeflow/core/prototypes/cloud-endpoints.jsonnet, kubeflow/core/prototypes/echo-server.jsonnet, kubeflow/core/prototypes/google-cloud-filestore-pv.jsonnet, kubeflow/core/prototypes/iap-ingress.jsonnet, kubeflow/core/prototypes/jupyterhub.jsonnet, kubeflow/core/prototypes/metric-collector.jsonnet, kubeflow/core/prototypes/prometheus.jsonnet, kubeflow/core/prototypes/spartakus.jsonnet, kubeflow/core/spartakus.libsonnet, kubeflow/new-package-stub/newpackage.libsonnet, kubeflow/new-package-stub/prototypes/newpackage.jsonnet
fixes #1486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1487)
=> fixes add ability to only generate parts of a component in the jsonnet file

scripts/kfctl.sh
fixes #1429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1498)
=> fixes kfctl.sh unable to find component ambassador

components/jupyterhub/docker/Dockerfile
Released [6 days ago](https://pypi.org/project/jupyterhub-kubespawner/0.9.0/).
Need this in place for progress on #56.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1497)
=> Update jupyterhub-kubespawner version

OWNERS
For some emergent times when we are short of approvers..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1505)
=> Add myself as one of the approvers.

bootstrap/cmd/bootstrap/app/ksServer.go, components/gcp-click-to-deploy/manifest/kf_app.yaml
Otherwise, after 30 sec of no response, FE will get 502.
/cc @kunmingg 
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1504)
=> Update webapp backend to respond and then finish deployment in the background

kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet, kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet
fixes #1500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1501)
=> fixes update tensorboard to use the same pattern as kubeflow/core/prototypes

bootstrap/cmd/bootstrap/app/ksServer.go
1. make backend server pods truly stateless by saving state to cloud source repos (as source of truth)
2. integrate with cloud source repos as private git repo which user can easily clone their kubeflow config after deploy succeeded.
3. with new approach, can implement robust kubeflow edit / update logic into backend server since now we have versioned / trackable state / app config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1515)
=> Integrate with cloud source repos to save ks app config.

bootstrap/cmd/bootstrap/app/ksServer.go, components/gcp-click-to-deploy/manifest/kf_app.yaml
update k8s version for k.libsonnet when do ks init; remove spartakus from web app config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1517)
=> update k8s version for k.libsonnet when do ks init; remove spartakus

components/gcp-click-to-deploy/manifest/kf_app.yaml
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1521)
=> update manifest for webapp

kubeflow/nvidia-inference-server/README.md, kubeflow/nvidia-inference-server/nvidia-inference-server.libsonnet, kubeflow/nvidia-inference-server/parts.yaml, kubeflow/nvidia-inference-server/prototypes/inference-server-all-features.jsonnet, kubeflow/registry.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1523)
=> NVIDIA TensorRT Inference Server

bootstrap/cmd/bootstrap/app/ksServer.go
Also check error for CloneRepoToLocal
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1526)
=> Replace logFatal with logError

scripts/kfctl.sh, scripts/util.sh
This PR resolves that it fails to apply all after delete all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1532)
=> Fix kfctl.sh remove the ksonnet environment for the deleted cluster

components/tensorflow-notebook-image/versions/1.10.1/version-config.json, components/tensorflow-notebook-image/versions/1.10.1gpu/version-config.json, components/tensorflow-notebook-image/versions/1.9.0/version-config.json, components/tensorflow-notebook-image/versions/1.9.0gpu/version-config.json
Closes #1546 
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1547)
=> Add version config for TF 1.9,1.10

kubeflow/core/cert-manager.libsonnet
fix https://github.com/kubeflow/kubeflow/issues/1554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1555)
=> fix cert-manager: add clusterrole back

scripts/gke/deployment_manager_configs/cluster.jinja
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1573)
=> bump gke version to 1.10.7-gke.2

components/gcp-click-to-deploy/src/DeployForm.tsx
Also change the check interval from 3s to 10s
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1581)
=> App frontend stop polling the status after it's done

kubeflow/seldon/core.libsonnet, kubeflow/seldon/json/template_0.2.json, kubeflow/seldon/prototypes/core.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1592)
=> Update Seldon to 0.2.3 version

kubeflow/seldon/core.libsonnet, kubeflow/seldon/json/template_0.2.json, kubeflow/seldon/prototypes/core.jsonnet
* Update Seldon to 0.2.3 version
* format jsonnet
Fixes #1598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1613)
=> Update Seldon to 0.2.3 version on 0.3 branch (#1592)

kubeflow/nvidia-inference-server/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1569)
=> Typo in nvidia inference server README

kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet
Update the pytorch image for 0.3 release
Fixes #1600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1614)
=> Update pytorch image on 0.3 release branch

bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/ksServer.go, components/gcp-click-to-deploy/manifest/kf_app.yaml, components/gcp-click-to-deploy/src/DeployForm.tsx
Need to force update IAM policy in case there are existing orphan IAM bindings for related service accounts in target project (accounts deleted but bindings are still there).
fix https://github.com/kubeflow/kubeflow/issues/1588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1595)
=> Force update IAM policy; print app url on web UI.

OWNERS
Adding myself to the list of PR approvers in kubeflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1622)
=> Add richardsliu to approvers

kubeflow/katib/prototypes/all.jsonnet
Some of these don't have the katib- prefix
/assign @jlewi
Related to #1604  Update Katib images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1625)
=> Update katib image URIs

components/tensorflow-notebook-image/Dockerfile
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1629)
=> Install tensorflow-data-validation in jupyter notebook

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet
Related to: #1541 0.3
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1632)
=> Update katib component to include studyjobcontroller

components/tensorflow-notebook-image/Dockerfile, kubeflow/core/prototypes/jupyterhub.jsonnet, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet
Update katib component to include studyjobcontroller #1632
Install tensorflow-data-validation in jupyter notebook #1629
Use JupyterNotebook as default instead of JupyterLab #1628
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1636)
=> Cherrypick changes from 0.3-branch to master

kubeflow/core/kubeform_spawner.py, releasing/image_tags.yaml, releasing/update_image_tags.sh, releasing/update_ksonnet.sh
- Tag and update images on master, will CP to 0.3.0 branch later
- Related to #1601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1637)
=> Tag release 0.3.0 for Jupyter notebook images

prow_config.yaml
Enable periodic prow tests for:
- kfctl_test
- e2e_minikube
- tf-serving
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1649)
=> Enable periodic prow tests

kubeflow/core/prototypes/centraldashboard.jsonnet, releasing/image_tags.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1657)
=> Tag and update centraldashboard image

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1665)
=> Add swiftdiaries as reviewer

kubeflow/core/cert-manager.libsonnet, kubeflow/core/util.libsonnet
Cherry pick #1580 into v0.3 branch
Related to #1666; need to actually test it to see if this fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1667)
=> remove prune from kubeflow core which delete required fields (#1580)

components/centraldashboard/dashboard.go, components/centraldashboard/frontend/layout/index.html
FileServer displays the directory inside it unless a index.html is provided. Changed the name from layout.html to index.html to fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1676)
=> Fix for "/" not directing to centralUI (#1670). 

releasing/image_tags.yaml
Fixes #1672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1688)
=> Tag images for TF notebooks 1.9.0 and 1.10.1

kubeflow/argo/prototypes/argo.jsonnet, scripts/gke/use_gcr_for_all_images.sh
Want to be included in release 0.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1690)
=> upgrade argo version to v2.2.0

kubeflow/argo/prototypes/argo.jsonnet, scripts/gke/use_gcr_for_all_images.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1692)
=> (cherry pick) upgrade argo version to v2.2.0

kubeflow/kubebench/prototypes/kubebench-job.jsonnet
This updates the followings
- fix default value of mainJobConfig
- update default value of postJobImage
Fix #1596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1693)
=> Update kubebench-job prototype default parameters

kubeflow/tf-serving/tf-serving-template.libsonnet
For #368 
/cc @jlewi 
cc @yupbank
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1700)
=> Add tf serving liveness probe

kubeflow/katib/prototypes/all.jsonnet, testing/deploy_kubeflow.py
Fixes presubmit errors for jsonnet formatting in katib/prototypes/all.jsonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1702)
=> Fix jsonnet formatting errors in katib

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet
The manifest of metrics collector needs namespace.
Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1680)
=> fix katib metrics collector bug

kubeflow/katib/vizier.libsonnet
Add persistency to Katib database in ksonnet prototye
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1687)
=> Add PVC to Katib

kubeflow/tf-serving/tf-serving-template.libsonnet
/cc @richardsliu @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1708)
=> Cherrypick #1700 - TF serving liveness probe

components/gcp-click-to-deploy/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1640)
=> Update link in README

kubeflow/tf-serving/tf-serving.libsonnet
Replace key.json with user-gcp-sa.json
/cc @texasmichelle 
For #1719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1720)
=> Cherry-pick: Update gcp credentials filename (#1716)

components/gcp-click-to-deploy/src/App.tsx
* Add some information to the page explaining what the App is doing so users can make an informed 
decision.
* Point users to the CLI if they prefer to use that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1713)
=> Add a notice explaining to users what the app is doing.

bootstrap/Dockerfile, bootstrap/config/gcp_prototype.yaml, bootstrap/image_registries.yaml
want to be included in 0.3 release if possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1705)
=> config & dockerfile update

components/tensorflow-notebook-image/Dockerfile
Related to #1721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1746)
=> Pin jupyter-console to 0.6.0

components/tensorflow-notebook-image/Dockerfile, scripts/gke/util.sh, scripts/kfctl.sh
Cherry pick #1746 and #1747 onto the 0.3 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1756)
=> Cherry pick #1746 and #1747

deployment/gke/deployment_manager_configs/cluster.jinja
For #1757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1765)
=> Use new stackdriver agents in DM config

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/suggestion.libsonnet, releasing/update_katib_ksonnet.sh
Add missing hyperband/bayesianoptimization suggestion images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1727)
=> Add katib's hyperband/bayesianoptimization suggestion images (#1464)

kubeflow/core/jupyterhub.libsonnet, kubeflow/core/tests/tensorboard_test.jsonnet, kubeflow/examples/prototypes/tensorboard.jsonnet, kubeflow/tensorboard/aws.libsonnet, kubeflow/tensorboard/gcp.libsonnet, kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet, kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet, kubeflow/tensorboard/tensorboard.libsonnet
Related to #1753
Will need to cherry pick onto v0.3-branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1754)
=> fixes tensorboard generated under kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet is incomplete

kubeflow/katib/prototypes/all.jsonnet
* Update katib suggestion images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1781)
=> Cherry pick #1779

kubeflow/katib/prototypes/all.jsonnet
This PR will update to latest working suggestion images, especially `bayesianoptimization` suggestion image.
See #1779
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1780)
=> Update katib suggestion images (#1779)

scripts/autoformat_jsonnet.sh
Just moving this logic in the conditional. `readarray` does not work on macOS, so only `scripts/autoformat_jsonnet --all` will work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1800)
=> skip readarray if --all provided to jsonnet fmt script

.travis.yml
We can move the copyright boilerplate verification to prow once its working.
ref #1789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1790)
=> remove travis config

kubeflow/core/tests/tensorboard_test.jsonnet, kubeflow/tensorboard/aws.libsonnet, kubeflow/tensorboard/gcp.libsonnet, kubeflow/tensorboard/prototypes/tensorboard-aws.jsonnet, kubeflow/tensorboard/prototypes/tensorboard-gcp.jsonnet, kubeflow/tensorboard/tensorboard.libsonnet
see PR #1754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1794)
=> cherry-pick PR #1754 onto V0.3 branch

kubeflow/knative-build/knative-build.libsonnet, kubeflow/knative-build/parts.yaml, kubeflow/knative-build/prototypes/knative-build.jsonnet
Addresses issue: https://github.com/kubeflow/kubeflow/issues/1317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1804)
=> Knative build for in-cluster image builds in Kubeflow

kubeflow/argo/argo.libsonnet, kubeflow/core/ambassador.libsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/cert-manager.libsonnet, kubeflow/core/cloud-endpoints.libsonnet, kubeflow/core/echo-server.libsonnet, kubeflow/core/google-cloud-filestore-pv.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/metric-collector.libsonnet, kubeflow/core/prometheus.libsonnet, kubeflow/core/spartakus.libsonnet, kubeflow/core/tf-job-operator.libsonnet
fixes #1798
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1799)
=> fixes 'add parts attribute to libsonnet for ksonnet incubator/best practices'

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/build_image.sh, components/tensorflow-notebook-image/releaser/components/workflows.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1797)
=> Pin tf-serving version in tf-notebook

bootstrap/build_image.sh, bootstrap/test_delete.sh, prow_config.yaml, testing/test_deploy_app.py, testing/workflows/components/click_deploy_test.jsonnet
Add ssl cert reuse logic in e2e & prober tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1817)
=> add ssl cert reuse logic in e2e & prober tests

components/gcp-click-to-deploy/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1792)
=> Make the project configurable.

bootstrap/cmd/bootstrap/app/ksServer.go
- Flow start time of request handling through the context
- create metrics around time to process the requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1836)
=> Add some latency metrics for GKE & KF deployments

components/contrib/rapidsai-notebook-image/Dockerfile, components/contrib/rapidsai-notebook-image/README.md
Related to #1806
Couldn't find their public Dockerfile repo.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1809)
=> Add RapidsAI notebook image

deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml, deployment/gke/deployment_manager_configs/cluster.jinja
fix #1840
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1852)
=> use broadwell

kubeflow/tf-serving/prototypes/tf-serving-gcp.jsonnet, kubeflow/tf-serving/tf-serving.libsonnet
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1850)
=> use TF serving 1.11.1

components/gcp-click-to-deploy/src/DeployForm.tsx
only provide version from stable release tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1868)
=> remove default version

kubeflow/core/configure_envoy_for_iap.sh, kubeflow/core/prometheus.yml
Want to include this fix in 0.3.2 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1869)
=> fix iap set up and prometheus config (#1847)

hack/cherry-picks.md, hack/cherry_pick_pull.sh
This is a copy of https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh. See the documentation for installation and usage details.
See https://github.com/kubeflow/kubeflow/pull/1877 for an example output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1880)
=> Add a script that automatically creates cherry-picks

testing/test_deploy_app.py
add prober test logic to test_deploy_app.py
which for loop:
1. clean up resource
2. make deploy call
3. check result
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1845)
=> prober test, kubeflow testing part

components/gcp-click-to-deploy/src/DeployForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1875)
=> upgrade app version to 0.3.2

kubeflow/core/configure_envoy_for_iap.sh
cherry pick fix to master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1879)
=> fix iap script

.gitignore, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/core/tf-job-operator.libsonnet
Related to #1883
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1884)
=> Automated cherry pick of #1717 upstream v0.3 branch

docs/gke/gateway.yaml, kubeflow/core/iap.libsonnet
`/istio` will be routed to istio-ingressgatway
Related to
#1844 
#1309 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1906)
=> Envoy config change for istio

components/gcp-click-to-deploy/src/App.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1910)
=> make links open in new tab

kubeflow/core/prototypes/tf-job-operator.jsonnet, kubeflow/core/tests/tf-job_test.jsonnet, kubeflow/core/tf-job-operator.libsonnet, kubeflow/examples/prototypes/tf-job-simple-v1beta1.jsonnet, testing/deploy_kubeflow.py, testing/tf_job_simple_test.py, testing/wait_for_kubeflow.py, testing/workflows/components/workflows.libsonnet
Install tf-operator v1beta1 by default.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1921)
=> Update tf-operator component to v1beta1

components/tensorflow-notebook-image/releaser/components/workflows.libsonnet, components/tensorflow-notebook-image/versions/1.11.0/version-config.json, components/tensorflow-notebook-image/versions/1.11.0gpu/version-config.json, components/tensorflow-notebook-image/versions/1.12.0/version-config.json, components/tensorflow-notebook-image/versions/1.12.0gpu/version-config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1786)
=> [tf-notebook-image] add tf 1.11 cpu and gpu images

kubeflow/core/spartakus.libsonnet
fixes #1940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1941)
=> Switch spartakus volunteer image to v1.1.0

components/centraldashboard/frontend/index/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1951)
=> Add pipeline to centaldashboard

kubeflow/tf-serving/prototypes/tf-serving-service.jsonnet, kubeflow/tf-serving/tf-serving-service-template.libsonnet
Fix #1036 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1958)
=> Add prometheus annotation to tf serving service

components/gcp-click-to-deploy/src/DeployForm.tsx
fixes missing . in the url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1962)
=> Fix dashboard URI and increase poll interval.

kubeflow/argo/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1974)
=> Add IronPan as Argo owner

kubeflow/pipeline/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1980)
=> Add IronPan to pipeline ks package owner

bootstrap/config/default.yaml, bootstrap/config/gcp_prototype.yaml, components/gcp-click-to-deploy/manifest/kf_app.yaml, kubeflow/pipeline/parts.yaml, scripts/kfctl.sh, scripts/util.sh
And promote Argo as a required component
Fixed the parts.yaml format
Verified it works with kfctl.sh
TODO verify one-click-deployment works. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1981)
=> add pipeline as part of kf deployment

bootstrap/cmd/bootstrap/app/ksServer.go
As now DM won't touch IAM directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1984)
=> Remove IAM permission from DM service account

kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet, kubeflow/pytorch-job/prototypes/pytorch-operator.jsonnet, kubeflow/pytorch-job/pytorch-operator.libsonnet
1. New docker image with v1beta1 binary is added
2. v1beta1 version is included by default
3. v1alpha1 version is removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1978)
=> Adding Pytorch v1beta1 image

.travis.yml, bootstrap/config/default.yaml, bootstrap/config/gcp_prototype.yaml, components/gcp-click-to-deploy/manifest/kf_app.yaml, kubeflow/argo/OWNERS, kubeflow/pipeline/OWNERS, kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/mysql.libsonnet, kubeflow/pipeline/parts.yaml, kubeflow/pipeline/pipeline-apiserver.libsonnet, kubeflow/pipeline/pipeline-persistenceagent.libsonnet, kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet, kubeflow/pipeline/pipeline-ui.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet, kubeflow/pipeline/spartakus.libsonnet, kubeflow/registry.yaml, scripts/kfctl.sh, scripts/util.sh
Cherry-pick the pipelines component to the 0.3-branch in preparation for cutting a v0.3.4 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1998)
=> Pipelines 0.3.3 cherrypick

bootstrap/cmd/bootstrap/app/gcpUtils.go
To maximize throughput when concurrent requests targeting same project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2004)
=> use backoff module to handle IAM policy retry with randmize wait time

kubeflow/tf-training/tf-job-operator.libsonnet
Adding deployment scope to tf-job-dashboard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2002)
=> Adding scope for tf job dashboard

components/tensorflow-notebook-image/Dockerfile
And I'll update the version once the new SDK is released
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2008)
=> Add latest stable DSL SDK to jupyter image

bootstrap/config/gcp_prototype.yaml, testing/test_deploy_app.py
1. make concurrent deploy requests to staging api.
2. wait and verify all outcomes are succeeded.
3. recycle resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1986)
=> deploy app loadtest, python part

kubeflow/application/application.libsonnet
fixes #2001, #2006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2007)
=> fixes 'trying to deploy a component using ks after initial deployment fails'

kubeflow/application/application.libsonnet, kubeflow/argo/argo.libsonnet, kubeflow/core/ambassador.libsonnet, kubeflow/core/centraldashboard.libsonnet, kubeflow/core/cert-manager.libsonnet, kubeflow/core/cloud-endpoints.libsonnet, kubeflow/core/echo-server.libsonnet, kubeflow/core/google-cloud-filestore-pv.libsonnet, kubeflow/core/iap.libsonnet, kubeflow/core/metric-collector.libsonnet, kubeflow/core/prometheus.libsonnet, kubeflow/core/spartakus.libsonnet, kubeflow/jupyter/jupyter.libsonnet, kubeflow/knative-build/knative-build.libsonnet, kubeflow/metacontroller/metacontroller.libsonnet, kubeflow/new-package-stub/newpackage.libsonnet, kubeflow/profiles/profiles.libsonnet, kubeflow/tensorboard/tensorboard.libsonnet, kubeflow/tf-serving/prototypes/tf-serving-all-features.jsonnet, kubeflow/tf-serving/tf-serving-service-template.libsonnet, kubeflow/tf-serving/tf-serving-template.libsonnet, kubeflow/tf-training/tf-job-operator.libsonnet, testing/test_deploy.py
fixes #1924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/1939)
=> fixes 'ksonnet env should override params'

deployment/gke/deployment_manager_configs/iam_bindings_template.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2013)
=> grant KF user SA CMLE admin permission

components/gcp-click-to-deploy/src/DeployForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2017)
=> Activate CMLE during one-click deployment

istio/grafana-virtual-service.yaml
This will expose grafana dashboard at
https://KFDEPLOY.endpoints.PROJECT.cloud.goog/istio/grafana/
/cc @jlewi 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2025)
=> Grafana routing rule

scripts/gke/util.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2018)
=> Activate CMLE during kfctl deployment

kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2045)
=> Update Pipeline version to v0.1.3

bootstrap/cmd/bootstrap/app/gcpUtils.go, bootstrap/cmd/bootstrap/app/ksServer.go
* counters: merge counters to Counter Vec with label ```status```
* failure count: exclude failure caused by user input
* gauge: exclude traffic from prober test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2048)
=> refactor monitoring metrics

components/contrib/rapidsai-notebook-image/Dockerfile
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2053)
=> Updates for RAPIDS AI v0.4.0 image

components/centraldashboard/frontend/index/index.html, components/centraldashboard/frontend/layout/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2056)
=> unify central dashboard layout

kubeflow/core/prototypes/centraldashboard.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2047)
=> upgrade central dashboard image to v0.3.4 to include pipeline ui link

kubeflow/jupyter/jupyter.libsonnet, kubeflow/jupyter/tests/jupyter_test.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2015)
=> Give jupyter-notebook pods/log permission for fairing

components/gcp-click-to-deploy/src/DeployForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2063)
=> update kf version to v0.3.4

components/contrib/rapidsai-notebook-image/Dockerfile, components/contrib/rapidsai-notebook-image/README.md
/assign @abhi-g 
Last mile updates in Dockerfile and README for an MVP image. Please expedite since the blog should probably link the details in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2066)
=> Temp workaround for RAPIDS shared lib issues

components/tensorflow-notebook-image/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2046)
=> Update Pipeline SDK version to v0.1.3

components/centraldashboard/frontend/layout/index.html, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet, kubeflow/katib/vizier.libsonnet, releasing/update_components.sh
- Update katib components to support TFJob hyperparameter tuning
- Allow katib studyjobcontroller to delete pods
- Add ambassador annotation to katib-ui
- Fixed katib url in centraldashboard 
- Fixed bug in update_components script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2064)
=> Update katib components

scripts/setup-minikube.sh
Fixes: https://github.com/kubeflow/kubeflow/issues/2068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2082)
=> Fix variable in setup-minikube.sh

kubeflow/gcp/cloud-endpoints.libsonnet, kubeflow/metacontroller/prototypes/metacontroller.jsonnet, kubeflow/metacontroller/tests/metacontroller_test.jsonnet, kubeflow/profiles/tests/profiles_test.jsonnet
fixes #1824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2080)
=> fixes 'upgrade cloud-endpoints-controller to use metacontroller/metacontroller:v0.3.0

OWNERS
For the v0.4.0 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2106)
=> add r2d4 to approvers

kubeflow/pipeline/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2108)
=> Add yebrahim to pipeline ksonnet owner

components/gcp-click-to-deploy/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2138)
=> Fix one click deployer url in README

scripts/util.sh
Add a fall back from which to type to support aliases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2137)
=> Fixes initialization script does not correctly detect ks installation

kubeflow/kubebench/OWNERS, kubeflow/kubebench/kubebench-operator.libsonnet, kubeflow/kubebench/parts.yaml, kubeflow/kubebench/prototypes/kubebench-operator.jsonnet
Fixes: https://github.com/kubeflow/kubeflow/issues/2110. 
Related to: https://github.com/kubeflow/kubebench/issues/155. 
This is ksonnet package for kubebench operator CRD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2111)
=> Kubebench operator ksonnet package

kubeflow/katib/README.md, kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet, kubeflow/katib/vizier.libsonnet
Fixes: https://github.com/kubeflow/kubeflow/issues/2126.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2135)
=> Update ksonnet package for Katib

components/tensorflow-notebook-image/Dockerfile, kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2151)
=> update pipeline version

components/gcp-click-to-deploy/src/DeployForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2161)
=> update kf version to 0.3.5; add retry around IAM policy edit

bootstrap/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2164)
=> [gcp-click-to-deploy] cleanup: remove ks and kubectl from Dockerfile

kfctl/OWNERS, kfctl/README.md
Related to #1419 
kfctl functional description in README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2091)
=> kfctl functional description and changes required

docs_dev/releasing.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2179)
=> Add instructions for enabling the periodic tests on the new release branch

components/gcp-click-to-deploy/src/DeployForm.tsx
fixes #2166 and fixes #2165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2167)
=> Add log timestamps, and do not wait for IAP if skipped IAP

ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2200)
=> Add CUJs for  multiuser kubeflow to the ROADMAP.

components/gcp-click-to-deploy/src/DeployForm.tsx
Merging the changes to v0.4 as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2198)
=> Add log timestamps, and do not wait for IAP if skipped IAP 

kubeflow/pipeline/pipeline-apiserver.libsonnet
Cherrypick https://github.com/kubeflow/kubeflow/pull/2199 to v0.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2203)
=> Cherrypick - Add retry to loading the sample job (#2199)

kubeflow/katib/prototypes/all.jsonnet, releasing/add_image_shas.py, releasing/add_katib_image_shas.sh, releasing/image_tags.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2204)
=> Tag and update katib for v0.4.0 release

scripts/kfctl.sh
/assign @abhi-g 
I'll send a follow up cherry-pick to v0.4-branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2210)
=> kfctl: add default zone if not specified

scripts/kfctl.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2214)
=> Cherrypick v0.4-branch: kfctl: add default zone if not specified (#2210)

components/gcp-click-to-deploy/src/DeployForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2217)
=> publish v0.4.0 on web app

kubeflow/kubebench/kubebench-dashboard.libsonnet, kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2219)
=> Add kubebench-dashboard package

kubeflow/kubebench/kubebench-dashboard.libsonnet, kubeflow/kubebench/prototypes/kubebench-dashboard.jsonnet, kubeflow/kubebench/prototypes/kubebench-job.jsonnet, kubeflow/kubebench/prototypes/kubebench-operator.jsonnet, releasing/image_tags.yaml, releasing/update_components.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2220)
=> Kubebench component update cherrypick

kubeflow/common/ambassador.libsonnet, kubeflow/common/prototypes/ambassador.jsonnet, kubeflow/common/tests/ambassador_test.jsonnet, scripts/kfctl.sh
Fixes #1112.
Fix the test based on the change from the original PR https://github.com/kubeflow/kubeflow/pull/2049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2224)
=> Make ambassador number of replicas configurable #1112

bootstrap/Dockerfile, bootstrap/Makefile, bootstrap/cmd/bootstrap/app/ksServer.go
ks init params have incompatible changes in v0.13.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2245)
=> update params following ksonnet v0.13.1; update image build file path

testing/test_jsonnet.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2246)
=> Minor readability modifications in test_jsonnet.py

scripts/util.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2243)
=> update jupyter hub with customized docker registry

kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2252)
=> Update Pipeline version to v0.1.7

components/tensorflow-notebook-image/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2253)
=> bump pipeline sdk version to 0.1.7

kubeflow/registry.yaml
clean up v0.4 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2266)
=> remove ghost registries from 0.4 branch

releasing/sync_images.py, scripts/kfctl.sh, scripts/util.sh
Cherry pick:
- Sync up Kubeflow official docker images to user's registry (#2230)
- Fix katib repo for  the docker registry which doesn't support sub namespace (#2237)
- update jupyter hub with customized docker registry (#2243)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2255)
=> Branch v0.4.0 fix

kubeflow/pipeline/pipeline-apiserver.libsonnet, kubeflow/pipeline/pipeline-persistenceagent.libsonnet, kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet, kubeflow/pipeline/pipeline-ui.libsonnet
fixes: #2249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2251)
=> Update image pull policy for pipeline

kubeflow/registry.yaml
kubeflow registry seems missing some pkgs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2276)
=> add missing pkg to registry

kubeflow/registry.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2281)
=> add gcp to registry

components/tensorflow-notebook-image/Dockerfile, kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/mysql.libsonnet, kubeflow/pipeline/pipeline-apiserver.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2274)
=> cherrypick changes to V0.4 branch

components/gcp-click-to-deploy/src/DeployForm.tsx
customize params for v0.3, can be removed after https://github.com/kubeflow/kubeflow/pull/2019 fully functional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2285)
=> adjust param name for v0.3 compatibility

scripts/kfctl.sh
Relates to kubeflow/testing#95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2278)
=> Update kfctl to export PLATFORM and GKE_API_VERSION

kubeflow/pipeline/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2297)
=> add neuromage to owner of pipeline registry

kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2298)
=> Bump ScheduledWorkflow CRD version to v1beta1

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2301)
=> update katib studyjob controller manifest

components/tensorflow-notebook-image/requirements.txt
Fix #1932
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2241)
=> Added 'google-api-python-client' to JH images

components/tensorflow-notebook-image/Dockerfile
The credential helper needs to be invoked after the user is created.
Adds xgboost to the image and bumps the fairing library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2286)
=> Add xgboost to image, fix credential-helper

scripts/kfctl.sh
- Fixes #1669 
- Syntax improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2305)
=> Added context check before issuing delete

docs/gke/iap_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2283)
=> Define signer_email in main to remove flake8 F821 #2229

kubeflow/pipeline/pipeline-apiserver.libsonnet
accidentally included in https://github.com/kubeflow/kubeflow/pull/2251. remove it to clean up the registry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2322)
=> Clean up - Remove the load sample job

scripts/gke/util.sh
Cherrypicked #2313 from master branch to v0.4-branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2324)
=> GCP secrets cherrypick

dependencies/istio/install/README.md, dependencies/istio/install/istio-noauth.yaml
See https://cloud.google.com/iap/docs/enabling-kubernetes-howto#kubernetes-configure
/cc @jlewi 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2352)
=> Add annotation to istio ingressgateway to enable IAP

components/gcp-click-to-deploy/README.md, components/gcp-click-to-deploy/app-config.yaml
For deploy app frontend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2346)
=> update config and README for local test

bootstrap/cmd/bootstrap/app/ksServer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2362)
=> one-click-deploy fix - break if deploy successfully

kubeflow/jupyter/tests/conftest.py, kubeflow/jupyter/tests/jupyter_test.py, scripts/kfctl.sh, testing/workflows/components/kfctl_test.jsonnet, testing/workflows/components/workflows.libsonnet, testing/workflows/environments/kubeflow-testing/params.libsonnet
Fix #2174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2333)
=> Integrate Jupyter e2e test into CI

components/tensorflow-notebook-image/Dockerfile, kubeflow/pipeline/prototypes/pipeline.jsonnet
/assign @kunmingg @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2295)
=> Update pipelines version to 0.1.8

scripts/kfctl.sh, scripts/util.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2369)
=> Combine check for kf client dependencies into one utility function check_installed_deps

kubeflow/pipeline/all.libsonnet, kubeflow/pipeline/minio.libsonnet, kubeflow/pipeline/prototypes/pipeline.jsonnet, kubeflow/pipeline/storage.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2425)
=> provision minio using pv or pd directly. only create nfs conditionally

kubeflow/pipeline/pipeline-scheduledworkflow.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2424)
=> Specify CRD version using v1beta1 schema

kubeflow/pipeline/prototypes/pipeline.jsonnet
/assign @neuromage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2427)
=> Bump pipeline version to 0.1.9

deployment/gke/deployment_manager_configs/storage-kubeflow.yaml, scripts/gke/util.sh, scripts/kfctl.sh, testing/workflows/components/kfctl_test.jsonnet
Create kubeflow storage DM as part of kfctl.sh
This creates GCE PD as permanent storage and the storage is used by pipeline service for storing data permanently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2373)
=> deploy storage through kfctl.sh

scripts/kfctl.sh
Mitigate https://github.com/kubeflow/kubeflow/issues/2408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2409)
=> Wait for at most 100s on namespace deletion

bootstrap/test_delete.sh, testing/test_deploy_app.py, testing/workflows/components/click_deploy_test.jsonnet
- The test was not producing any junit and thus not shown on testgrid.
- Also added some logging.
- Fix some bugs
https://github.com/kubeflow/testing/issues/301
https://github.com/kubeflow/kubeflow/issues/2364
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2437)
=> make click-deploy-test upload junit artifacts

components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go, components/notebook-controller/pkg/controller/notebook/notebook_controller.go, kubeflow/jupyter/notebook_controller.libsonnet
#2417
- Also watch the service
- enable [status sub-resource](https://book.kubebuilder.io/basics/status_subresource.html)
/cc @kkasravi 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2439)
=> NB controller fix

kubeflow/pipeline/storage.libsonnet
Since the corresponding PVC only need 20Gb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2464)
=> Reduce NFS disk size from 200 -> 20 GB

bootstrap/Makefile, bootstrap/go.mod, bootstrap/go.sum, components/gatekeeper/auth/AuthServer.go, components/gcp-click-to-deploy/package-lock.json, components/gcp-click-to-deploy/package.json, components/gcp-click-to-deploy/src/DeployForm.tsx, components/gcp-click-to-deploy/src/Utils.ts, kubeflow/common/prototypes/basic-auth.jsonnet, kubeflow/gcp/basic-auth-ingress.libsonnet
1. add basic auth as alternative of iap access to deploy app; 
2. makefile clean up
TODO: update docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2455)
=> add basic auth as alternative of iap access to deploy app; 

testing/Dockerfile, testing/workflows/components/click_deploy_test.jsonnet, testing/workflows/components/tfserving.libsonnet, testing/workflows/components/unit_tests.jsonnet, testing/workflows/components/workflows.libsonnet
click to deploy test is failing because test image is too old
/cc @jlewi 
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2477)
=> fix test image

kubeflow/profiles/profiles.libsonnet, kubeflow/profiles/tests/profiles_test.jsonnet
fix #2423 
/cc @kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2473)
=> Fix typo in profile CR

bootstrap/cmd/bootstrap/app/saKey.go, components/gcp-click-to-deploy/src/DeployForm.tsx, kubeflow/common/basic-auth.libsonnet, kubeflow/common/prototypes/basic-auth.jsonnet
Follow up of https://github.com/kubeflow/kubeflow/pull/2455
Avoid checkin credential hash values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2485)
=> pass username & password hash as k8s secret instead of ks parameters

bootstrap/cmd/bootstrap/app/ksServer.go
fix https://github.com/kubeflow/kubeflow/issues/2489
follow up of https://github.com/kubeflow/kubeflow/pull/2485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2494)
=> add missing fields

kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2496)
=> Bump up pipeline version to 0.1.10

kubeflow/pipeline/prototypes/pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2501)
=> Bump up pipeline version to 0.1.10 (#2496)

components/centraldashboard/OWNERS
Added myself to OWNERS so I can merge after LGTMs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2502)
=> Add myself to Central Dashboard owners

kubeflow/kubebench/tests/kubebench-operator_test.jsonnet, testing/test_jsonnet.py, testing/workflows/components/unit_tests.jsonnet
Fixes: https://github.com/kubeflow/kubeflow/issues/2134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2495)
=> Add kubebench-operator jsonnet unit test

bootstrap/cmd/bootstrap/app/ksServer.go, deployment/gke/deployment_manager_configs/storage-kubeflow.yaml, deployment/gke/deployment_manager_configs/storage.jinja.schema, scripts/gke/util.sh
Name the PD generically to avoid future renaming
Also assign PDs to minio to skip creating nfs by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2503)
=> name the PD generically and assign to minio

bootstrap/README.md, bootstrap/developer_guide.md, components/gcp-click-to-deploy/README.md
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2527)
=> Update dev guide for bootstrapper

components/tensorflow-notebook-image/Dockerfile, components/tensorflow-notebook-image/start-notebook.sh
Modified entrypoint command for jupyter images to launch jupyter on boot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2517)
=> Change jupyter images to work with the new jupyter CR, issue# 2458

kubeflow/pipeline/pipeline.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2534)
=> update pipeline image version to v0.1.10

bootstrap/developer_guide.md
Previously the args are not used.
/cc @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2538)
=> fix command in bootstrap dev guide

kubeflow/gcp/iap.libsonnet, kubeflow/gcp/tests/iap_test.jsonnet
To be the same as https://github.com/kubeflow/kubeflow/blob/master/dependencies/istio/install/istio-noauth.yaml#L13729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2542)
=> fix backendconfig name

components/notebook-controller/pkg/controller/notebook/notebook_controller.go
/cc @kunmingg  
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2506)
=> Small fix for notebook controller

bootstrap/cmd/bootstrap/app/gcpUtils_test.go
I noticed #1895 and decided to help you guys. As this is the first contribution and I didn't know what style to follow, I wrote unit tests only for one function. The less (test) code, the easier it will be for me to fix accordingly to your review comments.
If everything will be fine, I may write unit tests for other functions at `gcpUtils.go` as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2516)
=> Added unit tests for GetUpdatedPolicy at gcpUtils.go - bootstrap/app

kubeflow/katib/prototypes/all.jsonnet, kubeflow/katib/studyjobcontroller.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2553)
=> update katib component

components/centraldashboard/package-lock.json, components/centraldashboard/package.json, components/centraldashboard/public/.eslintrc.json, components/centraldashboard/public/components/main-page.js, components/centraldashboard/public/index.js, components/centraldashboard/webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2579)
=> Add ESLint to enforce Google JS style in public/

testing/tf_job_simple_test.py, testing/workflows/components/workflows.libsonnet
We have renamed top level python package of tf-operator in [this PR](https://github.com/kubeflow/tf-operator/pull/945). Therefore, we need to update the related imports here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2581)
=> Updating python package imports related to tf-operator

kubeflow/jupyter/prototypes/jupyter-web-app.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2589)
=> Update the jupyter-web-app Image

components/tensorflow-notebook-image/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2606)
=> Updated jupyter images to allow any origin

kubeflow/katib/studyjobcontroller.libsonnet
Related: https://github.com/kubeflow/katib/pull/405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2597)
=> Adding backOffLimit to metric collector spec

components/centraldashboard/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2613)
=> Add prodonjs to OWNERS

components/centraldashboard/public/components/main-page.js
***Description**: What the title says*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2619)
=> [Dashboard v1] Changed sidebar tab from JupyterHub to Notebooks

components/notebook-controller/OWNERS, components/profile-controller/.gitignore, components/profile-controller/Makefile, components/profile-controller/OWNERS, components/profile-controller/gcb_build.jsonnet
- Verified: `make build-gcb` succeeded 
- Also add OWNERS file to profile and notebook controller
/cc @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubeflow/2603)
=> Add build using GCB support to profile controller
